### ISSUE TITLE
Spurious SO data lines in  Wiley_STM\ Collection__2012_2014_Nesli2.csv

### ISSUE THREAD

**Issue by ianibo** [k-int/KBPlus#1]
the SO datafile  Wiley_STM\ Collection__2012_2014_Nesli2.csv seems to have some lines containing organisation names like

free back issues after 1 year back to 1996

The lines seem to contain the right number of fields, but the wrong text in some places.

**Comment by ostephens** [comment]
Affects all the Wiley files:
Wiley_SSH Collection__2012_2014_Nesli2.csv
Wiley_Full Collection__2012_2014_Nesli2.csv
Wiley_Medicine and Nursing_2012_2014_Nesli2.csv
WileySTM Collection_2012_2014_Nesli2.csv

Will ask Magaly to correct and update files
