### ISSUE TITLE
Display content provider name with Package name

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#10]
How hard would it be to add the package content provider name in brackets after the package name whenever it is displayed? This would ensure that generic package names like "Option 1" are given context

**Comment by ianibo** [comment]
It's not technically hard, but it has to be done everywhere a package name appears. Will do this for as many as I can see in M3, but could use an eye cast over the app after M3, with this issue specifically listing any occurrences that I've missed.

**Comment by ostephens** [comment]
OK - actually the package name should really be more specific than 'Option 1' but this will save us a bit of time right now in updating all the package names - thanks
