### ISSUE TITLE
Data Migration - NoticePeriod

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1002]
Data need to be moved to the new  custom property using the UPGRADE script

https://github.com/k-int/KBPlus/commit/049abb8bee9097805c8897513a58e75da90bf89a

**Comment by ostephens** [comment]
NB just Notice Period affected - not applicable to Cancellation Allowance

**Comment by ianibbo** [comment]
Ok - in the upcoming new world order this would be a change request methinks

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
