### ISSUE TITLE
Error in DB update script

### ISSUE THREAD

**Issue by ianibo** [k-int/KBPlus#1003]
test-deploy on test returns the following from '/var/lib/jenkins/jobs/KB+/workspace/app/UPGRADE-pre.txt

....

Started by upstream project "KB+" build number 62
originally caused by:
 Started by an SCM change
Building in workspace /var/lib/jenkins/jobs/kbplus-deploy/workspace
[workspace] $ /bin/sh -xe /tmp/hudson241828127968244778.sh
- sudo /var/lib/jenkins/scripts/kbplus_deploy.sh
  KBPlusDeploy script
  Kill off any running tomcat
  Reset database
  Clear old app
  Install new war
  ERROR 1093 (HY000) at line 10 in file: '/var/lib/jenkins/jobs/KB+/workspace/app/UPGRADE-pre.txt': You can't specify target table 'license_custom_property' for update in FROM clause
  Updating spelling mistakes
  Updating spelling mistakes
  @notSpecifiedId
  70
  Restart Tomcat
  Tomcat started.
  Tomcat started
  Sleeping 180 seconds for startup to complete
  Running upgrade-post
  Upgrade-post
  Upgrade-post
  Running TEST enhancement script
  Set up some MySQL Variables to hold the IDs of our custom property definitions
  Set up some MySQL Variables to hold the IDs of our custom property definitions
  Get IDs of known custom properties
  Get IDs of known custom properties
  @InstitutionTypeId := rdv_id
  308
  @AdmRoleId := id
  5
  @JCNamespace := idns_id
  3
  @BorsetshireUniId := org_id
  2107
  @FakeUniId := id_id
  81720
  Finished: SUCCESS

**Comment by iyawnis** [comment]
Apparently you cant have a select on table a, when you delete on table a on the same query. Nesting the queries can work:

delete from license_custom_property where type_id = @concurrentUsersPropDefId and owner_id in 
(select owners.id from( select owner_id as id from license_custom_property where  ref_value_id = @concurrentUsersPropDefId ) as owners) and int_value = 0; 

Just  testing that it actually worked..

**Comment by iyawnis** [comment]
Should I also remove Concurrent Access ?

**Comment by ostephens** [comment]
I don't think we should remove the Concurrent Access property as someone has specifically set it to 'Not Specified' - but trying to mind read at this point...

**Comment by ianibbo** [comment]
:) Consistency is important I'd say - perhaps more so than getting it right
for one user, but thats a throw-away opinion

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
