### ISSUE TITLE
Add JR1 GOA (Gold Open Access) statistics from JUSP on the Issue Entitlement Details

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1004]
I know what Issue Entitlement is, @ostephens  can you fill me in the rest of the words please?

**Comment by ostephens** [comment]
Bah - started to type a long answer then realised this seems to be already displaying on live - so assume Ian added at some point (or this is automatically displayed now we get the data from JUSP)

<img width="1248" alt="screen shot 2015-08-12 at 14 40 25" src="https://cloud.githubusercontent.com/assets/576174/9225241/288d8510-4100-11e5-9cfd-345eb4d02da6.png">

**Comment by iyawnis** [comment]
Great, so I will mark it as done.
