### ISSUE TITLE
Test: Remove additional title information from tipview screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1013]
In the listing on tipview screen (e.g. https://www.kbplus.ac.uk/test/myInstitutions/Anglia_Ruskin_University/tipview?filter=all) the title is displayed twice - it should only display once:

<img width="652" alt="screen shot 2015-08-16 at 23 50 55" src="https://cloud.githubusercontent.com/assets/576174/9295805/06a300fe-4472-11e5-8d72-e71e57005b9f.png">

Remove the additional title in brackets

**Comment by iyawnis** [comment]
One is linking to the tipp, the other on the TitleInstance

**Comment by ostephens** [comment]
@ianibbo has adjusted wording on this screen to make differentiation clearer
