### ISSUE TITLE
TIPPs with status set to 'Deleted' shouldn't appear in currentTitles page

### ISSUE THREAD

**Issue by d3vAdv3ntur3s** [k-int/KBPlus#1014]
**Issue** If the status field is set to 'Deleted' on a TIPP instance  

**Example of issue** 
[Current Titles](https://www.kbplus.ac.uk/kbplus/myInstitutions/Canterbury_Christ_Church_University/currentTitles/filtering-form?filterSub=all&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=radiography&validOn=2015-08-05)

[Corresponding TIPP with deleted status](https://www.kbplus.ac.uk/kbplus/tipp/show/136374)

**Support Ticket**
As per [K-int Support Ticket](https://knowint.zendesk.com/agent/tickets/1641)

**Comment by ostephens** [comment]
If this corresponds to the issue raised by Damyanti via Zendesk, I don't think this is quite right. It is Issue Entitlements that appear on the currentTitles page, not TIPPs. Based on this, I believe the issue is that when an IE has been set to 'Deleted' it is still being used to generate the currentTitles list.

I'll try and setup and example and post it to the Zendesk ticket with the details - but won't be until this evening

(and if I've got the wrong end of the stick here, apologies!)

**Comment by d3vAdv3ntur3s** [comment]
Hi Owen, it is indeed the same issue.

OK, well I'll hold off then for now, the code is filtering via:

sub_qry += "AND ie.subscription.status.value != 'Deleted' "
sub_qry += "AND ie.status != 'Deleted'" 

Nothing on TIPP level

**Comment by ostephens** [comment]
I think that's right - I don't think there should be any filter based on the TIPP status. I'll set up a test to see exactly what is going on in this scenario and get back to you with some more details

**Comment by d3vAdv3ntur3s** [comment]
OK, great stuff!

**Comment by ostephens** [comment]
OK - setup a test:

Issue Entitlement for "Alzheimer's Research & Therapy": https://www.kbplus.ac.uk/test/issueEntitlement/show/1219398 has status 'Deleted':

<img width="959" alt="screen shot 2015-08-17 at 22 07 11" src="https://cloud.githubusercontent.com/assets/576174/9316682/679af422-452e-11e5-8f56-acae93576afb.png">

But despite this - it is still creating an entry in the institutional title list:

<img width="1199" alt="screen shot 2015-08-17 at 22 20 43" src="https://cloud.githubusercontent.com/assets/576174/9316690/79b92e6c-452e-11e5-9bbf-007aa263b3c6.png">

The Deleted status on the IE should mean that it isn't displayed in the Title list

**Comment by raztiff** [comment]
Thanks Owen :) 

I'll have to check out the HQL. Not the simpliest of querries to look at, I'll let you know ASAP.

**Comment by d3vAdv3ntur3s** [comment]
On inspection... it would appear to be a simple change 

AND ie.status != 'Deleted'"

should be 

AND ie.status.value != 'Deleted'"
