### ISSUE TITLE
Test: Non-critical issues

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1017]
Several non-critical issues reported during v5.0 testing - all on this one issue. All should be small/cosmetic. If any need more info or prove substantial we can split into separate issue and decide what we do with it
- Licence Details screen - when showing a licence change notification, the heading above licence change notifications says “This Subscription has pending change notifications” - should read "This licence..."
- Typo in the change notification info – “template license.Accept” (missing space after the full stop)
- Typo in breadcrumb – “Current Licenses” should read “Current Licences”
- On https://www.kbplus.ac.uk/kbplus/terms-and-conditions there is a link to a word document https://www.kbplus.ac.uk/kbplus/JISC%20Collections%20Knowledge%20Base+%20Subscriber%20Agreement%202012-2013%20310713.doc - this URL does not work
- Release version number in bottom right of screen links to non-existent page
- Remove the Institution name and the phrase 'Subscription Taken' from between the Breadcrumbs and the Subscription Name on the following screens:
  ++ /subscriptionDetails/linkPackage/
  ++ /subscriptionDetails/addEntitlements/
  ++ /subscriptionDetails/renewals/
  ++ /subscriptionDetails/previous/
  ++ /subscriptionDetails/expected/
  ++ /subscriptionDetails/documents/
  ++ /subscriptionDetails/notes/
- Change styling on 'Export' dropdown button so blue rather than grey (e.g. on /subscriptionDetails/index/, /myInstitutions/Aberystwyth_University/currentTitles etc.)
  (html is <a class="dropdown-toggle badge" id="export-menu" role="button" data-toggle="dropdown" data-target="#" href="">Exports<b class="caret"></b></a>)
- Relabel the button on the ‘Import subscription taken’ page to ‘Upload New Subscription Taken Worksheet’ instead of ‘Upload Renewals Worksheet’

**Comment by ianibo** [comment]
Release number links to non existent page because we've not done the release yet. #WontFix

**Comment by ianibo** [comment]
Don't understand the breadcrumb changes on subscriptionDetails - need more info - like why - they seem to be correct and consistent at the moment?

**Comment by ostephens** [comment]
subscriptionDetails - the issue isn't the breadcrumbs - better illustrated with a screenshot - there is redundant text circled in the red oval which needs removing.

<img width="821" alt="screen shot 2015-08-18 at 18 11 57" src="https://cloud.githubusercontent.com/assets/576174/9337030/bcb6daba-45d4-11e5-95c0-8baa9c3bd307.png">

Affects:
- /subscriptionDetails/linkPackage/ 
- /subscriptionDetails/addEntitlements/ 
- /subscriptionDetails/renewals/ 
- /subscriptionDetails/previous/ 
- /subscriptionDetails/expected/ 
- /subscriptionDetails/documents/ 
- /subscriptionDetails/notes/

**Comment by ianibo** [comment]
Ahhhh! ok
