### ISSUE TITLE
Test: 'Unlink' Package from Sub gives Grails error when no IEs attached to that package in sub

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1019]
E.g. https://www.kbplus.ac.uk/test/subscriptionDetails/details/572
Has "American Chemical Society:NESLI2:Web Editions:2014" (https://www.kbplus.ac.uk/test/packageDetails/show/310) linked to it, but there are no IEs in the Sub attached to that Package. Clicking 'Unlink', then 'Confirm Delete' leads to the following Grails error:

Error 500: Internal Server Error

URI
    /test/subscriptionDetails/unlinkPackage
Class
    org.hibernate.hql.ast.QuerySyntaxException
Message
    unexpected end of subtree [delete from com.k_int.kbplus.IssueEntitlement ie where ie.id in ()]
Trace

```
Line | Method
```

->>  271 | unlinkPackage in com.k_int.kbplus.SubscriptionDetailsController

---

|    198 | doFilter      in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . .  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke        in net.bull.javamelody.JspWrapper
|    285 | invoke . . .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter      in net.bull.javamelody.MonitoringFilter
|    176 | doFilter . .  in     ''
|   1142 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run           in java.lang.Thread

**Comment by ianibbo** [comment]
Ioannis - needs defensive code around the id delete if the list of ie.id is
empty. Would actually be better to do this by embedding the query rather
than passing the list of IDs around. Also - just looking at the code - be
very careful to delete things in the right order [Lowest level items first]
to avoid dangling references in the DB.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
