### ISSUE TITLE
PackageDelete - improve messages

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1026]
On the hardPkgDelete, instead of suggesting that subscriptions need to be deleted, we should be saying that they need to be unlinked. We might be able to add the unlink links inside the hardDelete pacakge popup to make it faster

**Comment by ianibbo** [comment]
Not sure about this - having a sub linked to a deleted package is bad - and
not just a matter of unlinking as the IEs can still point to deleted TIPPS.
If the scenario is deleting a package would you not want to destroy
anything associated with the package you are deleting [Maybe only IEs and
then unlink] - but just unlinking seems like it might cause issues?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iyawnis** [comment]
Unlinking a package from a subscription will delete any IEs from that Package as well as any pending changes
