### ISSUE TITLE
"Licence" mispelt in URL

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#103]
e.g. in http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Edinburgh/licenses

Should be

http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Edinburgh/licences

**Comment by ianibo** [comment]
also for 104... Problem here is that this spelling is ingrained in the app.. down to database table and column naming level. Text on screens is easy to change, places like this are absolutely fraught with danger and need a day set aside to try and go through and methodically change everything from the ground up.. Need some time set aside specifically for this.

**Comment by ostephens** [comment]
I'm happy to put this as low priority and push to future - unless you feel better to tackle before we go live?

**Comment by ostephens** [comment]
This seems like high cost to fix with small benefit. Closing this now, but will be raised with LE for steer on if he still wishes to see this fixed.
