### ISSUE TITLE
PackageDetails/PublicExport asAt

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1033]
If we are before start date use a date after it, and if after end date use date before it.
This should also be done for exports as well.
For packageDetails change page background as with subscription.

If the user wants to use current date for the packageDetails use the exiting option.
For the publicExport there will be no option to change the behaviour.

**Comment by iyawnis** [comment]
@ostephens Is there are ideal default date we should be using for this? Eg the package startDate? 
Also, this is going to be applied to the previous/expected/current screens?

**Comment by ostephens** [comment]
Sorry - not sure I quite understand the question. Default date where?

**Comment by iyawnis** [comment]
The default date that will be automatically set as the 'asAt' date when a package is expected, or in the past.

**Comment by ostephens** [comment]
Would be the first/last day of the package

**Comment by iyawnis** [comment]
Right, one or the either depending on whats available. Should the `asAt` option be applied to current/expected/previous pages as well ?

**Comment by ostephens** [comment]
No - they should always be shown as of the current date.

**Comment by iyawnis** [comment]
Ah this makes things much easier. Thanks

**Comment by iyawnis** [comment]
Should the date used for asAt be part of the export data, or should I append it on filename?

**Comment by ianibbo** [comment]
I'm all for adding it to the filename

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
I'm probably slightly tended towards having it in the data but not strongly.  My only concern on adding to the filename is the mechanism we have for producing the file via the xslt and whether adding the 'asAt' date to the filename is straightforward in that instance

**Comment by iyawnis** [comment]
That is not a concern, the file name is a variable set in one place and used by all exports. On the other hand if we add it to data we need to modify any relevant xslt and export services. So unless the users want it in the data and not filename, I suggest we leave it on the filename for now.

**Comment by ostephens** [comment]
Cool - sounds good

**Comment by iyawnis** [comment]
Fixed at 0b880f6a1901c88e465762f845f28fbf0ede4f98
