### ISSUE TITLE
Data Managers Title Index does not display Publisher or Identifiers

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1035]
The Data Managers Titles Index (https://www.kbplus.ac.uk/test/titleDetails/dmIndex) has columns labelled "Publisher" and "Identifiers" but no information appears in this column even where the journal title has an Org linked with the Publisher role or has Identifiers linked to it.

**Comment by ianibbo** [comment]
Think this index is driven off ES - has ES been rebuilt since the changes
were made?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Can can you supply an example of one with pub and identifiers not showing
pls.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Scratch those - our bad. fixing.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
ok np

**Comment by ianibo** [comment]
![image](https://cloud.githubusercontent.com/assets/53283/10071882/18c05654-62b5-11e5-83e7-a84079e40864.png)
