### ISSUE TITLE
Org Users - Wrong role checks

### ISSUE THREAD

**Issue by mike-campbell-k-int** [k-int/KBPlus#1042]
The editable buttons are available when there is a role request, but without checking that the role is actually accepted. This could be a problem on other screens as well.

**Comment by mike-campbell-k-int** [comment]
Handled as part of Issue #1041

**Comment by iyawnis** [comment]
Ian doesnt feel good about this. Check database for instances of more than one roles returned from the findBy... query

**Comment by iyawnis** [comment]
Fixed one bug here: defdf792a35a23decaab7a54ac194ef4be7ca23d
