### ISSUE TITLE
war: groovy-all conflicting version 2.4.4 vs. 2.4.3

### ISSUE THREAD

**Issue by julianladisch** [k-int/KBPlus#1045]
Using the latest code  f6f1707 the war file has this error when executing:

`groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.4 and you are trying to load version 2.4.3`

Doing `run-app` works fine, while doing `run-war` or `dev run-war` produces that exception.

**Comment by ianibo** [comment]
Aware of this, @latusaki is looking into it now - most likely candidate is a transitive dependency of spock-core - I expect it to be fixed shortly.

**Comment by ianibo** [comment]
Actually - looks like it's ES!

+--- org.elasticsearch:elasticsearch-groovy:1.7.0
|    --- org.codehaus.groovy:groovy-all:2.4.3

**Comment by iyawnis** [comment]
Fixed on https://github.com/k-int/KBPlus/commit/3a6f1edb6b3cf46b5b4f499fd759e890d481c27b
