### ISSUE TITLE
no_title_url report

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1047]
We want to only current packages for including the report. Current package is based on pkg status and end date in the future.

**Comment by mike-campbell-k-int** [comment]
@ostephens Magaly suggested that the current packages depend on package status. Looking at the code/interface  I cant see a way of setting the package status to deleted, are you aware of a process that does this ?

**Comment by ostephens** [comment]
I think you are correct - I can't see a way to edit package status (package.pkg_status_rv_fk) - not even via /package/edit/ 

I'd suggest that this check isn't needed and might end up excluding stuff they want to see. They can permanently delete packages if they need to, but they don't seem to be able to set status one way or the other.
