### ISSUE TITLE
packageDetals/titles exports

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1053]
Add a CSV export here

**Comment by mike-campbell-k-int** [comment]
Waiting on feedback

**Comment by iyawnis** [comment]
@mike-campbell-k-int  Delete the code instead of commenting out, and close issue

**Comment by ostephens** [comment]
Why remove the JSON and XML exports? Isn't what's needed the CSV to be added rather these to be removed?

**Comment by iyawnis** [comment]
The items they were exporting were the same with what is exported from packageDetails/show, so they didnt serve any purpose..

**Comment by ostephens** [comment]
I think either it should be the same on both screens, or only available on one of the two screens. I think having slightly different export options on the two screens is confusing! If this is what is happening then ignore me :)

**Comment by iyawnis** [comment]
That is what was happening(slightly different options) , so I now removed the export from the current titles screen, and its only available in the main page.

**Comment by ostephens** [comment]
OK - ty
