### ISSUE TITLE
XML export on subscription fails when Core dates exist

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1066]
Trying to export XML for a subscription, if a 'Core' start/end date exists for an IE/TIP then the XML fails to be generated with error

E.g. https://www.kbplus.ac.uk/demo/subscriptionDetails/index/14374?format=xml

Error 500: Internal Server Error
URI
/demo/subscriptionDetails/index/14374
Class
groovy.lang.MissingPropertyException
Message
Exception evaluating property 'endDate' for java.util.Arrays$ArrayList, Reason: groovy.lang.MissingPropertyException: No such property: endDate for class: java.sql.Timestamp Possible solutions: date

Trace
    Line | Method
->>  423 | doCall          in com.k_int.kbplus.ExportService$_addTitleListXML_closure8_closure33

---

|    420 | doCall          in com.k_int.kbplus.ExportService$_addTitleListXML_closure8
|    362 | addTitleListXML in com.k_int.kbplus.ExportService
|    497 | addSubIntoXML   in     ''
|    184 | doCall . . . .  in GrailsMelodyGrailsPlugin$_closure4_closure16_closure17
|    236 | doCall          in com.k_int.kbplus.SubscriptionDetailsController$_index_closure3_closure18
|    204 | index . . . . . in com.k_int.kbplus.SubscriptionDetailsController
|    198 | doFilter        in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . .  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke          in net.bull.javamelody.JspWrapper
|    285 | invoke . . . .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter        in net.bull.javamelody.MonitoringFilter
|    176 | doFilter . . .  in     ''
|   1145 | runWorker       in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run             in java.lang.Thread

Only the XML export is affected, the JSON and CSV exports are OK:
https://www.kbplus.ac.uk/demo/subscriptionDetails/index/14374?format=json
https://www.kbplus.ac.uk/demo/subscriptionDetails/index/14374?format=csv

**Comment by ostephens** [comment]
@mike-campbell-k-int  - have you looked at this?

**Comment by mike-campbell-k-int** [comment]
Sorry for the delay, that should fix the issue.
