### ISSUE TITLE
URLs appearing in Platform data

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#11]
A load of URLs in the platform list "http://www.bioone.org/loi/aorn" (all from the bioone_ import file) - the import file looks OK to me - can you check?

**Comment by ianibo** [comment]
I _think_ these are being created when the SO file is imported. In this case

../kb_plus_datafiles/bioone_collection_2012_2012_Nesli2.csv:13

References this url as a non-host platform (I think). So the platform gets created with a name of the URL.. Is this incorrect? if so what should happen?

**Comment by ostephens** [comment]
Ah - think I've got it, the header rows are wrong leading the import to misinterpret some cols - I'll get the data corrected

**Comment by ostephens** [comment]
This is now corrected - should be OK
