### ISSUE TITLE
"Platform" missing from Current Subscriptions screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#111]
On the Current Subs screen - e.g. http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions

There is a column for 'Platform' but this is not populated. This should be the host platform for the linked package

**Comment by ianibo** [comment]
Is this tied into the "nominal platform" discussions?

**Comment by ostephens** [comment]
Yes - should be the host platform URL.
E.g. in http://knowplus.edina.ac.uk/kbplus/package/show/89 you have the 'Provided by platform' heading, and a link to the relevant platform record underneath

**Comment by ianibo** [comment]
Well.. yes.. but no..

the platform column is repeated for each platform in the tipp ternary
relationship (usually 1 currently, but not always) how should I choose
which one to display?

On 6 August 2012 15:58, Owen Stephens <
reply@reply.github.com

> wrote:
> 
> Yes - should be the host platform URL.
> E.g. in http://knowplus.edina.ac.uk/kbplus/package/show/89 you have the
> 'Provided by platform' heading, and a link to the relevant platform record
> underneath
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/111#issuecomment-7525895

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
From Skype discussion:

Need to populate nominal_platform_fk - this will be done through an 'augment' batch process, that populates it using the host platform for the majority of the TIPPs within the package. If two or more platforms have same number of TIPPs, choose the first one alphabetically

This should be only used where nominal_platform_fk is null - if it is already populated then leave it.

Will be necessary to allow editing of the nominal_platform_fk - but I believe this is a task for phase 2 as this would happen at a 'global' level not a task for individual institutions. When this functionality is added recommend we allow any platform to be added as the nominal_platform_fk, even if no TIPPs list it as a host platform - just in case. An e.g. might be Highwire titles where Highwire only ever acts as an 'admin' platform at TIPP level, but might wish to list as the nominal_platform_fk anyway
