### ISSUE TITLE
Add columns to Add Subscription screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#112]
On this page
http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/addSubscription

Need to add more columns to display. Columns required, left to right:
1. Selection radio button (already displayed)
2. Subscription Offered (already displayed)
3. Package Name (same as on the Current Subscriptions screen http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions)
4. Vendor (as on the Current Subscriptions screen http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions)
5. Consortia  (as on the Current Subscriptions screen http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions)
6. Start date  (as on the Current Subscriptions screen http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions)
7. End date  (as on the Current Subscriptions screen http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions)
8. Platform  (as on the Current Subscriptions screen http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/currentSubscriptions - although also see issue #111)

**Comment by ianibo** [comment]
This is complex.. Currently the entries on this page come from ElasticSearch and not the database. I'll change it to be database driven, but the searching will be less functional, and may be slower as the number of SOs increases.

**Comment by ostephens** [comment]
The problem is that currently it isn't possible to tell enough about the thing you have found to know if it is the right subscription to copy.

Could more data be added to ElasticSearch to allow more comprehensive display?
