### ISSUE TITLE
Add ability to remove Issue Entitlements from a subscription

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#120]
From the Subscription Details page - e.g. http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/236 there should be the ability to remove Issue Entitlements from a subscription taken.

Suggest two mechanisms:

'Delete' or 'Remove' column that has a cross 'x' or some other 'delete' icon in it. Clicking this will remove that IE from the Subscription
Batch edit - at top of new column ability to delete all marked lines using batch edit function (something very clear - like a text drop down with 'Remove all marked'

Not sure if best to have the new column on the left or right. Suggest start with it on the right.

Always prompt someone using this function whether deleting single line or batch editing

**Comment by ianibo** [comment]
I really think this is one of those where we need to ask M&M? Putting a clickable thing on the right, with the bulk checkbox on the left, and having the bulk icon on the right seems like it's going to be way too busy to me?

Is helen OK from a usability perspective to have 1 control do 2 different things? Happy to do this, but want to try and avoid last minute rework at this stage, so would be good to get our ducks lined up before starting.

**Comment by ostephens** [comment]
See also #122 I've just submitted - the other side of this functionality

**Comment by ostephens** [comment]
Meant for bulk delete to work same as other batch edit functions - that is, change the value at the top, then 'Apply Batch Changes'

**Comment by ostephens** [comment]
Agree about some of the usability concerns though - and happy to talk to M&M (did chat to Helen this morning) - just not sure if they will be able to turn around in time, and need to get functionality in there
