### ISSUE TITLE
Clicking 'Content URL' on Subscription Details page does not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#121]
Currently clicking links in the 'Content URL' column on the Subs Details page (e.g. http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/247) goes to wrong destination and gives an error - e.g. goes to:

http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/www.nature.com/aps

When it should go to:

http://www.nature.com/aps

**Comment by ianibo** [comment]
The URLs in that SO are not well formed, the start www rather than http://www which means they get interpreted as local links. I can look at the strings and see if they start http:// and prepend it, but it's fraught with danger and really not ideal.. Can we fix the data?

**Comment by ianibo** [comment]
(You'll notice that, for example, NESLI2 Project Muse Premium Collection 2012-2013 does do the right thing)

**Comment by ostephens** [comment]
OK - could you give me a dump off all values in this field that don't start with "http://" (or just all and I'll filter)

**Comment by ianibo** [comment]
Agreed with owen that this is a data issue, list of offending URLs attached (Will contain duplicates, so should be sorted and piped through uniq before using as an edit list).

+-------------------------------------+
| tipp_host_platform_url              |
+-------------------------------------+
| none                                |
|                                     |
| www.nature.com/nature               |
| www.nature.com/nbt                  |
| www.nature.com/ncb                  |
| www.nature.com/nchembio             |
| www.nature.com/nchem                |
| www.nature.com/natureclimatechange  |
| www.nature.com/naturecommunications |
| www.nature.com/ng                   |
| www.nature.com/ngeo                 |
| www.nature.com/ni                   |
| www.nature.com/nmat                 |
| www.nature.com/nm                   |
| www.nature.com/nnano                |
| www.nature.com/neuro                |
| www.nature.com/nphoton              |
| www.nature.com/nphys                |
| www.nature.com/nprot                |
| www.nature.com/nsmb                 |
| www.nature.com/nrc                  |
| www.nature.com/nrcardio             |
| www.nature.com/nrclinonc            |
| www.nature.com/nrd                  |
| www.nature.com/nrendo               |
| www.nature.com/nrgastro             |
| www.nature.com/nrg                  |
| www.nature.com/nri                  |
| www.nature.com/nrmicro              |
| www.nature.com/nrm                  |
| www.nature.com/nrneph               |
| www.nature.com/nrneurol             |
| www.nature.com/nrn                  |
| www.nature.com/nrrheum              |
| www.nature.com/nrurol               |
| www.nature.com/scibx                |
| www.nature.com/scientificamerican   |
| www.nature.com/aps                  |
| www.nature.com/ajg                  |
| www.nature.com/ajh                  |
| www.nature.com/aja                  |
| www.nature.com/bdj                  |
| www.nature.com/bjc                  |
| www.nature.com/bmt                  |
| www.nature.com/cgt                  |
| www.nature.com/cdd                  |
| www.nature.com/cddis                |
| www.nature.com/cr                   |
| www.nature.com/cmi                  |
| www.nature.com/clpt                 |
| www.nature.com/ebd                  |
| www.embojournal.org                 |
| www.emboreports.org                 |
| www.nature.com/ejcn                 |
| www.nature.com/ejhg                 |
| www.nature.com/eye                  |
| www.nature.com/gt                   |
| www.nature.com/gene                 |
| www.nature.com/gim                  |
| www.nature.com/hdy                  |
| www.nature.com/hr                   |
| www.nature.com/icb                  |
| www.nature.com/ijir                 |
| www.nature.com/ijo                  |
| www.nature.com/ismej                |
| www.nature.com/ja                   |
| www.nature.com/jcbfm                |
| www.nature.com/jes                  |
| www.nature.com/jhg                  |
| www.nature.com/jhh                  |
| www.nature.com/jid                  |
| www.nature.com/jp                   |
| www.nature.com/ki                   |
| www.labanimal.com                   |
| www.laboratoryinvestigation.org     |
| www.nature.com/leu                  |
| www.nature.com/modpathol            |
| www.nature.com/mp                   |
| www.nature.com/msb                  |
| /www.nature.com/mt                  |
| www.nature.com/mi                   |
| www.nature.com/nutd                 |
| www.nature.com/npp                  |
| www.nature.com/oby                  |
| www.nature.com/onc                  |
| www.nature.com/pj                   |
| www.nature.com/pcan                 |
| www.nature.com/sc                   |
| www.nature.com/vital                |
| www.eupjournals.com/epi             |
|                                     |
|                                     |
| www.nature.com/nature               |
| www.nature.com/nbt                  |
| www.nature.com/ncb                  |
| www.nature.com/nchembio             |
| www.nature.com/nchem                |
| www.nature.com/natureclimatechange  |
| www.nature.com/naturecommunications |
| www.nature.com/ng                   |
| www.nature.com/ngeo                 |
| www.nature.com/ni                   |
| www.nature.com/nmat                 |
| www.nature.com/nm                   |
| www.nature.com/nnano                |
| www.nature.com/neuro                |
| www.nature.com/nphoton              |
| www.nature.com/nphys                |
| www.nature.com/nprot                |
| www.nature.com/nsmb                 |
| www.nature.com/nrc                  |
| www.nature.com/nrcardio             |
| www.nature.com/nrclinonc            |
| www.nature.com/nrd                  |
| www.nature.com/nrendo               |
| www.nature.com/nrgastro             |
| www.nature.com/nrg                  |
| www.nature.com/nri                  |
| www.nature.com/nrmicro              |
| www.nature.com/nrm                  |
| www.nature.com/nrneph               |
| www.nature.com/nrneurol             |
| www.nature.com/nrn                  |
| www.nature.com/nrrheum              |
| www.nature.com/nrurol               |
| www.nature.com/scibx                |
| www.nature.com/scientificamerican   |
| www.nature.com/aps                  |
| www.nature.com/ajg                  |
| www.nature.com/ajh                  |
| www.nature.com/aja                  |
| www.nature.com/bdj                  |
| www.nature.com/bjc                  |
| www.nature.com/bmt                  |
| www.nature.com/cgt                  |
| www.nature.com/cdd                  |
| www.nature.com/cddis                |
| www.nature.com/cr                   |
| www.nature.com/cmi                  |
| www.nature.com/clpt                 |
| www.nature.com/ebd                  |
| www.embojournal.org                 |
| www.emboreports.org                 |
| www.nature.com/ejcn                 |
| www.nature.com/ejhg                 |
| www.nature.com/eye                  |
| www.nature.com/gt                   |
| www.nature.com/gene                 |
| www.nature.com/gim                  |
| www.nature.com/hdy                  |
| www.nature.com/hr                   |
| www.nature.com/icb                  |
| www.nature.com/ijir                 |
| www.nature.com/ijo                  |
| www.nature.com/ismej                |
| www.nature.com/ja                   |
| www.nature.com/jcbfm                |
| www.nature.com/jes                  |
| www.nature.com/jhg                  |
| www.nature.com/jhh                  |
| www.nature.com/jid                  |
| www.nature.com/jp                   |
| www.nature.com/ki                   |
| www.labanimal.com                   |
| www.laboratoryinvestigation.org     |
| www.nature.com/leu                  |
| www.nature.com/modpathol            |
| www.nature.com/mp                   |
| www.nature.com/msb                  |
| /www.nature.com/mt                  |
| www.nature.com/mi                   |
| www.nature.com/nutd                 |
| www.nature.com/npp                  |
| www.nature.com/oby                  |
| www.nature.com/onc                  |
| www.nature.com/pj                   |
| www.nature.com/pcan                 |
| www.nature.com/sc                   |
| www.nature.com/vital                |
| none                                |
+-------------------------------------+
180 rows in set (0.09 sec)

**Comment by ostephens** [comment]
All these fixed in data files
