### ISSUE TITLE
Adding Issue Entitlements to a Subscription Taken

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#122]
This is a more complex set of functionality, so may need some discussion before it's finalised.

From the Subscriptions Details page, if the subscription does not already have IEs for each TIPP in the package, it should be possible to add Issue Entitlements to the subscription, based on the TIPPs that are in the package but don't yet have a linked IE in this subscription.

For e.g. in http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/147 there are two IEs. However in the linked package there are (in total) 89 TIPPs. This means we want to offer the ability to add any of the remaining 87 TIPPs to the Sub as IEs. Hope that makes sense.

Think what needs to happen:
Add a new 'lozenge' to the Subscription details screen (e.g. http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/147) along side existing "Current Entitlements". This would be labelled "Add Entitlements"
This would display all TIPPs that could be added (i.e. all those without a current IE within this subscription)
Layout would be tabular very similar to the layout on the Subscription Details screen but:
No need for 'click to edit' functionality on this page - edits should be done once converted to IE
Only need following columns:
Select check box (to allow adding multiple lines at one time)
# 

Title
ISSN
eISSN
Start Date
End Date
Embargo
Content URL
Coverage Depth
Coverage Note
Add to Subscription - clickable text/icon to add that line immediately to the subscription

Just one batch option to be supported - check all lines and option to 'add all checked to subscription'

Need to support search/filtering on this screen - at least by title, and if possible by identifier, although this is not crucial

**Comment by ianibo** [comment]
This is a really complex requirement, I'd like to be sure that this is the actual item of work before starting.. if we can get rid of all the "Happy to discuss" and make it definitive... that would be ideal from my perspective.
