### ISSUE TITLE
Add "Documents" and "Notes" areas to top of Subs Details pages

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#125]
E.g. on http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/236

Add Documents and Notes areas - for docs and notes attached at the 'Subscription' level. Use same layout/design as for Docs/Notes areas on the Licence screen (e.g. http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Edinburgh/licenseDetails/17)

**Comment by ianibo** [comment]
I don't think this is going to work well... The licence screen allows the right hand boxes to float along-side the text. If we're rolling up these elements into the collapse-able header then they will be much longer than the other info in the header, and expanding the header will cause lots of whitespace below the main properties in the header and the entitlements list.

Needs significant M&M input and workups I feel.
