### ISSUE TITLE
Make 'Header' area of Subs Details page 'collapsible'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#126]
Allow users to 'collapse' the header area on the Subs Details page (e.g. http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/236) so user can see the list of IEs without other data.

Area that should be 'collapsible' is everything from under the navigation 'pills' to the "Entitlements A to X of X" text. It should include the 'Docs' and 'Notes' areas as requested in #125 (i.e. they should be included in the 'collapse')

Once collapsed leave a 'Show subscription details' text to click to expand again

**Comment by ianibo** [comment]
Hey Owen.. Can you ask M&M to give me some html for this? Need a steer on how the show details link should work in place etc.. will look like a dogs breakfast if I do it.
