### ISSUE TITLE
corruption of UI display

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#137]
When I view KB+ in a restored (i.e. less than maximised) browser window the display of the onscreen items is thrown out. For example see on the Licence Detail page how the display of the top navigation bar and the Licence Information panel are thrown out [a screenshot demonstrating this is included in the Usability Review document].

[cross ref: issue 1.7 in \KB+\Spec - Forms\KB+ initial usability review - HH - 06082012 - v2]

**Comment by ianibo** [comment]
Could do with getting M&M on this tracker, this is one for them I feel.

**Comment by ianibo** [comment]
This seems better now, but really need @iamcreative and @nbrock to agree amongst themselves that it's fixed in the different areas. Will push new version up to live later today. /cc @ostephens

**Comment by ostephens** [comment]
Assume fixed. If still issues will be picked up in UI review. No further action needed against this issue
