### ISSUE TITLE
New Note pop-up window - Placement of action buttons

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#140]
Suggest adding some distance between the ‘Close’ and ‘Save Changes’ buttons to make it harder for the user to close the dialogue box by mistake. Ideally move the buttons to opposite sides of the New Note window

[cross ref: issue 1.9 in \KB+\Spec - Forms\KB+ initial usability review - HH - 06082012 - v2]

**Comment by ostephens** [comment]
If still an issue should be picked up in UI review. No action needed against this issue
