### ISSUE TITLE
Reduce size of the 'Create New Note' pop-up window

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#141]
Suggest reducing the default size of the 'Create New Note' pop-up window so that the size of the "Note:" field is in proportion to the amount of text we expect them to enter. You might need to get guidance from Owen on how large/small the text field should be.

[cross ref: issue 1.10 in \KB+\Spec - Forms\KB+ initial usability review - HH - 06082012 - v2]

**Comment by ianibo** [comment]
Closing. thx @nbrock
