### ISSUE TITLE
Add buffer space around the 'edit' icon image

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#142]
In some places, for example in the 'Licence Properties' table, the text displayed is overlapping/partially obscuring the ‘edit’ icon. [screenshot is included in the Usability Review word document]

[cross ref: issue 1.11 in \KB+\Spec - Forms\KB+ initial usability review - HH - 06082012 - v2]

**Comment by ianibo** [comment]
Fixed by nathans latest updated. Closing.
