### ISSUE TITLE
Sorting on Add Subscription page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#147]
e.g. http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Edinburgh/addSubscription should be possible to sort table by following columns:

Name
Package Name(s)
Vendor
Consortia
Start Date
End Date
Platform(s)

Click the column header to sort and switch between ascending/descending sort

**Comment by ianibo** [comment]
Cannot sort by package name as there are 1:m subscription -> package links.  Cannot sort by vendor as link is currently through subscription package, and 1:m sub -> pkg links. Cannot sort by consortia -> link is through org_roles, 1:m problem. Cannot sort by platform(s) 1:m
