### ISSUE TITLE
Behaviour of external hyperlinks, Current Entitlements

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#149]
On the 'Current Entitlements' screen clicking on the hyperlinked title names in the 'Title' column opens up the URL in the same browser tab. External URLs should be set to open in a new tab. Suggest also that the same external hyperlink icon used in the 'Documents' panel of the 'Licence Details' screen is displayed.

[cross ref: issue 1.14 in \KB+\Spec - Forms\KB+ initial usability review - HH - 06082012 - v2]

**Comment by ostephens** [comment]
Behaviour of hyperlinks to be picked up in UI review. No action needed on this issue
