### ISSUE TITLE
Add Entitlements does not work for a Subscription Offered

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#158]
e.g. from http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/1

This is the subscription details screen for a SO, not an ST (this is linked from http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Edinburgh/addSubscription). The Add Entitlement button displays but generates the following error:

Error 500: Internal Server Error
URI
/kbplus/subscriptionDetails/addEntitlements/1
Class
java.lang.NullPointerException
Message
null
Trace
    Line | Method
->>  374 | runWorker in /subscriptionDetails/addEntitlements.gsp

---

Caused by NullPointerException: null
->>   55 | doCall    in gsp_demo_subscriptionDetailsaddEntitlements_gsp$_run_closure2

---

|    131 | run       in gsp_demo_subscriptionDetailsaddEntitlements_gsp
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

I'm not sure if 'adding entitlements' to an SO is a valid action - if the SO represents the 'vanilla' it should always reflect the package TIPPs exactly shouldn't it?

I'd be happy to see the 'Add Entitlements' button suppressed on an SO Subscription Details screen.
We may also need to suppress any editing or deleting of the lines on this page?

Even if it is possible to edit items of the SO Subs Details, then currently no user should have that privilege - this would be reserved for JISC Collections statff - which puts the work clearly in Phase 2

**Comment by ianibo** [comment]
Closing as found and fixed this yesterday, not on live yet, but resolved.
