### ISSUE TITLE
Make fields on Subscription Details screen editable

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#161]
Make the following fields on Subs Details page editable (click to edit):

Vendor (may need to wait until Vendor->Subscription link sorted?)
Start date
End date

**Comment by ianibo** [comment]
Made start and end dates editable.. need more info and spec on how remaining properties should be "editable". They are all primarily reference data and/or org links. There are way too many orgs to be able to list them in a combo meaning we need some kind of popup or other select dialog. Issue needs to enumerate each field and say what should happen. Fields specifically are : Package Name - Editing this will edit it for all users currently, suspect this isn't whats wanted. Vendor - Currently an orgRole relationship at the (subscription?) level. Filter by org type? Spec org role type. Ditto Consortia. Nominal platform - editable? Set at the package level for all linked packages, updates values for all users - any user allowed to change?

**Comment by ostephens** [comment]
Only the ones requested - so Start Date and End Date, and link to Vendor - absolutely right the rest are not editable generally and need sorting when we look at what JC staff can do on the system - not in this issue.

Agreed presenting Vendor orgs problematic - will split out into separate issue for Future release (so not in this release)

Please close against your commit of making dates editable
