### ISSUE TITLE
Downloading docs from Licencedetails/documents page gives error

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#163]
If I try to download a doc from e.g. http://knowplus.edina.ac.uk/kbplus/licenseDetails/documents/12
URL triggered is http://knowplus.edina.ac.uk/oledocstore/document?uuid=9009bfa4-9452-4c17-bc7b-7f7683facde7 - gives error

If I download doc from 'Docs' panel on main licence details page that works fine

**Comment by ianibo** [comment]
Fixed
