### ISSUE TITLE
Restrict ability to edit subscriptions to those belonging to affiliated institutions

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#166]
You should only be able to edit a subscription, or any of the related Issue Entitlements if the subscription belongs (not sure how this is linked?) to an institution to which you are affiliated.

Most obvious example, it should not be possible to edit http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/1 unless you are affiliated with SHEDL - currently it is possible to edit and remove IEs etc.

**Comment by ianibo** [comment]
Any thoughts on how this should work.. it's problematic because the click to edit stuff is entwined within the page.. Should users be able to see but not edit if they don't have perms?

**Comment by ianibo** [comment]
Done.
