### ISSUE TITLE
Package names not displaying

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#168]
Some package names don't display in the Add Subscriptions, Current Subscriptions and Subscription details screen. I suspect it is a data issue, but not sure what - possibly where two SOs link to the same package? Examples are:

EUP Complete Collection 2012 NESLI2 - .e.g see http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/25
EUP Complete Collection No New Titles 2012 NESLI2 - see http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/49
Berg Visual Culture Collection 2011-2012 SHEDL - see http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/59
Berg Full Collection 2012 NESLI2 - see http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/index/95

In these 4 cases at least there is a NESLI and SHEDL SO for the packages

Can you see what the cause is, and whether it is a s/w fix or a data fix that needs applying?

**Comment by ianibo** [comment]
Working on this now.. it's very detailed data analysis problem and quite time consuming.. be useful to have priority steer if this is non-critical.

**Comment by ianibo** [comment]
Possibly caused where a package (pkg.contentProvider) is already set causing the package update not to happen and add sub. Rectified code, testing.

**Comment by ianibo** [comment]
Fixed.
