### ISSUE TITLE
No titles attached to some packages

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#17]
E.g. http://projects.k-int.com/kbplus/package/show/10 has no titles listed
Another example http://projects.k-int.com/kbplus/package/show/21

Not sure if this an import issue or a display issue?

**Comment by ianibo** [comment]
Can you check this again please.. I see titles on both those URLs... Could be an import glitch thats fixed now.

**Comment by ostephens** [comment]
Yes - those look fine. Could have been a data problem that's been fixed in the meantime

**Comment by ostephens** [comment]
Sorry - closed
