### ISSUE TITLE
Licence Signed? flag

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#183]
We want to be able to indicate if a Licence has been signed or not. Either Y/true or N/false

Thought as a new field on the Licence, but could be done via some other mechanism like user tagging as suggested by II

**Comment by ianibo** [comment]
Is this not tied up with license status tho? Is there no concern that we could have a license with status "Current" and a signed flag of false? or a status of "Awaiting Signature" and signed=true? Is it not better to infer this from the status field? Please confirm issue.

**Comment by ostephens** [comment]
Licences can be current without being signed (they probably shouldn't be, but there is no doubt it happens)

Agree issue with 'Awaiting signature' - I'll raise with DK

**Comment by ostephens** [comment]
'Awaiting Signature' should be removed as a possible Licence status, resolving possible conflict between this flag and licence status

**Comment by ianibo** [comment]
Probably not explained myself very well.. I think when we first discussed the "Types and Status" issues, I proposed a definition whereby types were static discriminators (selecting a particular state model), and status codes changes the state of the object, and hence what operations could be performed. To my laymans eye "Signing" the license almost certainly seems to belong in the core license status model. The concern wasn't so much about an individual status, as worry about the analysis of the problem and the proposed solution... which doesn't seem quite complete to me.. It seems like there very much should be a formal state model to accompany status fields.. they shouldn't just be lists of values. Doesn't cause me any problems technically, just raising the issue.

**Comment by ostephens** [comment]
OK - I think we would need further discussion between you, me and DK around defining a formal state model. Happy to do this post release.

**Comment by ianibo** [comment]
Yes, we can return to this post release.. this is just one of those where if we split a single state variable into 2 now it will be hard to go back to 1 later on.. and the 2 state variables can interact in unexpected ways. Just trying to avoid stitching ourselves up later down the line. Are we ok to defer the whole issue to next release, or do you still want license signed in this one?

**Comment by ostephens** [comment]
Have mailed you/me/DK with recommendation to put this on hold, up to DK to respond

**Comment by ostephens** [comment]
If this is still a requirement should be raised via users and added to backlog as with other requirements. No action needed on this issue.
