### ISSUE TITLE
Package list status

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#187]
Add new field to package: 'Package List Status'
Can take values:

Checked  
In progress

**Comment by ianibo** [comment]
Can this be tidied up and made definitive please. Add field to package.. What should the field name be - not clear to me from the issue text.

**Comment by ostephens** [comment]
Updated

**Comment by ianibo** [comment]
Does this issue need to have corresponding changes to screens? If so, where can the status be edited, or is it enough just to add it to the datamodel at the moment?

**Comment by ostephens** [comment]
Only in data model
