### ISSUE TITLE
KB+ Menus

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#189]
Currently have menus in the KB+ top bar:

Data Explorer (left)
Forms and Actions (left)
logout button (right)
name@institution (right)

Want to implement new menus:

Manage (left) - with options: Current Licences, Add Licences, Current Subscriptions, Add Subscriptions, Alerts, Reports, Help ( (prefer institution name not to be mentioned in any of these options if necessary)
name@institution (right) - with options: Profile, Logout
Institution (right) - drop down allowing selection of institutional context from all currently affiliated institutions

Bottom right new menu 'Tools'. If user in KB+ app, 'Tools' drop down shows links to 'Explorer' and 'Sandpit'. If the user is is sandpit view it will show 'Explorer' and 'KB+'. If the user is in Explorer, show KB+ and Sandpit.

Explorer = Data explorer. If in data explorer view then the current data explorer menu shows, new 'Manage' menu (defined above) does not show.

**Comment by ianibo** [comment]
Not really happy with this one.

**Comment by ostephens** [comment]
Which bits don't work for you?

**Comment by ianibo** [comment]
Ugh.. all of it if I'm really honest...
1. Can we split it down into 4/5 issues, there is a big batch of stuff.
2. Do we have any styling/design for this new "Tools" menu
3. How does the link to reports work? I can't deep link into reports (Indeed I don't have any URLs at all to shallow link yet)
4. Don't understand how the tools menu works. Currently the same app is deployed to all environments, so not sure how I can have separate links to different apps contextually
5. Don't understand how this "Data explorer" thing relates to URLs or anything about it really.. what does it actually change / do..

Just doesn't really make much sense to me at the moment.. many of these things require substantial rework to integrate  and rework URL structures to implement, don't think this is doable by wed.

**Comment by ostephens** [comment]
> Can we split it down into 4/5 issues, there is a big batch of stuff.
> Will do
> 
> Do we have any styling/design for this new "Tools" menu

Yes - being worked on by M&M and in the wireframes they circulated

> How does the link to reports work? I can't deep link into reports (Indeed I don't have any URLs at all to shallow link yet)
> Just a link to whereever the reports live (discussed on our last call with Edina + Peter R - thought we were all happy this would live at service.kbplus.ac.uk/reports ?)
> 
> Don't understand how the tools menu works. Currently the same app is deployed to all environments, so not sure how I can have separate links to different apps contextually
> OK - could have all links in all the time
> 
> Don't understand how this "Data explorer" thing relates to URLs or anything about it really.. what does it actually change / do..

Data explorer is all the stuff under the data explorer menu - currently the URLs:
http://knowplus.edina.ac.uk/kbplus/
http://knowplus.edina.ac.uk/kbplus/package/list
http://knowplus.edina.ac.uk/kbplus/org/list
http://knowplus.edina.ac.uk/kbplus/platform/list
http://knowplus.edina.ac.uk/kbplus/titleInstance/list
http://knowplus.edina.ac.uk/kbplus/titleInstancePackagePlatform/list
http://knowplus.edina.ac.uk/kbplus/subscription/list
http://knowplus.edina.ac.uk/kbplus/license/list

You had this separate out with different top bar displaying (no forms and actions menu showing when you went into a 'data explorer' screen (e.g. http://knowplus.edina.ac.uk/kbplus/titleInstance/show/1).

Would like to do the same in the other direction if possible - that is, don't show the Data Explorer menu when you are in a 'KB+' screen (such as http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Birmingham/addLicense)

**Comment by ostephens** [comment]
Split into #191, #192, #193 and #194
