### ISSUE TITLE
Allow user to set current institutional context

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#193]
At the moment if user has multiple affiliations, they see the 'Add' and 'Current' menu options for each institution they have affiliation to.

Would like to change this so they can set the institutional context, and then see only options based on that context. So for e.g. if I set the institutional context to 'University of Birmingham' I see options as if this was my only affiliation.

User only able to select institutional context for institutions they are currently affiliated to.

User controls their current context through a drop down menu at top right

**Comment by ianibo** [comment]
Problem really is how this manifests itself in URLs and actions... Really need to think through this from a technical perspective. -deeply uncomfortable with it-

**Comment by ostephens** [comment]
I've put this on Future release milestone - put to one side for now

**Comment by ostephens** [comment]
Agreed this is not right approach. As vast majority of users belong to a single institution, mainly not an issue. If there is a requirement for dealing with access to multiple institutions, should be raised through users in Phase 2 (or later phases)
