### ISSUE TITLE
New 'Tools' menu

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#194]
Add new menu at bottom right of screen. Heading 'Tools'. Options in menu:

KB+ (goes to http://service.kbplus.ac.uk/kbplus/myInstitutions/index)
Sandbox (goes http://test.kbplus.ac.uk/kbplus/myInstitutions/index - possibly)
Explorer (goes to http://knowplus.edina.ac.uk/kbplus/ - currently anyway)

**Comment by ianibo** [comment]
Can you point me at the HTML/Styling for this?

**Comment by ostephens** [comment]
It's part of the stuff M&M are working on - see email from Chris 10th August
