### ISSUE TITLE
Field for specified number of concurrent users no longer displays

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#196]
The "Concurrent Access" key value field in the licence details page (e.g. http://knowplus.edina.ac.uk/kbplus/licenseDetails/index/13) can be set to 'Specified' and used to then prompt for a number. This prompt is no longer displaying - needs to be reinstated

**Comment by ianibo** [comment]
Think this needs to be referred back to @nbrock but will investigate

**Comment by ianibo** [comment]
Fixed by @nbrock suggestion to wrap status editable in it's own span.
