### ISSUE TITLE
More info in 'Subscriptions' display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#20]
Is it possible to add more detail to the 'Subscriptions' display?
http://projects.k-int.com/kbplus/subscription/list

Ideally would show:
Vendor
Subscribing Org
Sub name (or package)

I'd suggest don't need start/end dates in list display, but would like in full display
Vendor/Subscribing Org also added to the 'full' subscription display http://projects.k-int.com/kbplus/subscription/show/1

**Comment by ianibo** [comment]
Can add subscription name, no problem.
Subscribing Org, probably
Vendor: Can you suggest the proper access path to get to vendor from subscription? Sub -> many Sub-Package -> Package -> Vendor?

**Comment by ostephens** [comment]
Vendor: Looks like this is an oversight on my part. Each subscription should have a subscribing org and a vendor (vendor is different to the content provider which is the path you describe above). However, looking at the data import docs, I haven't mentioned vendor. I may have overlooked this, or perhaps I realised we don't necessarily know who the vendor is for a given sub.

I'll need to revisit this - but not going to be sorted by Thursday, so ignore the Vendor aspect for now!

**Comment by ianibo** [comment]
Roger, thanks!
