### ISSUE TITLE
Display of 'Document Type' on Doc screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#200]
e.g. on http://knowplus.edina.ac.uk/kbplus/licenseDetails/documents/13 and http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/documents/238

The 'Type' column currently displays 'Licence' no matter what 'Document Type' you select when adding a document (e.g. If you use the 'Add new Document' button from http://knowplus.edina.ac.uk/kbplus/licenseDetails/index/13, the form prompts you for a document type of 'Licence', 'General' or 'Addendum'

**Comment by ianibo** [comment]
Fixed.. was actually problem with generic doc upload form setting type on context instead of doc.
