### ISSUE TITLE
Consortium membership data incorrect

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#214]
It looks like all orgs within the KB+ have been linked to NESLI2 with a consortium combo link - see http://knowplus.edina.ac.uk/kbplus/org/show/5

Only members of NESLI2 should be linked in this way

Also neither SHEDL nor WHEEL have their members linked to them using the consortium combo link.

The consortia memberships are defined in the file:

KB+/System - Data/Current/Subscribing Orgs/consortium.csv

The import is defined in KB+/Spec - Data & Data Model/120618 Data Import.doc

<table>
<tr>
<th>Place in file</th><th>Name in file</th><th>Data entity/element</th><th>Other data population</th><th>Notes</th></tr>
<tr><td>col1</td><td>consortia_id</td><td><Combo>/Link 1</td><td>Create <Combo> to link the consortia <org> entity identified by this ID(<Combo>/Link 1) to the <org> entity identified in col2 (<Combo>/Link 2) with a <ComboType> as specified in col3 (in this case always ‘consortium’ </td><td>Presumably will need to look up the correct internal ID via the consortia_id</td></tr>
<tr><td>col2</td><td>member_jc_id</td><td><Combo>/Link 2</td><td></td><td>Presumably will need to look up the correct internal ID via the  member_jc_id</td></tr>
<tr><td>col3</td><td>link_type</td><td><ComboType></td></tr>
</table>

**Comment by ianibo** [comment]
Heya

Is this something thats ever worked do you know? or something thats broken
recently?

Also, the code has a hard-coded link for NESLI2 membership, which I rather
distinctly recall was in one of the spec documents for orgs import, but
doesn't seem to be there now.. Have the specs been "cleaned up"?

On 16 August 2012 18:16, Owen Stephens notifications@github.com wrote:

> It looks like all orgs within the KB+ have been linked to NESLI2 with a
> consortium combo link - see http://knowplus.edina.ac.uk/kbplus/org/show/5
> 
> Only members of NESLI2 should be linked in this way
> 
> Also neither SHEDL nor WHEEL have their members linked to them using the
> consortium combo link.
> 
> The consortia memberships are defined in the file:
> 
> KB+/System - Data/Current/Subscribing Orgs/consortium.csv
> 
> The import is defined in KB+/Spec - Data & Data Model/120618 Data
> Import.doc
>  Place in file Name in file Data entity/element Other data population
> Notes  col1 consortia_id /Link 1 Create to link the consortia entity
> identified by this ID(/Link 1) to the entity identified in col2 (/Link 2)
> with a as specified in col3 (in this case always ‘consortium’ Presumably
> will need to look up the correct internal ID via the consortia_id  col2
> member_jc_id /Link 2 Presumably will need to look up the correct internal
> ID via the member_jc_id  col3 link_type
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/214.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
I'm afraid I don't know if it has worked in the past. It came to light today after Edina tried to write a report based on consortium membership - which didn't work as expected. Apologies it wasn't picked up earlier.

Linking orgs to NESLI2 automatically is part of the spec (in the Subscribing Organisations section of the data import spec). "Create <Combo> to link the NESLI2 <org> entity (<Combo>/Link 1) to the new <org> entity (<Combo>/Link 2) with a <ComboType> of “Consortium” "

However - this should only apply to those orgs created via this import - it looks like all orgs within KB+ are being linked to NESLI2 no matter how they are created (e.g. content providers and publishers)

**Comment by ianibo** [comment]
> However - this should only apply to those orgs created via this import -
> it looks like all orgs within KB+ are being linked to NESLI2 no matter how
> they are created (e.g. content providers and publishers)

How can I tell one org type from another in the orgs xml file?

>  —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/214#issuecomment-7801102.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Which orgs xml file?

Should be taken from /KB+/System - Data/Current/Subscribing Orgs/subscribing organisations.csv

**Comment by ianibo** [comment]
Ah I see...

Currently the nesli membership is applied in phase 2 of the import.. after
all the files have been read and the intermediate objects been created.

This requires a change to work the way you describe.

On 16 August 2012 23:12, Owen Stephens notifications@github.com wrote:

> Which orgs xml file?
> 
> Should be taken from /KB+/System - Data/Current/Subscribing
> Orgs/subscribing organisations.csv
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/214#issuecomment-7801326.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
What if remove requirement to auto-link to NESLI2 and only use memberships as specified in consortium.csv file?

**Comment by ianibo** [comment]
That would deffo be the best solution from my perspective if thats doable?

**Comment by ostephens** [comment]
Yes - absolutely fine

**Comment by ostephens** [comment]
Memberships as specified in the consortium membership file still don't seem to have loaded properly in latest upload? (if this is the latest data?) http://knowplus.edina.ac.uk/kbplus/org/show/5

**Comment by ianibo** [comment]
Can you explain why this isn't right?

On 20 August 2012 12:59, Owen Stephens notifications@github.com wrote:

> Memberships as specified in the consortium membership file still don't
> seem to have loaded properly in latest upload? (if this is the latest
> data?) http://knowplus.edina.ac.uk/kbplus/org/show/5
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/214#issuecomment-7867085.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
(For example, if I look at

http://knowplus.edina.ac.uk/kbplus/org/show/190

The links seem to correspond 1:1 with those defined in the consortia.csv
file... Is it something structural or something else about the nesli data?

Wheel less so (http://knowplus.edina.ac.uk/kbplus/org/show/186) But I
suspect thats because the org-ids aren't connecting up.
)

On 20 August 2012 13:40, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Can you explain why this isn't right?
> 
> On 20 August 2012 12:59, Owen Stephens notifications@github.com wrote:
> 
> > Memberships as specified in the consortium membership file still don't
> > seem to have loaded properly in latest upload? (if this is the latest
> > data?) http://knowplus.edina.ac.uk/kbplus/org/show/5
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/214#issuecomment-7867085.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
e.g. first linked org is:

Consortium Association of Avian Veterinarians

This is a publisher. It isn't listed in the KB+/System - Data/Current/Subscribing Orgs/consortium.csv file and should not be linked to NESLI2 as a consortium member

**Comment by ostephens** [comment]
Hmm - http://knowplus.edina.ac.uk/kbplus/org/show/190 I don't see any Orgs (except NESLI2 - which is incorrect) listed as belonging to SHEDL consortium? Are we seeing different data?

I see:

Name
SHEDL
Outgoing Combos
Consortium NESLI2
Other org links
Subscription: EUP Complete Collection No New Titles 2012 SHEDL (Subscription Consortia)
Subscription: Project Muse Standard Collection 2012-2013 SHEDL (Subscription Consortia)
Subscription: CUP Full Package 2010-2012 SHEDL (Subscription Consortia)
Subscription: Project Muse Basic Research Collection 2012-2013 SHEDL (Subscription Consortia)
Subscription: Springer Open Access 2011_2012 SHEDL (Subscription Consortia)
Subscription: Berg Visual Culture Collection 2011-2012 SHEDL (Subscription Consortia)
Subscription: ACS collection 2012-2012 SHEDL (Subscription Consortia)
Subscription: Project Muse Humanities Collection 2012-2013 SHEDL (Subscription Consortia)
Subscription: ACS Other Titles 2012-2012 SHEDL (Subscription Consortia)
Subscription: Project Muse Social Science collection 2012-2013 SHEDL (Subscription Consortia)
Subscription: OUP Journals Collections 2012-2013 SHEDL (Subscription Consortia)
Subscription: Springer Option 1 Closed Consortium Agreement 2011_2012 SHEDL (Subscription Consortia)
Subscription: Project Muse Premium Collection 2012-2013 SHEDL (Subscription Consortia)
Subscription: OUP Free Titles 2012-2013 SHEDL (Subscription Consortia)
Subscription: EUP Complete Collection 2012 SHEDL (Subscription Consortia)
Subscription: Project Muse Humanities Collection 2012-2013 SHEDL (Subscription Consortia)
Subscription: Springer Open Access Hybrid 2011_2012 SHEDL (Subscription Consortia)
Subscription: Berg Full Collection 2012 SHEDL (Subscription Consortia)
Imp Id
5027d900e4b0d2e61bbd1308

**Comment by ianibbo** [comment]
You don't see 18 links on that page listed as other org
links....(Subscription consortia)

Is this not right? What should it be?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Ah yea... Maybe I should go sleep before looking at this

On 20 August 2012 13:58, Owen Stephens notifications@github.com wrote:

> e.g. first linked org is:
> 
> Consortium Association of Avian Veterinarians
> 
> This is a publisher. It isn't listed in the KB+/System -
> Data/Current/Subscribing Orgs/consortium.csv file and should not be linked
> to NESLI2 as a consortium member
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/214#issuecomment-7868223.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Hey owen.. did the update and re-import resolve this one? Can I close?

**Comment by ostephens** [comment]
Yes - all looks good, please close
