### ISSUE TITLE
"Home" page should be http://knowplus.edina.ac.uk/kbplus/myInstitutions/dashboard

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#220]
Currently "Home" (e.g. in breadcrumbs) takes you to:
http://knowplus.edina.ac.uk/kbplus/

which displays a search box for searching in the 'data explorer' area

Suggest ideally http://knowplus.edina.ac.uk/kbplus/ would take user to http://knowplus.edina.ac.uk/kbplus/myInstitutions/dashboard

At the least any links to 'Home' in breadcrumbs should result in the user ending up at http://knowplus.edina.ac.uk/kbplus/myInstitutions/dashboard

**Comment by ianibo** [comment]
The problem with the first suggestion is that myInstitutions/dashboard is a secured page, so isn't really appropriate for display at http://knowplus.edina.ac.uk/kbplus/  need a better thought out solution for that. Changed rest of links.
