### ISSUE TITLE
Document download broken on live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#223]
For documents in the doc store that are part of the data import process (e.g. from http://service.kbplus.ac.uk/kbplus/licenseDetails/index/1 there is a doc AIP NESLi2 Offer 2011 to 2012 Final.doc)

Download is broken - get the error:
Error 500: Internal Server Error

URI
/kbplus/docstore/index
Class
java.lang.NullPointerException
Message
null
Trace

```
Line | Method
```

->>  251 | <init>            in java.io.File

---

|    115 | <init>            in java.util.zip.ZipFile
|    170 | streamResponseDoc in com.k_int.kbplus.DocstoreService
|     98 | retrieve          in     ''
|     10 | index . . . . . . in com.k_int.kbplus.DocstoreController
|   1110 | runWorker         in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run               in java.lang.Thread

**Comment by ianibo** [comment]
Fixed by mod_proxy config. could use some defensive code around this tho.
