### ISSUE TITLE
Editing licence name does not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#227]
Editing licence name e.g. from http://service.kbplus.ac.uk/kbplus/licenseDetails/index/13 no longer works (did work previously). You can click and make changes, but when you click 'OK' it reverts back to previous name

**Comment by ostephens** [comment]
Actually none of the click to edit fields on the licence details screen seem to work this morning

**Comment by ianibo** [comment]
Corrected proxy config. Seems to have resolved this and other click to edit issues.
