### ISSUE TITLE
Current subscriptions not displaying

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#237]
E.g. on http://service.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentSubscriptions

Should list two subs
http://service.kbplus.ac.uk/kbplus/subscriptionDetails/index/244
http://service.kbplus.ac.uk/kbplus/subscriptionDetails/index/245

But just blank

**Comment by ianibo** [comment]
Fixed - Caused by addition of deleted flags.
