### ISSUE TITLE
Can't add a licensor to a licence when creating from scratch

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#241]
Not implemented - challenge to know what to allow when attaching an org to a role - and how to make it easy to find/choose orgs to attach to a role

**Comment by ostephens** [comment]
User story in Phase 2

**Comment by ianibo** [comment]
Think this one needs to go back to trello and not be listed as a bug.. it's
tied up with click to edit-ness and the need to have a server object before
we can click-to-edit so it's more involved than "fix a bug"

On 9 October 2012 12:19, Owen Stephens notifications@github.com wrote:

> User story in Phase 2
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/241#issuecomment-9257109.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Agreed - have closed it for that reason
