### ISSUE TITLE
Batch changes on issue entitlements not working

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#242]
e.g. from http://service.kbplus.ac.uk/kbplus/subscriptionDetails/index/246 try to make batch change - when click 'Apply batch changes' nothing happens

**Comment by ostephens** [comment]
I'm an idiot - helps if you select one or more rows to apply the batch edit to. Sorry

**Comment by ianibbo** [comment]
hehe you're not actually the first person to fall foul of that.. had my own
panic at one stage.. Maybe we should have an alert if you hit the go button
and don't have anything selected?
