### ISSUE TITLE
Link to 'Data Explorer' from Tools menu wrong

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#244]
Currently links to http://knowplus.edina.ac.uk/kbplus/ should be http://service.kbplus.ac.uk/kbplus

**Comment by ostephens** [comment]
Actually scratch that - there is no decent URL for the 'Data Explorer', and always available when you are in the KB+ application, so remove the Data Explorer link from the Tools menu

**Comment by ianibbo** [comment]
Ok..

Just done a redeploy with the last change.. Can we group all these changes
up and I'll push up a new version once they are all in.. Say 17:00?

Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - couple of other changes:
KB+ Icon in header (top right) can now link to http://service.kbplus.ac.uk (instead of http://service.kbplus.ac.uk/kbplus)
In Tools menu KB+ Sandpit link should go to http://test.kbplus.ac.uk/kbplus/myInstitutions/index (not http://test.kbplus.edina.ac.uk/kbplus/myInstitutions/index as currently)

**Comment by ianibo** [comment]
Ok.. this will have to be last change I think...

KB+ Icon in header (top right) can now link to
http://service.kbplus.ac.uk(instead of

> http://service.kbplus.ac.uk/kbplus)
> 
> In Tools menu KB+ Sandpit link should go to
> http://test.kbplus.ac.uk/kbplus/myInstitutions/index (not
> http://test.kbplus.edina.ac.uk/kbplus/myInstitutions/index as currently)

Could be my eyes, these look like the same link? Mean service.kbplus.ac.uk?

>  —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/244#issuecomment-8304203.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Nope.. I see the difference now.. Code blind :/

On 5 September 2012 17:11, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Ok.. this will have to be last change I think...
> 
> KB+ Icon in header (top right) can now link to http://service.kbplus.ac.uk(instead of
> 
> > http://service.kbplus.ac.uk/kbplus)
> > 
> > In Tools menu KB+ Sandpit link should go to
> > http://test.kbplus.ac.uk/kbplus/myInstitutions/index (not
> > http://test.kbplus.edina.ac.uk/kbplus/myInstitutions/index as currently)
> 
> Could be my eyes, these look like the same link? Mean service.kbplus.ac.uk
> ?
> 
> >  —
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/244#issuecomment-8304203.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Toolbox link done... are we sure about top level KB+ icon linking to / and not /kbplus? Doing so will take the user out of the app context. Admittedly, they can always just click home but usually home and the icon go to the same place.. Guess this is all tied up with the artificial static distinction really. Please just confirm.

**Comment by ostephens** [comment]
See #262
