### ISSUE TITLE
Public Exports page on test needs updating to match live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#250]
The public exports page on test http://test.kbplus.ac.uk/exports (http://test.kbplus.ac.uk/kbplus/publicExport) is currently using outdated html. Should be updated to use the same as the current live version (http://service.kbplus.ac.uk/kbplus/publicExport)

See also issue 249 - there are updates to make to navigation options on live and test

**Comment by wadec** [comment]
Hey Ian,
Please let me know if you need anything from us! Hope all going OK,
Chris

Sent from Samsung Mobile on O2

Owen Stephens notifications@github.com wrote:

The public exports page on test http://test.kbplus.ac.uk/exports (http://test.kbplus.ac.uk/kbplus/publicExport) is currently using outdated html. Should be updated to use the same as the current live version (http://service.kbplus.ac.uk/kbplus/publicExport)

See also issue 249 - there are updates to make to navigation options on live and test
