### ISSUE TITLE
Link to 'Reports' from Manage menu on Test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#252]
On the test version, this should go to http://test.kbplus.ac.uk/reports not http://service.kbplus.ac.uk/reports

**Comment by ostephens** [comment]
This was reported by Des, haven't had chance to confirm this is still an issue

**Comment by ostephens** [comment]
Won't be a disaster if not done for Monday am

**Comment by ianibbo** [comment]
This is actually more problematic, given that it's not an app URL thats
being modified which means I end up with a horrid switch of per environment
pages in the code..

I'll have a go at setting it to /../reports but I need the chance to verify
approaches with some of these issues.. some are not as easy as you might be
led to believe

**Comment by ostephens** [comment]
Ok. I don't want to change too much at thus stage so please reassign for the 21st milestone. On Monday we can always get Des to shove a redirect in for now and work out the overall approach later

Owen

**Comment by ostephens** [comment]
Seems to work now - can be closed if you are happy
