### ISSUE TITLE
Implement different colour scheme on test than on live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#253]
See comments from Chris:
The following selector could be used for the time being to override the standard header for the sandbox, assuming the code is included after the other CSS include (it's currently green - David has requested that we look at a sandy / more playful version of this) :

.navbar-inner.explorer {
    background-color: #007A5E;
    background-image: url('../images/header_graphic_green.jpg');
}

**Comment by wadec** [comment]
Hey Ian, FYI – the sandpit also requires the following overriding selector to make the KB+ title white:

.navbar .brand {
color: #fff;
}

Nathan can add this to the bootstrap css too, but just in case you end up creating a new separate include.
Of course in time all this may change into a sandy beach theme ;-)

Cheers,
Chris

**Comment by ianibbo** [comment]
Wotcher Chris,

Thanks for this.. Yep, its in a separate include now (sandbox.css) I'll add
it.

Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Can this be closed now? Think it's been successfully implemented?

**Comment by ianibo** [comment]
Happy to close it.

**Comment by wadec** [comment]
We’ve supplied new code/gfx for the colour scheme, so just waiting for our latest branch to be merged in when Ian gets a moment.
Thanks,
Chris

**Comment by ianibo** [comment]
Merged.. Just waiting for the nod from owen that I'm ok to update live this
eve.

On 17 September 2012 12:34, wadec notifications@github.com wrote:

> We’ve supplied new code/gfx for the colour scheme, so just waiting for our
> latest branch to be merged in when Ian gets a moment.
> Thanks,
> Chris
> 
> From: Owen Stephens [mailto:notifications@github.com]
> Sent: 17 September 2012 11:41
> To: k-int/KBPlus
> Cc: Chris Wade
> Subject: Re: [KBPlus] Implement different colour scheme on test than on
> live (#253)
> 
> Can this be closed now? Think it's been successfully implemented?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/k-int/KBPlus/issues/253#issuecomment-8610286>.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/253#issuecomment-8611455.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
