### ISSUE TITLE
Sandbox: 'Manage' dropdown text re: Affiliations

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#255]
When the user clicks on the 'Manage' dropdown menu in the Sandbox they see this wording: "Please use the manage affiliations option to request access to your home institution" (see screenshot saved under 'KB+ > Spec - Forms' in Dropbox) - I don't think the user will know where they need to go from those instructions. Suggest we either:
a) add a hyperlinked 'Affiliations' menu item under the wording which goes to: http://test.kbplus.ac.uk/kbplus/profile/index
b) change to wording to (for example) "Request access to your home institution by going to your Profile page" (ideally with a hyperlinked 'Your Profile' menu item which goes to: http://test.kbplus.ac.uk/kbplus/profile/index

**Comment by ianibo** [comment]
Will do, although usual users with real affiliations will never see this page, only pseudo UKFAM users who don't really have a home institution will see it (Although thats most people testing, which skews things I guess).
