### ISSUE TITLE
On Public Exports page 'KBART' should be all in upper case

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#257]
On http://service.kbplus.ac.uk/kbplus/publicExport. Currently uses 'KBart'. Should be 'KBART'

**Comment by ianibbo** [comment]
Heya..

There's something else going on with the license files...

I think maybe they all used to be at the ./ level in the zip file, and now
some seem to be in subdirectories? Unfortunately this is confusing the
bagit construction a little.. Can you let me know what the proper structure
of the zip file should be? I'll make it work with that structure and we'll
see where we go from there

(I think it's probably better if they don't have subdirectories, as the
file names are used for the download filenames and could cause platform
problems I guess)

Cheers
e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Sorry - this is entirely my fault (I know - you can hardly believe it). I'll redo, double check and confirm I've corrected

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936
