### ISSUE TITLE
KB+ link at top left should now point to dashboard

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#262]
The KB+ link in the top left (next to the Data Explorer/Manage menus) currently links to ./kbplus
This should be changed to link to the Dashboard ./kbplus/myInstitutions/dashboard

**Comment by ianibbo** [comment]
this is possible, but I don't particularly think it's a good idea.

I'll make the change, but this has to be the last of the changes in the URL
structure area I think.. it's getting silly now.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
