### ISSUE TITLE
Link to 'Help' from Manage menu

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#263]
We are going to host the KB+ documentation on a Wordpress blog. The address for the 'Help' page will be https://knowledgebaseplus.wordpress.com/kb-support/
The link to Help is in the 'Manage' menu, and currently points to http://service.kbplus.ac.uk/help

I have a slight preference for keeping the link pointing at ./help but redirecting to the help page on the blog. However would also be happy if menu link points directly to the new address if you feel this is preferable or easier.

**Comment by ianibbo** [comment]
Great... more infrastructure :(
