### ISSUE TITLE
Notes shared with community only visible if you are affiliated to org that owns underlying entity?

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#266]
If you add a note shared with 'community' it should be visible to all on the system. This isn't currently happening.

I've added a shared note to the following items:
http://service.kbplus.ac.uk/kbplus/licenseDetails/index/17
http://service.kbplus.ac.uk/kbplus/licenseDetails/index/18

Only those affiliated to the University of Westminster can see the note attached to http://service.kbplus.ac.uk/kbplus/licenseDetails/index/17 on the Dashboard or Alerts pages (http://service.kbplus.ac.uk/kbplus/myInstitutions/dashboard and http://service.kbplus.ac.uk/kbplus/myInstitutions/index)

When notes are shared with the community they should be visible to all users on the Dashboard and Alerts pages

**Comment by ianibo** [comment]
I thought this was the requirement.. otherwise you will see everything everyone has commented on, even if it's nothing to do with you. If you really want everything to be visible to everyone, please confirm and I'll change.

**Comment by ostephens** [comment]
Don't want everything visible to everyone. Want notes shared with Community to be visible to everyone and to appear on the Dashboard and Alerts page.

Private notes should work as currently.

Does that make sense?

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Ah I see.. I thought this was about affiliations and visibility.. OK.. will change.

**Comment by ianibo** [comment]
Tried calling etc.. Currently we actually list licenses with public notes on the dashboard so that the notes are "In context". If you could just confirm for me exactly what should be shown for a public note in the context of the dash. ta.
