### ISSUE TITLE
Cannot add comments to notes on Licence or Subscription details pages

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#267]
E.g. on http://service.kbplus.ac.uk/kbplus/licenseDetails/index/18 there is a 'Notes' section with a shared note.  Below the note it says "0 Comment(s)" with the text linked to #modalComments. Clicking this link has not effect - it should pop up a lightbox to add a comment to the note

**Comment by ostephens** [comment]
The same functionality is present in the Dashboard http://service.kbplus.ac.uk/kbplus/myInstitutions/dashboard - the comments button is styled differently and works as intended.

**Comment by ostephens** [comment]
This has changed in latest update (tested on test.kbplus.ac.uk). Now clicking the 'Comments' link from the Licence details page brings up a Comments lightbox but it is empty - no place to add comments etc.

**Comment by ostephens** [comment]
This is still an issue on test.kbplus.ac.uk. E.g.
http://test.kbplus.ac.uk/kbplus/licenseDetails/index/1

Clicking on the "Comments" link on a shared note currently does nothing (no pop-up)

Same issue also on Subscription details screen - e.g. :
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/247

Link from Dashboard works fine

**Comment by ianibo** [comment]
Tested and unable to repeat (Added note to both the above license and sub, and commented on that note). If still an issue, please reopen and supply browser details and user account as it could be linked to permissions. Closing for now tho.
![working_comments_on_notes](https://f.cloud.github.com/assets/53283/36643/2c24812e-535a-11e2-9dd0-4659d03ce7fe.png)

**Comment by ostephens** [comment]
Agree this is fixed
