### ISSUE TITLE
jQuery UI Custom Theme

### ISSUE THREAD

**Issue by nathanbrock** [k-int/KBPlus#268]
For the purposes of the DateUI widget. Custom theme with KBPlus colouring and styles needs to overwrite the existing theme that is in use. Needs to overwrite /static/plugins/jquery-ui-1.8.15/jquery-ui/themes/ui-lightness/jquery-ui-1.8.15.custom.css.

Custom Theme : http://cl.ly/0F2C2I0f1F3N

Cheers!

**Comment by ostephens** [comment]
Has this been done?

**Comment by ianibo** [comment]
@nbrock I've added a commented out section of the appropriate config stanza to the bottom of Config.groovy and commited it on the dev branch. Hopefully will let you override the necessary css.

**Comment by ostephens** [comment]
I'm going to close this - seems like we are past any further action happening here and if fix needed can be applied as described by Ian
