### ISSUE TITLE
Subscriptions taken import errors

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#27]
Seeing lines in the ST 'BAD' files like:
[, Journal of Instrumentation, , 1748-0221, 01/04/2006, , , , , , , ],"row 13/45 - Unable to locate ISSN for title """
[, Journal of Optics, 2040-8978, 2040-8986, 01/01/2001, , , , , , , ],"row 16/45 - Unable to locate ISSN for title "2040-8978""

in the first case the eISSN is correctly recorded in the data, in the second case the ISSN is correctly recorded (and also in the equivalent SO http://projects.k-int.com/kbplus/titleInstance/show/416)

Haven't checked other rows - but want to work out what is going on here before investigating all these

**Comment by ianibo** [comment]
This looks like it could be my problem and not yours.. double checking now

**Comment by ianibo** [comment]
Bit worried about this.. My intermediate database shows

{ "_id" : ObjectId("4fbce7e8b7600d59df2a8686"), "title" : "Journal of Optics", "identifier" : [     {   "type" : "ISSN",    "value" : "0972-8821" },    {   "type" : "eISSN",   "value" : "0974-6900" } ], "publisher" : ObjectId("4fbce769b760976658be2c09"), "lastmod" : NumberLong("1337780200830") }

Which does have an ISBN, but not the one listed in the bad file, or shown in the interface.

**Comment by ostephens** [comment]
Same title, different ISSN should result in a different 'Title Instance'

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Ah ok.. think it's just that I'd stopped that import half way through to restart with new rules.. Spotted these in import files.. Different journal same title?

kb_plus_datafiles/springer_OPTION1CLOSED CONSORTIUM AGREEMENT_2011_2012_nesli2.csv:Journal of Optics,0972-8821,0974-6900,2009,38,,,,,,,,,,,Springer Link,host,http://www.springerlink.com/content/0972-8821,Springer Link,administrative,
kb_plus_datafiles/springer_OPTION1CLOSED CONSORTIUM AGREEMENT_2011_2012_shedl.csv:Journal of Optics,0972-8821,0974-6900,2009,38,,,,,,,,,,,Springer Link,host,http://www.springerlink.com/content/0972-8821,Springer Link,administrative,

**Comment by ianibo** [comment]
Yep.. all OK I think

**Comment by ianibo** [comment]
Need to be careful because I can feel we're starting to thrash a bit with all these changes.

**Comment by ostephens** [comment]
Also noting that also "Journal of Optics" has both ISSN and eISSN in SO offered file (IOP_option1_2011_2012_nesli2.csv and IOP_option2_2011_2012_nesli2.csv) the eISSN (2040-8986) doesn't seem to be appearing in the identifiers table

**Comment by ianibo** [comment]
Over eager matching of titles when no matching identifier was falling back to title and merging the 2. Removed.

**Comment by ostephens** [comment]
OK - yes, we have to rely on IDs for journals, titles too dodgy!

**Comment by ianibo** [comment]
Latest import with the eager matching seems to have outed this problem, and significantly reduced the number of BAD files.

**Comment by ostephens** [comment]
Closing this for a clean start - but still seeing issues
