### ISSUE TITLE
Cannot add integer number to 'Concurrent Access' key value when set to 'Specified'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#273]
E.g. from http://www.kbplus.ac.uk/kbplus/licenseDetails/index/24
When change the 'Concurrent Access' key value to 'Specified' should display box to set integer value - this does not display (tested in latest versions of Safari & Chrome on Mac OS X Mountain Lion)

**Comment by ianibo** [comment]
Should be fixed.

**Comment by ostephens** [comment]
Yes - confirmed fixed

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936
