### ISSUE TITLE
General issue with click to edit fields not displaying/appearing blank after edit carried out

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#277]
See #276 and #274. Also editing a subscription name (e.g. on http://www.kbplus.ac.uk/kbplus/subscriptionDetails/index/250) then after saving the display shows no name at all until you refresh the page

**Comment by ianibo** [comment]
Need to redeploy with latest M&M changes, then retest and re-raise please. Will ping you once redeployed.

**Comment by ianibo** [comment]
Redeployed and issue still present on subscription details. Q: Can you point out where else this happens? Title says "General" issue, but license details click to edits seem ok.. am I missing something?

**Comment by ianibo** [comment]
#276 and #274 are both very separate cases as they have custom code to implement the special icon handling and licence number fields. Can you just confirm for me (this being the case) that there are just these three unrelated issues or have I missed something? ta.

**Comment by ostephens** [comment]
OK - if #276 and #274 unrelated then not a general issue - just three instances I guess - those described in #276 and #274 and the Subscription Name described in this issue.
