### ISSUE TITLE
Pagination when >10 (?) pages does not work correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#278]
E.g. pagination at the bottom of  http://www.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/addSubscription

In the pagination navigation it has:
'1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '..' '15'

Navigation to pages 1-10 via this method work fine. However clicking the '..' option takes you to what seems like a random position (offset=6) and clicking '15' takes to what should be page 2 (offset=10).

If you click on '10' you see options in the page navigation for pages 11, 12, 13, and 14 that work correctly.

If you then click on '14' you see navigation to '15' that works correctly

**Comment by ianibo** [comment]
Pagination plugin has changed to prevent clicking on ... seems to work find on dev now.
