### ISSUE TITLE
Get error when accessing http://test.kbplus.ac.uk/kbplus/myInstitutions/index

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#279]
This worked before the latest update (c. 16:30 24/09/2012). Now gives a 500 with the error:

Error 500: Internal Server Error
URI
/kbplus/myInstitutions/index
Class
java.lang.NullPointerException
Message
Cannot get property 'shortcode' on null object
Trace
    Line | Method
->>   56 | runWorker in /myInstitutions/index.gsp

---

Caused by NullPointerException: Cannot get property 'shortcode' on null object
->>   37 | doCall    in gsp_demo_myInstitutionsindex_gsp$_run_closure2

---

|     69 | run       in gsp_demo_myInstitutionsindex_gsp
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

**Comment by ianibo** [comment]
Is this from just now? I had this briefly during the update but it seemed
to vanish.. I assume there is something on your dashboard that isn't on
mine then.. Not sure how to proceed

On 24 September 2012 17:12, Owen Stephens notifications@github.com wrote:

> This worked before the latest update (c. 16:30 24/09/2012). Now gives a
> 500 with the error:
> 
> Error 500: Internal Server Error
> URI
> /kbplus/myInstitutions/index
> Class
> java.lang.NullPointerException
> Message
> Cannot get property 'shortcode' on null object
> Trace
> Line | Method
> 
> ## ->> 56 | runWorker in /myInstitutions/index.gsp
> 
> Caused by NullPointerException: Cannot get property 'shortcode' on null
> object
> 
> ## ->> 37 | doCall in gsp_demo_myInstitutionsindex_gsp$_run_closure2
> 
> | 69 | run in gsp_demo_myInstitutionsindex_gsp
> | 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
> | 603 | run in java.util.concurrent.ThreadPoolExecutor$Worker
> ^ 722 | run . . . in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/279.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Fixed.. missed that it was on the alerts action, thought it was happening at login. Once I realised easy to fix.
