### ISSUE TITLE
Non-fatal errors on import

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#28]
Would it be possible to differentiate between 'failed import' and 'warning' lines in the "BAD" files?

**Comment by ianibo** [comment]
To be honest, non failed shouldn't be appearing in the bad files.. I'll scratch them.

**Comment by ostephens** [comment]
Done in latest import. Thanks. If you want to dump any 'warnings' somewhere else then I'll look at those as well when time allows
