### ISSUE TITLE
"Delete Note" button in Subscription Details should only display when note selected

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#280]
E.g. from http://test.kbplus.ac.uk/kbplus/subscriptionDetails/notes/248
The 'Delete Note' button appears even when you haven't selected any notes (this is different to the behaviour on a Licence - e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/16 where the Delete note option only appears when you select a note via a checkbox

**Comment by ianibo** [comment]
Tested and button now behaves as expected.
