### ISSUE TITLE
Change to Public Export reports

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#281]
The Public Export files should contain the following columns/data:
# Col name -> KB+ field

publication_title -> (as currently)
print_identifier -> (as currently)
online_identifier -> (as currently)
date_first_issue_online -> (as current but truncated to YYYY-MM-DD)
num_first_vol_online -> (as currently)
num_first_issue_online -> (as currently)
date_last_issue_online -> (as current but truncated to YYYY-MM-DD)
num_last_vol_online -> (as currently)
num_last_issue_online -> (as currently)
title_url -> title_instance_package_platform.tipp_host_platform_url
first_author -> (blank)
title_id -> (if there is a DOI available via TI->Identifier link, use first occurrence, otherwise blank)
embargo_info -> (as currently)
coverage_depth -> title_instance_package_platform.tipp_coverage_depth
coverage_notes -> title_instance_package_platform.tipp_coverage_note
publisher_name -> (if there is an org available via TI->Org link with role publisher, use org_name from first occurrence - for example see http://www.kbplus.ac.uk/kbplus/titleInstance/show/4521 which has a linked Org as publisher of "Annual Reviews". Otherwise blank)

**Comment by ostephens** [comment]
Ping me if you have any Qs

**Comment by ianibbo** [comment]
Okies.. there's a fair bit more on this list than "adding title URL" so
might take me more than a day to go through each one and figure out whats
there currently and what needs to be changed if anything.

**Comment by ostephens** [comment]
OK - do you want me to find out from Liam is priority is to add the URL or to have all the fields?

**Comment by ostephens** [comment]
My view would be let's do the whole lot and get it done even if it takes a little longer

**Comment by ianibbo** [comment]
All done apart from publisher..

publisher_name -> (if there is an org available via TI->Org link with role
publisher, use org_name from first occurrence - for example see
http://www.kbplus.ac.uk/kbplus/titleInstance/show/4521 which has a linked
Org as publisher of "Annual Reviews")

Is the link to 4521 actually there, or something that we expect to be
there? #bit confused#

**Comment by ostephens** [comment]
Sorry the reference to http://www.kbplus.ac.uk/kbplus/titleInstance/show/4521 was just to point to an example of a TI that had an Org linked via a Publisher role.

**Comment by ianibo** [comment]
Changes made as requested and deployed to test.
