### ISSUE TITLE
User has edit permissions when should be 'read only'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#284]
The user "TestUserA: UoW ReadOnly [HH] / oaYDLonYlJRXD3hKbU30N1mn4YQ=@edina.ac.uk"
has a read only members of the University of Westminster.

However, they are able to create and edit licences/subscriptions linked to that Organisation. e.g. can edit http://test.kbplus.ac.uk/kbplus/licenseDetails/index/88

It may (or not) be relevant that the user has a 'Rejected' affiliation request as an Editor also for the University of Westminster

**Comment by ianibo** [comment]
Heya.. this page:

http://test.kbplus.ac.uk/kbplus/licenseDetails/additionalInfo/88

Lists the following

Logged in user permissions
Affiliated via Role Permissions
Affiliated to University of Westminster with role Editor  
edit
--> This org is related to JISC Collections ( Consortium )  
view
Affiliated to University of Westminster with role Read only user  
view
--> This org is related to JISC Collections ( Consortium )  
view

Showing editor role for UoW for this user.. Hence the rejected permission is being allowed to influence the selection.

This is not right!

Question becomes, should we delete rejected permissions, or keep them on the system for all time?

**Comment by ianibo** [comment]
Merged a fix onto test branch for this. Please retest once test updated.
