### ISSUE TITLE
Error messages when trying to view a Licence or Subscription you do not have permission to view

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#286]
No error message is displayed when you try to view a Subscription but do not have appropriate permissions - just a blank screen.

For Licences you get a short message, but just a simple text message against a white background.

It would be better if the message could be displayed in a KB+ styled page (i.e. with menus etc present). At the very least a message for inaccessible subscriptions should be added. Also in Licence error the text:
"You do not have permission to view license XX" - spelling of license needs changing to licence.

**Comment by ianibo** [comment]
Should be fixed, hard for me to retest due to shib setup. Please retest and report/close.
