### ISSUE TITLE
Member of University of Westminster cannot view linked licences/subs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#288]
The following user:
TestUserB: UoW Admin [HH] / tF2UwXx/Z3WL5CLCXhfGFva3pxM=@edina.ac.uk

Has 'editor' membership of the University of Westminster. However, they are unable to view University of Westminster licences/subscriptions - e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/90 gives error "You do not have permission to view license 90"

It may (or not) be relevant that when looking at the showAffiliations screen as an admin the role is listed as "University_of_Westminster:1:deprecated" while when I view the affiliation on the profile page of TestUserB (logged in as TestUserB) it displays as 'Editor'

**Comment by ianibo** [comment]
Something is really wrong with this user.. All the page links seem to be broken for it... Am investigating...

**Comment by ostephens** [comment]
Looking at http://test.kbplus.ac.uk/kbplus/licenseDetails/additionalInfo/90 I get

<table>
        <tr>
          <th>Organisation</th><th>Roles and Permissions</th>
        </tr>
        
          <tr>
            <td>JISC Collections</td>
            <td>
              Connected to this license through role Licensor.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
              </ul>
            </td>
          </tr>
        
          <tr>
            <td>University of Westminster</td>
            <td>
              Connected to this license through role Licensee.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
                  <li>edit 
                      
                        [Granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>edit 
                      
                        [Granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>edit 
                      
                        [Granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
              </ul>
            </td>
          </tr>
        
      </table>

Logged in user permissions

<table>
        <tr>
          <th>Affiliated via Role</th><th>Permissions</th>
        </tr>
        
          <tr>
            <td>Affiliated to University of Westminster with role Editor</td>
            <td>
              <ul>
                
                  <li>edit</li>
                
              </ul>
            </td>
          </tr>
          
            <tr>
              <td> --&gt; This org is related to JISC Collections ( Consortium )</td>
              <td>
                <ul>
                  
                    <li>view</li>
                  
                </ul>
              </td>
            </tr>
          
        
      </table>

**Comment by ianibo** [comment]
Really worried about this info from the additionalInfo Page:

The following organisations are granted the listed permissions from this licence
Organisation    Roles and Permissions
University of Westminster    Connected to this license through role Licensee.
This role grants the following permissions to members of that org whose membership role also includes the permission
edit [Not granted]
view [Granted]
edit [Not granted]
edit [Not granted]
view [Granted]
view [Granted]
view [Granted]
view [Granted]

Not sure why the permission is repeated so many times.. Ongoing..

**Comment by ostephens** [comment]
OK - just to note what you've pasted here is the reverse of what I'm seeing - that is I see all 'edit' permissions as 'granted' and all 'view' permissions as 'not granted' as pasted in comment above.

This oddity of allowing 'edit' but not 'view' also fits with my experience that the user _could_ view && edit 'Public' entities that were linked to Westminster

**Comment by ianibo** [comment]
mysql> select \* from org_perm_share ops, perm p, refdata_value r where ops.perm_id = p.id and ops.rdv_id = r.rdv_id order by r.rdv_id, p.id;
+----+---------+---------+--------+----+---------+------+--------+-------------+----------+-----------+------------------------+
| id | version | perm_id | rdv_id | id | version | code | rdv_id | rdv_version | rdv_icon | rdv_owner | rdv_value              |
+----+---------+---------+--------+----+---------+------+--------+-------------+----------+-----------+------------------------+
|  1 |       0 |       1 |      8 |  1 |       0 | edit |      8 |           0 | NULL     |         2 | Licensee               | 
|  4 |       0 |       1 |      8 |  1 |       0 | edit |      8 |           0 | NULL     |         2 | Licensee               | 
| 12 |       0 |       1 |      8 |  1 |       0 | edit |      8 |           0 | NULL     |         2 | Licensee               | 
|  2 |       0 |       2 |      8 |  2 |       0 | view |      8 |           0 | NULL     |         2 | Licensee               | 
|  5 |       0 |       2 |      8 |  2 |       0 | view |      8 |           0 | NULL     |         2 | Licensee               | 
|  6 |       0 |       2 |      8 |  2 |       0 | view |      8 |           0 | NULL     |         2 | Licensee               | 
| 13 |       0 |       2 |      8 |  2 |       0 | view |      8 |           0 | NULL     |         2 | Licensee               | 
| 14 |       0 |       2 |      8 |  2 |       0 | view |      8 |           0 | NULL     |         2 | Licensee               | 
|  9 |       0 |       1 |     12 |  1 |       0 | edit |     12 |           0 | NULL     |         2 | Subscriber             | 
| 17 |       0 |       1 |     12 |  1 |       0 | edit |     12 |           0 | NULL     |         2 | Subscriber             | 
| 10 |       0 |       2 |     12 |  2 |       0 | view |     12 |           0 | NULL     |         2 | Subscriber             | 
| 18 |       0 |       2 |     12 |  2 |       0 | view |     12 |           0 | NULL     |         2 | Subscriber             | 
| 11 |       0 |       1 |     82 |  1 |       0 | edit |     82 |           0 | NULL     |         2 | Subscription Consortia | 
| 19 |       0 |       1 |     82 |  1 |       0 | edit |     82 |           0 | NULL     |         2 | Subscription Consortia | 
|  3 |       0 |       2 |     83 |  2 |       0 | view |     83 |           0 | NULL     |        18 | Consortium             | 
|  8 |       0 |       2 |     90 |  2 |       0 | view |     90 |           0 | NULL     |         2 | Negotiator             | 
| 16 |       0 |       2 |     90 |  2 |       0 | view |     90 |           0 | NULL     |         2 | Negotiator             | 
|  7 |       0 |       1 |     91 |  1 |       0 | edit |     91 |           0 | NULL     |         2 | Licensing Consortium   | 
| 15 |       0 |       1 |     91 |  1 |       0 | edit |     91 |           0 | NULL     |         2 | Licensing Consortium   | 
+----+---------+---------+--------+----+---------+------+--------+-------------+----------+-----------+------------------------+
19 rows in set (0.01 sec)

SQL for investigating the fix

**Comment by ianibo** [comment]
Erm, thats not right at all then. _super confused_

On 28 November 2012 13:07, Owen Stephens notifications@github.com wrote:

> OK - just to note what you've pasted here is the reverse of what I'm
> seeing - that is I see all 'edit' permissions as 'granted' and all 'view'
> permissions as 'not granted' as pasted in comment above
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/288#issuecomment-10801758.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Thats how it appears to me now.. were it not for the cut-and-paste I'd be
doubting my sanity right now.

On 28 November 2012 13:45, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Erm, thats not right at all then. _super confused_
> 
> On 28 November 2012 13:07, Owen Stephens notifications@github.com wrote:
> 
> > OK - just to note what you've pasted here is the reverse of what I'm
> > seeing - that is I see all 'edit' permissions as 'granted' and all 'view'
> > permissions as 'not granted' as pasted in comment above
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/288#issuecomment-10801758.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Following update on 29th Nov, there is still an issue here. For TestUserB: UoW Admin [HH] / tF2UwXx/Z3WL5CLCXhfGFva3pxM=@edina.ac.uk on sandpit can't access http://test.kbplus.ac.uk/kbplus/licenseDetails/index/87 , on http://test.kbplus.ac.uk/kbplus/licenseDetails/additionalInfo/87 I get:

 <h2>Permissions for user</h2>

```
  <h2>The following organisations are granted the listed permissions from this licence</h2>
```

<table>
        <tr>
          <th>Organisation</th><th>Roles and Permissions</th>
        </tr>
        
          <tr>
            <td>IoP Publishing Limited</td>
            <td>
              Connected to this license through role Licensor.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
              </ul>
            </td>
          </tr>
        
          <tr>
            <td>University of Westminster</td>
            <td>
              Connected to this license through role Licensee.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>edit 
                      
                        [Granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
              </ul>
            </td>
          </tr>
        
      </table>

```
  <h2>Logged in user permissions</h2>
```

<table>
        <tr>
          <th>Affiliated via Role</th><th>Permissions</th>
        </tr>
        
          <tr>
            <td>Affiliated to University of Westminster with role Editor</td>
            <td>
              <ul>
                
                  <li>edit</li>
                
              </ul>
            </td>
          </tr>
          
            <tr>
              <td> --&gt; This org is related to JISC Collections ( Consortium )</td>
              <td>
                <ul>
                  
                </ul>
              </td>
            </tr>
          
        
      </table>

**Comment by ianibo** [comment]
Thanks for this.. No idea whats going on.. I explicitly added the view role
for editors (Thats what the change in the bootstrap file was) I'll get on
and check the database again

On 29 November 2012 17:40, Owen Stephens notifications@github.com wrote:

> Following update on 29th Nov, there is still an issue here. For TestUserB:
> UoW Admin [HH] / tF2UwXx/Z3WL5CLCXhfGFva3pxM=@edina.ac.uk on sandpit
> can't access http://test.kbplus.ac.uk/kbplus/licenseDetails/index/87 , on
> http://test.kbplus.ac.uk/kbplus/licenseDetails/additionalInfo/87 I get:
> 
> Permissions for user
> 
>   <h2>The following organisations are granted the listed permissions from this licence</h2>
> 
>  Organisation Roles and Permissions  IoP Publishing Limited Connected to
> this license through role Licensor.
> This role grants the following permissions to members of that org whose
> membership role also includes the permission
> 
>   University of Westminster
> Connected to this license through role Licensee.
> This role grants the following permissions to members of that org whose
> membership role also includes the permission
> - view [Not granted]
> - edit [Granted]
> - view [Not granted]
>   
>   <h2>Logged in user permissions</h2>
>   
>   Affiliated via Role Permissions  Affiliated to University of Westminster
>   with role Editor
> - edit
>   
>   --> This org is related to JISC Collections ( Consortium )
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/288#issuecomment-10858163.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
This should be fixed now.
Added the view perm to the editor role.
Done this in SQL on live, and re-factored the code to make sure the permission is asserted every start up, in case of partial starts that set up the preconditions, but don't complete OK.
Changed the constraints on the perms grant table to make sure the the setup we need is allowed.
