### ISSUE TITLE
Styling on menus in sandpit has changed

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#289]
The styling of the dropdown menus in sandpit has changed - text looks like it is overlayed, and changes colour on roll over. Needs to revert to previous style (extant on live)

**Comment by ostephens** [comment]
Now v1.1 has been rolled out to live, I'm seeing the same effect on the Live instance - the styling that controls the top menu bar needs looking at to correct this

**Comment by ianibo** [comment]
Seems OK to me now, can someone look and confirm if this is still an issue?

**Comment by ostephens** [comment]
It's OK on test now. Live is still an issue but we can wait for next release to live for this to be fixed. Closing for now
