### ISSUE TITLE
eISSNs not importing?

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#29]
It looks like in some circumstances eISSNs are not importing. E.g in SO file IOP_option1_2011_2012_nesli2.csv has the line
Journal of Optics,2040-8978,2040-8986,01/01/2002,,,,,,2040-8986,,full text,,IOP,,IOPScience,host,http://iopscience.iop.org/2040-8986,IOP For Librarians,administrative,

Note that "2040-8986" appears as both the eISSN (col 3) and as an additional identifier (col 10). The second instance imports OK (currently labelled as a 'KBART' ID), but it doesn't appear as an eISSN.

(based on the KBPlus-23-May-2012-2 import)

**Comment by ianibo** [comment]
Fixed
