### ISSUE TITLE
Permissions to view via Org-to-Org links don't work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#293]
The following scenario:

JISC Collections -> Licensing Consortia (org role link) -> Licence 1
University of Westminster -> consortialMember (Consortium org-to-org combo) -> JISC Collections

Users who are members of JISC Collections can Edit/View (depending on their role) Licence 1 as this is conferred by the Licensing Consortia link.

Users who are members of the University of Westminster should be able to view Licence 1 because UoW is a consortial member of JC, which is Licensing Consortia for Licence 1.

For Subscriptions the "Subscription Consortia" role should work in the same way. These are the only two Org roles that are currently intended to grant view permissions in this way.

This does not currently work - e.g. for user TestUserF: JC Admin [HH] / Xf8bVt77cA+Xr7ZXSNxoZbFuiOQ=@edina.ac.uk (JISC_Collections:1:INST_ADM) gets the following info on licence http://test.kbplus.ac.uk/kbplus/licenseDetails/additionalInfo/1

<h2>The following organisations are granted the listed permissions from this licence</h2>

<table>
        <tr>
          <th>Organisation</th><th>Roles and Permissions</th>
        </tr>
        
          <tr>
            <td>IoP Publishing Limited</td>
            <td>
              Connected to this license through role Licensor.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
              </ul>
            </td>
          </tr>
        
          <tr>
            <td>JISC Collections</td>
            <td>
              Connected to this license through role Licensing Consortium.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
                  <li>edit 
                      
                        [Granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Granted]
                      
 
                  </li>
                
              </ul>
            </td>
          </tr>
        
      </table>

```
  <h2>Logged in user permissions</h2>
```

<table>
        <tr>
          <th>Affiliated via Role</th><th>Permissions</th>
        </tr>
        
          <tr>
            <td>Affiliated to JISC Collections with role Editor</td>
            <td>
              <ul>
                
                  <li>edit</li>
                
                  <li>view</li>
                
              </ul>
            </td>
          </tr>
          
        
      </table>

# 

However user TestUserB: UoW Admin [HH] / tF2UwXx/Z3WL5CLCXhfGFva3pxM=@edina.ac.uk (University_of_Westminster:1:INST_ADM) sees the following permissions on the same licence:

 <h2>The following organisations are granted the listed permissions from this licence</h2>

<table>
        <tr>
          <th>Organisation</th><th>Roles and Permissions</th>
        </tr>
        
          <tr>
            <td>IoP Publishing Limited</td>
            <td>
              Connected to this license through role Licensor.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
              </ul>
            </td>
          </tr>
        
          <tr>
            <td>JISC Collections</td>
            <td>
              Connected to this license through role Licensing Consortium.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
                  <li>edit 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Not granted]
                      
 
                  </li>
                
              </ul>
            </td>
          </tr>
        
      </table>

```
  <h2>Logged in user permissions</h2>
```

<table>
        <tr>
          <th>Affiliated via Role</th><th>Permissions</th>
        </tr>
        
          <tr>
            <td>Affiliated to University of Westminster with role Editor</td>
            <td>
              <ul>
                
                  <li>view</li>
                
                  <li>edit</li>
                
              </ul>
            </td>
          </tr>
          
            <tr>
              <td> --&gt; This org is related to JISC Collections ( Consortium )</td>
              <td>
                <ul>
                  
                </ul>
              </td>
            </tr>
          
        
      </table>

**Comment by ianibo** [comment]
Refdata that allows the view permission to propagate along the consoria combo type was missing.. Appropriate key selection is in the file:
select (@cons_member_rdv:=rdv_id) from refdata_value, refdata_category where rdv_owner = rdc_id and rdv_value='Consortium' and rdc_description = 'Combo Type';

But upgrade.sql was missing this insert

insert into org_perm_share(perm_id,rdv_id) values ( @view_perm, @cons_member_rdv );

Have added to upgrade.sql and made the change manually.

Having made the insert manually, the appropriate perms seem to be listed in the additionalInfo page.
