### ISSUE TITLE
View Only users should not be able to add/delete Org links

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#294]
Currently users with only 'View' permissions on an object can add or delete Org links (e.g. add a Licensor to a Licence), even though they cannot edit the rest of the record.

**Comment by ianibo** [comment]
This is functionality in development.. the new org links widget will
observe perms once finished.

On 3 December 2012 08:21, Owen Stephens notifications@github.com wrote:

> Currently users with only 'View' permissions on an object can add or
> delete Org links (e.g. add a Licensor to a Licence), even though they
> cannot edit the rest of the record.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/294.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Could do with a testing plan maybe so we don't get testing reports for
things that are in dev?

On 3 December 2012 08:21, Owen Stephens notifications@github.com wrote:

> Currently users with only 'View' permissions on an object can add or
> delete Org links (e.g. add a Licensor to a Licence), even though they
> cannot edit the rest of the record.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/294.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
OK - no problem

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ostephens** [comment]
Looks like this is done in latest test release? Testing looks OK to me so could be closed as long as you are happy
