### ISSUE TITLE
/additionalInfo/ page for Subscriptions

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#295]
Could we have additionalInfo page for Subscriptions as well as Licences?

**Comment by ianibo** [comment]
Should be there

http://test.kbplus.ac.uk/kbplus/subscriptionDetails/additionalInfo/149

On 3 December 2012 11:34, Owen Stephens notifications@github.com wrote:

> Could we have additionalInfo page for Subscriptions as well as Licences?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/295.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Sorry - when I tested it didn't come up, but it does now - could have been a connection issue from my end.

**Comment by ianibo** [comment]
NPS.. Think we might need to do something more tidy when user requesting
the page doesn't have view perm.. Suspect it's a blank page atm.

On 3 December 2012 12:22, Owen Stephens notifications@github.com wrote:

> Sorry - when I tested it didn't come up, but it does now - could have been
> a connection issue from my end.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/295#issuecomment-10950766.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
