### ISSUE TITLE
Alerts created on change to a template licence URL

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#296]
A change to a template licence creates Public alerts on each of the linked Actual licences on http://test.kbplus.ac.uk/kbplus/myInstitutions/dashboard

Ideally these would only display to users who are members of the Orgs linked to the Actual licences

**Comment by ostephens** [comment]
I didn't add this as a compulsory feature for our next release - but having played around a bit I'm wondering if I've made an error here. How complex is this problem?

**Comment by ianibo** [comment]
Pretty complex.. tied up in the general alerts malaise I think. Certainly couldn't restrict only change alerts to a particular inst.. would have to be an all-or-nothing really.

**Comment by ostephens** [comment]
No longer an issue following introduction of Announcements and ToDos in 3.3
