### ISSUE TITLE
Search box in 'Add Org Link' does not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#298]
I know this is in dev, but just because I noticed it I thought I'd throw it in

**Comment by ostephens** [comment]
Still an issue on current test deploy

**Comment by ianibo** [comment]
Can you let me have browser versions pls? seems OK to me on win/chrome?
(Attached)

[image: Inline images 1]

On 5 December 2012 13:43, Owen Stephens notifications@github.com wrote:

> Still an issue on current test deploy
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/298#issuecomment-11041677.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Sorry - mucked up the testing. It does work ... but - there seems to be a problem including uppercase characters in the search - if I search "JISC" or "Oxford" no results, but searching "jisc" or "oxford" works fine.

Tested on Ff 17.0, Chrome 23.x, Safari 6.0.2 on Mac

**Comment by ianibo** [comment]
Search made case insensitive.
