### ISSUE TITLE
Subscriptions Taken failing to match existing titles

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#30]
An example from 625_IOP_option 1_2011_2012_Nesli2.csv_BAD:

[, Journal of Instrumentation, , 1748-0221, 01/04/2006, , , , , , , ],"row 13/45 - Unable to locate ISSN for title ""  or eISSN "1748-0221""

But the journal is in the system: http://projects.k-int.com/kbplus/titleInstance/show/2140

**Comment by ianibo** [comment]
Fixed
