### ISSUE TITLE
List of possible Roles in 'Add Org Role' function

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#300]
Is there any way we can filter the list of possible Roles based on context of the Add Org Role - i.e. only show roles relevant to a licence when using the Add Org Role from a Licence?

**Comment by ostephens** [comment]
For a licence (e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/1330)  the relevant Org Roles are:
Licensee
Licensing Consortium
Licensor
Negotiator

For a subscription (e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/3748) the relevant Org Roles are:
Subscriber
Provider
Subscription Agent
Subscription Consortia

For a package (e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/show/609) the relevant Org Roles are:
Content Provider
Package Consortia

For a title (e.g. http://test.kbplus.ac.uk/kbplus/titleDetails/edit/6201) the relevant Org Roles are:
Publisher

For a platform (e.g. http://test.kbplus.ac.uk/kbplus/platform/show/1) the relevant Org Roles are:
Aggregator
Gateway
Host

Currently there is no UI mechanism (afaik) to add Org roles to platforms, so this is not required as part of this issue.

**Comment by iyawnis** [comment]
Thank you, I will look into this as soon as I can.

**Comment by iyawnis** [comment]
For the titleDetails screen, currently there is a search box for the Role name, should that be replaced by a dropdown ? Keep in mind that with these changes, only Publisher will be available.

**Comment by ostephens** [comment]
A dropdown would be great

**Comment by iyawnis** [comment]
Should I replace the current way org links are displayed, to use the same way they are displayed on all other instances (bottom one ). That should keep everything consistent.
![scrn](https://cloud.githubusercontent.com/assets/2336352/5956123/d192ef68-a7a1-11e4-8a54-23b36874ede4.jpeg)

**Comment by iyawnis** [comment]
This is for TitleDetails.

**Comment by ostephens** [comment]
Agreed this should be consistent. I'd probably go with the first example as a preference because it saves a click (I think?) but as long as we have consistency I'm happy either way
