### ISSUE TITLE
You should not be able to Copy things you can't View

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#303]
At the moment it is possible to create a copy of a licence from http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/addLicense or a Subscription from http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/addSubscription, without having permission to view the thing you are copying.

You should only be able to Copy things you can already View

**Comment by ianibo** [comment]
Implemented with flash message as per deletes.. Commited, needs test refresh and test.

**Comment by ostephens** [comment]
This now seems to test for 'edit' permissions on the the object you wish to copy? Correct behaviour is that you should be able to copy things if you have at least 'view' perms on them.
E.g.
User: TestUserB: UoW Admin [HH] / tF2UwXx/Z3WL5CLCXhfGFva3pxM=@edina.ac.uk
User roles: University_of_Westminster:1:INST_ADM
Try to copy http://test.kbplus.ac.uk/kbplus/licenseDetails/index/1, get error "You do not have edit permission for the selected license."

I look at the permissions via /additionalInfo

<h2>The following organisations are granted the listed permissions from this licence</h2>

<table>
        <tr>
          <th>Organisation</th><th>Roles and Permissions</th>
        </tr>
        
          <tr>
            <td>IoP Publishing Limited</td>
            <td>
              Connected to this license through role Licensor.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
              </ul>
            </td>
          </tr>
        
          <tr>
            <td>JISC Collections</td>
            <td>
              Connected to this license through role Licensing Consortium.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
                  <li>edit 
                      
                        [Not granted]
                      
 
                  </li>
                
                  <li>view 
                      
                        [Granted]
                      
 
                  </li>
                
              </ul>
            </td>
          </tr>
        
      </table>

<h2>Logged in user permissions</h2>

<table>
        <tr>
          <th>Affiliated via Role</th><th>Permissions</th>
        </tr>
        
          <tr>
            <td>Affiliated to University of Westminster with role Editor</td>
            <td>
              <ul>
                
                  <li>edit</li>
                
                  <li>view</li>
                
              </ul>
            </td>
          </tr>
          
            <tr>
              <td> --&gt; This org is related to JISC Collections ( Consortium )</td>
              <td>
                <ul>
                  
                    <li>view</li>
                  
                </ul>
              </td>
            </tr>
          
        
      </table>
