### ISSUE TITLE
You should not be able to delete things you cannot edit

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#304]
A user can delete subscriptions from http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentSubscriptions and delete licences from http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentLicenses, even if they don't have edit permission on the items in question.

Users should only be able to delete things they have permission to edit

**Comment by ianibo** [comment]
Just checked and delete license is protected by a has admin perm check.. Need to understand why you were able to delete in this case.

**Comment by ianibo** [comment]
Can you let me know the user you were using here please.. can't replicate without that. Think I have logins for all the test accounts now.

**Comment by ianibo** [comment]
Just tested delete subscription using the kb+test3 account and the UoW link at the head of the issue. System correctly did not delete the license, and put up a flash message with the text "unable to delete". Need to fix the text in the flash message, but users DON'T appear to be able to do this on test.. Is there any more detail you can add to this? Hoping to have a day nailing the release issues, and am held up on this one as I think it's the only live issue!

**Comment by ostephens** [comment]
Will check as soon as I can - I'm afraid it may be later this pm

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ostephens** [comment]
OK - using 
TestUserA: UoW ReadOnly [HH] / oaYDLonYlJRXD3hKbU30N1mn4YQ=@edina.ac.uk 
University_of_Westminster:0:INST_ADM
University_of_Westminster:1:INST_USER

Should be a read only user (requested INST_ADM but not approved)

Was able to delete http://test.kbplus.ac.uk/kbplus/licenseDetails/index/91

**Comment by ostephens** [comment]
Just to check the extra unapproved admin role was not confusing matters, I've also tested this with user
TestUserC: UoS ReadOnly [HH] / Wftpsag2zAwBtIO53BjsJ9YIx1Y=@edina.ac.uk
University_of_Stirling:1:INST_USER

was able to delete http://test.kbplus.ac.uk/kbplus/licenseDetails/index/92

**Comment by ianibo** [comment]
Got it... Was using an old hasAdminPerms call that does not take notice of the role... permission was being approved by nature of an existing view rather than edit permission. Useful when tracking these down in future if we can grab a copy of the additionalInfo page before/after delete.

**Comment by ostephens** [comment]
Ok will do
