### ISSUE TITLE
Batch edit/delete of IEs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#305]
I wasn't sure if there was a fix for this in the test branch but not deployed? Anyway, capturing here just in case:

Trying to do a batch edit/remove of IEs gives an error - e.g.:

/kbplus/subscriptionDetails/subscriptionBatchUpdate/149
Class
groovy.lang.MissingPropertyException
Message
No such property: result for class: com.k_int.kbplus.SubscriptionDetailsController Possible solutions: request
Trace
    Line | Method
->>  151 | subscriptionBatchUpdate in com.k_int.kbplus.SubscriptionDetailsController

---

|   1110 | runWorker               in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                     in java.lang.Thread

**Comment by ianibbo** [comment]
Fix checked in and pushed on to test branch last week.. awaiting redeploy
from edina afaik..

Bit out of step now between whats on test and whats checked into the test
branch.. probably need a mechanism to track this.

Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Tested. Fixed.
