### ISSUE TITLE
Licence Key Value - no notes

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#31]
No notes are displaying alongside Licence Key Values - e.g. on http://projects.k-int.com/kbplus/license/show/1

Is this because we haven't got the Doc Store working yet? Is there any way we can fake this for tomorrow?

**Comment by ianibo** [comment]
I think I can show the notes... I have them in a field I think

However.. advanced warning.. I'm not sure how practical it's going to be to
show notes inline from the docstore when they do get in there... It's a
reasonably heavy operation to get stuff in and out, and the kind of thing
you describe here is not perhaps what it's best suited for..

Lets worry about that after tomorrow.

On 23 May 2012 16:32, ostephens <
reply@reply.github.com

> wrote:
> 
> No notes are displaying alongside Licence Key Values - e.g. on
> http://projects.k-int.com/kbplus/license/show/1
> 
> Is this because we haven't got the Doc Store working yet? Is there any way
> we can fake this for tomorrow?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/31

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
