### ISSUE TITLE
Blank screen when Read Only user tries to accept a change notification

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#310]
e.g. if a change has been made to a template licence - if you go to an actual licence derived from the template you see notification of the change and 'accept' and 'reject' buttons. If a read-only user clicks one of these, they get directed to a blank screen (e.g. URLs http://test.kbplus.ac.uk/kbplus/licenseDetails/acceptChange/91?changeid=1, http://test.kbplus.ac.uk/kbplus/licenseDetails/rejectChange/91?changeid=1)

Either - hide the accept/reject buttons from users who don't have edit permissions on the item (preferred); or if clicked, redirect back to licence screen with appropriate error message ("You do not have edit permissions for this licence")

**Comment by ianibo** [comment]
This should be sorted, but it's very hard for me to test. Retest please and report here.
