### ISSUE TITLE
Implement change/notification on Template Licences and Subscriptions Offered

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#312]
Extend this from the current implementation for the licence URL field to the following fields in Template Licences and Subscriptions Offered - notifications to go be alerted on derived Actual Licences and Subscriptions Taken respectively.

Template Licence:

licence.lic_licensee_ref
licence.lic_licensor_ref
licence.lic_notice_period
licence.lic_ref
licence.lic_concurrent_user_count

Subscription Offered:

subscription.sub_name
subscription.sub_start_date
subscription.sub_end_date

There are also a set of fields that contain FKs to Reference Data. I guess for these easy to track as long as it's the FK that changes not the Reference Data value. But there might be some work to be done to state the change in terms of the reference data value rather than the FK? These fields are:

licence.lic_alumni_access_rdv_fk
licence.lic_concurrent_users_rdv_fk
licence.lic_coursepack_rdv_fk
licence.lic_enterprise_rdv_fk
licence.lic_ill_rdv_fk
licence.lic_multisite_access_rdv_fk
licence.lic_partners_access_rdv_fk
licence.lic_pca_rdv_fk
licence.lic_remote_access_rdv_fk
licence.lic_vle_rdv_fk
licence.lic_walkin_access_rdv_fk

**Comment by ostephens** [comment]
Ian - from your comments on the call yesterday are these all done now?

**Comment by ianibbo** [comment]
Found a bug in the fk stuff, rest is OK, but pls hold off testing the fk
stuff until I give you the nod.

Ian.
