### ISSUE TITLE
Default sort orders for lists

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#315]
For various list screens we should implement default sort orders as follows:

/currentLicenses = Reference Description, alpha
/addLicense = Reference Description, alpha
/licenseDetails/documents = last_updated (not displayed - not sure if this a problem), date order ascending (i.e. most recently updated at the top)
/licenseDetails/notes =  = last_updated (not displayed - not sure if this a problem), date order ascending (i.e. most recently updated at the top)

/currentSubscriptions = Name, alpha
/addSubscription = Name, alpha
/subscriptionDetails/index (IE listing on this page) = Title, alpha
/subscriptionDetails/addEntitlements (TIPP listing on this page) = Title, alpha
/subscriptionDetails/documents = last_updated (not displayed - not sure if this a problem), date order ascending (i.e. most recently updated at the top)
/subscriptionDetails/notes =  = last_updated (not displayed - not sure if this a problem), date order ascending (i.e. most recently updated at the top)

/myInstitutions/dashboard (Alerts on this page) = Date, date order ascending (i.e. most recent at the top)
/myInstitutions/index (Alerts on this page) = Date, date order ascending (i.e. most recent at the top)

**Comment by ianibo** [comment]
Arg.. multi job issue :(

/currentLicenses - done
/addLicense - done
/licenseDetails/documents - Can't be done for this release. Substantial change  (Docs/Notes)
/licenseDetails/notes - Can't be done for this release. Substantial change  (Docs/Notes)
/currentSubscriptions - Done
/addSubscription - Done
/subscriptionDetails/index - Done
/subscriptionDetails/addEntitlements - Already sorted on title asc
/subscriptionDetails/documents - Can't be done for this release. Substantial change (D/ocs/Notes)
/subscriptionDetails/notes - Can't be done for this release. Substantial change (D/ocs/Notes)
/myInstitutions/dashboard - Done
/myInstitutions/index - Done

Closing issue, some done, some can't be done. Please split off can't be dones for next release if needed.

**Comment by ostephens** [comment]
Sorry - will split off ones that can't be done
