### ISSUE TITLE
Add 'Create Subscription' option to Subscription Details page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#318]
On a Subscription Details page for an SO (e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1) add a 'Create Subscription' option - suggested position top right of screen - see attached mockup.

Use same styling/options as with the 'Create Subscription option on the //addSubscription screen

![Screen Shot 2012-12-21 at 16 38 47](https://f.cloud.github.com/assets/576174/27503/62dc8808-4b8d-11e2-83cf-8cd9b2a89326.png)

**Comment by ianibo** [comment]
This cannot be done currently. The license details screen is context free wheras the "Add subscription" screen sits under the myInstitutions/inst-id/ URI, which means we know what institution to add the sub  to. Needs a rethink of the IA to implement.
