### ISSUE TITLE
Add 'Copy' to Licence details screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#319]
Add option to copy a licence from the //licenseDetails screen.

Add a 'Copy' button styled as the 'Copy Selected' button on the /addLicense but the label on the button should just read 'Copy'. Position suggested top right - mock up screen shot attached

![Screen Shot 2012-12-21 at 16 43 15](https://f.cloud.github.com/assets/576174/27517/fd809f66-4b8d-11e2-9678-4000aefd4260.png)

**Comment by ianibo** [comment]
This cannot be done currently. The license details screen is context free wheras the "Add license" screen sits under the myInstitutions/inst-id/ URI, which means we know what institution to add the license to. Needs a rethink of the IA to implement.
