### ISSUE TITLE
Error when adding new Package on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#321]
Using the New Package menu (http://test.kbplus.ac.uk/kbplus/packageDetails/create) to create a package. Filled out all details, clicked 'Create Package', got error:

HTTP Status 404 - /kbplus/packageDetails/edit/128

type Status report

message /kbplus/packageDetails/edit/128

description The requested resource (/kbplus/packageDetails/edit/128) is not available.

---

However, checking the existence of the package I can see it has been partially created:
http://test.kbplus.ac.uk/kbplus/package/show/128

But no Content Provider has been added, although this was specified on the Create Package screen as 'AAAS' (from the auto-complete list)

**Comment by ianibo** [comment]
Should I just remove this? This was added when we thought we would do a hybrid create tool, but we have chosen to use old style package format uploads, so this isn't how we're doing new packages any more. We should just remove?

**Comment by ostephens** [comment]
Yes I think so.
