### ISSUE TITLE
New possible values for Core field in IE

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#329]
As discussed in Sheffield 10/1/13 rather than remove current Core field and introduce new 'Core type' field, rather allow new values for Core field. Currently can be "True" or "False" (at least those are values available via UI).

In addition this field should now be able to take values:
True (could be shortened to Y)
False (could be shortened to N)
Print (could be shortened to P)
Electronics (could be shortened to E)
Print+Electronic (could be shortened to P+E)

In display (e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/149) the Core field currently displays with a graphic tick or cross for True or False. This graphic would not be required with new values.

See also change of column layout for subscriptionDetails screen in issue #328 which includes this value

**Comment by ianibo** [comment]
Replaced old core boolean with new refdata element.
