### ISSUE TITLE
Change date format on subscriptionDetails screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#332]
e.g. on http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/149

In the Subscription Information section, change format of 'Start Date' and 'End Date' to DD/MM/YYYY

Listing of IEs on this screen due to get new layout as per #328 which includes specification of date formats as DD/MM/YYYY for each date associated with the IEs

**Comment by ianibo** [comment]
Is YYYY/MM/DD better, as it might travel better?
