### ISSUE TITLE
"Public" flag shows as 'Unknown refdata category' on Test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#333]
On both licences and subscriptions:
e.g. on http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1

The Public field displays as:

Public? Unknown refdata category YN

And cannot be edited

**Comment by ianibbo** [comment]
This looks like  a problem with the upgrade script not being run... License
field has changed form a YNO (Yes/No/Other) field to a YN (Yes/No) refdata
category. YN is a new category created by the upgrade script.

Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Script / Process / Upgrade problem.
