### ISSUE TITLE
Fulltext index not updated on import of SO information?

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#334]
Just noticed on test that although three new SOs starting in 2013 had been imported I wasn't seeing any entries in the 'comparison search' with 'Start Year' of 2013.

These appeared as soon as I triggered the 'Start FT Index Update' via the admin menu

**Comment by ianibo** [comment]
Nope, it has to be triggered manually... is the presence of this issue suggesting something else needs to be done?

**Comment by ostephens** [comment]
I think ideally the full-text index would update when new packages/SOs are added, but don't have a big issue with updating manually if this is easier for now.
