### ISSUE TITLE
Convert old Core values to new and remove old core status

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#342]
Following implementation of new 'core type' field and deprecation of previous 'core' status field, need to set new core type based on old core status:

If old Core value is True, set new core type to Y
If old Core value is False, set new core type to N

Once this is done, remove old Core status

**Comment by ianibo** [comment]
Done and SQL added to upgrade script. UPGRADE SCRIPT NEEDS TO BE RUN OR WORLD ENDING PARADOXES  MAY ENSUE!
