### ISSUE TITLE
Default value for IsCore on renewal

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#344]
When importing Renewals spreadsheet, if the IsCore? cell is empty, then Core value in KB+ should default to 'N'

**Comment by ianibo** [comment]
Erm.. it should be.. not sure what to do about this one.. Doesn't default until the you actually process the page tho.. are you looking for to be displayed on the post upload screen? Can we get away with this for this release - Or is the defaulting actually broken?

**Comment by ostephens** [comment]
Need to check - I was only looking at the preview screen.
