### ISSUE TITLE
Click to edit styling not present on Subscriptions Details page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#348]
e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/151

Most editable fields on this page are missing the small 'pen' icon indicating the field can be edited by clicking in it. The only place on the page this has been retained is the Batch Edit area for the 'Core Status' column in the IE display

**Comment by nathanbrock** [comment]
@ianibbo The click to edit styles and JS used the original classes that were in use through out the site. The subs' page now uses a new style 'ynrefdataedit'. If you could also add the style 'ipe' as well to the click to edit that should resolve most of the issue. I'll push a small style change to ensure the select inputs are positioned correctly. Cheers.
