### ISSUE TITLE
Comparison spreadsheet cells not coloured correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#349]
Populated Cells are all coloured Yellow (indicating 'Core'). Where the title is in the package, but not marked as core in the current ST, they should be coloured light green.

Suspect broken because we've moved from using the old Core status to new Core type? Think the rules is that when the value in the 'IsCore?' col in the spreadsheet is anything except 'N' or blank, then the cells should be coloured yellow. Otherwise they should be coloured green.

**Comment by ianibo** [comment]
Fixed with SQL supplied for issue #353 (SQL also now in upgrade script)

**Comment by ostephens** [comment]
This problem is still occurring
