### ISSUE TITLE
Error on uploading Renewals worksheet

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#353]
When trying to upload a renewals worksheet an error relating to the lack of default value for ie_core_title

Error 500: Internal Server Error
URI
/kbplus/myInstitutions/University_of_Huddersfield/processRenewal
Class
java.sql.SQLException
Message
Field 'ie_core_title' doesn't have a default value

TRACE
   Line | Method
->> 1074 | createSQLException in com.mysql.jdbc.SQLError

---

|   4074 | checkErrorPacket   in com.mysql.jdbc.MysqlIO
|   4006 | checkErrorPacket . in     ''
|   2468 | sendCommand        in     ''
|   2629 | sqlQueryDirect . . in     ''
|   2719 | execSQL            in com.mysql.jdbc.ConnectionImpl
|   2155 | executeInternal .  in com.mysql.jdbc.PreparedStatement
|   2450 | executeUpdate      in     ''
|   2371 | executeUpdate . .  in     ''
|   2355 | executeUpdate      in     ''
|    105 | executeUpdate . .  in org.apache.commons.dbcp.DelegatingPreparedStatement
|   1479 | processRenewal     in com.k_int.kbplus.MyInstitutionsController
|   1110 | runWorker . . . .  in java.util.concurrent.ThreadPoolExecutor
|    603 | run                in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . .  in java.lang.Thread

**Comment by ianibo** [comment]
Heya

This is cause by me missing some SQL off the upgrade script. I've added it and committed.. fixable by re-updating or running the following SQL by hand:

alter table issue_entitlement modify ie_core_title bit(1) null;
