### ISSUE TITLE
Access to /renewalsUpload blocked

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#358]
Access to this seems to be blocked unless you are a KB+ Editor? e.g.
try to access:
http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/renewalsUpload

as TestUserB and get redirected to http://test.kbplus.ac.uk/kbplus/login/denied

TestUserB is an Editor member of University of Westminster as follows:

TestUserB: UoW Admin [HH] / 661UJcy09/JZdcxfjYZBzQRXD+A=@edina.ac.uk  
University_of_Westminster:1:INST_ADM

As an Editor member of the University of Westminster they should have access to this page.

**Comment by ianibbo** [comment]
Fixed and merged onto test

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Fixed
