### ISSUE TITLE
Editors unable to add licences/subscriptions

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#359]
Users who are members of an institution with Editor role are not able to add licences or subscriptions.

e.g. 

TestUserB: UoW Admin [HH] / 661UJcy09/JZdcxfjYZBzQRXD+A=@edina.ac.uk  
University_of_Westminster:1:INST_ADM

When on http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/addSubscription
see's message
"You must have editor role to be able to add licences"

also if on http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/addLicense
and selects a licence to copy via radio button message appears:
"Sorry, you must have editor role to be able to add licences"

In both cases this user (who is editor for UoW) should be able to copy subs/licences.
The user (correctly) sees the option to "Create New Licence" on http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentLicenses

**Comment by ianibo** [comment]
Fixed, tested locally, but can't test shib perms until up to test....
(Fix on test branch)

**Comment by ostephens** [comment]
Have tested and looks OK
