### ISSUE TITLE
Change to concurrentUserCount on Template licence results in incorrect update to Actual 

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#360]
Updating the concurrentUserCount on a Template licence (http://test.kbplus.ac.uk/kbplus/licenseDetails/index/15) triggers an alert on derived Actual licences (e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/102)

If concurrentUserCount changed to 2 on Template licence, when you 'Accept' change on actual licence the concurrentUserCount on the Actual licence is updated to '50' rather than '2'

**Comment by ianibo** [comment]
Ah.. 50 is the ascii value for "2", so there is a type conversion problem here.. investigating...
