### ISSUE TITLE
Change Notifications for Licence Key values don't decode Ref Data

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#362]
When a change is made to a Key Value on a template licence, a change notification is created on all linked Actual licences.

However, the change notification does not decode the ref data to the actual value of the change, so you get notifications like:

<table class="table table-bordered">
          <thead>
            <tr>
              <td>Field</td>
              <td>Has changed to</td>
              <td>Reason</td>
              <td>Actions</td>
            </tr>
          </thead>
          <tbody>
            
              <tr>
                <td style="white-space:nowrap;">coursepack</td>
                <td>com.k_int.kbplus.RefdataValue:67</td>
                <td>The template used to derive this licence has changed</td>
                <td>
                  <a href="/kbplus/licenseDetails/acceptChange/29?changeid=32" class="btn btn-primary">Accept</a>
                  <a href="/kbplus/licenseDetails/rejectChange/29?changeid=32" class="btn btn-primary">Reject</a>
                </td>
              </tr>
          
            
          </tbody>
        </table>

It would be better if the change notification gave the actual value in the 'Has changed to' column

**Comment by ianibo** [comment]
Think this is closable... no longer relevant with new stuff.
