### ISSUE TITLE
If 'core' type is "Unknown Combo Type" spreadsheet cell should be green

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#364]
In the comparison spreadsheet if the 'IsCore?' column has the value 'Unknown Combo Type' the spreadsheet cell should be green. It is currently yellow

**Comment by ianibo** [comment]
Hmm.. not in my test data :/ _confused_

On 31 January 2013 13:28, Owen Stephens notifications@github.com wrote:

> In the comparison spreadsheet if the 'IsCore?' column has the value
> 'Unknown Combo Type' the spreadsheet cell should be green. It is currently
> yellow
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/364.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Still broken I'm afraid. This is specifically setting a Core status to 'Unknown Combo Type' in a sub, then using the Renewal process to generate the spreadsheet. Relates to line 1206 in MyInstitutionsController.groovy - this assumes that cell should be yellow if ie_info.core is anything except "No". Think rule should be anything except "No" or "Unknown Combo Type"

**Comment by ianibo** [comment]
But core status should _never_ be Unknown Combo Type should it?

On 14 February 2013 12:08, Owen Stephens notifications@github.com wrote:

> Still broken I'm afraid. This is specifically setting a Core status to
> 'Unknown Combo Type' in a sub, then using the Renewal process to generate
> the spreadsheet. Relates to line 1206 in MyInstitutionsController.groovy -
> this assumes that cell should be yellow if ie_info.core is anything except
> "No". Think rule should be anything except "No" or "Unknown Combo Type"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/364#issuecomment-13544800.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Probably not - but it is possible currently to set this in the UI. Perhaps the fix is to remove this option (in the dropdown on the core col in /subscriptionDetails/index) rather than fix the code for the spreadsheet generation.

**Comment by ianibo** [comment]
Yeah..

I think I sent round the SQL to remove the possibility of it appearing in
the UI at all. I'd certainly rather focus on the proper solution than
editing the generation.

On 14 February 2013 12:15, Owen Stephens notifications@github.com wrote:

> Probably not - but it is possible currently to set this in the UI. Perhaps
> the fix is to remove this option (in the dropdown on the core col in
> /subscriptionDetails/index) rather than fix the code for the spreadsheet
> generation.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/364#issuecomment-13544999.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
OK - works for me. Can't see that SQL though - do you want to implement in the next upgrade script?

**Comment by ianibo** [comment]
Can this be closed?

**Comment by ostephens** [comment]
I don't think the necessary SQL has been applied? If you send it round we can get Des to run it

**Comment by ianibo** [comment]
Sql needed is in upgrade script, should be run as  a part of upgrade process

**Comment by ostephens** [comment]
Think this is fixed - closing in lieu of any issues reported related to this
