### ISSUE TITLE
Sometimes get Grails error when viewing an Organisations 'users'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#366]
When trying to view an organisations users e.g. http://test.kbplus.ac.uk/kbplus/organisations/users/512 you get a grails error - below.

However some org/users links work fine (e.g. http://test.kbplus.ac.uk/kbplus/organisations/users/389)

Error 500: Internal Server Error
URI
/kbplus/organisations/users/512
Class
java.lang.NullPointerException
Message
Cannot get property 'authority' on null object
Trace
    Line | Method
->>   56 | runWorker in /organisations/users.gsp

---

Caused by NullPointerException: Cannot get property 'authority' on null object
->>   52 | doCall    in gsp_demo_organisationsusers_gsp$_run_closure2

---

|     89 | run       in gsp_demo_organisationsusers_gsp
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

**Comment by ianibbo** [comment]
I've superficially fixed this on all branches, but it's a consequence of a
user attached to an old style role when the update sql hasn't been run. The
fix will prevent the error, but won't stop the subsequent more important
situation when perms don't work properly for the user.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
