### ISSUE TITLE
Updating dates on Package details screen does not immediately update display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#372]
e.g. on http://test.kbplus.ac.uk/kbplus/packageDetails/show/129
When editing either Start Date or End Date - selecting a date from the calendar does not immediately update the display. You have to refresh the screen to see the changed date. 

This should ideally update the display immediately as on other screens where the date can be selected from the Calendar

**Comment by ianibo** [comment]
Think this can be closed now?

**Comment by ostephens** [comment]
Fixed
