### ISSUE TITLE
Icons for 'Concurrent Users' key value

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#381]
Currently the icons used for the different values of the Licence Key Value 'Concurrent Users' are:

No limit = red cross
Specified = green tick
Not specified = purple question mark
Other = purple question mark

This should be amended so the following icons are used instead:

No limit = green tick
Specified = purple question mark
Not specified = purple question mark
Other = purple question mark

**Comment by ianibbo** [comment]
Should be updated in db (refdata table)

How should we deal with this?

**Comment by ostephens** [comment]
What are the options? Either put in an upgrade script or run some SQL?

**Comment by ianibbo** [comment]
Yep...

But... I'm loath to allow the "upgrade script" be the mechanism by which we
deliver all day-to-day support (EG also taking out the unspecified core
type)... It's really there for things that are a part of the deployment
process (To my mind at least) and these seem  more like operational "Fix"
issues..

Can do it in the upgrade script if you like, not my first choice tho

e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
I'm OK with some other mechanism, but not sure what it should be - are we talking a 'manage ref data types' function in the app?

**Comment by ianibo** [comment]
Was thinking more like someone typing "update X set Y=Z" into an sql
console tbh

On 14 February 2013 14:04, Owen Stephens notifications@github.com wrote:

> I'm OK with some other mechanism, but not sure what it should be - are we
> talking a 'manage ref data types' function in the app?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/381#issuecomment-13550502.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Oh - that's fine!

Might need to get some documentation together so we can make this an Edina job?

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
New taglib has disposed of all custom js. Please add a requirement at a higher level for the behaviour of refdata editing.
