### ISSUE TITLE
Dates in Package/SO upload not parsed correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#387]
Tested on newdev branch 2013-04-02

Date parsing is not working correctly on uploads. Currently only validates file if date in formats:

yyyy/MM/dd
dd/MM/yyyy

Other formats (specifically yyyy which works on current release branch) fail validation.

On upload dates in yyyy/MM/dd and dd/MM/yyyy are not always parsed correctly. E.g. imported https://github.com/k-int/KBPlus/blob/newdev/manual_test_data/so_v3/upload_so_test_001.csv. All dates in dd/MM/yyyy format.

Sometimes dates parsed successfully:
http://knowplusdev.edina.ac.uk/kbplus/tipp/show/35148 - start date correctly parsed

Some dates fail to parse correctly - e.g.
http://knowplusdev.edina.ac.uk/kbplus/tipp/show/35155
has a start date of 0006-06-17 whereas in file it is 01/01/1994

**Comment by ianibo** [comment]
Struggling to investigate this.. can you confirm that dates were reported incorrectly on import feedback page as well as tipp show page? Need to track down exact point of error.. might not be in upload. upload_so_test_001 should never load as it has missing aggreement term start year?

**Comment by ianibo** [comment]
Hm.. OK. I'm guessing you've taken one of my test files and hacked it around somehow or just changed the identifier on one of the existing packages in the old format? Can you attach the csv used to this issue so we can re-create pls.

**Comment by ianibo** [comment]
Detected edge case when month == Jan and extra month check (Month <=12) interacted in unexpected way (Month now 0-based). Fixed that and merged onto test, but doesn't explain behaviour above, so not closing).

**Comment by ianibo** [comment]
N.B. Must be careful with date formats, and standardisation not code is the way to address... EG can't detect error if date 01/11/1999 but format MM/DD/YYYY. Really should just mandate date format IMO.

**Comment by ostephens** [comment]
Agree on mandating the format but had some kick back last time we proposed this. I wonder if we could strip it down to 2 options - either YYYY or MM/DD/YYYY - since I've yet to see a date in any other format in the import files.

**Comment by ostephens** [comment]
Imported same file successfully on dev branch now (this is rebuilding every few hours so I think it has your latest modification in it - which I guess solves that particular problem). For reference I used https://github.com/k-int/KBPlus/blob/newdev/manual_test_data/so_v3/upload_so_test_001.csv with no modification - it has all fields necessary to pass validation

**Comment by ostephens** [comment]
Are you happy with proposal to have two options for date:
YYYY
MM/DD/YYYY

or is this still going to create too many headaches?

**Comment by ianibo** [comment]
I think this should be working now.
