### ISSUE TITLE
TI matching in SO/Package import does not work correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#390]
Tested on newdev branch 2013-04-03

When importing SO/Package file, the process on matching TIPPs to existing TIs does not work correctly.

A TI should only count as matched if the import matches on key IDs (ISSN/eISSN/DOI/ISBN) and a Title 'fingerprint' match. At the moment it looks like a match will work on a single ID even if other IDs/Title don't match.

Examples:
publication_title,ID.issn,ID.eissn
Ambix,0002-6980,1745-8234
matches existing TI http://knowplusdev.edina.ac.uk/kbplus/titleDetails/edit/1029 which has details
Ambix: The Journal of the Society for the History of Alchemy and Chemistry,0002-6980,1745-8234
## Should fail as Title fingerprint does not match

publication_title,ID.issn,ID.eissn
Byzantine & Modern Greek Studies,0361-2112,1749-625X
matches existing TI http://knowplusdev.edina.ac.uk/kbplus/titleDetails/edit/1033 which has details:
Dress,0361-2112,2042-1729

**Comment by ianibo** [comment]
New tests passed in most recent commit.
