### ISSUE TITLE
New Identifiers not added to TIs when matched in SO/Package import

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#391]
Tested on newdev 2013-04-03

Where a TI is matched successfully to a TIPP line in the import file, but additional identifiers are specified in the imported TIPP line, these should be added to the TI.

Example:
publication_title,ID.issn,ID.eissn,ID.doi
Costume:  Journal of the Costume Society,0590-8876,1749-6306,DOI1234

Successfully matches correct existing TI which has details:
publication_title,ID.issn,ID.eissn,
Costume:  Journal of the Costume Society,0590-8876,1749-6306

But the new DOI specified in the import is not added

**Comment by ianibo** [comment]
Added code to do this, but can't find so file with the costume society record, struggling to test atm.

**Comment by ostephens** [comment]
Files for testing uploads are in dropbox https://www.dropbox.com/sh/kbuee67sguglofk/cPKJ_JlViC
Expected behaviour given in "test details.txt"
The example line given above is in test_upload_6.csv - however overall test_upload_6.csv will fail because of other errors. I'll create a new test file in the folder for this case to check ID is added OK

**Comment by ianibo** [comment]
Amy clues where this is in the folder hierarchy? Can't find it and need to
get the actual files

On 17 April 2013 15:49, Owen Stephens notifications@github.com wrote:

> Files for testing uploads are in dropbox
> https://www.dropbox.com/sh/kbuee67sguglofk/cPKJ_JlViC
> Expected behaviour given in "test details.txt"
> The example given above is in test_upload_6.csv
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/391#issuecomment-16510199
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
NVM found it

On 17 April 2013 15:53, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Amy clues where this is in the folder hierarchy? Can't find it and need to
> get the actual files
> 
> On 17 April 2013 15:49, Owen Stephens notifications@github.com wrote:
> 
> > Files for testing uploads are in dropbox
> > https://www.dropbox.com/sh/kbuee67sguglofk/cPKJ_JlViC
> > Expected behaviour given in "test details.txt"
> > The example given above is in test_upload_6.csv
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/391#issuecomment-16510199
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Added test_upload_9.csv that checks this specific case

**Comment by ianibo** [comment]
File rejected because I don't have a test org 1...  working on it

On 17 April 2013 15:54, ianibbo@gmail.com ianibbo@gmail.com wrote:

> NVM found it
> 
> On 17 April 2013 15:53, ianibbo@gmail.com ianibbo@gmail.com wrote:
> 
> > Amy clues where this is in the folder hierarchy? Can't find it and need
> > to get the actual files
> > 
> > On 17 April 2013 15:49, Owen Stephens notifications@github.com wrote:
> > 
> > > Files for testing uploads are in dropbox
> > > https://www.dropbox.com/sh/kbuee67sguglofk/cPKJ_JlViC
> > > Expected behaviour given in "test details.txt"
> > > The example given above is in test_upload_6.csv
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/391#issuecomment-16510199
> > > .
> > 
> > ## 
> > 
> > Ian Ibbotson
> > W: http://ianibbo.me
> > E: ianibbo@gmail.com
> > skype: ianibbo
> > twitter: ianibbo
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Yep - single pre-requisite is that existing "Test Org 1"

**Comment by ostephens** [comment]
Also test_upload_1.csv should successfully upload first if working from an empty db as this will populate all other data for subsequent tests (I think - that's how I tried to design files)

**Comment by ianibbo** [comment]
Manually created test org 1 and now get

Matched title identifier does not pass title fingerprint match.
titleid=838, alchemy ambix and chemistry for history journal of society the
!= ambix

Matched title identifier does not pass title fingerprint match.
titleid=800, armour arms != and armour arms

Mix of identifiers in row 2 match more than one title:([841, 839]). Please
correct. identifiers:[issn:0361-2112, eissn:1749-625X, kbart_title_id:BYZ]

Which I guess is a fair test?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Latest build up on the server is having some problems with the title fingerprint - but looks different to what you have here. Not quite sure when the build went up, so will leave testing now and have a look tomorrow when it has rebuilt from latest source
