### ISSUE TITLE
Combining year facet with other facet in Renewals basket search always results in 0 hits

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#393]
e.g. I select facet of 'Start Year' of 2013, and Consortia name of JISC Collections. URL generated on hitting search is:

http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsSearch?offset=0&pkgname=&search=yes&_fct%3AstartYear%3A2013=&fct%3AstartYear%3A2013=on&_fct%3AstartYear%3A2012=&_fct%3AstartYear%3A2011=&_fct%3AstartYear%3A2010=&_fct%3AcontentProvider%3AManey+Publishing=&_fct%3AcontentProvider%3AWiley=&_fct%3AcontentProvider%3AProject+Muse=&_fct%3AcontentProvider%3AOxford+University+Press=&_fct%3AcontentProvider%3ASpringer=&_fct%3AcontentProvider%3ARoyal+Society+of+Chemistry=&_fct%3AcontentProvider%3AIOP=&_fct%3AcontentProvider%3ADuke+University+Press=&_fct%3AcontentProvider%3ABioOne=&_fct%3AcontentProvider%3ABMJ=&_fct%3AconsortiaName%3AJISC+Collections=&fct%3AconsortiaName%3AJISC+Collections=on

Should result in (I believe) 100 items. Currently results in 0 items.

Conversely if I select Content Provider of Wiley and Consortia name of JISC Collections URL generated is:

http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsSearch?offset=0&pkgname=&search=yes&_fct%3AstartYear%3A2013=&_fct%3AstartYear%3A2012=&_fct%3AstartYear%3A2011=&_fct%3AstartYear%3A2010=&_fct%3AcontentProvider%3AManey+Publishing=&_fct%3AcontentProvider%3AWiley=&fct%3AcontentProvider%3AWiley=on&_fct%3AcontentProvider%3AProject+Muse=&_fct%3AcontentProvider%3ASpringer=&_fct%3AcontentProvider%3AOxford+University+Press=&_fct%3AcontentProvider%3AIOP=&_fct%3AcontentProvider%3AAmerican+Chemical+Society=&_fct%3AcontentProvider%3ABrill=&_fct%3AcontentProvider%3ABMJ=&_fct%3AcontentProvider%3ARoyal+Society+of+Chemistry=&_fct%3AconsortiaName%3AJISC+Collections=&fct%3AconsortiaName%3AJISC+Collections=on&_fct%3AconsortiaName%3ASHEDL=&_fct%3AconsortiaName%3AWHEEL=

Which correctly finds 18 items.

**Comment by ianibo** [comment]
Not able to reproduce locally.. solr issue?

![Screenshot from 2013-04-16 13:50:18](https://f.cloud.github.com/assets/53283/385857/40e416b4-a694-11e2-9b01-ffd45f49eb4d.png)

**Comment by ostephens** [comment]
Something in ES config then (looks like your local is config different to that on test). Suggestions on how to diagnose further?

**Comment by ianibo** [comment]
Well.. was looking at adding some info to results page explaining what
facets are in force.. probably need to get on and look in the logs then
paste the queries into the ES interface.

On 16 April 2013 13:56, Owen Stephens notifications@github.com wrote:

> Something in ES config then (looks like your local is config different to
> that on test). Suggestions on how to diagnose further?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/393#issuecomment-16442789
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
