### ISSUE TITLE
Updating Title on TitleDetails screen does not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#394]
Tested on test branch as at 2013-04-03
Editing a TI Title. I think this previously worked from a title details page like http://test.kbplus.ac.uk/kbplus/titleDetails/edit/547 - you just clicked the title at the top of the screen to edit it? It does not work now and I'm pretty sure it did before

**Comment by ianibo** [comment]
[predictably] broken along with most of the other js by the css merge. Fixed along with all the other broken css/js components.
