### ISSUE TITLE
Display of package content provider alongside package name on /packageDetails/list

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#399]
JC requested that on package list (e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/list) the content provider name should not appear in brackets after the package name in the 'Name' column

I'm guessing that changing this on this screen would also effect display of Package name in all other screens in the system such as:
http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentSubscriptions

Can you confirm that this is the case?

**Comment by ianibo** [comment]
Nope each page is a unique template. Needs to be changed everywhere if this is needed generally.. Is this really needed? It seems like extra information that is easily ignored, which some people might find useful, whilst others don't? Removing it seems a bit odd?

**Comment by ostephens** [comment]
Agree seems odd, but specifically requested!
