### ISSUE TITLE
Browse and/or filter organisations by role?

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#4]
Would it be possible to add the ability to browse and/or filter organisations by role? Would be handy to browse Publishers separate to Subscribing Orgs etc.

**Comment by ostephens** [comment]
Also thought about this - when viewing the organisation record (via the 'show' button) perhaps list the roles taken and link to relevant entities (e.g. 'Content provider for package A, package B'; Publisher for title list...). This might be as well or instead of the ability to browse or filter by org roles.

**Comment by ianibo** [comment]
How do you want this to work if an org is listed in multiple contexts.. If I choose "Publishers" it's anyone who has an org-role with a role-type of "publisher", is that right?

**Comment by ostephens** [comment]
Yes - so Orgs can appear in more than one list
