### ISSUE TITLE
Diacritics not showing correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#40]
Saw this in the CUP STM Package:
Animal Genetic Resources / Resources g??n??tiques animales / Recursos gen??ticos animales

Accents on letters not appearing

---

Submitted from: http://knowplusdev.edina.ac.uk:8080/kbplus/package/show/26

**Comment by ianibbo** [comment]
Heya..

I looked in the file in the import directory, and that file seems to have
??'s in it too... Is the file "corrupted" by the source system? I'm
guessing excel is spitting out CP1252 or something else thats not UTF-8?
I'm not 100% certain about this without getting a hex file editor out and
looking at the file tho.

Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Thu, Jun 14, 2012 at 12:39 PM, ostephens <
reply@reply.github.com

**Comment by ianibo** [comment]
Double checked.. input file does contain actual "?" characters, and isn't simply showing those for a non utf-8 diacritic.

**Comment by ostephens** [comment]
Ok thanks. Sorry for not checking file - still working between computers and not got the Dropbox synced everywhere yet

Owen

**Comment by ianibbo** [comment]
No worries...

Had it just been encoded in the windows code-page I could have fixed it,
but the characters seem to have been actively destroyed and replaced by "?"
so there's not much I can do..

Don't worry about checking the files.. I'm quite sure it's more efficient
to just get them in there and then spot problems.. There are way too many
variables and areas where things can go wrong to think we can pre-check
everything.

Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Thu, Jun 14, 2012 at 4:18 PM, ostephens <
reply@reply.github.com

> wrote:
> 
> Ok thanks. Sorry for not checking file - still working between computers
> and not got the Dropbox synced everywhere yet
> 
> Owen
>

**Comment by ostephens** [comment]
These characters are now correct in the data file, but in the Data Explorer they are not displaying at all (no ?? now, just not displaying)

**Comment by ianibo** [comment]
Need to check with edina that the database has been created with UTF8
charset.

On 20 June 2012 22:49, ostephens <
reply@reply.github.com

> wrote:
> 
> These characters are now correct in the data file, but in the Data
> Explorer they are not displaying at all (no ?? now, just not displaying)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/40#issuecomment-6468330

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Heya Owen.. Double checked the file in dropbox and I don't _believe_ (which is to say I can be wrong on this, but I don't think I am) that it contains UTF-8 Characters. They might be UTF-16 or something else still.. but not UTF-8 I'm afraid.

**Comment by ostephens** [comment]
OK - fixed in data files I hope - definitely saved as UTF-8 now - I did it myself!

I suspect there is a problem with M using Excel to edit the files - looks like saving csv as utf8 is not something that comes naturally to Excel

**Comment by ianibo** [comment]
Seems sorted with latest update to source files:
http://knowplus.edina.ac.uk/kbplus/?q=Animal+Genetic+Resources
And
http://knowplus.edina.ac.uk/kbplus/titleInstance/show/225
