### ISSUE TITLE
Cannot edit fields on Licence screens

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#402]
e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/85 - none of the fields that should be editable allow click/edit

**Comment by ostephens** [comment]
Further testing suggests some issues here may be caused by permissions problems. E.g. Test User A (oaYDLonYlJRXD3hKbU30N1mn4YQ=@edina.ac.uk) is affiliated to University of Westminster and is able to edit some fields of a template licence (e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/15) even though permissions suggest they should have read only rights

![Screen Shot 2013-04-16 at 09 21 51](https://f.cloud.github.com/assets/576174/384972/cf661a3e-a66e-11e2-8a21-c1facf7c471d.png)

**Comment by ianibo** [comment]
Nope.. not related to permissions, although permissions might come into play with the new style click to edits. This was caused by some JS libs being removed and some legacy JS calls no longer being available. Removing the old code seems to have fixed the click edit.
