### ISSUE TITLE
Editing on Subscription details screen not working correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#405]
e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/461

All fields in 'Subscription Information' area work correctly but in table of IEs only the batch edit cell for 'Core Status' works correctly. (this is the first editable cell in the table, so maybe related to issues #403 and #404 ?)

**Comment by ianibo** [comment]
Fixed start and end date batch edit.
