### ISSUE TITLE
Editing in Subscription Documents screen not working correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#406]
e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/documents/461

Click/edit does not work in Title/Filename cells
Clicking Subscription name on this screen opens up a edit box but box does not display correctly - rather than appearing in the correct location as on other similar screens, the top of the box is obscured by the menu bar

**Comment by ianibo** [comment]
Are these supposed to be editable?

**Comment by ianibo** [comment]
(Easy to add, just wasn't sure it's a req / a good idea?)

**Comment by ianibo** [comment]
Ditto some other recent issues.. maybe we should discuss before adding any more issues?

**Comment by ostephens** [comment]
To be honest not entirely certain what aspects of the Document data should be editable - but I'd want it to be consistent across the Subscription Document and Licence Document screens. V happy to discuss - do you want to chat?
