### ISSUE TITLE
When new titles added not indexed in ES

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#408]
When a user adds a new title from new 'add title' function (http://test.kbplus.ac.uk/kbplus/titleDetails/findTitleMatches) the title does not seem to be indexed in ES automatically

**Comment by ianibo** [comment]
Index update job should run every 10 mins... Can you just confirm suitable pause was left?

**Comment by ostephens** [comment]
Sounds likely that there was not a long enough gap - will let the team know this is the timing
