### ISSUE TITLE
Adding new TI ID

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#410]
When adding a new TI ID via a TI edit screen - e.g. http://test.kbplus.ac.uk/kbplus/titleDetails/edit/5438

If you simply type in an ID (whether existing or new) then click 'Add Identifier' then nothing happens. In order to successfully add the ID, you need to type it in (or partially type it in), then click on the ID in the dropdown list (even if you have typed in the whole ID string).

Is it possible that if you type a whole ID (especially if not already existing?) to avoid the step of clicking in the dropdown list?

**Comment by ianibbo** [comment]
Not possible afaik at the moment. But we could add some text making it
obvious that this needs to be done.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - thought it might be a limitation. Don't worry - it only affects 3/4 staff and I'm going to do some training with them so can point it out
