### ISSUE TITLE
Cannot edit Licence Properties or related notes on licence details screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#415]
Tested on newdev 2013-04-17
e.g. on http://knowplusdev.edina.ac.uk/kbplus/licenseDetails/index/143 cannot edit any of the licence property values:
Concurrent Access
Remote Access
Walk In Access
Multi Site Access
Partners Access
Alumni Access
ILL -  Inter Library Loans
Include in Coursepacks
Include in VLE
Enterprise Access
Post Cancellation Access Entitlement

Or any of associated notes from this screen (if notes already exist they can be edited from the licenseDetails/notes/ page

**Comment by ianibo** [comment]
Cause by same JS error as unable to edit public flag. Fixed in commit  e53c270..b0e7e02
