### ISSUE TITLE
User with read-only permissions can edit licence details

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#416]
Tested on newdev 2013-04-17
e.g. user TestUser1 http://knowplusdev.edina.ac.uk/kbplus/userDetails/edit/6
Has read-only membership of University of Westminster but is still able to edit following fields on a licence details screen (e.g. http://knowplusdev.edina.ac.uk/kbplus/licenseDetails/index/129)

Reference
Notice Period
Licence URL
Licensor Ref
Licensee Ref

Can also edit same fields on a totally unconnected licence such as 
http://knowplusdev.edina.ac.uk/kbplus/licenseDetails/index/15 (template licence)

**Comment by ianibo** [comment]
Latest checkin should sort this..

HOWEVER

care must be taken, the taglib now only allows users to edit if editable==true on the model, or editable is not set (Allowing all the screens that currently don't have global permissions to continue to work). This is a 2 line change that has an effect on every editable control in the app.. Since the controls are used in different contexts, and those contexts can change the behaviour, a substantial retest is suggested.

**Comment by ostephens** [comment]
Looks like there are still problems with a user with read-only membership of an org being able to edit things. E.g. 
http://test.kbplus.ac.uk/kbplus/userDetails/edit/59 (username Wftpsag2zAwBtIO53BjsJ9YIx1Y=@edina.ac.uk)

Is read only member of University of Westminster. Can edit licences:
http://test.kbplus.ac.uk/kbplus/licenseDetails/index/129 (Univ of Westminster actual licence)
http://test.kbplus.ac.uk/kbplus/licenseDetails/index/15 (Template licence not linked to UoW)

can edit subscriptions:
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/203 (Univ of Westminster sub taken)
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/19 (Sub Offered)

**Comment by ostephens** [comment]
Latest build (evening 2013-04-18) from newdev deployed on dev.kbplus.ac.uk
Some fields now behaving as expected, but still some issues. Read-only user correctly cannot edit the following fields:
- Reference
- Notice Period
- Licence URL
- Licensor Ref
- Licensee Ref

However following fields can still be edited by read-only user:
- Public?
- All "Licence Property" Status and associated Notes - except the Concurrent Access integer value

**Comment by ianibo** [comment]
Is it please possible to add links to the system for offending pages, and appropriate accounts for each test case. Really struggling to recreate these. Screenies would also help in some places.

**Comment by ostephens** [comment]
Does xEditableFieldNote also need checking? Think this is the other class of data on the licence screen that is appearing editable at the moment - e.g. on 
http://test.kbplus.ac.uk/kbplus/licenseDetails/index/129
Username: hharrop
Screenshot
![Screen Shot 2013-04-19 at 09 46 23](https://f.cloud.github.com/assets/576174/401079/52621f8a-a8ce-11e2-99f5-6b0985ca2db1.png)

**Comment by ianibo** [comment]
Should be done already - certainly made some changes recently. I _expect_ the notes to work as expected, but testing regularly proves me wrong ;)
