### ISSUE TITLE
Cannot edit 'Concurrent Access' property + note on licence screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#420]
Tested on newdev 2013-04-17 (pm)
All other licence properties now editable, but Concurrent Access property still not.
Related note also not editable

**Comment by ianibo** [comment]
Don't think I can make the count hidden in this release, need to add eventing to generic taglib, bigger job.

**Comment by ostephens** [comment]
No problem - really minor issue not worth large effort
