### ISSUE TITLE
On Subscription Details screen Dates displaying with format YYYY-MM-DD HH:MM:SS.s

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#430]
Tested from newdev build evening 2013-04-18
e.g. http://knowplusdev.edina.ac.uk/kbplus/subscriptionDetails/index/203
All dates:
Subscription Start Date
Subscription End Date
In IE table each Start Date and End Date

All display YYYY-MM-DD HH:MM:SS.s
Should display YYYY-MM-DD

**Comment by ianibo** [comment]
Am investigating, all appear YYYY-MM-DD for me.. not sure whats going on

![image](https://f.cloud.github.com/assets/53283/399258/924f4e18-a86c-11e2-83fb-ccac42278c4a.png)

**Comment by ostephens** [comment]
Looks like it is related to login. If I login with my own account displays correctly as you have here. If I login with kb+test2 then I see the alternative date display

**Comment by ianibo** [comment]
Can't seem to view any sub details page for kb+test2 as it doesn't have any org links?

**Comment by ianibo** [comment]
ooh wait.. is this for non-editable date display? Ah ha
