### ISSUE TITLE
'Editor' user cannot edit from issueEntitlement/show screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#431]
E.g. Username: kb+test5
http://test.kbplus.ac.uk/kbplus/issueEntitlement/show/37713

Would expect this user who has Editor membership of University of Westminster to be able to edit Issue Entitlement data on this screen - i.e.:
From Date
From Volume
From Issue
To Date
To Volume
To Issue
Embargo

Currently cannot - screenshot of relevant part of screen
![Screen Shot 2013-04-19 at 13 39 40](https://f.cloud.github.com/assets/576174/401912/95c49fb2-a8ee-11e2-8456-c00580e24151.png)
(editing of these fields initially requested via #401 )

**Comment by ianibo** [comment]
Ok.. this is because the [slightly complex] rules governing what is
editable haven't been written for an IE, hence nobody can edit. Will assume
that if Sub is editable then IE is editable and implement accordingly.

On 19 April 2013 13:44, Owen Stephens notifications@github.com wrote:

> E.g. Username: kb+test5
> http://test.kbplus.ac.uk/kbplus/issueEntitlement/show/37713
> 
> Would expect this user who has Editor membership of University of
> Westminster to be able to edit Issue Entitlement data on this screen - i.e.:
> From Date
> From Volume
> From Issue
> To Date
> To Volume
> To Issue
> Embargo
> 
> Currently cannot - screenshot of relevant part of screen
> [image: Screen Shot 2013-04-19 at 13 39 40]https://f.cloud.github.com/assets/576174/401912/95c49fb2-a8ee-11e2-8456-c00580e24151.png
> (editing of these fields initially requested via #401https://github.com/k-int/KBPlus/issues/401)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/431
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Thanks - that sounds like the right behaviour - i.e. A user can edit any IE attached to a subscription to which they have editing rights

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Fixed and merged on to test.

For ref.. can we report any page that should have editable fields that
doesn't have a nav-bar with "Editable By You" - Such pages are unlikely to
allow editing, and probably should have that info. If pages don't have
this, problems with editable fields are more likely to be somewhere other
than the fields themselves, so it will save effort for testers reporting
individual fields.

On 19 April 2013 13:53, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Ok.. this is because the [slightly complex] rules governing what is
> editable haven't been written for an IE, hence nobody can edit. Will assume
> that if Sub is editable then IE is editable and implement accordingly.
> 
> On 19 April 2013 13:44, Owen Stephens notifications@github.com wrote:
> 
> > E.g. Username: kb+test5
> > http://test.kbplus.ac.uk/kbplus/issueEntitlement/show/37713
> > 
> > Would expect this user who has Editor membership of University of
> > Westminster to be able to edit Issue Entitlement data on this screen - i.e.:
> > From Date
> > From Volume
> > From Issue
> > To Date
> > To Volume
> > To Issue
> > Embargo
> > 
> > Currently cannot - screenshot of relevant part of screen
> > [image: Screen Shot 2013-04-19 at 13 39 40]https://f.cloud.github.com/assets/576174/401912/95c49fb2-a8ee-11e2-8456-c00580e24151.png
> > (editing of these fields initially requested via #401https://github.com/k-int/KBPlus/issues/401)
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/431
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
