### ISSUE TITLE
Remote Access note displays with old 'click to edit' icon

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#435]
e.g. on http://test.kbplus.ac.uk/kbplus/licenseDetails/index/129
Remote Access note still shows 'pencil' icon - see screenshot
![Screen Shot 2013-04-19 at 23 15 56](https://f.cloud.github.com/assets/576174/404270/ecea1baa-a93e-11e2-8e63-0635a6131a28.png)

**Comment by ianibo** [comment]
Cleaned up along with other edit field note edit issues.
