### ISSUE TITLE
Cannot 'blank' text in a licence properties note

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#436]
E.g. on http://test.kbplus.ac.uk/kbplus/licenseDetails/index/129
If one of the Licence Properties has a related text note, with text in it
![Screen Shot 2013-04-19 at 23 22 14](https://f.cloud.github.com/assets/576174/404288/9fe26b36-a93f-11e2-9246-1abf84b7f5e4.png)

There does not seem to be a way of completely removing all text from a note. If you edit note, delete all text, click the 'tick' icon - field displays as 'Empty' on screen. However refreshing page shows previous text - indicating the 'blank' note not saved.

Any other edit on the note works and saves without a problem

**Comment by ianibo** [comment]
This is due in part to the fact that the field notes are notes, not fields on the object. Blanking them is really asking for a record delete of the context and the doc. Implemented, but uncomfortable with this area of the schema.. it's complex for no particularly good reason, and an accident waiting to happen. Should probably revisit at some point. (Deleting note from notes page would be better from a logic POV, but appreciate this appears inconsistent to user, so implemented as requested, also field notes no longer visible on notes page.)
