### ISSUE TITLE
Subscriptions taken screens not working

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#44]
Gives a Grails runtime exception
See http://knowplus.edina.ac.uk/kbplus/subscription/show/136

**Comment by ianibo** [comment]
This looks like it's caused by a subscription -> Org link that does not have a role type. I've adjusted to not blow up in this situation, but will leave the issue open until I'm certain that it's a valid thing to happen.

**Comment by ianibo** [comment]
Mea Culpa! I forgot to set up the reference data before this import, which means some of the type entries are not present. We need to re-run the import anyway as I need the scope from the FAM file to be able to auto match up users with orgs. Will re-run the import and re-set up.. probably late this eve.

**Comment by ianibo** [comment]
Clean upload. Sorted.
