### ISSUE TITLE
Subscriptions appearing multiple times via ES search on Test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#443]
e.g. http://test.kbplus.ac.uk/kbplus/home/index?q=bioone+master

The same subscription "BioOne Master 2013 ()" http://test.kbplus.ac.uk/kbplus/subscription/show/377 appears several times over in the results list. Also seen when using the 'Comparison Basket' search.

Not seeing same behaviour on live _yet_

Running 'Full Reset' http://test.kbplus.ac.uk/kbplus/admin/fullReset does not seem to resolve the problem

**Comment by ianibo** [comment]
Can you get me 9200 opened up on the test server pls? Need to look in ES
interface to try and figure out whats going on.

On 25 April 2013 11:21, Owen Stephens notifications@github.com wrote:

> e.g. http://test.kbplus.ac.uk/kbplus/home/index?q=bioone+master
> 
> The same subscription "BioOne Master 2013 ()"
> http://test.kbplus.ac.uk/kbplus/subscription/show/377 appears several
> times over in the results list. Also seen when using the 'Comparison
> Basket' search.
> 
> Not seeing same behaviour on live _yet_
> 
> Running 'Full Reset' http://test.kbplus.ac.uk/kbplus/admin/fullReset does
> not seem to resolve the problem
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/443
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Did you get anywhere with this?

**Comment by ianibbo** [comment]
Can't seem to get on to 9200 yet?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
See email from Gareth

**Comment by ianibbo** [comment]
System looks for and imports the kbart defined field "Coverage_notes",
example for this issue seems to use coverage_note? Please confirm which
should be used?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
YEs seen his email..

Tried to catch you on skype but not available.

Best guess is that ES isn't being correctly cleared down, but it's
incredibly hard to investigate at this distance and with this lack of
tooling.

/shrug

On 26 April 2013 15:00, Owen Stephens notifications@github.com wrote:

> See email from Gareth
> 
> On 26 Apr 2013, at 14:59, ianibbo notifications@github.com wrote:
> 
> > Can't seem to get on to 9200 yet?
> > 
> > Ian Ibbotson
> > Director
> > Knowledge Integration Ltd
> > 35 Paradise Street, Sheffield. S3 8PZ
> > T: 0114 273 8271
> > M: 07968 794 630
> > W: http://www.k-int.com
> > 
> > On 26 April 2013 14:44, Owen Stephens notifications@github.com wrote:
> > 
> > > Did you get anywhere with this?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/k-int/KBPlus/issues/443#issuecomment-17075044>
> > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/443#issuecomment-17075897
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by desreid** [comment]
Hi Ian, can you let me know what happened when you tried what Gareth suggested? Need to figure out if it's firewall prob or other. Also, let me know what tooling you need, assuming you're referring to knowplustest.

Ian Ibbotson notifications@github.com wrote:

> YEs seen his email..
> 
> Tried to catch you on skype but not available.
> 
> Best guess is that ES isn't being correctly cleared down, but it's
> incredibly hard to investigate at this distance and with this lack of
> tooling.
> 
> /shrug
> 
> On 26 April 2013 15:00, Owen Stephens notifications@github.com wrote:
> 
> > See email from Gareth
> > 
> > On 26 Apr 2013, at 14:59, ianibbo notifications@github.com wrote:
> > 
> > > Can't seem to get on to 9200 yet?
> > > 
> > > Ian Ibbotson
> > > Director
> > > Knowledge Integration Ltd
> > > 35 Paradise Street, Sheffield. S3 8PZ
> > > T: 0114 273 8271
> > > M: 07968 794 630
> > > W: http://www.k-int.com
> > > 
> > > On 26 April 2013 14:44, Owen Stephens notifications@github.com
> > > wrote:
> > > 
> > > > Did you get anywhere with this?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/k-int/KBPlus/issues/443#issuecomment-17075044>
> > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/k-int/KBPlus/issues/443#issuecomment-17075897
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/443#issuecomment-17077698

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ianibbo** [comment]
Wget does, as before work in it's own right, it's just not really usable
for me as I have tools that use the REST API over HTTP to give me an admin
console I can use to navigate ES structures.

It's not so much the ability to send a single request as have an app have a
conversation on my behalf. ES doesn't provide 1 big message that does
everything, its loads of micro rest calls over a HTTP substrate. Saying
"use wget" doesn't really work for me :(

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Should be resolved by latest change defaulting in an impId for SOs created by materialising a pkg as a result of new import process.

**Comment by desreid** [comment]
Ok, I think we are at cross purposes. Im not suggesting you use wget. Just asking if you can access port 9200 on knowplustest.edina (_not_ test.kbplus, which defo wont work). If you need some other ports to be open too, because of the tools you are using, then let me know. 

ianibbo notifications@github.com wrote:

> Wget does, as before work in it's own right, it's just not really
> usable
> for me as I have tools that use the REST API over HTTP to give me an
> admin
> console I can use to navigate ES structures.
> 
> It's not so much the ability to send a single request as have an app
> have a
> conversation on my behalf. ES doesn't provide 1 big message that does
> everything, its loads of micro rest calls over a HTTP substrate. Saying
> "use wget" doesn't really work for me :(
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 26 April 2013 15:40, desreid notifications@github.com wrote:
> 
> > Hi Ian, can you let me know what happened when you tried what Gareth
> > suggested? Need to figure out if it's firewall prob or other. Also,
> > let me
> > know what tooling you need, assuming you're referring to
> > knowplustest.
> > 
> > Ian Ibbotson notifications@github.com wrote:
> > 
> > > YEs seen his email..
> > > 
> > > Tried to catch you on skype but not available.
> > > 
> > > Best guess is that ES isn't being correctly cleared down, but it's
> > > incredibly hard to investigate at this distance and with this lack
> > > of
> > > tooling.
> > > 
> > > /shrug
> > > 
> > > On 26 April 2013 15:00, Owen Stephens notifications@github.com
> > > wrote:
> > > 
> > > > See email from Gareth
> > > > 
> > > > On 26 Apr 2013, at 14:59, ianibbo notifications@github.com
> > > > wrote:
> > > > 
> > > > > Can't seem to get on to 9200 yet?
> > > > > 
> > > > > Ian Ibbotson
> > > > > Director
> > > > > Knowledge Integration Ltd
> > > > > 35 Paradise Street, Sheffield. S3 8PZ
> > > > > T: 0114 273 8271
> > > > > M: 07968 794 630
> > > > > W: http://www.k-int.com
> > > > > 
> > > > > On 26 April 2013 14:44, Owen Stephens notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > Did you get anywhere with this?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > > https://github.com/k-int/KBPlus/issues/443#issuecomment-17075044>
> > > > > > 
> > > > > > .
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on
> > 
> > GitHubhttps://github.com/k-int/KBPlus/issues/443#issuecomment-17075897
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Ian Ibbotson
> > > W: http://ianibbo.me
> > > E: ianibbo@gmail.com
> > > skype: ianibbo
> > > twitter: ianibbo
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/k-int/KBPlus/issues/443#issuecomment-17077698
> > 
> > ## 
> > 
> > Sent from my Android phone with K-9 Mail. Please excuse my brevity.
> > The University of Edinburgh is a charitable body, registered in
> > Scotland, with registration number SC005336.
> > 
> > —
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/k-int/KBPlus/issues/443#issuecomment-17078245
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/443#issuecomment-17078726

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
