### ISSUE TITLE
Changing start/end dates on SO

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#447]
Changing start/end dates for an SO should create an alert on related STs (see also #361)

At the moment it looks like changing the start/end date creates an alert of somekind - visible via the dashboard, but this does not appear as a change you can accept/reject on the ST.

The other field for which this should happen is SO Name (subscription.sub_name) - and this works fine with alert appearing on the ST with an accept/reject option

**Comment by ianibo** [comment]
Closing since we don't have SOs any longer?
