### ISSUE TITLE
Coverage notes not picked up in Package/SO upload

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#448]
Coverage notes (col heading coverage_notes) do not seem to be picked up correctly in the upload.

When you do the upload, they do appear on the confirmation screen, 

![Screen Shot 2013-04-26 at 14 16 33](https://f.cloud.github.com/assets/576174/430697/b2fde77a-ae73-11e2-8dfc-7182067f4e2e.png)

but then they are not present in the relevant TIPP

![Screen Shot 2013-04-26 at 14 17 13](https://f.cloud.github.com/assets/576174/430698/b7784bce-ae73-11e2-83a3-ae0de9b57ab5.png)

**Comment by ianibo** [comment]
Scratch last.. still investigating

**Comment by ianibo** [comment]
Fixed in head.

**Comment by ostephens** [comment]
Just in case my example has confused - it should be 'coverage_notes' in col heading. Variation here was my fault, but it didn't work with coverage_notes either

**Comment by ianibo** [comment]
No, there was an error, it's fixed now. My bad. sorry.

On 26 April 2013 16:20, Owen Stephens notifications@github.com wrote:

> Just in case my example has confused - it should be 'coverage_notes' in
> col heading. Variation here was my fault, but it didn't work with
> coverage_notes either
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/448#issuecomment-17080796
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
