### ISSUE TITLE
When adding licence to Subscription, if the licence does not have a 'reference' it appears as 'null'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#451]
If a licence lacks a 'reference' then on the Subscription screen it appears as 'null' instead of 
'No licence reference'. Also in the dropdown to select the licence

e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/461

**Comment by ianibbo** [comment]
Should we make reference mandatory rather than defaulting in "No license
reference"?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Latest fix displays correctly in dropdown, but once value is saved the reference string does not display - the licence database reference displays instead - see screenshot

![Screen Shot 2013-04-29 at 11 14 37](https://f.cloud.github.com/assets/576174/437991/e55030fe-b0b5-11e2-9da2-d61210b015d5.png)

**Comment by ostephens** [comment]
Fixed
