### ISSUE TITLE
Agreement Term Start Date and Agreement Term End date not being set on Package/SO upload

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#453]
When uploading a Package/SO file the Agreement Start and End dates are not being picked up and set correctly.

Tested on test branch 2pm 30th April. E.g. tried uploading
/KB+/Spec - Imports/SO Import/testdata/test_upload_1.csv

Has dates set:
Agreement Term Start Year,01/01/2013,,,,,,,,,,,,,,,,,,,,,
Agreement Term End Year,31/12/2013,,,,,,,,,,,,,,,,,,,,,

On upload the reviewSO screen looks OK:

![screen shot 2013-04-30 at 13 59 29](https://f.cloud.github.com/assets/576174/443962/13bc2c50-b196-11e2-96f8-80bbc119ecc4.png)

but when you look at the Subscription created (http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/542) - you can see no dates set
![screen shot 2013-04-30 at 14 03 00](https://f.cloud.github.com/assets/576174/443965/5b14d408-b196-11e2-83d1-de3e1ce62fc3.png)

**Comment by ianibo** [comment]
This should be fixed in test.

**Comment by ostephens** [comment]
Thanks Ian - looking good - apologies for not picking these up before :(

**Comment by ianibo** [comment]
No worries, all good :) ta for getting em in.

On 30 April 2013 21:18, Owen Stephens notifications@github.com wrote:

> Thanks Ian - looking good - apologies for not picking these up before :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/453#issuecomment-17251538
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
