### ISSUE TITLE
Grails error when trying to view user

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#456]
Most users work fine, but trying to look at http://test.kbplus.ac.uk/kbplus/userDetails/edit/98
Get error:
URI
/kbplus/userDetails/edit/98
Class
java.lang.NullPointerException
Message
Cannot get property 'authority' on null object

Trace

```
Line | Method
```

->>   56 | runWorker in /userDetails/edit.gsp

---

Caused by NullPointerException: Cannot get property 'authority' on null object
->>   67 | doCall    in gsp_demo_userDetailsedit_gsp$_run_closure2

---

|     97 | run       in gsp_demo_userDetailsedit_gsp
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

**Comment by ianibbo** [comment]
Have added an extra null  check, but this suggests that some SQL has not
been run as it's a hangback to the old roles stuff.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Extra check has fixed issue
