### ISSUE TITLE
Prevent addition of >1 TIPP for a TI within a package

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#457]
At the moment the 'Add Title to this Package' function (e.g. from http://test.kbplus.ac.uk/kbplus/packageDetails/show/1) allows the addition of a TIPP for a TI, even if there is already a TIPP representing that TI in the package. This should not be allowed.

**Comment by ianibo** [comment]
Closing this one - I think it's complex - and probably should be allowed in some circumstances. Open a new one after discussion if still an issue that needs to be addressed.
