### ISSUE TITLE
Add option to (soft) delete TIs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#458]
Suggest an option to set TI status on titleDetails edit screen (e.g. http://test.kbplus.ac.uk/kbplus/titleDetails/edit/6192) although happy with other approaches.

Should not be allowed if there are any TIPPs associated with TI

If there are SIDs attached to TI, could allow the delete and also update statuses on those SIDs to 'deleted'?

If there are Orgs attached to TI, allow delete and do not change status of Org

**Comment by ianibo** [comment]
Deleted - conflates too much stuff - esp wrt the deleted SIDS.
