### ISSUE TITLE
Checking ISSN/eISSN/ISBN format when adding new SIDs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#459]
When adding a SID to a TI via titleDetails page (e.g. http://test.kbplus.ac.uk/kbplus/titleDetails/edit/1) is it possible to enforce the same rules for ISSNs/ISBNs as on upload of Package? That is:

ISSNs - issn_string ==~ '[0-9]{4}-[0-9]{3}[0-9X]'
ISBNs - isbn_string ==~ '(97(8|9))?[0-9]{9}[0-9X]'

**Comment by ianibbo** [comment]
This is tricky, because the SIDs are just strings, will investigate special
cases.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - maybe some validation in page on submit rather than on the data side?

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibbo** [comment]
Trouble with that is what if you want to add an identifier that isn't an
isxn = like a doi or even a URI or a title key string?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
But submitted string has to start with namespace? So could check for namespace on submission and see if it matches a 'validated' format?

Sorry - just thinking out load, not got any particular preference as to how is implemented

**Comment by ianibbo** [comment]
yes, we could add some code to say that a namespace implies a format, or
better yet that a namespace can have validation criteria attached.. but
it's not entirely trivial. Deffo OK as a requirement, but not "Just adding
some client side validation code"

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Understood

**Comment by latusaki** [comment]
Validation will happen only for specified namespaces .  This validation will be inside Identifier.groovy.  Currently it looks like the is no easy way to give personalized error msg for validation, so there will be one for every case.

**Comment by iyawnis** [comment]
If you need this Identifier validation on other screens let me know so I can add the relevant gsp code.

**Comment by iyawnis** [comment]
I have added a new field under IdentifierNamespace, for providing a validation regex. Any Identifiers that provide that regex will be validated. The regex will be added through post script, so if we need more validators than ISSN/ ISBN let me know.

**Comment by ostephens** [comment]
The 'ISSN' pattern should be used to validate both the ISSN and the eISSN namespace.
The 'jusp' namespace should contain only digits
The 'juspsid' namespace should contain only digits
