### ISSUE TITLE
Titles published by org

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#46]
If you look at Cambridge University Press org page
http://knowplus.edina.ac.uk/kbplus/org/show/1

It lists one title instance (Dance Research Journal) where CUP has the role of 'publisher'. However, there are several titles in the data (and in the same data file) where "Cambridge University Press" is listed in the publisher column (loaded from KB+\System - Data\Current\Subscriptions Offered\Project muse_premium collection_2012_2013_nesli2.csv)

Why does only this one display?

**Comment by ianibo** [comment]
Titles are not updated with info from the current file if they already
exist.

Is it possible these titles come from other files where publisher is not
listed? I don't have the csvs with me atm so can't check. This would be my
starter for 10 tho.

I can update titles with info from the current file, its possibly dangerous
tho..

Thoughts?

Ian.

On 20 June 2012 22:48, ostephens <
reply@reply.github.com

> wrote:
> 
> If you look at Cambridge University Press org page
> http://knowplus.edina.ac.uk/kbplus/org/show/1
> 
> It lists one title instance (Dance Research Journal) where CUP has the
> role of 'publisher'. However, there are several titles in the data (and in
> the same data file) where "Cambridge University Press" is listed in the
> publisher column (loaded from KB+\System - Data\Current\Subscriptions
> Offered\Project muse_premium collection_2012_2013_nesli2.csv)
> 
> Why does only this one display?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/46

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
OK - that makes sense - looks like the one title that displays is 
probably unusual as being made available via Project Muse (which lists 
publisher) but not directly from Cambridge University Press (the CUP 
files oddly don't list publisher, even though its CUP for all of them)

Not sure about best way to handle conflicting information across two 
data files - in this case since one file doesn't state publisher, and 
another one does I think I'd tend to add in the information but can see 
if they both stated a different publisher we'd have conflict and no 
clear way to resolve...

Not sure tbh

Owen

**Comment by ianibo** [comment]
OK.. I've made a change to set publisher only if the importer sees a title
with a publisher but doesn't currently handle ones. Conflicts will be
ignored, and a subsequent null won't reset whats in the file..

Testing it now.

Ian.

On 20 June 2012 23:52, ostephens <
reply@reply.github.com

> wrote:
> 
> OK - that makes sense - looks like the one title that displays is
> probably unusual as being made available via Project Muse (which lists
> publisher) but not directly from Cambridge University Press (the CUP
> files oddly don't list publisher, even though its CUP for all of them)
> 
> Not sure about best way to handle conflicting information across two
> data files - in this case since one file doesn't state publisher, and
> another one does I think I'd tend to add in the information but can see
> if they both stated a different publisher we'd have conflict and no
> clear way to resolve...
> 
> Not sure tbh
> 
> Owen
> 
> On 20/06/2012 23:34, Ian Ibbotson wrote:
> 
> > Titles are not updated with info from the current file if they already
> > exist.
> > 
> > Is it possible these titles come from other files where publisher is not
> > listed? I don't have the csvs with me atm so can't check. This would be
> > my
> > starter for 10 tho.
> > 
> > I can update titles with info from the current file, its possibly
> > dangerous
> > tho..
> > 
> > Thoughts?
> > 
> > Ian.
> > 
> > On 20 June 2012 22:48, ostephens <
> > reply@reply.github.com
> > 
> > > wrote:
> > > If you look at Cambridge University Press org page
> > > http://knowplus.edina.ac.uk/kbplus/org/show/1
> > > 
> > > It lists one title instance (Dance Research Journal) where CUP has the
> > > role of 'publisher'. However, there are several titles in the data (and
> > > in
> > > the same data file) where "Cambridge University Press" is listed in the
> > > publisher column (loaded from KB+\System - Data\Current\Subscriptions
> > > Offered\Project muse_premium collection_2012_2013_nesli2.csv)
> > > 
> > > Why does only this one display?
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/k-int/KBPlus/issues/46
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/46#issuecomment-6469767

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
http://knowplus.edina.ac.uk/kbplus/org/show/1

Should be sorted now.. Titles without publishers were being added to "Unknown Publisher". The subsequent test to default in a publisher if a title sees one later: "Set publisher if publisher null" therefore never evaluated to true, and the real publisher never is able to overwrite "Unknown Publisher". "Unknown Publisher" disabled to fix this problem, but don't know if null publishers might cause us trouble elsewhere.
