### ISSUE TITLE
kbart_title_id from upload file needs to be associated with TIPP not TI

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#462]
See also #461 

The kbart_title_id needs to be at the TIPP level, not the TI level. The kbart_title_id is a kbart concept (http://www.uksg.org/kbart/s5/guidelines/data_fields#title_ID):

"... the proprietary identifier for the content title, if you use a Title ID to create
links to content. If more than one identifier exists, then supply the Title ID used
for linking."

So as you can see, not really an 'ID', more of a 'link fragment'. The main motiviation for KB+ storing this is in order to output KBART files that can be used by link resolvers. This can only happen if kbart_title_id is stored at TIPP level.

This suggests we need to agree a way of changing the upload process to allow the import of TIPP level IDs vs TI level IDs. This may also resolve #461 - at least in this instance

**Comment by ianibo** [comment]
Bit confused by this one too.. which upload is this for? SO Upload isn't kbart compliant anyway is it, since we've switched to the id.xxx (ID.kbart_title_identifier). Think I understand the general gist, but confused by where the kbart stuff fits in?

**Comment by ianibo** [comment]
Would be easier if we could reserve id.XXX for title identifiers and use an alternate field - either tippid.TYPE or just tippid if this is a unique case for this. Thoughts?

**Comment by ostephens** [comment]
The requirement is basically to be able to add TIPP level IDs. This is the only case we have currently, but I guess may not be in the future, so I'd go for tippid.TYPE
