### ISSUE TITLE
Grails error when viewing Org

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#468]
A grails error when viewing an org e.g. 
http://service.kbplus.ac.uk/kbplus/organisations/show/172

Think it may only occur when Org has a content provider role? E.g. http://service.kbplus.ac.uk/kbplus/organisations/show/2 works fine

Error 500: Internal Server Error
URI
/kbplus/organisations/show/172
Class
groovy.lang.MissingPropertyException
Message
No such property: status for class: com.k_int.kbplus.Package

  Line | Method
->>  464 | runWorker in /organisations/show.gsp

---

Caused by GrailsTagException: Error executing tag <g:link>: No such property: status for class: com.k_int.kbplus.Package
->>   88 | doCall    in /WEB-INF/grails-app/views/organisations/show.gsp

---

Caused by MissingPropertyException: No such property: status for class: com.k_int.kbplus.Package
->>  159 | doCall    in gsp_demo_organisationsshow_gsp$_run_closure2_closure9

---

|    162 | doCall    in gsp_demo_organisationsshow_gsp$_run_closure2
|    210 | run . . . in gsp_demo_organisationsshow_gsp
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run       in java.lang.Thread

**Comment by ianibo** [comment]
Fixed in newdev.
