### ISSUE TITLE
Package not displaying content provider

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#47]
This package http://knowplus.edina.ac.uk/kbplus/package/show/65 isn't showing content provider (Project Muse) in brackets correctly after the package name. I can't see an obvious problem in the relevant data files:
KB+\System - Data\Current\Subscriptions Offered\Project muse_socialscience collection_2012_2013_nesli2.csv
KB+\System - Data\Current\Subscriptions Offered\Project muse_socialscience collection_2012_2013_shedl.csv

but may be missing something obvious.

Other files for same content provider work fine

**Comment by ianibo** [comment]
This seems OK now.. can you confirm?

**Comment by ostephens** [comment]
Yes - fixed

Thanks
