### ISSUE TITLE
Grails error when trying to create comparison sheet export on newdev

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#472]
On trying to export a comparison sheet get a Grails error - url http://knowplusdev.edina.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsSearch?offset=0&pkgname=brill&generate=yes&_fct%3AstartYear%3A2013=&_fct%3AstartYear%3A2012=

Error 500: Internal Server Error
URI
/kbplus/myInstitutions/JISC_Collections/renewalsSearch
Class
org.hibernate.ObjectNotFoundException
Message
No row with the given identifier exists: [com.k_int.kbplus.RefdataValue#0]
Trace
    Line | Method
->> 1369 | doCall         in com.k_int.kbplus.MyInstitutionsController$_generateMatrix_closure14_closure56

---

|   1368 | doCall         in com.k_int.kbplus.MyInstitutionsController$_generateMatrix_closure14
|   1325 | generateMatrix in com.k_int.kbplus.MyInstitutionsController
|   1308 | generate       in     ''
|   1120 | renewalsSearch in     ''
|   1110 | runWorker      in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run            in java.lang.Thread

**Comment by ianibo** [comment]
This is a problem with db migration script.. investigating. Looks like new tipps are not getting default status set and somehow tipp status field is not null in db. Should not be.

**Comment by ianibo** [comment]
Changed update.txt to also set tipp status where it's == 0 as well as null. _should_ fix it.

**Comment by ostephens** [comment]
Fixed
