### ISSUE TITLE
On newdev when an 'empty' subscription created, doesn't show in current subs list

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#474]
By 'empty' mean not attached to any packages / no subscriptionPackage

e.g. e.g. http://knowplusdev.edina.ac.uk/kbplus/subscriptionDetails/index/683 doesn't display in http://knowplusdev.edina.ac.uk/kbplus/myInstitutions/JISC_Collections/currentSubscriptions

**Comment by ianibo** [comment]
Still working on this, please leave for now

**Comment by ianibo** [comment]
(Doesn't show because no start/end dates and date filter set btw)

**Comment by ostephens** [comment]
Ah - doh!

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936
