### ISSUE TITLE
On newdev creating a "New Subscription (via Package)" always allocates the same 'Identifier'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#476]
Creating a "New Subscription (via Package)" always allocates the 'Identifier' "A New subscription identifier....." - e.g. see http://knowplusdev.edina.ac.uk/kbplus/subscription/edit/684

**Comment by ianibo** [comment]
Yes, what would you like it to be instead?

On 23 May 2013 22:18, Owen Stephens notifications@github.com wrote:

> Creating a "New Subscription (via Package)" always allocates the
> 'Identifier' "A New subscription identifier....." - e.g. see
> http://knowplusdev.edina.ac.uk/kbplus/subscription/edit/684
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/476
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Don't know tbh - maybe it doesn't matter? Or could just be incremental sequence?

**Comment by ostephens** [comment]
Does it matter what the identifier is? I don't think Institutions will know what to put in here, so we should allocate a sensible default - if this is just the current situation I'm happy and we can close this, but my feeling is that we may as well assign a GUID in the background as have loads of Subs with the same default ID?

**Comment by ianibo** [comment]
Closing (New sub via package has gone) New Sub (empty) allocates a guid but allows users to override.
