### ISSUE TITLE
On newdev creating a "New Subscription (via Package)" always copies entitlements

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#478]
Even when using the 'without entitlements' option e.g. this URL
http://knowplusdev.edina.ac.uk/kbplus/subscriptionDetails/index/684?createSubAction=nocopy&packageId=136&shortcode=JISC_Collections

The entitlements are still copied

**Comment by ianibo** [comment]
Can be closed now?

**Comment by ostephens** [comment]
This option has been removed, so can close issue
