### ISSUE TITLE
Packages provided by 'Annual Reviews' not displaying properly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#48]
None of the packages with content provider of Annual Reviews (http://knowplus.edina.ac.uk/kbplus/org/show/106) are displaying properly - e.g.

http://knowplus.edina.ac.uk/kbplus/package/show/50
http://knowplus.edina.ac.uk/kbplus/package/show/66
http://knowplus.edina.ac.uk/kbplus/package/show/86
http://knowplus.edina.ac.uk/kbplus/package/show/7
http://knowplus.edina.ac.uk/kbplus/package/show/12
http://knowplus.edina.ac.uk/kbplus/package/show/43
http://knowplus.edina.ac.uk/kbplus/package/show/81
http://knowplus.edina.ac.uk/kbplus/package/show/49
http://knowplus.edina.ac.uk/kbplus/package/show/78

**Comment by ianibo** [comment]
Heya Owen...

Some debug from the import (Below) seems to indicate that the so doesn't have a platform, hence the TIPP isn't created.. What should I do in this case?

**Processing pub title:Annual Review of Anthropology, print identifier 0084-6570 (0 prop cols, 2 plat cols)
Publisher name: Annual Reviews
Process platform Annual Reviews / host  / http://www.annualreviews.org/journal/anthro
Non host platform: host  : http://www.annualreviews.org/journal/anthro
Process platform Annual Reviews / administrative /
Non host platform: administrative :
One of title-[_id:4fdb4c26b76028a0e7f4cba4, title:Annual Review of Anthropology, identifier:[[type:ISSN, value:0084-6570], [type:eISSN, value:1545-4290]], publisher:4fdb4c25b76028a0e7f4cba0, lastmod:1339771942009], pkg-[_id:4fdb4d1fb76062d54ba752f4, identifier:Annual Reviews:Sciences Collection of 34, normIdentifier:AnnualReviewsSciencesCollectionof34, name:Annual Reviews Sciences Collection of 34, lastmod:1339772191550, subs:[4fdb4d1fb76062d54ba752f3], contentProvider:4fdb4c25b76028a0e7f4cba0] or platform-null are missing!!!

**Comment by ianibo** [comment]
Platform role in so file had, you guessed it, a space, so it read 'host ' and not 'host' thus we weren't able to identify a host platform. Trimmed now.

**Comment by ostephens** [comment]
I suspect it is right not to import something with no host platform (is 
this written in the _bad files?)

But in this case I can't see why it thinks there is no platform - the 
data file looks OK to me, specifying a host platform and an admin 
platform and the output here seems to be picking them both up but then 
seeing the host platform as a 'non host platform'?

Puzzled!

Owen

**Comment by ianibo** [comment]
Yep.. it adds up from my side... "Host" platform is the special one that
the FK from tipp rests on for it's ternary relationship. Other platform
links go via the platforms link table. It's this special case that was
tripping things up I think.

Lets see what happens :)

On 22 June 2012 10:24, ostephens <
reply@reply.github.com

> wrote:
> 
> I suspect it is right not to import something with no host platform (is
> this written in the _bad files?)
> 
> But in this case I can't see why it thinks there is no platform - the
> data file looks OK to me, specifying a host platform and an admin
> platform and the output here seems to be picking them both up but then
> seeing the host platform as a 'non host platform'?
> 
> Puzzled!
> 
> Owen
> 
> On 22/06/2012 10:10, Ian Ibbotson wrote:
> 
> > Heya Owen...
> > 
> > Some debug from the import (Below) seems to indicate that the so doesn't
> > have a platform, hence the TIPP isn't created.. What should I do in this
> > case?
> > 
> > **Processing pub title:Annual Review of Anthropology, print identifier
> > 0084-6570 (0 prop cols, 2 plat cols)
> > Publisher name: Annual Reviews
> > Process platform Annual Reviews / host  /
> > http://www.annualreviews.org/journal/anthro
> > Non host platform: host  : http://www.annualreviews.org/journal/anthro
> > Process platform Annual Reviews / administrative /
> > Non host platform: administrative :
> > One of title-[_id:4fdb4c26b76028a0e7f4cba4, title:Annual Review of
> > Anthropology, identifier:[[type:ISSN, value:0084-6570], [type:eISSN,
> > value:1545-4290]], publisher:4fdb4c25b76028a0e7f4cba0,
> > lastmod:1339771942009], pkg-[_id:4fdb4d1fb76062d54ba752f4,
> > identifier:Annual Reviews:Sciences Collection of 34,
> > normIdentifier:AnnualReviewsSciencesCollectionof34, name:Annual Reviews
> > Sciences Collection of 34, lastmod:1339772191550,
> > subs:[4fdb4d1fb76062d54ba752f3], contentProvider:4fdb4c25b76028a0e7f4cba0]
> > or platform-null are missing!!!
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/k-int/KBPlus/issues/48#issuecomment-6503574
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/48#issuecomment-6503805

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
