### ISSUE TITLE
On linkPackage screen button should read 'Add to Subscription'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#488]
Currently button in 'additional info' column on http://test.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/461 reads 'Add to package'. Should read 'Add to Subscription'

**Comment by ianibo** [comment]
Think this was done as a part of the dev? please repopen if still wrong.

**Comment by ostephens** [comment]
Currently reads 'Add to package' - see screenshot (from dev.kbplus.ac.uk just now)
![screen shot 2013-06-06 at 16 32 24](https://f.cloud.github.com/assets/576174/618860/742a7598-cebe-11e2-81e5-bc4c58b7ab76.png)

**Comment by ianibo** [comment]
Hmms.. Something wrong with build then:

![screenshot from 2013-06-06 17 04 23](https://f.cloud.github.com/assets/53283/619026/d385712e-cec2-11e2-8800-74b07a7e6037.png)

**Comment by ianibo** [comment]
Hmm.. nope.. it appears like that on dev for me too.. _confused_

**Comment by ianibo** [comment]
But stuck how to progress this one.. it looks fixed to me.. dunno how to recreate what you are seeing.

**Comment by ostephens** [comment]
Ok - let me check again - will be later this eve

**Comment by ostephens** [comment]
Must have just been a delay in deployment - working now - although display of Link/Link + Entitlements button is a bit off on my Mac
