### ISSUE TITLE
On upload package Content Provider org not always matched/created

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#501]
e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/show/271 and http://test.kbplus.ac.uk/kbplus/packageDetails/show/272 created by identical upload files

From what I can tell in the first case (http://test.kbplus.ac.uk/kbplus/packageDetails/show/271) no matching Org found, so created successfully and added as Content Provider

In second case (http://test.kbplus.ac.uk/kbplus/packageDetails/show/272) there should have been a matching Org found - but this has failed at some point (either in terms of finding the org, or in terms of creating the content provider role?)

**Comment by ianibo** [comment]
Any more info on this? http://test.kbplus.ac.uk/kbplus/packageDetails/show/272 seems to have CP set to JC? Can you attach the original upload files to the issue pls? ta.

**Comment by ostephens** [comment]
Data has been refreshed since the original report so ignore URLs in original report now - sorry. Example file content at https://gist.github.com/ostephens/5722006/download

Upload to test at 2013-06-06 15:40 led to http://test.kbplus.ac.uk/kbplus/packageDetails/show/278 - no CP

**Comment by ianibo** [comment]
Just tested locallaly by updating package ID and loading AACR Master Twice. Both deffo have CP set to "American Association of Cancer Research" so certain this is working in local codebase. One for tuesday call if still not working on test.

**Comment by ianibo** [comment]
Closing due to absence of sustained opposition :) please re-open if re-appears.
