### ISSUE TITLE
404 for packageDetails/index

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#502]
Accessing URL http://test.kbplus.ac.uk/kbplus/packageDetails/index

Get following 404

HTTP Status 404 - /kbplus/WEB-INF/grails-app/views/packageDetails/index.jsp

type Status report

message /kbplus/WEB-INF/grails-app/views/packageDetails/index.jsp

description The requested resource (/kbplus/WEB-INF/grails-app/views/packageDetails/index.jsp) is not available.

Apache Tomcat/7.0.27

**Comment by ianibo** [comment]
Think this is fixed on dev. Didn't deploy to test because of helen.

**Comment by ostephens** [comment]
Ah - thanks. Should have checked dev - sorry
