### ISSUE TITLE
Adding counts to title lists

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#51]
How easy would it be to add a 'count' as standard to any list of TIs or TIPPs in the data explorer.

My first priority would be that any Package included a count of the number TIPPs in the package. However, if it was possible would also be nice to have:

TIs per platform
TIPPs per subscription (offered or taken)

Think this would make quick spot checking of data easier - an immediate indicator if your knowledge of the data differs to that of the KB+

**Comment by ianibbo** [comment]
_think_ it should be OK, as the data has to be collated in the controller
anyway before display for those table layouts.. So it should be easy to add
this in.. Will investigate.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Fri, Jun 22, 2012 at 3:35 PM, ostephens <
reply@reply.github.com

**Comment by ianibo** [comment]
Done in package listing as requested.
