### ISSUE TITLE
Add Notes and Docs 'pills' + screens to packageDetails page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#510]
Add Notes and Docs 'pills' + screens to packageDetails page (e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/show/165) as on subscriptions details screen
![screen shot 2013-06-03 at 15 41 09](https://f.cloud.github.com/assets/576174/599918/adc2e818-cc5b-11e2-95ec-43a9c01f8130.png)
![screen shot 2013-06-03 at 15 41 15](https://f.cloud.github.com/assets/576174/599919/adc48a10-cc5b-11e2-874d-cbabf25d4083.png)

**Comment by iyawnis** [comment]
Is this issue still valid ? There are options to add Document and Note in packageDetails/show/ . 
Should I make these work as the above image ?

**Comment by ostephens** [comment]
Yes - still valid. The problem is that while you can add Docs and Notes via packageDetails/show/ you can't edit or delete docs and notes from packageDetails/show.

The pattern established with subscriptionDetails/ is that Docs/Notes can be added on /show/ then edited/deleted through specific tabs subscriptionDetails/documents/ and subscriptionDetails/notes/ -e.g.
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/documents/3748
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/notes/3748

Suggest that these should be replicated for packages

However, only those with editing perms on packageDetails/show should have editing perms on packageDetails/documents and packageDetails/notes
