### ISSUE TITLE
Grail error on Dashboard/Alerts page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#511]
Not sure if this is data issue or code issue. From dashboard e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/dashboard

Get error:

Error 500: Internal Server Error
URI
/kbplus/myInstitutions/dashboard
Class
java.lang.NullPointerException
Message
Cannot get property 'notes' on null object
Trace
    Line | Method
->>   43 | doCall              in com.k_int.kbplus.AlertsService$_getAllVisibleAlerts_closure1

---

|     17 | getAllVisibleAlerts in com.k_int.kbplus.AlertsService
|     62 | dashboard . . . . . in com.k_int.kbplus.MyInstitutionsController
|   1110 | runWorker           in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                 in java.lang.Thread

**Comment by ianibo** [comment]
Packages not being catered for as a doc context. Fixed. Waiting for OK from
HH to deploy to test.

On 10 June 2013 11:43, Owen Stephens notifications@github.com wrote:

> Not sure if this is data issue or code issue. From dashboard e.g.
> http://test.kbplus.ac.uk/kbplus/myInstitutions/dashboard
> 
> Get error:
> 
> Error 500: Internal Server Error
> URI
> /kbplus/myInstitutions/dashboard
> Class
> java.lang.NullPointerException
> Message
> Cannot get property 'notes' on null object
> Trace
> Line | Method
> ->> 43 | doCall in
> 
> ## com.k_int.kbplus.AlertsService$_getAllVisibleAlerts_closure1
> 
> | 17 | getAllVisibleAlerts in com.k_int.kbplus.AlertsService
> | 62 | dashboard . . . . . in com.k_int.kbplus.MyInstitutionsController
> | 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
> | 603 | run . . . . . . . . in
> java.util.concurrent.ThreadPoolExecutor$Worker
> ^ 722 | run in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/511
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Fix on test now
