### ISSUE TITLE
Users who are not KB+ Editors get error on viewing titleDetails screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#516]
e.g. try to view http://test.kbplus.ac.uk/kbplus/titleDetails/edit/6920 if you do not have KB+ editor role get grails error:

Error 500: Internal Server Error
URI
/kbplus/titleDetails/edit/6920
Class
org.springframework.expression.spel.SpelEvaluationException
Message
EL1008E:(pos 0): Field or property 'KBPLUS_EDITOR' cannot be found on object of type 'org.springframework.security.web.access.expression.WebSecurityExpressionRoot'

Trace

  Line | Method
->> 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor

---

|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

Caused by SpelEvaluationException: EL1008E:(pos 0): Field or property 'KBPLUS_EDITOR' cannot be found on object of type 'org.springframework.security.web.access.expression.WebSecurityExpressionRoot'
->> 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor

---

|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

I think the correct behaviour should be that titleDetails page should be viewable by other users, but only editable by KB+ Editors. Alternative approach (if easier?) only show links to titleDetails pages from packageDetails page if user is KB+ Editor

**Comment by ianibo** [comment]
I think the correct behaviour should be that titleDetails page should be viewable by other users, but only editable by KB+ Editors. Alternative approach (if easier?) only show links to titleDetails pages from packageDetails page if user is KB+ Editor

This is not really an option now that we have spread links to this page throughout the app. Probably going to need quite a bit of work to sort this.. Hadn't really wanted to get into a big cosmetic task with 3.0 but seems to be getting that way.

**Comment by ianibo** [comment]
Have added titleDetails.show and linked to that action from packageDetails. Not sure where else in the app a link to edit page might be found. Will need to do work in next release to shore up security around title edits.
