### ISSUE TITLE
Grail error when attempting tsv upload of Package

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#519]
When trying to upload package file in tsv format (csv works fine) get error.
File is in dropbox /Spec - Imports/SO Import/testdata/test_upload_1.tsv

Error 500: Internal Server Error
URI
/kbplus/upload/reviewSO
Class
java.lang.ArrayIndexOutOfBoundsException
Message
1
Trace
    Line | Method
->>  389 | processCsvLine             in com.k_int.kbplus.UploadController

---

|    311 | readSubscriptionOfferedCSV in     ''
|     58 | reviewSO . . . . . . . . . in     ''
|   1110 | runWorker                  in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                        in java.lang.Thread

**Comment by ianibo** [comment]
Crashing in line trying to read header data. Please attach file you are trying to upload so I can test.

**Comment by ostephens** [comment]
File is in dropbox /Spec - Imports/SO Import/testdata/test_upload_1.tsv
Also trying to attach to this email reply to see if github keeps it [edit - doesn't look like it allows me to attach to issue - I'll send separately]
