### ISSUE TITLE
Grails error on titleDetails/show

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#529]
e.g. http://test.kbplus.ac.uk/kbplus/titleDetails/show/10347
Error 500: Internal Server Error
URI
/kbplus/titleDetails/show/10347
Class
groovy.lang.MissingPropertyException
Message
No such property: SpringSecurityUtils for class: com.k_int.kbplus.TitleDetailsController
Trace
    Line | Method
->>   59 | show      in com.k_int.kbplus.TitleDetailsController

---

|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run       in java.lang.Thread

**Comment by ianibbo** [comment]
Arse. Fixed. Redeploy?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Fixed
