### ISSUE TITLE
'Link' and 'Link + Entitlements' buttons on subscriptionDetails/linkPackage/ do not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#530]
From subscriptionDetails/linkPackage page e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/756

Clicking either 'Link' or 'Link + Entitlements' button does not add package to subscription. URL generated is (e.g.)
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/756?offset=0&id=756&pkgname=&_fct%3AstartYear%3A2013=&_fct%3AstartYear%3A2012=&_fct%3AstartYear%3A2011=&_fct%3AstartYear%3A2010=&_fct%3AconsortiaName%3AJISC+Collections=&_fct%3AconsortiaName%3ASHEDL=&_fct%3AconsortiaName%3AEduserv=&_fct%3AconsortiaName%3AWHEEL=&_fct%3Acpname%3AElsevier=&_fct%3Acpname%3AAnnual+Reviews=&_fct%3Acpname%3AManey+Publishing=&_fct%3Acpname%3AWiley=&_fct%3Acpname%3AProject+Muse=&_fct%3Acpname%3AOxford+University+Press=&_fct%3Acpname%3AAmerican+Chemical+Society=&_fct%3Acpname%3ACambridge+University+Press=&_fct%3Acpname%3AIOP=&_fct%3Acpname%3ASpringer=

**Comment by ianibbo** [comment]
Seems to be working for me :/ any more info on what was done prior to
linking?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Also.. what are symptoms.. Any errors or just redirect to a particular page
with no changes made?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Also what browser?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Was on Safari 6.0.5, no errors just goes back to subscriptionDetails/linkPackage
I will re-check on Safari and another browser just to be sure I'm not doing something stupid

**Comment by ostephens** [comment]
OK - works in Ff 21.0, but not Safari.
If getting this working across browsers is going to be problematic we could remove pop-up warning for v3.0 release

**Comment by ianibbo** [comment]
Hmms... nothing special about HTML other than using the value of the button
used to submit.. MIght be a safari specific behaviour.. INvestigating.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Confirmed also works in Chrome Version 29.0.1538.0 canary

**Comment by ianibbo** [comment]
Temporarily removed confirm. Be interested to see if this makes it work
again. Only on newdev currently.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Checking on http://dev.kbplus.ac.uk with Safari
Still seeing confirm pop-up - I think this is the latest build (http://knowplusdev.edina.ac.uk/kbplus/appinfo says 1607)
Also seeing inconsistent behaviour - it worked for me in one instance, but then all subsequent attempts failed

**Comment by ianibbo** [comment]
There seems to be a fair few forums about this intermittent issue.. Could
be a timing issue with when the submit value gets set.

No idea why you are still seeing the confirm dlg tho.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
I'm slightly unsure if the build has been successfully deployed tbh

**Comment by ostephens** [comment]
Can you check change is merged into newdev - last commit I'm seeing is https://github.com/k-int/KBPlus/commit/b22a587f75b38575c6a5408605eb6e689e041be4

**Comment by ostephens** [comment]
Still not working on Safari with new setup 20130615 09:26
Works on Ff still

**Comment by ianibo** [comment]
Are you sure this didn't work? I can see this in the log:

013-06-15 09:27:15,305 [http-bio-8080-exec-10] DEBUG kbplus.SubscriptionDetailsController  - Add package Without to subscription [addType:Without, _fct:consortiaName:JISC Collections:, _fct:cpname:Elsevier:, _fct:cpname:Project Muse:, _fct:cpname:Annual Reviews:, addId:61, _fct:consortiaName:Eduserv:, pkgname:, _fct:cpname:Cambridge University Press:, id:762, _fct:startYear:2010:, _fct:cpname:Springer:, _fct:consortiaName:WHEEL:, _fct:startYear:2011:, _fct:consortiaName:SHEDL:, _fct:cpname:Oxford University Press:, _fct:cpname:IOP:, _fct:startYear:2012:, _fct:cpname:Wiley:, _fct:startYear:2013:, _fct:cpname:American Chemical Society:, offset:0, _fct:cpname:Maney Publishing:, action:linkPackage, controller:subscriptionDetails, max:10]

Which seems to indicate adding without entitlements to OS Test Subscription 1 : Link Subscription to Packages

When I go to that package I can see it's linked to British Medical Journal:NESLI2:Free and OA journals:2011-2012:Year 2 which is the package with id 61

When I go to the add entitlements tab I see the three titles in that package.

Is it that it's doing what it should but you are expecting something else, or am I loosing the plot?

**Comment by ianibo** [comment]
Link for sub I'm looking at
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/762

**Comment by ostephens** [comment]
That was the successful test with Ff I think

**Comment by ianibbo** [comment]
Ah ok - No sign of the other test then..something going horribly wrong.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Away from my mac at the moment. I can see if I can track what is happening in the browser via the console later this evening

**Comment by ostephens** [comment]
Been trying to see if I can work out what is/isn't happening via the browser console - but no luck I'm afraid. Unless you have any further thoughts suggest we take it out of the release for Monday

**Comment by ostephens** [comment]
Still getting javascript pop-up when clicking link. However, if I click 'Cancel' the action goes ahead anyway

**Comment by ostephens** [comment]
It works! Fixed :)
