### ISSUE TITLE
Remove any additional information appended to Package Name in /linkPackage search results

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#537]
Previously it was required to add the Content Provider name in brackets after the Package Name. Now the Package naming is intended to always include the Content Provider, making the inclusion of the Content provider in brackets redundant. Can this be removed?

Also there is another piece of information in brackets following the Package name and Content Provider that is usually (or always?) blank. Can these extraneous brackets/information also be removed. Illustrated in screenshot attached

Would also apply to /packageDetails/index and /renewalsSearch do these need separate issues, or is it all controlled in the same way?

![screen shot 2013-06-17 at 09 30 16](https://f.cloud.github.com/assets/576174/661385/5741bfce-d731-11e2-9345-208928ba21fd.png)

**Comment by ianibbo** [comment]
Don't think this is possible - The value is inside the database, not added
on the page. We can (And have already?) change package ingest so this isn't
appended any more.

Info in brackets after package name is row type. Removed. Different on
every page this happens on, so specific separate issues please.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Where is the value in the database? I can't see it on the Package name?
Will create other issues for the other displays

**Comment by ianibbo** [comment]
I think in these cases it's in the ES index.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK.
Not now - but is it possible to change the ES Indexing so it doesn't include this extra info in the future?

**Comment by ianibo** [comment]
Probably so, just commited a change for this, but scared of regressions.

On 17 June 2013 10:53, Owen Stephens notifications@github.com wrote:

> OK.
> Not now - but is it possible to change the ES Indexing so it doesn't
> include this extra info in the future?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/537#issuecomment-19535656
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Fixed
