### ISSUE TITLE
Packages missing from Package Search

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#539]
Some packages not appearing in package search - http://test.kbplus.ac.uk/kbplus/packageDetails/index

Search for 'Sage'
http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=sage&search=yes
Zero results

However search for sage via
http://test.kbplus.ac.uk/kbplus/packageDetails/list?q=sage

Finds 7 packages with 'Sage' in the title

**Comment by ianibbo** [comment]
Package name is not tokenised, so full package name works OK

eg

http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=Emerald%3AMaster%3A2013&search=yes&_fct%3AstartYear%3A2013=&_fct%3AstartYear%3A2012=&_fct%3AstartYear%3A2011=&_fct%3AstartYear%3A2010=&_fct%3AconsortiaName%3AJISC+Collections=&_fct%3AconsortiaName%3ASHEDL=&_fct%3AconsortiaName%3AEduserv=&_fct%3AconsortiaName%3AWHEEL=&_fct%3Acpname%3AElsevier=&_fct%3Acpname%3AAnnual+Reviews=&_fct%3Acpname%3AManey+Publishing=&_fct%3Acpname%3AWiley=&_fct%3Acpname%3AProject+Muse=&_fct%3Acpname%3AOxford+University+Press=&_fct%3Acpname%3AAmerican+Chemical+Society=&_fct%3Acpname%3ACambridge+University+Press=&_fct%3Acpname%3AIOP=&_fct%3Acpname%3ASpringer=

But partials dont. Can change index defn if wanted.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - so it looks like this is caused by using the colon as the seperator between bits of the package name (as opposed to a space)? e.g. for
Maney Publishing:NESLI2:History Collection:2012 you can successfully search 'Maney' but not 'publishing' (have to use 'publishing:nesli2:history')

Is it possible to tweak the index so that the colon is treated as a word seperator?

Would this need a code redeploy or can it be done independently?

Thanks

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Because the full reset now does a full reset and re-sets the index config,
it's a code redeploy.

On 17 June 2013 12:52, Owen Stephens notifications@github.com wrote:

> OK - so it looks like this is caused by using the colon as the seperator
> between bits of the package name (as opposed to a space)? e.g. for
> Maney Publishing:NESLI2:History Collection:2012 you can successfully
> search 'Maney' but not 'publishing' (have to use
> 'publishing:nesli2:history')
> 
> Is it possible to tweak the index so that the colon is treated as a word
> seperator?
> 
> Would this need a code redeploy or can it be done independently?
> 
> Thanks
> 
> Owen
> 
> Owen Stephens
> Owen Stephens Consulting
> Web: http://www.ostephens.com
> Email: owen@ostephens.com
> Telephone: 0121 288 6936
> 
> On 17 Jun 2013, at 12:37, ianibbo notifications@github.com wrote:
> 
> > Package name is not tokenised, so full package name works OK
> > 
> > eg
> > 
> > http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=Emerald%3AMaster%3A2013&search=yes&_fct%3AstartYear%3A2013=&_fct%3AstartYear%3A2012=&_fct%3AstartYear%3A2011=&_fct%3AstartYear%3A2010=&_fct%3AconsortiaName%3AJISC+Collections=&_fct%3AconsortiaName%3ASHEDL=&_fct%3AconsortiaName%3AEduserv=&_fct%3AconsortiaName%3AWHEEL=&_fct%3Acpname%3AElsevier=&_fct%3Acpname%3AAnnual+Reviews=&_fct%3Acpname%3AManey+Publishing=&_fct%3Acpname%3AWiley=&_fct%3Acpname%3AProject+Muse=&_fct%3Acpname%3AOxford+University+Press=&_fct%3Acpname%3AAmerican+Chemical+Society=&_fct%3Acpname%3ACambridge+University+Press=&_fct%3Acpname%3AIOP=&_fct%3Acpname%3ASpringer=
> > 
> > But partials dont. Can change index defn if wanted.
> > 
> > Ian Ibbotson
> > Director
> > Knowledge Integration Ltd
> > 35 Paradise Street, Sheffield. S3 8PZ
> > T: 0114 273 8271
> > M: 07968 794 630
> > W: http://www.k-int.com
> > 
> > On 17 June 2013 12:27, Owen Stephens notifications@github.com wrote:
> > 
> > > Some packages not appearing in package search -
> > > http://test.kbplus.ac.uk/kbplus/packageDetails/index
> > > 
> > > Search for 'Sage'
> > > 
> > > http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=sage&search=yes
> > > Zero results
> > > 
> > > However search for sage via
> > > http://test.kbplus.ac.uk/kbplus/packageDetails/list?q=sage
> > > 
> > > Finds 7 packages with 'Sage' in the title
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/k-int/KBPlus/issues/539>
> > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/539#issuecomment-19540243
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
