### ISSUE TITLE
Remove columns from Organisation browse

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#54]
Can you remove the 'address', 'ip range' and 'sector' columns from the Org List browse (e.g. http://knowplus.edina.ac.uk/kbplus/org/list?sort=name&max=10&order=desc&offset=240)

These don't need to be displayed, and the IP Range particularly can be very long and so start hogging screen estate

I'm happy for there to be no further info on these pages, but if anything is to be displayed the most useful thing I can think of is a list of roles fulfilled by that Org in the KB+

**Comment by ianibbo** [comment]
Generally speaking, I'll push back on things that need set operations when
creating a list of records.

In order to list "The roles an org has" we need to retrieve the list of
relationships and then sum over all unique roles. To do this when listing
records is quite intensive, and something we should avoid. If it's a
requirement, we need to pre-process and aggregate this info so it's not
assembled in real time. Doesn't sound like a requirement at this stage, so
I'll just wipe out all the extra fields.. Will look very bare in there tho.

On Mon, Jun 25, 2012 at 10:48 PM, ostephens <
reply@reply.github.com

**Comment by ostephens** [comment]
No problem - I guessed you'd say exactly that :)

I'm happy with the list of orgs looking sparse

Owen

On Tue, 26 Jun 2012 00:15:06 +0100, ianibbo  
reply@reply.github.com  
wrote:

> Generally speaking, I'll push back on things that need set operations  
> when
> creating a list of records.
> 
> In order to list "The roles an org has" we need to retrieve the list of
> relationships and then sum over all unique roles. To do this when listing
> records is quite intensive, and something we should avoid. If it's a
> requirement, we need to pre-process and aggregate this info so it's not
> assembled in real time. Doesn't sound like a requirement at this stage,  
> so
> I'll just wipe out all the extra fields.. Will look very bare in there  
> tho.
> 
> On Mon, Jun 25, 2012 at 10:48 PM, ostephens <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Can you remove the 'address', 'ip range' and 'sector' columns from the  
> > Org
> > List browse (e.g.
> > http://knowplus.edina.ac.uk/kbplus/org/list?sort=name&max=10&order=desc&offset=240
> > )
> > 
> > These don't need to be displayed, and the IP Range particularly can be
> > very long and so start hogging screen estate
> > 
> > I'm happy for there to be no further info on these pages, but if  
> > anything
> > is to be displayed the most useful thing I can think of is a list of  
> > roles
> > fulfilled by that Org in the KB+
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/k-int/KBPlus/issues/54
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/54#issuecomment-6562795

## 

Owen Stephens
Owen Stephens Consulting
e: owen@ostephens.com
t: 0121 288 6936
skype: owen.stephens

**Comment by ianibo** [comment]
Done
