### ISSUE TITLE
Number of values displayed in a facet e.g. on /packageDetails/index

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#541]
Is there a way of offering a 'view all' for the values in each of the facets e.g. on http://test.kbplus.ac.uk/kbplus/packageDetails/index. At the moment it is limited to 10 values with no option to see more. This is especially an issue with the 'Content Provider' facet.

Is there any way of displaying all the values, or offering the user the option to display all the values, in a facet?

**Comment by ostephens** [comment]
Now including facets with zero hits but still displaying only 10 terms in each facet on test - screenshot attached. See Content Providers - doesn't include e.g. 'Emerald'
![screen shot 2013-06-27 at 13 19 31](https://f.cloud.github.com/assets/576174/715948/e777ef18-df2a-11e2-82ba-342644748c12.png)

If I search for Emerald in package name - values in facet changes - now includes Emerald, and others with a zero count:
![screen shot 2013-06-27 at 14 11 30](https://f.cloud.github.com/assets/576174/715958/268252c0-df2b-11e2-8f45-e667a7e07bcd.png)

Ideal behaviour would be to display all non-zero terms in facets. If this is problematic I'd probably go with all terms even if zero count

**Comment by ostephens** [comment]
Still an issue I'm afraid - now no facet values appearing at all!
Looks like this might be relevant? http://stackoverflow.com/questions/16358543/fetch-all-matching-facets-in-elasticsearch-query - which points at https://github.com/elasticsearch/elasticsearch/issues/1776

Perhaps the answer is for me to say I'm happy with (e.g.) up to 50 terms displaying?

**Comment by ianibbo** [comment]
It was working but somthing f****d up the deployment.. Pushing another
change.. maybe wait for me to verify the install before re-testing. Getting
grumpy with the infrastructure

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - will wait for you to confirm deploy

**Comment by ostephens** [comment]
Looks like this is now fixed. Will be requesting the same change to two other package search screens

**Comment by ianibo** [comment]
OK.. there was something undeniably screwy about the infrastructure
yesterday!

On 28 June 2013 14:24, Owen Stephens notifications@github.com wrote:

> Looks like this is now fixed. Will be requesting the same change to two
> other package search screens
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/541#issuecomment-20187643
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
