### ISSUE TITLE
Typing diacritic/special characters via /titleDetails does not result in correct display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#546]
Tested on /titleDetails page not tested elsewhere

This only applies to some special characters, not all. For example å works fine while ā does not.

When you enter via the web UI, initially seems to work OK. Click the 'tick' on the text entry box, and it still looks OK. Refresh the page and character displays as a '?' instead. Screenshots attached all taken from http://test.kbplus.ac.uk/kbplus/titleDetails/edit/13654

Typing in details OK:
![screen shot 2013-06-27 at 08 21 46](https://f.cloud.github.com/assets/576174/714319/9ffe8122-defa-11e2-9bc8-324e1eaf7b24.png)

Clicked 'tick' to save OK:
![screen shot 2013-06-27 at 08 21 58](https://f.cloud.github.com/assets/576174/714320/a01209d6-defa-11e2-813a-3bfa3a73b4a8.png)

Refresh - one character OK, the other displays as '?'
![screen shot 2013-06-27 at 08 22 33](https://f.cloud.github.com/assets/576174/714322/a0e39ece-defa-11e2-9a9d-b6a50743b7dc.png)

**Comment by ianibo** [comment]
Heya..

I have also edited this title (http://test.kbplus.ac.uk/kbplus/titleDetails/edit/13654) by typing in unicode characters and everything seems OK.

Can you explain exactly how you typed the characters into the title edit page and if they were copied, where they were copied from. Used hexedit on the characters in the original edit and I don't think they are unicode. a bubble might be working becuase there is an apprpriate non unicode char that happens to be working.

**Comment by ianibo** [comment]
ooh.. my second a-bar seems to have gone.. weird!

**Comment by ostephens** [comment]
Tried quite a few different ways of entering the data which are all meant to be Unicode. In this case used the 'special characters' function in Mac OS X which Apple claim is Unicode http://support.apple.com/kb/HT1518?viewlocale=en_US&locale=en_US

**Comment by ianibo** [comment]
This this is prolly one for the edina chaps.. ON my local box

mysql> show variables like '%character%';  
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+

On test
mysql> show variables like '%character%';  

+--------------------------+------------------------------------------------------------------------------+
| Variable_name            | Value                                                                        |
+--------------------------+------------------------------------------------------------------------------+
| character_set_client     | latin1                                                                       | 
| character_set_connection | latin1                                                                       | 
| character_set_database   | utf8                                                                         | 
| character_set_filesystem | binary                                                                       | 
| character_set_results    | latin1                                                                       | 
| character_set_server     | latin1                                                                       | 
| character_set_system     | utf8                                                                         | 
| character_sets_dir       | /home/mysql/distributions/mysql-5.1.42-solaris10-sparc-64bit/share/charsets/ | 
+--------------------------+------------------------------------------------------------------------------+

**Comment by ianibo** [comment]
Fixed by addition of parameters to JDBC connect string? Can be closed?

**Comment by ostephens** [comment]
Yes - this is now fixed
