### ISSUE TITLE
Package URIs contain double //

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#559]
On the Package display on test (e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/show/313) the package persistent identifier contains a double '//' after 'kbplus' - see:

Package Persistent Identifier
uri://kbplus//package/313

**Comment by ianibbo** [comment]
This is because of missing config - there shold be a system identifier in
the app config file. WIll add one.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
