### ISSUE TITLE
Use readable string for ONIX-PL licence 'name'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#562]
There should be a readable string used to refer to an ONIX-PL licence. E.g. when linking to ONIX-PL licence from a KB Licence (e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/15) currently link looks something like:

Id: 1 | Version: 0 | License: AAAS Science Online 2011-2012 NESLi2.... | Document: com.k_int.kbplus.Doc : 1235

![screen shot 2013-07-27 at 08 32 28](https://f.cloud.github.com/assets/576174/866535/b8b5f762-f68e-11e2-810c-b51b6c7aedfb.png)

Need to have a readable 'name' or label for the ONIX-PL licence that can be used when displaying this to the user

**Comment by rwincewicz** [comment]
This is just the string that I built for debugging which is the output from the overridden toString() method. When the ONIX-PL license is imported it doesn't have a name of its own so I wasn't sure what to display here. Should it refer to the linked KB+ license and say something like "ONIX-PL license associated with AAAS Science Online 2011-2012 NESLi2"?

**Comment by rwincewicz** [comment]
An alternative would be to take the title entered when the license is uploaded. This is not currently required and so we would still need to create a name for the ONIX-PL license if the user didn't enter anything here.

**Comment by ostephens** [comment]
Based on Neil's comments about single ONIX-PL being linked to multiple licences in KB+ (Issue #564) I think we have to go with the ONIX-PL title.

Rather than require title to be entered could display a 'No title' message where it is not populated. This is what happens if a user creates a KB+ licence without a licence reference - in any displays in place of the licence reference the string "*\* No licence reference **" is used.

Suggest we also look at populating the 'title' from the ONIX-PL licence //LicenseDetails/Description if it exists (and no title has been set already)

**Comment by rwincewicz** [comment]
Neil has added a title field to the ONIX-PL license table which is populated with the contents of LicenseDetail/Description when the license is imported. I'm currently using this as the displayed title of the ONIX-PL license. Do we just want to use this title or, if present, show the user-provided title from the upload page?

**Comment by ostephens** [comment]
This sounds fine - but raises the question of what the point of prompting the user for a title on the upload page is? Do we need this?

**Comment by neilmayo** [comment]
This is a title to be used for the document when it is uploaded to the 
docstore. It will end up being displayed in e.g. the documents box on 
the licenseDetails page. It can be null, but a descriptive title would 
make more sense. Should it just use the same string used for the title 
of the KB+ license? Or it could be called something like "Original 
ONIX-PL License".

On 05/08/13 11:35, Owen Stephens wrote:

> This sounds fine - but raises the question of what the point of 
> prompting the user for a title on the upload page is? Do we need this?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/k-int/KBPlus/issues/562#issuecomment-22098245.

## 

Neil Mayo
Software Engineer
EDINA (JISC National Data Centre)
University of Edinburgh

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ostephens** [comment]
I think it should be defaulted to "ONIX-PL Licence document" (note spelling) and user shouldn't be prompted. They can edit it after if they want, but suspect that most of the time they won't want to.

**Comment by neilmayo** [comment]
I've done this. By the way I've been meaning to comment that there is already a pretty even distribution of license/licence throughout the app, you may need to define one as preferred and add an issue to make sure usage is consistent!
