### ISSUE TITLE
Display ONIX-PL licence properties on licence page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#563]
Is it possible to add the display of the ONIX-PL Licence properties to the linked KB+ Licence display, below the KB+ Licence properties?

i.e. on a licence display like http://test.kbplus.ac.uk/kbplus/licenseDetails/index/15 include the ONIX-PL licence properties at the bottom of the page. Obviously only where there is a linked ONIX-PL licence

Not sure how possible this is?

**Comment by rwincewicz** [comment]
It is possible to do, I was just concerned that having both license properties there would be too much information on one page. At the moment I've got the ONIX-PL properties showing in a different page (http://test.kbplus.ac.uk/kbplus/licenseDetails/onixpl/15) similar to where you can view documents and notes.

**Comment by ostephens** [comment]
OK - let's go with this approach (as you've already implemented) for now, and we can tweak if we get user feedback asking for all details on a single page
