### ISSUE TITLE
Copying a template licence should copy link to a linked ONIX-PL licence

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#564]
When a user copies a template licence to an actual licence (e.g. via http://test.kbplus.ac.uk/kbplus/licenseDetails/index/534?copy-licence=Copy+Selected&baselicense=15&shortcode=JISC_Collections)

Needs to copy the link to the ONIX-PL licence so that there is a link from the new actual licence to the ONIX-PL licence

**Comment by neilmayo** [comment]
This has been implemented. Had to change the relationship between onixpl_license (OPL) and license to "one to one or more". This means a OPL must maintain its own identifying properties, therefore I added a title field. This is what should be used in issue #562. Richard has separately updated the display pages to account for the new relationship.

OPL imports and edits require admin role, but can be viewed by anyone.
