### ISSUE TITLE
In Serials Solutions transformation/export all values should be enclosed in All values enclosed in inverted commas (Unicode U+0022)

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#567]
In Serials Solutions transformation/export all values should be enclosed in All values enclosed in inverted commas (Unicode U+0022)

E.g.:

"Chemical & Engineering News"
not
Chemical & Engineering News

Currently inverted commas are not used where the field is populated

**Comment by desreid** [comment]
Fixed I think. Owen can you verify?

**Comment by ostephens** [comment]
Fixed
