### ISSUE TITLE
In Serials Solutions export redundant hyphens/dashes appearing when no date specified

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#568]
In screenshot to the right of "01-01-1942" you can see "--" which seems to result from the absence of a date value being available to populate "Custom To Date". Where there is no value to put into a date field, it should be empty of any value.

Inverted commas should still be used to indicate the field, even if there is no value to populate it - i.e. "" would be used in this instance

![screen shot 2013-08-15 at 15 43 50](https://f.cloud.github.com/assets/576174/969221/25276820-05b9-11e3-8963-69820fea4da4.png)

**Comment by desreid** [comment]
Owen can you verify this? I believe it to be fixed, but can no longer find that exact journal.

**Comment by ostephens** [comment]
Fixed
