### ISSUE TITLE
When displaying start/end dates in data explorer, never requires time (HH:MM etc)

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#57]
NOT URGENT

When displaying start/end dates in data explorer (or the application of course) we only ever need to display to the accuracy of one day, never specific time

**Comment by ianibo** [comment]
Hard to action issues like this.. If we can list specific screens rather than general concerns that will help me lots. Fixed the subscriptions data explorer date display. Closing this issue. Please add issues per screen if you find others.

**Comment by ostephens** [comment]
Since a Data Explorer issue, probably won't be reporting any more.

On 7/16/12, Ian Ibbotson
reply@reply.github.com
wrote:

> Hard to action issues like this.. If we can list specific screens rather
> than general concerns that will help me lots. Fixed the subscriptions data
> explorer date display. Closing this issue. Please add issues per screen if
> you find others.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/57#issuecomment-7003026

## 

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
