### ISSUE TITLE
Login denied error message

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#570]
http://test.kbplus.ac.uk/kbplus/login/denied

Very short error message styled as Grails screen.
Should be styled as KB+ screen, and would be good if there was a direction to raise a support issue via the Feedback tab

**Comment by ianibo** [comment]
Don't really understand this one. You should never see this screen using shib login since you should get the IDP error login rather than the app login. Can you describe how you arrived at this page?

**Comment by ostephens** [comment]
Sorry - can't remember - we were doing something on system and it came up and you said we should improve look of screen. Can't remember how we got the screen though :(

**Comment by ostephens** [comment]
Have now got an example of this page.
If a non KB+ Editor tries to access http://test.kbplus.ac.uk/kbplus/announcement/index?at=Package+Link%3A+http%3A%2F%2Ftest.kbplus.ac.uk%2Fkbplus%2FpackageDetails%2Fshow%2F113&as=RE%3A+Package+American+Association+for+the+Advancement+of+Science%3AMaster%3A2013

Then they are directed to http://test.kbplus.ac.uk/kbplus/login/denied
Capturing HTTP headers in Firefox I see:

http://test.kbplus.ac.uk/kbplus/announcement/index?at=Package+Link%3A+http%3A%2F%2Ftest.kbplus.ac.uk%2Fkbplus%2FpackageDetails%2Fshow%2F113&as=RE%3A+Package+American+Association+for+the+Advancement+of+Science%3AMaster%3A2013

GET /kbplus/announcement/index?at=Package+Link%3A+http%3A%2F%2Ftest.kbplus.ac.uk%2Fkbplus%2FpackageDetails%2Fshow%2F113&as=RE%3A+Package+American+Association+for+the+Advancement+of+Science%3AMaster%3A2013 HTTP/1.1
Host: test.kbplus.ac.uk
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:24.0) Gecko/20100101 Firefox/24.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://test.kbplus.ac.uk/kbplus/packageDetails/show/113
Cookie: JSESSIONID=0682193298500C02039B85FB41C22A0F; __utma=213964621.513013463.1353057178.1379517150.1379580235.17; __utmz=213964621.1371213500.14.3.utmcsr=knowplusdev.edina.ac.uk|utmccn=(referral)|utmcmd=referral|utmcct=/kbplus/packageDetails/index; __utma=5407670.1532532065.1353057476.1372758647.1379582329.51; __utmz=5407670.1360785158.18.4.utmcsr=kbplus.ac.uk|utmccn=(referral)|utmcmd=referral|utmcct=/kbplus/profile/index; __utmb=213964621.16.10.1379580235; __utmb=5407670.7.10.1379582329; __utmc=5407670
Connection: keep-alive

HTTP/1.1 302 Moved Temporarily
Date: Thu, 19 Sep 2013 09:32:36 GMT
Server: Apache-Coyote/1.1
Location: http://test.kbplus.ac.uk/kbplus/login/denied
Content-Length: 0
Content-Type: text/plain
Keep-Alive: timeout=5, max=100

## Connection: Keep-Alive

http://test.kbplus.ac.uk/kbplus/login/denied

GET /kbplus/login/denied HTTP/1.1
Host: test.kbplus.ac.uk
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:24.0) Gecko/20100101 Firefox/24.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://test.kbplus.ac.uk/kbplus/packageDetails/show/113
Cookie: JSESSIONID=0682193298500C02039B85FB41C22A0F; __utma=213964621.513013463.1353057178.1379517150.1379580235.17; __utmz=213964621.1371213500.14.3.utmcsr=knowplusdev.edina.ac.uk|utmccn=(referral)|utmcmd=referral|utmcct=/kbplus/packageDetails/index; __utma=5407670.1532532065.1353057476.1372758647.1379582329.51; __utmz=5407670.1360785158.18.4.utmcsr=kbplus.ac.uk|utmccn=(referral)|utmcmd=referral|utmcct=/kbplus/profile/index; __utmb=213964621.16.10.1379580235; __utmb=5407670.7.10.1379582329; __utmc=5407670
Connection: keep-alive

HTTP/1.1 200 OK
Date: Thu, 19 Sep 2013 09:32:36 GMT
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=UTF-8
Content-Language: en-US
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive

## Transfer-Encoding: chunked
