### ISSUE TITLE
Subscription Consortia Org links on Packages

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#571]
Some packages have Orgs linked as 'Subscription Consortia' following the removal of the SO concept and the migration of these links to the Package level. However, we are now using 'Package Consortia' links on newly created packages.

Can we convert any existing Subscription Consortia links on Packages to 'Package Consortia' links instead.

In some cases there are multiple Subscription Consortia links for the same Org on a single package. Once these have been converted to Package Consortia links then there will be multiple Package Consortia links for the same Org on a package (this conversion may increase the number if there are examples where currently a Package has one Subscription Consortia link and one Package Consortia link).

We should remove any duplication Package/Subscription consortia links (it doesn't matter which one is preserved in any particular case). Because of the potential of the conversion creating more duplication I'd suggest worth doing this after the conversion, but whatever works :)

An example is http://www.kbplus.ac.uk/kbplus/packageDetails/show/78 which has two Subscription Consortia links to JISC Collections Org

**Comment by ianibo** [comment]
Very nervous about this.. Can attempt it, but can't be responsible for lost data.

**Comment by ianibo** [comment]
SQL update in upgrade-post.sql script now.

**Comment by ostephens** [comment]
Have checked the data on test and it looks good. Happy to sign off on this SQL update and take responsibility if there are issues
