### ISSUE TITLE
Renewals Search should use Package Consortia

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#574]
e.g. http://www.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsSearch

Should use Package Consortia org links to generate the Consortia Name facet and for display in the Results listing 'Consortium' column.

See also #572 and #573

**Comment by ianibo** [comment]
Don't understand..

**Comment by ostephens** [comment]
E.g. see search result:
http://www.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsSearch?search=yes&offset=0&pkgname=American+Chemical+Society+SHEDL+Web+Editions+2014&max=10

This has package http://www.kbplus.ac.uk/kbplus/packageDetails/show/311
This package has a Package Consortia of JISC Collections

However in search results JISC Collections does not appear as the Consortia Name in the facet, or in the Consortium column in results list

**Comment by ianibbo** [comment]
Have started to look at some of this.. it's very scary and a side effect of
the SO removal. Email inc about the SQL needed.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Presumably we could make this change - to use Package Consortia vs Subscription Consortia here, and deal with the actual data manipulation separately (manually) if we are too nervous about the SQL? i.e. the change to the indexing is not the issue, but the SQL to do the change of relationship and de-duping?

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibbo** [comment]
If we're going to change it, we should probably change it everywhere - Have
made packages return either Sub Cons or Pkg Cons links when asked for
consortia, so this should improve the situation for text indexing.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Should be fixed following update.sql and a full re-index.
