### ISSUE TITLE
Error trying to view a licence without a name

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#575]
Get a Grails error when trying to view http://test.kbplus.ac.uk/kbplus/licenseDetails/index/604 (or http://dev.kbplus.ac.uk/kbplus/licenseDetails/index/604)

Gives grails error:

Error 500: Internal Server Error
URI
/kbplus/licenseDetails/index/604
Class
java.lang.NullPointerException
Message
Cannot invoke method replace() on null object
Trace
    Line | Method
->>   44 | index     in com.k_int.kbplus.LicenseDetailsController

---

|    195 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run       in java.lang.Thread

**Comment by ianibo** [comment]
Heya...

I think I logged a fix for a related issue not so long ago.. Suspect it's
tied up with the license changes. Not sure how to figure out who should
investigate.

On 5 September 2013 11:12, Owen Stephens notifications@github.com wrote:

> Get a Grails error when trying to view
> http://test.kbplus.ac.uk/kbplus/licenseDetails/index/604 (or
> http://dev.kbplus.ac.uk/kbplus/licenseDetails/index/604)
> 
> Gives grails error:
> 
> Error 500: Internal Server Error
> URI
> /kbplus/licenseDetails/index/604
> Class
> java.lang.NullPointerException
> Message
> Cannot invoke method replace() on null object
> Trace
> Line | Method
> 
> ## ->> 44 | index in com.k_int.kbplus.LicenseDetailsController
> 
> | 195 | doFilter in
> grails.plugin.cache.web.filter.PageFragmentCachingFilter
> | 63 | doFilter in grails.plugin.cache.web.filter.AbstractFilter
> | 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
> | 603 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
> ^ 722 | run in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/575
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Let me dig some more and check under what circumstances it happens - assuming it is related to some of the recent licence changes I'll assign it appropriately - so don't worry about this further unless I assign it to you :)

**Comment by ianibo** [comment]
Ah. I've checked in a patch. Basically blows up when reference isn't set.

On 5 September 2013 11:51, Owen Stephens notifications@github.com wrote:

> Let me dig some more and check under what circumstances it happens -
> assuming it is related to some of the recent licence changes I'll assign it
> appropriately - so don't worry about this further unless I assign it to you
> :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/575#issuecomment-23859468
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by desreid** [comment]
Thanks Ian, I think you picked up one of ours there

**Comment by ostephens** [comment]
Fixed
