### ISSUE TITLE
On Test/Dev, if no default dashboard set, get Grails error

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#578]
You might already have this but 

Error 500: Internal Server Error
URI
/kbplus/home/index
Class
groovy.lang.MissingMethodException
Message
No signature of method: org.hibernate.collection.PersistentSortedSet.get() is applicable for argument types: (java.lang.Integer) values: [0] Possible solutions: getAt(int), grep(), grep(), getAt(java.lang.String), grep(java.lang.Object), grep(java.lang.Object)
Trace
    Line | Method
->>   28 | index     in com.k_int.kbplus.HomeController

---

|    195 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run       in java.lang.Thread

**Comment by ianibo** [comment]
Nope, don't have this (Or see it :() anything special about the account you are logging in as? Do you know how many affiliations it has?

**Comment by ianibo** [comment]
Ah.. Guessing 1 affiliation? Code to auto-allocate that org as default might be in error. Possible fix checked in.

**Comment by ostephens** [comment]
Looks fixed
