### ISSUE TITLE
URL to package in auto-generated announcement incorrect

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#579]
On dashboard (e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/dashboard) in announcements created automatically after package changes the announcements includes a link to the Package - but it is incorrect.

E.g seeing URL http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/[:]/packageDetails/show/215

instead of

http://test.kbplus.ac.uk/kbplus/packageDetails/show/215

**Comment by ianibbo** [comment]
Config error.. will sort

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Following latest update now link is:
http://test.kbplus.ac.uk/kbplus//packageDetails/show/215
- the additional / in the middle stops the URL working
