### ISSUE TITLE
XML for Package export not correctly structured on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#583]
The XML export for a package (e.g. from the Package Details screen http://test.kbplus.ac.uk/kbplus/packageDetails/show/215?max=25&format=xml) is incorrectly structured
The &lt;TitleList&gt; element should be within the &lt;Package&gt; element, it is currently outside this (i.e. nodes are siblings rather than Package parent of TitleList)

_think_ problem maybe with lines 387-388 in ExportService.groovy:
def titlesElem = addXMLElementInto(doc, into_elem, "TitleList", null)
addTitleListXML(doc, titlesElem, tipps, "TIPP")

should this be:
def titlesElem = addXMLElementInto(doc, subElem, "TitleList", null)
addTitleListXML(doc, titlesElem, entitlements)

**Comment by WilliamPetit** [comment]
There is no entitlements variables in the addPackageIntoXML(Document doc, Element into_elem, pck, tipps) method so your second line of code won't work, but I think you located the mistake in my code.

If it's just about the TitleList element not being inside the Package element then, I believe, only the first line of code needs to be changed:
def titlesElem = addXMLElementInto(doc, subElem, "TitleList", null)
addTitleListXML(doc, titlesElem, tipps, "TIPP")

I'll add this change in my next push on the newdev branch.

**Comment by ostephens** [comment]
Yes agreed - ignore my second line (I copied and pasted from the Subs code as the structure there was correct - that'll teach me :)

**Comment by ostephens** [comment]
William - can these changes be merged into newdev so we can get them deployed?
Thanks

**Comment by WilliamPetit** [comment]
Yes, it should be on newdev now.

**Comment by ostephens** [comment]
Confirm fixed
