### ISSUE TITLE
Include TI Title and/or link on TIPP change announcements

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#586]
When an Announcement is created due to a TIPP change currently text is similar to:

TIPP change - The startDate field was changed from "1997-03-01 00:00:00.0" to "Sun Mar 02 00:00:00 GMT 1997".

Is it easily possible to add the relevant TI Title and/or a link to the affected TIPP to the announcement?

One or the other fine - just to give some context otherwise not possible to really understand what has changed. I would choose adding the Title over the TIPP link, but the TIPP link better than nothing

**Comment by ianibo** [comment]
Should be there now
