### ISSUE TITLE
Problem upload package on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#588]
Trying to upload what should be a valid package (on Dropbox /Spec - Import/SO Import/testdata/test_upload_1.csv - requires 'Test Org 1' to exist)

Get Grails error:

Error 500: Internal Server Error
URI
/kbplus/upload/reviewSO
Class
groovy.lang.MissingPropertyException
Message
No such property: ti for class: com.k_int.kbplus.Package Possible solutions: id, all, URL, tipps
Trace
    Line | Method
->>  267 | doCall          in com.k_int.kbplus.Package$_closure2

---

|    114 | processUploadSO in com.k_int.kbplus.UploadController
|     63 | reviewSO . . .  in     ''
|    195 | doFilter        in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . .  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker       in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run             in java.lang.Thread

**Comment by ianibo** [comment]
Currently unable to replicate on dev system. Also, copied test data into git project, manual_test_data/so_v3 if we could maintain there would help.

**Comment by ianibo** [comment]
Also unable to replicate on test - Get package already uploaded message? Any ideas?

**Comment by ianibo** [comment]
Actually, it did an incremental import for me.. Package header found, tipps created. _very confused_

**Comment by ianibo** [comment]
Wonder if a previous redeploy has fixed this for me. Something funny going on with test server. please retest.

**Comment by ostephens** [comment]
Will retest later see if I can recreate

**Comment by ostephens** [comment]
Have recreated on test
Tried to upload https://github.com/k-int/KBPlus/blob/newdev/manual_test_data/so_v3/test_upload_1.csv

Got Grails error:

Error 500: Internal Server Error
URI
/kbplus/upload/reviewSO
Class
groovy.lang.MissingPropertyException
Message
No such property: ti for class: com.k_int.kbplus.Package Possible solutions: id, all, URL, tipps
Trace
    Line | Method
->>  267 | doCall          in com.k_int.kbplus.Package$_closure2

---

|    114 | processUploadSO in com.k_int.kbplus.UploadController
|     63 | reviewSO . . .  in     ''
|    195 | doFilter        in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . .  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker       in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run             in java.lang.Thread

Package was created successfully:
http://test.kbplus.ac.uk/kbplus/package/show/398

But not TIPPs created.
I've left this package as-is but other tests show that I can replicate this error on package creation, but then subsequent uploading of same file leads to incremental package update - and TIPPs correctly created. So only upload of new package that is not working here by the looks of it
