### ISSUE TITLE
'Home' in breadcrumbs goes to wrong location

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#589]
'Home' breadcrumb (lots of pages - e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/dashboard)

goes to /myInstitutions/dashboard

Needs to go to /home/index instead I think

**Comment by ianibo** [comment]
Started up update links in as many places as could be found.. Don't know how we're going to decide this one is closed.

**Comment by ostephens** [comment]
Close it now, I'll ask HH to check as she goes through and we'll report issues individually

**Comment by ostephens** [comment]
Adding issues for each page where link appears

**Comment by ostephens** [comment]
Working through these - there are a lot of them! Would it make more sense (is it possible?) to always redirect from /myInstitutions/dashboard to /home/index ? I can create github issues for each page where there is a link to /myInstitutions/dashboard - based on https://github.com/k-int/KBPlus/search?p=1&q=action%3D%22dashboard%22&type=Code that's about 38 pages - but time consuming for both of us. If redirecting is a shortcut to the same end then it would be a time saver

What do you think?

**Comment by ianibo** [comment]
I thought about this initially, but really I think we need to do it properly.
