### ISSUE TITLE
Forms and Actions menu only displays from 'Home'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#59]
Maybe intended behaviour?

As soon as I go to another screen in the data explorer - eg http://knowplus.edina.ac.uk/kbplus/package/list menu Forms and Actions menu disappears

**Comment by ianibo** [comment]
Yep.. data explorer not wired up in the same way.. can be, but assumed we were removing data explorer before go-live so seemed like redundant work.. Want me to wire it all in?

**Comment by ostephens** [comment]
No - that's fine
