### ISSUE TITLE
Grails error on uploading 'Subscription Taken Worksheet'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#591]
Trying to upload spreadsheet get Grails error:

Error 500: Internal Server Error
URI
/kbplus/subscriptionImport/importSubscriptionWorksheet/processSubscriptionImport
Class
groovy.lang.MissingMethodException
Message
No signature of method: org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestWrapper.getFile() is applicable for argument types: (java.lang.String) values: [renewalsWorksheet] Possible solutions: getXML(), getPart(java.lang.String), getAt(java.lang.String), getAt(java.lang.String), getLocale(), getJSON()
Trace
    Line | Method
->>  605 | importSubscriptionWorksheet in com.k_int.kbplus.SubscriptionImportController

---

|    195 | doFilter                    in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker                   in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                         in java.lang.Thread

**Comment by ianibo** [comment]
Unable to replicate on local dev system.

**Comment by ianibo** [comment]
Can replicate on test.. investigating..

**Comment by ianibo** [comment]
Redeploy seems to have fixed test. _worrying_

**Comment by ostephens** [comment]
Replicated on test today
However - only occurred when using Import option from the Manage -> Institution menu - in this case
http://test.kbplus.ac.uk/kbplus/subscriptionImport/importSubscriptionWorksheet/35
The Upload works fine and shows preview as expected, but the "Accept and Process" gives the error 

In the HTML for the form at the Institutional specific URL (http://test.kbplus.ac.uk/kbplus/subscriptionImport/importSubscriptionWorksheet/35) I see:
<form action="processSubscriptionImport" method="post" params="[renewalsWorksheet:org.springframework.web.multipart.commons.CommonsMultipartFile@54abc2, id:35]">

while in the non-institutional specific (http://test.kbplus.ac.uk/kbplus/subscriptionImport/importSubscriptionWorksheet)  I see:
<form action="processSubscriptionImport" method="post" params="[renewalsWorksheet:org.springframework.web.multipart.commons.CommonsMultipartFile@1b95eb0]">

Grails error as before is:

Error 500: Internal Server Error
URI
/kbplus/subscriptionImport/importSubscriptionWorksheet/processSubscriptionImport
Class
groovy.lang.MissingMethodException
Message
No signature of method: org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestWrapper.getFile() is applicable for argument types: (java.lang.String) values: [renewalsWorksheet] Possible solutions: getXML(), getPart(java.lang.String), getAt(java.lang.String), getAt(java.lang.String), getLocale(), getJSON()
Trace
    Line | Method
->>  605 | importSubscriptionWorksheet in com.k_int.kbplus.SubscriptionImportController

---

|    195 | doFilter                    in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker                   in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                         in java.lang.Thread

**Comment by ianibo** [comment]
Yep, this is fixed in dev.. it's a number format parse exception for manually entered org IDs
