### ISSUE TITLE
Serials Solutions transformation truncates export

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#599]
Tried a Serials Solutions transformation from
http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=1216&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=&validOn=2013%2F09%2F17

Get a truncated result - stops in the middle of a line

**Comment by WilliamPetit** [comment]
This issue and #600 are probably related to the same problem.

We used to have the same issue when I was working on the transformation, Des has found a way to fix it: something related to "conflicting versions of the XSLT library".
I don't remember how he did it, but he might have done it only on the dev.kbplus server.

I've just checked and the transformation seems to work fine from this url (development server): 
http://knowplusdev.edina.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=1216&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=&validOn=2013%2F09%2F17

**Comment by ostephens** [comment]
Thanks William - this sounds like it is an issue with the version of the library installed on each server? I guess it is a matter of making sure this is consistent across servers - on this basis I'll re-allocate to Des

**Comment by WilliamPetit** [comment]
Hi Owen - Sorry, I don't really have any detail about how to fix it. I've just picked up a old comment Des made about this issue in case it helps him to remember what he did. The same thing will probably have to be done on the live server.

**Comment by desreid** [comment]
Yes, the wrong xslt libs were being picked up, as William guessed. The solution is to put the following line in the config for the apache running the transform:
SetEnv LD_LIBRARY_PATH /home/cpan/syslib/lib
where /home/cpan/syslib/lib is where the correct libxslt libs are found
I've done this, and tested both transforms. They look ok now, Owen can you confirm?

**Comment by ostephens** [comment]
Fixed on test
