### ISSUE TITLE
SFX Transformation truncates export

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#600]
Trying to do an SFX transformation from http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=1216&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=&validOn=2013%2F09%2F17

Transformation returns file truncated in the middle of a line

**Comment by desreid** [comment]
Same issue as #599, I believe I've fixed this now. Can you confirm Owen?

**Comment by ostephens** [comment]
Fixed
