### ISSUE TITLE
Use date picker in filter on /packageDetails/show

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#601]
Is it possible to use a date picker for the filter values 'Starts Before' and 'Ends After' and adopt the standard YYYY-MM-DD format for these boxes (as opposed to current YYYY/MM/DD)

**Comment by desreid** [comment]
Same issue as #599, I believe I've fixed this now. Can you confirm Owen?

**Comment by desreid** [comment]
Sorry, ignore previous comment, wrong ticket.
