### ISSUE TITLE
Use date picker in filter on /myInstitutions/[...]/currentTitles

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#609]
E.g. on http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentTitles

Is it possible to use a date picker for the filter value 'Subscriptions Valid on' and adopt the standard YYYY-MM-DD format for these boxes (as opposed to current YYYY/MM/DD)

By date picker I mean such as is used to edit 'Start Date' and 'End Date' on http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1666

**Comment by WilliamPetit** [comment]
Yes I saw how Ian made the change for issue #601, I'll try to do the same.
For the YYYY-MM-DD format, I'm using session.sessionPreferences.globalDateFormat or if it's not defined: YYYY-MM-DD. Should I change that and hard code it to YYYY-MM-DD?

**Comment by ostephens** [comment]
@ianibbo Can you comment on William's Q here? Thanks

**Comment by ianibo** [comment]
Don't really understand what the question is

**Comment by WilliamPetit** [comment]
@ianibbo - Should I use the session.sessionPreferences.globalDateFormat value when it exists, for example:
def sdf = new java.text.SimpleDateFormat(session.sessionPreferences?.globalDateFormat?:"yyyy-MM-dd")

or should I hard code the date format to 'YYYY-MM-DD':
def sdf = new java.text.SimpleDateFormat("yyyy-MM-dd")

I don't really know what session.sessionPreferences.globalDateFormat represents but I think you used to use it for date formats?

**Comment by ianibo** [comment]
Ah I see.. Yes, use global format for display, but the dateformat is also used to parse the date sent by the in place date picker, that isn't variable, so needs to use the standard format. I've made all the changes needed to close the issue.
