### ISSUE TITLE
Date format in "Defaults from package" list in /issueEntitlement/show

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#611]
In the "Defaults from package : " table of details e.g. on http://test.kbplus.ac.uk/kbplus/issueEntitlement/show/393639

the 'From Date' and 'To Date' columns display dates as yyyy/MM/dd

Use yyyy-MM-dd instead

![screen shot 2013-09-19 at 11 23 35](https://f.cloud.github.com/assets/576174/1172055/9fa001e4-2115-11e3-8291-6d3bcf64e6f4.png)

**Comment by ianibo** [comment]
Fixed by previous update to global date format
