### ISSUE TITLE
Date format in "Occurences of this title against Packages / Platforms" on /tipp/show

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#612]
e.g. on http://test.kbplus.ac.uk/kbplus/tipp/show/4970
In table headed  "Occurences of this title against Packages / Platforms" the columns "From Date" and "To Date" display dates in format dd MMM yyyy

Should use format yyyy-MM-dd

**Comment by ianibo** [comment]
Fixed by prior change to global date format
