### ISSUE TITLE
Grails error on comparing ONIX-PL licences

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#618]
Tried to compare two licences got Grails error:

Error 500: Internal Server Error
URI
/kbplus/onixplLicenseCompare/matrix
Class
java.lang.IndexOutOfBoundsException
Message
Index: 0, Size: 0

TRACE

   Line | Method
->>  604 | doFilter  in /onixplLicenseCompare/matrix.gsp

---

Caused by IndexOutOfBoundsException: Index: 0, Size: 0
->>  604 | rangeCheck in java.util.ArrayList

---

|    382 | get       in     ''
|     77 | doCall .  in gsp_demo_onixplLicenseComparematrix_gsp$_run_closure2_closure6
|    325 | countRunAndMakeAscending in java.util.TimSort
|    189 | sort . .  in     ''
|    173 | sort      in     ''
|    659 | sort . .  in java.util.Arrays
|    217 | sort      in java.util.Collections
|     77 | doCall .  in gsp_demo_onixplLicenseComparematrix_gsp$_run_closure2
|    164 | run       in gsp_demo_onixplLicenseComparematrix_gsp
|    195 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

**Comment by rwincewicz** [comment]
I've fixed this issue which was caused by some usage terms not having licence text associated with them and I've pushed the changes to newdev. 
I also came across an issue with one of the ONIX-PL licences I was using where there are terms that completely contradict each other. An example is "JISC Collections/NESLi2 Sublic/AAAS/Science Online Link NESLi2 2011-12/01012011-31122012" where the file I have contains two entries for paragraph 3.1.3.9. The usage type and licence text are identical but one of the entries permits "Include" and the other entry prohibits it. This makes it difficult to compare the usage terms in the ONIX-PL licences and so I need to know whether this is intentional and how common it's likely to be.

**Comment by ostephens** [comment]
The term in the licence refers to two different types of use:

 <Usage>
            <UsageType>onixPL:Include</UsageType>
            <UsageStatus>onixPL:Prohibited</UsageStatus>
            <Annotation>
                <AnnotationType>onixPL:VariationsFromModel</AnnotationType>
                <AnnotationText>This agreement permits only links to licensed material to be included in material for presentation. Further permissions may be granted if the Authorized User registers independently with the Publisher.</AnnotationText>
            </Annotation>
            <LicenseTextLink href="Ex03010309"/>
            <User>onixPL:AuthorizedUser</User>
            <UsedResource>onixPL:LicensedContentPart</UsedResource>
            <UsageRelatedResource>
                <UsageResourceRelator>onixPL:TargetResource</UsageResourceRelator>
                <RelatedResource>onixPL:MaterialForPresentation</RelatedResource>
            </UsageRelatedResource>
        </Usage>

<Usage>
            <UsageType>onixPL:Include</UsageType>
            <UsageStatus>onixPL:Permitted</UsageStatus>
            <Annotation>
                <AnnotationType>onixPL:VariationsFromModel</AnnotationType>
                <AnnotationText>Note that only links to licensed material are permitted to be included in material for presentation.</AnnotationText>
            </Annotation>
            <LicenseTextLink href="Ex03010309"/>
            <User>onixPL:AuthorizedUser</User>
            <UsedResource>onixPL:LinkToLicensedContent</UsedResource>
            <UsageRelatedResource>
                <UsageResourceRelator>onixPL:TargetResource</UsageResourceRelator>
                <RelatedResource>onixPL:MaterialForPresentation</RelatedResource>
            </UsageRelatedResource>
        </Usage>

The key difference in this case is the 'UsedResource' - it is permitted for UsedResource type 'LinkToLicensedContent' but prohibited for UsedResource type 'LicensedContentPart'
I don't know how common this will be but almost certainly this is not a one-off occurrence

I guess in terms of comparing these you need the additional information - in this case I'd guess UsedResource, UsageRelatedResource/RelatedResource and possible User to know you were comparing like with like? I'd probably have to go back to the ONIX-PL documentation and the ElCat screenshots/spec to say more

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by rwincewicz** [comment]
I've added the User and UsedResource elements to allow these licences to be compared properly. The ONIX-PL matching and comparison methods now use these values in addition to the previous ones that were being used.

**Comment by ostephens** [comment]
Thanks Richard

I can see the values are being imported but I'm not clear how this has affected the comparison (the comparison looks fine by the way, so not asking for changes as such just trying to understand how it operates). What I see at the moment is like

![screen shot 2013-09-24 at 10 46 14](https://f.cloud.github.com/assets/576174/1198780/825159f2-24fe-11e3-8aa4-84a955d2fd72.png)

How do the new values (User and UsedResource elements) affect the comparison?

Thanks

**Comment by rwincewicz** [comment]
Before I was using the usage status and licence text to compare the usage terms for the ONIX-PL licence as these were the only values that were being parsed. If they all matched then it was assumed that the licences were the same. With the example above just using these values wasn't enough and so I've added the user and used resource elements to the comparison. Now the methods use all of these values to compare each of the usage terms in the licence. Now the methods can distinguish the terms above.

**Comment by ostephens** [comment]
Now working
