### ISSUE TITLE
On import of ONIX-PL licence some notes display with para numbers, some with code

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#619]
See screenshot
![screen shot 2013-09-19 at 11 53 34](https://f.cloud.github.com/assets/576174/1172173/d2a4344e-2119-11e3-8cba-549aa683a188.png)

In first note rather than para numbers or similar each bit of text is preceded with a code:
Ex03010301 - The Sub-Licensee may allow Authorised Users to: access the Licensed Material by Secure Authentication in order to search, retrieve, display and view the Licensed Material;
d1e108d1e168920110113T225813.565Z - "Secure Authentication" means access to the Licensed Material by Internet Protocol (“IP”) or by another means of authentication agreed between the JISC Collections and the Publisher.

In second note uses para numbers correctly:
1.1.9 - "Secure Authentication" means access to the Licensed Material by Athens Authentication or by UK Access Management Federation Compliant technologies, Internet Protocol (“IP”) ranges or by another means of authentication agreed between Thomas Telford Ltd and JISC Collections from time to time. 
3.1.2 - Throughout the term of this Sub-Licence the Sub-Licensee may for Educational Purposes only: allow Authorised Users to access the Licensed Material by Secure Authentication in order to search, retrieve, display and view, and otherwise use portions thereof;

I guess this is something related to how the XML is parsed rather than the first one lacking the relevant numbers?

**Comment by rwincewicz** [comment]
The code that displays the licence text checks to see if there is a para number associated with the text. If there is then it displays it alongside the text. If it's missing then it uses the element ID. If there are para numbers missing from the licence text then it means that those numbers aren't being parsed properly on import.

**Comment by ostephens** [comment]
Hi Richard

I think the parsing code is no longer picking up the para numbers correctly. The ONIX-PL xml parsing has changed since the last release (and works correctly on the release branch as far as I'm aware)

On release branch https://github.com/k-int/KBPlus/blob/release/app/grails-app/controllers/com/k_int/kbplus/LicenseImportController.groovy
Lines 106-112

```
 // There can be multiple LicenseTexts linked to a single UsageTerm
        result.usageTerms[n].licenseTexts = []
        licTexts.eachWithIndex { lt, m ->
          result.usageTerms[n].licenseTexts[m] = [:]
          result.usageTerms[n].licenseTexts[m].text = [lt.TextPreceding.text(), lt.Text.text()].join(" ")
          result.usageTerms[n].licenseTexts[m].elId = lt.SortNumber.text()
        }
```

On test newdev branch etc https://github.com/k-int/KBPlus/blob/newdev/app/grails-app/controllers/com/k_int/kbplus/LicenseImportController.groovy
Lines 240-248

```
     // There can be multiple LicenseTexts linked to a single UsageTerm
      usageTerms[n].licenseTexts = []
      licTexts.eachWithIndex { lt, m ->
        usageTerms[n].licenseTexts[m] = [:]
        usageTerms[n].licenseTexts[m].text = [lt.TextPreceding.text(), lt.Text.text()].join(" ")
        usageTerms[n].licenseTexts[m].elId = lt.@id.text() //lt.SortNumber.text()
        usageTerms[n].licenseTexts[m].displayNum = lt.DisplayNumber?.text()
      }
```

The latter deprecates the use of SortNumber for the @id attribute and adds the displayNum from the DisplayNumber element - which mades sense.
I'm not familiar with the syntax here, but is the DisplayNumber being picked up correctly, since it looks like it is this that is generating the display

**Comment by rwincewicz** [comment]
I've tracked this issue to TextElements in the ONIX-PL licence that don't have display numbers, only sort numbers. The import code will only extract the display number and so if this is missing then the display code will show the element id instead. The example I'm using is "JISC Collections NESLi2 Licence 2013" with text element "Ex010102". Should the import code use the sort number in the absence of a display number?

**Comment by ostephens** [comment]
Yes - please use the Sort Number if no Display Number, and only fall back on element id if both missing

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by rwincewicz** [comment]
OK, the import code now grabs the sort number if the display number is absent. If neither of these values is present then the element id will be shown.

**Comment by ostephens** [comment]
Fixed
