### ISSUE TITLE
CUP Package name blank/not displaying

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#62]
In list of institutional subscriptions - e.g

http://knowplus.edina.ac.uk/kbplus/myInstitutions/King%27s_College_London/currentSubscriptions

the last one in this list should be a CUP package, but the package name not displaying

**Comment by ianibo** [comment]
Please see recent email.. should STs copy the package reference from their parent SO or just link through the SO

**Comment by ianibo** [comment]
Fixed as a part of recent package mods.
