### ISSUE TITLE
Serials Solutions & SFX exports/transforms should be available/work from /subscriptionDetails/index/

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#622]
At the moment these transforms are only available from /myInstitutions/[org]/currentTitles

Ideally should also be available from 
/subscriptionDetails/index/

e.g http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1666

**Comment by ianibo** [comment]
Whilst doing this would it be possible to take the chunks of logic out of the view and move it into the controller please?
