### ISSUE TITLE
Number of Licences count on new Stats page includes Deleted licences

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#624]
from http://test.kbplus.ac.uk/kbplus/stats/statsHome
Current Manchester Metropolitan University listed as having 290 licences

This includes those with status of Deleted
Looking at http://test.kbplus.ac.uk/kbplus/myInstitutions/Manchester_Metropolitan_University/currentLicenses only 160 'Current' Licenses with MMU as Licensee

Prefer count to only be of licences with status Current

**Comment by ianibbo** [comment]
If liam is using this as an indication of usage, does it matter that they
are deleted? that was my thinking in not excluding them.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Just on Skype with L at the moment - asking him the Q

**Comment by ostephens** [comment]
Liam's preference is to have two figures: one of just those with status 'Current' and one for Total (whatever Status)
However, if he can have just one of those in 3.3 he would prefer to just have the 'Current' status count

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936
