### ISSUE TITLE
Number of Subscriptions count on new Stats page includes Deleted Subscriptions

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#625]
From http://test.kbplus.ac.uk/kbplus/stats/statsHome
e.g. for Manchester Metropolitan University lists 249 subs currently
Looking at http://test.kbplus.ac.uk/kbplus/organisations/show/439 I can see this is made of 
194 subs with status 'Current' where MMU 'subscriber'
55 subs with status 'Deleted' where MMU 'subscriber'

Would prefer if the count given here was only those Subs with status 'Current'

**Comment by ianibo** [comment]
Bit confused as to why this has re-appeared. Does the revised stats page not deal with this?

**Comment by ostephens** [comment]
No idea - wasn't deliberate - it is fixed
