### ISSUE TITLE
Control number of TIPPs displayed on /subscriptionDetails/addEntitlements via user set value

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#638]
See #631 
e.g. on http://test.kbplus.ac.uk/kbplus/subscriptionDetails/addEntitlements/1666
Also desirable, but not essential option to 'Show all' in list for users who want to add TIPPs from across the package in one go

**Comment by ianibo** [comment]
Will work on these but non-trivial.. Wish we'd done this separate to the C&C wireframes.. should have picked it up but ignored it.

**Comment by ianibo** [comment]
Not really it still amounts to a change to every page with a list on it. I'm on it.

**Comment by ostephens** [comment]
Not sure if it is possible to tackle one at a time, but I've added issues for each one where I think it is a particular issue, and prioritised within that list

**Comment by ostephens** [comment]
That is to say, if we don't manage to do all lists then it wouldn't be a disaster, but would be nice to do the key ones
