### ISSUE TITLE
Compare ONIX-PL licence screen does not show 'Manage' menu

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#639]
Manage menu missing from the top bar on
http://test.kbplus.ac.uk/kbplus/onixplLicenseCompare/index - needs to be there to allow navigation to rest of system

**Comment by ianibo** [comment]
Think I might have just committed a change that will fix this globally.

**Comment by rwincewicz** [comment]
I've just pulled down the latest changes to newdev and this issue is now fixed on the ONIX-PL comparison screen.

**Comment by ianibo** [comment]
Tested - new pre filter sets user so this all works as expected now.
