### ISSUE TITLE
SFX/Serials Solutions transforms include additional data when applied to Subscription xml

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#642]
The additional data in the Subscriptions xml leads is included in SFX/Serial Solutions transform output. Think the XSLT needs to explicitly match the TitleListEntry via &lt;xsl:apply-templates select="TitleListEntry"&gt; or similar?

Subs xml e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1666?format=xml - includes &lt;Subscription&gt; and related elements at top of xml (parent of TitleList element

Titles listing xml doesn't have the additional subs data in it and so transform is ok e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=1666&sort=tipp.title.title&order=asc&validOn=2013-09-21&filterOtherPlat=all&filterHostPlat=all&filterPvd=all&filter=&format=xml

**Comment by desreid** [comment]
Owen, I've rolled out the new xslt to dev and test. I've tested it, but could you verify?

**Comment by ostephens** [comment]
Hi Des

It looks like the fix has solved the problem, but on specific subscriptions we are getting a 500 from the transform - see http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1829?format=xml&transforms=1

I can't see anything obvious about the xml that would make this fail. Generally the transforms work though, so not a universal problem

Can you see anything obvious?

**Comment by ostephens** [comment]
Closing this - have noted issue with http status 500 response on some transforms in #646
