### ISSUE TITLE
Grails errors when on 'Accept All' or 'Reject All' ToDos for a particular subscription/licence

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#645]
Found by Helen:
Grails errors when I either 'Accept All' or 'Reject All' ToDos for a particular subscription or licence.

The screenshots below are the ones I encountered for a subscription but the same errors showed for a licence too: 
![pastedgraphic-2](https://f.cloud.github.com/assets/576174/1200685/247a8bac-2529-11e3-9502-08a7331e8cfa.png)
![pastedgraphic-1](https://f.cloud.github.com/assets/576174/1200686/24c8da6e-2529-11e3-81a3-d5fdd95a5fa4.png)

**Comment by ostephens** [comment]
Screenshot of Sub where clicking 'reject all' creates error above
![screen shot 2013-09-24 at 18 25 57](https://f.cloud.github.com/assets/576174/1202130/cde932fe-253f-11e3-86e3-df1656c8e0cb.png)

**Comment by ianibo** [comment]
Unable to see those changes under JC, just did an accept all on JC and
worked fine.. Sure this was pre test update?

On 24 September 2013 18:36, Owen Stephens notifications@github.com wrote:

> Screenshot of Sub where clicking 'reject all' creates error above
> [image: screen shot 2013-09-24 at 18 25 57]https://f.cloud.github.com/assets/576174/1202130/cde932fe-253f-11e3-86e3-df1656c8e0cb.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/645#issuecomment-25025837
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Following latest update on test seeing same error on 'reject all' - see 
http://test.kbplus.ac.uk/kbplus/pendingChange/rejectAll/com.k_int.kbplus.Subscription%3A561

however, after seeing this error it looks like the change itself has been Accepted rather than Rejected
Change notification was on:
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/561 - now gone - IE looks like it has updated (IE is http://test.kbplus.ac.uk/kbplus/issueEntitlement/show/154190)

"Accept All" seemed to work OK (on different change of course)

**Comment by ostephens** [comment]
Have made further change on Test on same TIPP to try to recreate
