### ISSUE TITLE
HTTP Status 500 error on SS/SFX transform

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#646]
On specific subscriptions we are getting a 500 from the transform - see http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1840?format=xml&transforms=1

I can't see anything obvious about the xml that would make this fail. Generally the transforms work though, so not a universal problem

Can you see anything obvious?

**Comment by ostephens** [comment]
Cannot replicated on knowplusdev - following exactly same steps does not replicate issue - transforms all seem to work on dev.kblus.ac.uk

Something about xml/xsl setup on test?

**Comment by desreid** [comment]
Fixed I think. The problem arose when a rebuild occurred. The apache config gets swapped out to display the 'undermaintenance' page and the settings needed for lib path were getting lost. I no longer get a 500 from the above example, but there are no records in the above example. Perhaps they were lost in the rebuild this morning? Can you verify the fix?

**Comment by ostephens** [comment]
Fixed
