### ISSUE TITLE
Error on uploading Subscription Taken spreadsheet

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#651]
Trying to upload Subscription Taken spreadsheet - get the preview OK but when clicking 'Accept and Process' get error:

Error 500: Internal Server Error
URI
/kbplus/subscriptionImport/importSubscriptionWorksheet/processSubscriptionImport
Class
groovy.lang.MissingMethodException
Message
No signature of method: org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestWrapper.getFile() is applicable for argument types: (java.lang.String) values: [renewalsWorksheet] Possible solutions: getXML(), getPart(java.lang.String), getAt(java.lang.String), getAt(java.lang.String), getLocale(), getJSON()
Trace
    Line | Method
->>  605 | importSubscriptionWorksheet in com.k_int.kbplus.SubscriptionImportController

---

|    195 | doFilter                    in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker                   in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                         in java.lang.Thread

**Comment by ianibo** [comment]
Sure about this? That line number relates to the file upload... Bit weird.
What browser?

On 27 September 2013 15:50, Owen Stephens notifications@github.com wrote:

> Trying to upload Subscription Taken spreadsheet - get the preview OK but
> when clicking 'Accept and Process' get error:
> 
> Error 500: Internal Server Error
> URI
> 
> /kbplus/subscriptionImport/importSubscriptionWorksheet/processSubscriptionImport
> Class
> groovy.lang.MissingMethodException
> Message
> No signature of method:
> org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestWrapper.getFile()
> is applicable for argument types: (java.lang.String) values:
> [renewalsWorksheet] Possible solutions: getXML(),
> getPart(java.lang.String), getAt(java.lang.String),
> getAt(java.lang.String), getLocale(), getJSON()
> Trace
> Line | Method
> ->> 605 | importSubscriptionWorksheet in
> 
> ## com.k_int.kbplus.SubscriptionImportController
> 
> | 195 | doFilter in
> grails.plugin.cache.web.filter.PageFragmentCachingFilter
> | 63 | doFilter . . . . . . . . . in
> grails.plugin.cache.web.filter.AbstractFilter
> | 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
> | 603 | run . . . . . . . . . . . . in
> java.util.concurrent.ThreadPoolExecutor$Worker
> ^ 722 | run in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/651
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Never mind - found it... Stupid developer error...

**Comment by ostephens** [comment]
Confirmed fixed
