### ISSUE TITLE
ES Index Full Reset function on Live causes Grails error

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#653]
Noticed that the index on live didn't seem to be fully up to date, so tried to run
http://www.kbplus.ac.uk/kbplus/admin/fullReset

Get Grails error:
Error 500: Internal Server Error
URI
/kbplus/admin/fullReset
Class
org.elasticsearch.indices.IndexAlreadyExistsException
Message
[kbplus] Already exists
Trace
    Line | Method
->>  496 | validate   in org.elasticsearch.cluster.metadata.MetaDataCreateIndexService

---

|     86 | access$100 in     ''
|    148 | execute .  in org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1
|    229 | run        in org.elasticsearch.cluster.service.InternalClusterService$2
|     95 | run . . .  in org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable
|   1110 | runWorker  in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run        in java.lang.Thread

Cannot replicate this on test or demo servers where full reset function seems to work OK

**Comment by ostephens** [comment]
Also looks like indexing behaving differently on live to test/demo in terms of facets of words vs phrases in package search - see screenshots to see how facets differ between live (red) and test (green)

![screen shot 2013-10-02 at 12 01 51](https://f.cloud.github.com/assets/576174/1252755/2f90fbfa-2b52-11e3-9b76-7b3487397a37.png)
![screen shot 2013-10-02 at 12 01 41](https://f.cloud.github.com/assets/576174/1252756/2fe796d6-2b52-11e3-9118-1bf32b1dca5b.png)

**Comment by ianibbo** [comment]
Probably fallout from the underlying issue that the create wasn't waiting
for the drop to complete, which means the live index is never properly
reconstituted.

Fix uploaded.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Fix has changed the Test index so now behaving like Live in terms of facet indexing - need it to behave like old Test index - i.e. should have "JISC Collections" as facet not "jisc" and "collections" as separate facets

**Comment by ianibbo** [comment]
Actually, fix is OK, the fact that we both ran the FT reset at the same
time caused a different problem.

Please leave alone for now, will put some extra defensive code in and shout
when its good to go.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - apols

**Comment by ianibo** [comment]
NPS.. need to bear in mind also that deploy now calls full reset too, so
now that the process waits for the drop to complete, this can take longer.
Added some code to fall through do full reset if one already running..
testing now...

On 2 October 2013 12:40, Owen Stephens notifications@github.com wrote:

> OK - apols
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/653#issuecomment-25532024
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Fixed
