### ISSUE TITLE
On import of ONIX-PL licence properties appear twice

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#655]
Looks like the latest changes to ONIX-PL licence import lead to properties appearing twice post import - once with notes with paragraph numbers and once without

![screen shot 2013-10-07 at 13 36 52](https://f.cloud.github.com/assets/576174/1280269/e71b52d0-2f4d-11e3-9926-91fd58ac2ce1.png)

**Comment by rwincewicz** [comment]
Could you tell me which server this was on and which licence this is? I've tried a few of the licences on my local copy of the newdev branch and everything seems to import properly.

**Comment by ostephens** [comment]
This was reported on live, which is where I've taken the screenshot from - I'll do some more checking and get back to you - issue assigned to me while I check. Thanks

**Comment by ostephens** [comment]
Looks like this may have been an issue when a specific licence was uploaded but now resolved - at least cannot replicate right now
