### ISSUE TITLE
Package name missing from Current Subs display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#66]
Reported by Liam. E.g. 
http://knowplus.edina.ac.uk/kbplus/myInstitutions/JISC_Collections/currentSubscriptions

Missing package names for numbers
173 (NESLI2 EUP Complete Collection No New Titles 2012)
175 (also NESLI2 EUP Complete Collection No New Titles 2012?)
186 (NESLI2 Springer Option 1 Closed Consortium Agreement 2011_2012)

**Comment by ianibo** [comment]
Taking 173 as an example... This indicates that there were no packages instances attached to the subscription.. Don't know why that would be the case... http://knowplus.edina.ac.uk/kbplus/subscription/show/173 seems to show no packages. Is this therefore actually a data issue?

**Comment by ostephens** [comment]
Wonder if this is the problem - two Subscriptions Offered files using the same package identifier:
eup_completecollection no new titles_2012_nesli2
eup_completecollection no new titles_2012_shedl

Would this cause this problem - the package details from the second one overwriting the first?

**Comment by ostephens** [comment]
Ian - any chance of confirming this before we do tonight's upload? Would be good to see if we can sort in this load. But if not, no worries

**Comment by ianibo** [comment]
I can try.. Just trying to investigate the docstore issue some more.

On 10 July 2012 16:09, ostephens <
reply@reply.github.com

> wrote:
> 
> Ian - any chance of confirming this before we do tonight's upload? Would
> be good to see if we can sort in this load. But if not, no worries
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/66#issuecomment-6878353

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
There's nothing obvious in the code to indicate that this could be whats
happening. I suggest we re-upload and then look again.

On 10 July 2012 16:09, ostephens <
reply@reply.github.com

> wrote:
> 
> Ian - any chance of confirming this before we do tonight's upload? Would
> be good to see if we can sort in this load. But if not, no worries
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/66#issuecomment-6878353

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
Fixed, currently showing package and package from parent whilst testing that copying forward of package to ST is working as expected.. will then remove display of parent package.
