### ISSUE TITLE
New line characters in Export

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#665]
Downloading the 'CUFTS' style csv export from http://www.kbplus.ac.uk/kbplus/publicExport/idx?format=csv I get extraneous new line characters in the output

Downloading the file this morning and opening as csv lines 10 and 11 should be a single line but I get a newline char resulting in
"American Association for the Advancement of Science:NESLI2:Science Journals Free Titles:2011-2012
","publicExport/pkg/20?format=csv","20"

There are a number of examples throughout the file

**Comment by ostephens** [comment]
From investigation by @ianibbo the newline chars are actually in the data not an artefact of the export

**Comment by ostephens** [comment]
I'd prefer to correct the data than work around this, but I can't see any way of correcting this in the web UI at the moment. E.g. from http://www.kbplus.ac.uk/kbplus/packageDetails/show/14 I don't see the newline character in the edit box, and editing the value and saving it doesn't seem to remove the newline character (which is at the end of the field by the looks of it).

Any ideas/suggestions. I agree we don't want to try to work around the data and would prefer to correct it

**Comment by ianibo** [comment]
Ok. as per email - control changed to simple text, which will stop it happening in future. To fix current data, the following SQL should work...

update title_instance_package_platform SET tipp_host_platform_url = TRIM(TRAILING '\n' FROM TRIM(tipp_host_platform_url))

**Comment by ostephens** [comment]
SQL has now been run by Des on all platforms
