### ISSUE TITLE
Cannot add Org link for Jisc Collections on Live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#670]
E.g. http://www.kbplus.ac.uk/kbplus/licenseDetails/index/15
Click 'Add Org Link'
Select JISC Collections, check box, set a role and click 

In HTML code seeing this for JISC Collections:
&lt;input type="checkbox" name="orm_orgoid" value="com.k_int.kbplus.Org_$$_javassist_84:35"&gt;

Seems specific to JISC Collections org (or at least does not effect all orgs) - for comparison IOP works correctly:
&lt;input type="checkbox" name="orm_orgoid" value="com.k_int.kbplus.Org:34"&gt;

**Comment by ianibo** [comment]
Think this has been reported before and fixed in dev? Will double check in
a month tho.

**Comment by ostephens** [comment]
It rang a bell with me as well so you may well be right - however could check because of https://github.com/k-int/KBPlus/issues/669 and didn't want to forget. I'll dig back through issues and see if I can track it down

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Just retested on test and deleted-then-re-added JC as a licensee on http://test.kbplus.ac.uk/kbplus/licenseDetails/index/556. Closing. Pls reopen if repeats
