### ISSUE TITLE
On Test: 'Add Transformers' options still displaying on Profile page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#673]
Think we agreed that this would be removed and all transformations would be shown? So I think this section of the Profile page no longer required

**Comment by ianibbo** [comment]
We did.. this was left in deliberately for now, I'll yank it now.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Fixed

**Comment by ianibo** [comment]
Hmm.. I removed it, but can't get to test at the moment to check :/

On 15 January 2014 10:00, Owen Stephens notifications@github.com wrote:

> Think we agreed that this would be removed and all transformations would
> be shown? So I think this section of the Profile page no longer required
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/673
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibbo** [comment]
Seems to have vanished now

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
