### ISSUE TITLE
When carrying out a 'title merge' the 'deprecated title' should no longer appear to users

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#675]
E.g. merge TIs
http://dev.kbplus.ac.uk/kbplus/admin/titleMerge?titleIdToDeprecate=13586&correctTitleId=6279

The TIPPs are transferred correctly, but the deprecated title is still found via a title search:
http://dev.kbplus.ac.uk/kbplus/titleDetails/index?offset=0&title=Classical+world&search=yes

Once a title is deprecated via a merge, should no longer appear in this search (possibly by updating TI status to deleted?)

**Comment by ostephens** [comment]
Also looks like IDs are not moved between titles on a title merge?

**Comment by ianibo** [comment]
Is it wise to move ID's between titles? I'm getting a bit confused. Also, deprecated title now has a status of deleted, but hiding it in all situations is a big-scope item. This issue is mushrooming a little?

**Comment by ostephens** [comment]
That seems fair comment. No further development on this for 4.0.

**Comment by ianibo** [comment]
Saw this on the DMs ZenDesk List - Can we enumerate all the places where deleted titles appear and we will work through each one and sort it out. Unfortunately, there is no magic button that will do them all (Titles appear in almost every screen) - So maybe we could identify the 5 most critical places?

**Comment by ostephens** [comment]
The only real issue is them appearing in  the Title Search - which I think you've already looked at for 4.2? While Titles appear in many other places, in all other cases they are displaying because they are linked to some other thing - so I'd dispute in these cases you want them to 'not display' even if they are marked as 'deleted'.

So Title Search is number one critical place on this
