### ISSUE TITLE
Headings on Subscription 'History Tab' in incorrect place

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#679]
e.g. http://dev.kbplus.ac.uk/kbplus/subscriptionDetails/history/1219
Headings:
ToDo History
Subscription history

Appear, unstyled, above both tables - correct heading should appear in heading style above the correct table

![screen shot 2014-01-20 at 14 45 03](https://f.cloud.github.com/assets/576174/1954971/b252d28a-81e1-11e3-9067-60009618807b.png)

**Comment by ianibo** [comment]
Will fix.. really should be testing against test tho!

On 20 January 2014 14:46, Owen Stephens notifications@github.com wrote:

> e.g. http://dev.kbplus.ac.uk/kbplus/subscriptionDetails/history/1219
> Headings:
> ToDo History
> Subscription history
> 
> Appear, unstyled, above both tables - correct heading should appear in
> heading style above the correct table
> 
> [image: screen shot 2014-01-20 at 14 45 03]https://f.cloud.github.com/assets/576174/1954971/b252d28a-81e1-11e3-9067-60009618807b.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/679
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
