### ISSUE TITLE
Incorrect links to transforms from /currentTitles on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#682]
From /currentTitles (e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles) the links to the transformations are incorrect. 

They should be like “http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles?format=xml&transformId=oclc” but are currently like “http://test.kbplus.ac.uk/kbplus/myInstitutions/index?format=xml&transformId=oclc"

**Comment by iamcreative** [comment]
This is not fixed for OCLC, Serial Solutions and SFX resolvers - All three throw a Grails error when the user selects them.

e.g.
Error 500: Internal Server Error
URI
/kbplus/myInstitutions/currentTitles
Class
java.lang.IllegalArgumentException
Message
Named parameter [institution] value may not be null
Trace
    Line | Method
->>  778 | currentTitles in com.k_int.kbplus.MyInstitutionsController

---

|    195 | doFilter      in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . .  in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter      in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker . . in java.util.concurrent.ThreadPoolExecutor
|    603 | run           in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . in java.lang.Thread

**Comment by ostephens** [comment]
URLs still incorrect but have changed.

URLs are now like 
http://test.kbplus.ac.uk/kbplus/myInstitutions/currentTitles?format=xml&transformId=oclc

should be like
http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles?format=xml&transformId=oclc

**Comment by ianibo** [comment]
Argh.. spent a fair while trying to understand why this works for me but is still broken on test - test doesn't seem to have updated since thursday, which is why it still looks broken for you.

**Comment by ostephens** [comment]
Looks like recent commit has triggered test to re-build - this is now fixed on test
