### ISSUE TITLE
New Documents not displayed on licenseDetails/documents

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#686]
e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/documents/625 - three pre-existing docs are displayed, but newly uploaded doc does not (you can see 4 docs listed in Documents display on http://test.kbplus.ac.uk/kbplus/licenseDetails/index/625)

See also #685

**Comment by iamcreative** [comment]
This looks like a partial fix. The newly uploaded docs now appear on the 'Documents' tab but only pre-existing documents have a 'Download' link next to them. The documents can be downloaded from the licenseDetails view though. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/1

**Comment by iamcreative** [comment]
Confirmed as fixed now!
