### ISSUE TITLE
Read only users can accept/reject ToDo items on subscriptions

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#693]
On a subscription when there are ToDo items a Read only user can accept/reject ToDos. If they 'accept' a data change via a ToDo the relevant subscription or IE will be updated.

You should only be able to Accept/Reject ToDo items from screens where you have edit capability

**Comment by iamcreative** [comment]
Read Only user can no longer action a ToDo item from the 'details'  screen but they can still accept/reject ToDos from the 'History' tab of a licence or subscription.
See: http://test.kbplus.ac.uk/kbplus/licenseDetails/history/128 and http://test.kbplus.ac.uk/kbplus/subscriptionDetails/history/149

**Comment by ostephens** [comment]
Fixed - Accept/Reject options no longer show on /history/ screens for any user - i.e. /history/ page for reference only, not for actions
