### ISSUE TITLE
Title/TIPP editing split between /titleDetails/show and /titleDetails/edit

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#696]
Not urgent to fix but...

On /titleDetails/show I can edit the TIPPs associated with a title
On /titleDetails/edit I can edit the TI details (name, identifiers, orgs)

From http://test.kbplus.ac.uk/kbplus/titleDetails/index clicking the journal title itself takes you to /titleDetails/show while clicking on 'Edit' link goes to /titleDetails/edit

Would be nice to have all these edit functions on one screen. 
Not urgent!

**Comment by ianibo** [comment]
Ok.. wasn't editing tipps on titleDetails/show a change requested in this
release?

On 28 January 2014 10:06, Owen Stephens notifications@github.com wrote:

> Not urgent to fix but...
> 
> On /titleDetails/show I can edit the TIPPs associated with a title
> On /titleDetails/edit I can edit the TI details (name, identifiers, orgs)
> 
> From http://test.kbplus.ac.uk/kbplus/titleDetails/index clicking the
> journal title itself takes you to /titleDetails/show while clicking on
> 'Edit' link goes to /titleDetails/edit
> 
> Would be nice to have all these edit functions on one screen.
> Not urgent!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/696
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Yes, editing tipps new in this release - sorry my fault clearly didn't check where current edit functions lived. I'd suggest we leave for 4.0 as this question would fall nicely under the review of various screens via the focus groups in 4.1/4.2

**Comment by ianibo** [comment]
Cool, ty.

On 28 January 2014 11:24, Owen Stephens notifications@github.com wrote:

> Yes, editing tipps new in this release - sorry my fault clearly didn't
> check where current edit functions lived. I'd suggest we leave for 4.0 as
> this question would fall nicely under the review of various screens via the
> focus groups in 4.1/4.2
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/696#issuecomment-33470216
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Closing as if this is still an issue will come up through enhancement requests
