### ISSUE TITLE
Grails error on ONIX-PL import

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#697]
When importing an ONIX-PL document the following Grails error appears:

Error 500: Internal Server Error
URI
/kbplus/licenseImport/doImport
Class
groovy.lang.MissingPropertyException
Message
No such property: size for class: java.lang.String
Trace
    Line | Method
->>  302 | processImport in com.k_int.kbplus.LicenseImportController

---

|    129 | doImport      in     ''
|    195 | doFilter . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter      in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter . .  in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run           in java.lang.Thread

**Comment by iamcreative** [comment]
Still throwing an error [note that the error message itself has changed]:

Error 500: Internal Server Error
URI
/kbplus/licenseImport/doImport
Class
groovy.lang.MissingMethodException
Message
No signature of method: org.springframework.web.multipart.commons.CommonsMultipartFile.size() is applicable for argument types: () values: [] Possible solutions: is(java.lang.Object), find(), use([Ljava.lang.Object;), find(groovy.lang.Closure), with(groovy.lang.Closure), sleep(long)
Trace
    Line | Method
->>  302 | processImport in com.k_int.kbplus.LicenseImportController

---

|    129 | doImport      in     ''
|    195 | doFilter . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter      in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter . .  in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run           in java.lang.Thread

**Comment by ostephens** [comment]
I'm afraid now seeing a new error on this now:

Error 500: Internal Server Error
URI
/kbplus/licenseImport/doImport
Class
groovy.lang.MissingPropertyException
Message
No such property: filename for class: com.k_int.kbplus.LicenseImportController
Trace
    Line | Method
->>  315 | processImport in com.k_int.kbplus.LicenseImportController

---

|    129 | doImport      in     ''
|    195 | doFilter . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter      in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter . .  in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run           in java.lang.Thread
