### ISSUE TITLE
"JUSP Usage Link" should only display to KB+ Editors

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#698]
On /issueEntitlement/show/ e.g. http://test.kbplus.ac.uk/kbplus/issueEntitlement/show/431456 the JUSP Usage Link should only display to users with KB+ Editor perms (i.e. data managers etc.)

**Comment by ianibo** [comment]
Could I ask why? This seems like it might legitimately be of use to the institution?

**Comment by ostephens** [comment]
The JUSP API isn't openly accessible - users just get an error if they click on the link (it's IP auth)

**Comment by ianibbo** [comment]
YEah - but those institutions that do have auth will be able to see it?
Security by obscurity isn't really the right way to define open interfaces
- Admittedly the JUSP failed auth page could be better, but still - this
  doesn't seem like quite the best approach to me.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
As far as I know the only IPs with access to this JUSP API are mine, yours/K-ints, and the kbplus servers.

We can check with PN but afaik this API was setup solely for KB+ use.

I'd agree that there are better ways of doing this, but at the moment we keep get people clicking the link and reporting it as a bug.

**Comment by ianibo** [comment]
SO we add some text that says "You need to have JUSP authentication for this to work" - I mean I don't really give a stuff - but I would have thought it better for JUSP rather than us just leeching off their work with no way for institutions to get directly to the data.

**Comment by ostephens** [comment]
I can't see this makes sense until JUSP support an API that is accessible to users - which I agree would be a good idea - but if essentially no-one except you and me can access this link there's no point in displaying it

**Comment by ostephens** [comment]
In terms of offering traffic back to JUSP I also agree - and originally suggested we have a link back to JUSP from here - but JUSP couldn't support direct linking to the relevant stats which would have just left us with a generic link to the JUSP front page

**Comment by ianibbo** [comment]
Why should editors be able to see it then?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Fair point
