### ISSUE TITLE
Display of 'Documents' table is overspilling the screen

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#699]
long filenames seem to break the text wrap/table display and the user is unable to scroll the screen to see the text that is off screen to the right hand side.

e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/documents/127

Screenshot:
![kbplusscreenoverflow](https://f.cloud.github.com/assets/2110374/2040625/8bcc3900-89b9-11e3-8fdd-3f00b45b2f2e.jpg)

**Comment by ostephens** [comment]
Fixed
