### ISSUE TITLE
Not all Subscriptions Taken loading

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#70]
E.g. for the University of Westminster (http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentSubscriptions) only 3 Subs Taken successfully imported.

In files there are 11 Subs taken listed:

647_AnnualReviews_biomedcollectionof22_2012_2014_Nesli2.csv
647_Project muse_basic research collection_2012_2013_nesli2.csv
647_acs_collection_2012_2012_nesli2.csv
647_bmj_collection_2011-2012_nesli2.csv
647_bmj_freetitles_2011-2012_nesli2.csv
647_nature_collection_2012_2012_Nesli2.csv
647_oup_collection_2012-2013_nesli2.csv
647_sage_collection_2010_2010_nesli2.csv
647_springer_option1closedconsortium agreement_2011_2012_nesli2.csv
647_wiley_full collection_2012-2014_nesli2.csv
647_wiley_opt-in_2012-2014_nesli2.csv

**Comment by ianibbo** [comment]
You able to text chat on skype?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Thu, Jul 12, 2012 at 11:15 PM, ostephens <
reply@reply.github.com

**Comment by ianibo** [comment]
Working through these and documenting rules here as I find cases.

First case: Text if identifier in SO and ST files was different, causing matching of ST/SO identifier to fail, hence ST not created. Lowercase and trim identifiers to base matching on a normalised string.

**Comment by ianibo** [comment]
Second issue;
project muse_basic research collection_2012-2013_nesli2
vs
Project muse_basic research collection_2012_2013_nesli2

One has - and the other has _ to separate out the dates. Don't want to remove this punctuation. Going to do a replace all of - to _.

**Comment by ianibo** [comment]
Last change sorted 10/11 UoW issues. Final one is 

647_springer_option1closedconsortium\ agreement_2011_2012_nesli2.csv

Which lists "springer_OPTION1closedconsortiumagreement_2011_2012_nesli2" as it's SO, but the only similar SO I can find is in file

springer_option1closed consortium agreement_2011_2012_sheld.csv

Which is not nesli2, and appears to be sheld rather than shedl? Dunno if that's a typo or deliberate?

**Comment by ianibo** [comment]
Most recent changes seems to have fixed these. All 11 loading.

**Comment by ostephens** [comment]
Should I expect to see these in the KB+ app now? Still seeing only 3 of these in the 'Current Subs' for University of Westminster?

Either in Data Explorer: http://knowplus.edina.ac.uk/kbplus/org/show/537
Or in KB+ App: http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentSubscriptions

**Comment by ianibo** [comment]
No,

I've not updated the database yet

On 23 July 2012 13:00, ostephens <
reply@reply.github.com

> wrote:
> 
> Should I expect to see these in the KB+ app now? Still seeing only 3 of
> these in the 'Current Subs' for University of Westminster?
> 
> Either in Data Explorer: http://knowplus.edina.ac.uk/kbplus/org/show/537
> Or in KB+ App:
> http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentSubscriptions
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/70#issuecomment-7176107

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment]
(Longer answer)

I was going to, but thought I'd hold off until I get a response on the
dates-in-volume issue (Ha, no pun intended) as that seemed quite important

e

On 23 July 2012 13:00, ostephens <
reply@reply.github.com

> wrote:
> 
> Should I expect to see these in the KB+ app now? Still seeing only 3 of
> these in the 'Current Subs' for University of Westminster?
> 
> Either in Data Explorer: http://knowplus.edina.ac.uk/kbplus/org/show/537
> Or in KB+ App:
> http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Westminster/currentSubscriptions
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/70#issuecomment-7176107

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
OK.

I've emailed Magaly and Liam regarding the dates-in-volume issue but M is away this week, so not expecting immediate response - I'd go ahead and load the latest data whenever you are ready (I'd like to get Westminster their subs for checking)
