### ISSUE TITLE
Grails error on copying licence for Jisc Collections on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#702]
Specifically affects doing licence copy for Jisc Collections org, not affecting other institutions tested

From http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/addLicense

Selected licence http://test.kbplus.ac.uk/kbplus/licenseDetails/index/15 using radio button

Clicked 'Copy Selected'

Got error:

http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/actionLicenses
Error 500: Internal Server Error
URI
/kbplus/myInstitutions/JISC_Collections/actionLicenses
Class
org.hibernate.ObjectNotFoundException
Message
No row with the given identifier exists: [com.k_int.kbplus.Package#48]
Trace
    Line | Method
->>  551 | newLicense     in com.k_int.kbplus.MyInstitutionsController

---

|     81 | actionLicenses in     ''
|    195 | doFilter . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter       in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter . . . in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker      in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run            in java.lang.Thread

**Comment by ianibbo** [comment]
Yeah.. Seen this in other places. There is a link table pointing to a
(hard) deleted package. Not sure how this has happened. Needs investigation.

**Comment by ostephens** [comment]
OK - not urgent for 4.0

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
On live DB this query

mysql> select \* from org_role where or_title_fk is not null and not exists ( select \* from title_instance where ti_id = or_title_fk );

Returns

Empty set (0.05 sec)

When the same SQL is run on test

mysql> select \* from org_role where or_pkg_fk is not null and not exists ( select \* from package where pkg_id = or_pkg_fk );
+-------+------------+-----------+-----------+-----------+----------------+-----------+-------------+
| or_id | or_version | or_lic_fk | or_org_fk | or_pkg_fk | or_roletype_fk | or_sub_fk | or_title_fk |
+-------+------------+-----------+-----------+-----------+----------------+-----------+-------------+
|  3206 |          0 |      NULL |       203 |        48 |             81 |      NULL |        NULL | 
|  5902 |          0 |      NULL |        35 |        48 |            112 |      NULL |        NULL | 
|  8138 |          0 |      NULL |       595 |       425 |             81 |      NULL |        NULL | 
|  8300 |          0 |      NULL |       193 |       471 |            112 |      NULL |        NULL | 
+-------+------------+-----------+-----------+-----------+----------------+-----------+-------------+
4 rows in set (0.03 sec)

Somehow 4 rows in test point to now deleted packages. I'm not sure (a) how this has happened and (b) why the live clone isn't replacing the data?

The "fix" is to delete these rows.

maybe we need a nightly cron job that runs queries like this looking for inconsistencies.

Not sure this is a software one really tho.. Any thoughts?

e

**Comment by desreid** [comment]
For info, the test build doesn't do a clone of the live database. The clone takes hours (since the DB contains the JUSP data), and when we discussed this back in September it was decided to disable the sync on build. I can either do a one-off sync, set up a weekly sync like we set up for 'demo', or you could just delete the data.

**Comment by ostephens** [comment]
We probably need to re-instate some data update from live to test - potentially do this without the JUSP data included?

Probably a discussion for email - I'll put something round

**Comment by ianibbo** [comment]
Yep, I think I've posted the mysql dump command in several places to do an
export omitting the jusp tables.. I think it's --omit-table off the top of
my head.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Assigned back to owen to close or provide definitive action.

**Comment by ostephens** [comment]
Closing as cannot recreate on live, demo or test now (n.b. data on test has now been refreshed which would explain this)
