### ISSUE TITLE
Fields not appearing as editable on Live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#705]
All over live instance but e.g. http://www.kbplus.ac.uk/kbplus/subscriptionDetails/index/2742

None of the fields that should be 'click to edit' are showing as such on live. Works fine on demo and test which are built from the same code base

Compare screenshot from live (no fields have dotted underline, and don't go into edit mode when clicked)
![screen shot 2014-02-03 at 12 01 35](https://f.cloud.github.com/assets/576174/2064385/08abf5a0-8ccb-11e3-92d6-691387ceff88.png)

vs screenshot from demo - can see underlined fields which can be edited by clicking
![screen shot 2014-02-03 at 12 03 06](https://f.cloud.github.com/assets/576174/2064389/2ad494c0-8ccb-11e3-9327-cd5bcb32b9ed.png)

No obvious errors in my browser console

**Comment by ianibo** [comment]
Ditto 703 - maybe retest with chrome new incognito?

**Comment by ianibo** [comment]
Yep, just tested live now...Seems OK??
![image](https://f.cloud.github.com/assets/53283/2064669/06fde16c-8cd2-11e3-8e90-0c90b1d13521.png)

**Comment by ostephens** [comment]
Caused by old javascript caching. Solved with forced browser refresh
