### ISSUE TITLE
Discussions not displaying on live dashboard

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#706]
e.g. http://www.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/dashboard

In 'Discussions' column there is only the message:
"Recent forum activity not available. Please retry later."

**Comment by ianibbo** [comment]
Ah ok.. not the error I spotted - This is likely a config problem somewhere
then.. the logs need to be examined for the cause - Shall I do that or is
it an edina task?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Will raise with Edina - I'll close this for now and re-open if necessary

**Comment by ostephens** [comment]
Resolved - for reference:
The API call to Zendesk retrieves the most recent 100 topics from Zendesk discussions.
The results are then filtered to remove any topics starting "Changes related to Package" to remove any topics created by posting of automated announcements

This means that if all of the 100 most recent topics are created by posting of automated announcements, after filtering there are no topics left to display, resulting in the message "Recent forum activity not available. Please retry later."

**Comment by ianibbo** [comment]
Ah cool.. not ideal tho is it, maybe a better message is needed to
differentiate the error case from the no updates case?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Agreed if not too difficult
