### ISSUE TITLE
Grails error from packageDetails/list

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#707]
e.g. http://www.kbplus.ac.uk/kbplus/packageDetails/list
Gives Grails error

Error 500: Internal Server Error
URI
/kbplus/packageDetails/list
Class
java.lang.NullPointerException
Message
null
Trace
    Line | Method
->>   66 | list      in com.k_int.kbplus.PackageDetailsController

---

|    195 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter  in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

**Comment by ianibbo** [comment]
Can you let me know where you followed this link from? I think the right
URL is http://www.kbplus.ac.uk/kbplus/packageDetails/index Which seems OK.
Looks like a dodgy link, but without knowing where it was clicked from it's
tricky.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
manage->all packages seems ok?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Yes Manage > All Packages goes to the URL you quote and all works.
The http://www.kbplus.ac.uk/kbplus/packageDetails/list link comes from 'Editors > Search Packages' which is used by Magaly (at least).

My view is that this should be deprecated in favour of Manage > All Packages, but in email correspondence with M suggests we may need to add some things to the search display before deprecating. If possible for the immediate future fixing Editors > Search Packages maybe the simpler thing to achieve?

**Comment by ianibo** [comment]
Yeah.. replicated now, thanks. investigating.

**Comment by ianibo** [comment]
Fixed in code. Workaround: add ?max=10 to the URL.
