### ISSUE TITLE
Read Only users can create subscriptions via Import Renewals

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#709]
Read Only users can create subscriptions by uploading a comparison spreadsheet using Import Renewals - e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsUpload

Should not be possible for Read Only users to access the upload screen.

Not an urgent fix - does not need to be done for 4.0 update on Monday

**Comment by iyawnis** [comment]
The following are all the available roles: ROLE_USER, ROLE_EDITOR,ROLE_ADMIN,KBPLUS_EDITOR,ROLE_API,INST_ADM,INST_USER. We want role_editor and role_admin to be able to see reniewalsUpload screen ?

**Comment by ostephens** [comment]
I think the relevant roles are:
ROLE_ADMIN,KBPLUS_EDITOR

Not sure about ROLE_API - I guess this may need access.
Suggest checking with @ianibbo for confirmation

**Comment by iyawnis** [comment]
![denied](https://cloud.githubusercontent.com/assets/2336352/3052907/186ef638-e1a1-11e3-947b-48939c2c52c0.png)
