### ISSUE TITLE
Pagination on packageDetails/list does not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#710]
Pagination control on http://test.kbplus.ac.uk/kbplus/packageDetails/list links to:

http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index?offset=10&max=10

rather than

http://test.kbplus.ac.uk/kbplus/packageDetails/list?offset=10&max=10

**Comment by ostephens** [comment]
Thanks Ian. Can't check presently as dev build not deploying, but just checking - does the 'controller' parameter need updating to packageDetails in this code as well?

Also, I know Magaly is keen to get this deployed - is it possible to patch the release branch with the fix? (Sorry, I know this is a slight pain)

**Comment by ianibbo** [comment]
yeah - I think you are right - will sort first thing wed.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
