### ISSUE TITLE
Org requires import ID

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#716]
When an import job (e.g. Package import) tries to create a new Org, get a grails error "Column 'org_imp_id' cannot be null". Same occurs if try to create an Org via data explorer http://test.kbplus.ac.uk/kbplus/org/create

Error 500: Internal Server Error
URI
/kbplus/org/create
Class
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
Message
Column 'org_imp_id' cannot be null
Trace
    Line | Method
->>  411 | handleNewInstance  in com.mysql.jdbc.Util

---

|    386 | getInstance        in     ''
|   1041 | createSQLException in com.mysql.jdbc.SQLError
|   4190 | checkErrorPacket   in com.mysql.jdbc.MysqlIO
|   4122 | checkErrorPacket . in     ''
|   2570 | sendCommand        in     ''
|   2731 | sqlQueryDirect . . in     ''
|   2818 | execSQL            in com.mysql.jdbc.ConnectionImpl
|   2157 | executeInternal .  in com.mysql.jdbc.PreparedStatement
|   2460 | executeUpdate      in     ''
|   2377 | executeUpdate . .  in     ''
|   2361 | executeUpdate      in     ''
|     59 | create . . . . . . in com.k_int.kbplus.OrgController
|    195 | doFilter           in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter           in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker . . . .  in java.util.concurrent.ThreadPoolExecutor
|    603 | run                in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . .  in java.lang.Thread

**Comment by ianibbo** [comment]
Heya...

Bit confused by this one - Correct that impId needs to be set on the create
org form, but orgs created by importing should have the impId set to a GUID?

Is there an example of the import that fails?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Will send e.g. file via email

**Comment by ianibo** [comment]
Ah right - got you.

It's actually only with publishers - not orgs in general (Content Providers for example are fine). Understand the problem now. I've actually removed the org not-null restriction in the last release, but the constraint is still on the DB (Hence the different message).

DBA will need to run 

alter table org modify org_imp_id varchar(255) null;

To make this change to the schema too.

**Comment by ostephens** [comment]
Following up with Edina via email

**Comment by ostephens** [comment]
Relevant SQL has been run on all dbs (dev/test/demo/live)
