### ISSUE TITLE
Cannot filter Org list using diacritic characters

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#726]
e.g.
http://test.kbplus.ac.uk/kbplus/organisations/list?orgNameContains=Vetenskapsrådet&orgRole=

and 

http://test.kbplus.ac.uk/kbplus/org/list?orgNameContains=Vetenskapsrådet&orgRole=

both fail to find the relevant organisation (http://test.kbplus.ac.uk/kbplus/org/show/1139)

(similarly http://test.kbplus.ac.uk/kbplus/organisations/list?orgNameContains=Tést&orgRole= fails)

**Comment by ianibo** [comment]
Tested locally - unable to reproduce. Suspect outstanding platform / UTF8 issue as discussed before.

**Comment by ianibo** [comment]
Seems fine
![screenshot from 2014-03-12 12 45 11](https://f.cloud.github.com/assets/53283/2397046/303266aa-a9e4-11e3-93c6-2e40c23b6e2e.png)

**Comment by ianibo** [comment]
Assigned back to owen - edina infrastructure issue

**Comment by ostephens** [comment]
I think URL is being treated as ISO-8859-1 encoded rather that UTF-8 encoded:

å is encoded in ISO-8859-1 as %E5
å is encoded in UTF-8 as %C3%A5

The following URL works:
http://test.kbplus.ac.uk/kbplus/organisations/list?orgNameContains=Vetenskapsr%E5det&orgRole=

The following URLs both fail:
- http://test.kbplus.ac.uk/kbplus/organisations/list?orgNameContains=Vetenskapsr%C3%A5det&orgRole=
- http://test.kbplus.ac.uk/kbplus/organisations/list?orgNameContains=Vetenskapsrådet&orgRole=

If this is correct likely to be a Tomcat config issue to resolve. Will raised on mailing list

**Comment by ostephens** [comment]
Fixed via Tomcat config
