### ISSUE TITLE
Uploading Renewals spreadsheet or Subscription Taken sheet fails if it would lead to the creation of 1250 or more IEs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#727]
When using a spreadsheet to create a subscription either via:

Manage->Import Renewals
Manage->Import Subscription Taken Worksheet

The import fails if there are >1250 rows with 'Y' cells in the Packages cols which indicate an IE should be created - with the grails error:

Error 500: Internal Server Error
URI
/kbplus/subscriptionImport/processSubscriptionImport/441
Class
java.lang.NumberFormatException
Message
null
Trace
    Line | Method
->>  454 | parseInt                  in java.lang.Integer

---

|    527 | parseInt                  in     ''
|    758 | processSubscriptionImport in com.k_int.kbplus.SubscriptionImportController
|    195 | doFilter                  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter                  in com.k_int.kbplus.filter.ApiauthFilter
|   1110 | runWorker . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    603 | run                       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . . . . . . in java.lang.Thread

If there are 1249 'Y' or less then the upload succeeds

**Comment by ianibbo** [comment]
Ah fab.. didn't we leave this with testing some VM settings? Have a vague
recollection of digging into this and finding it to be an environmental
problem with form post truncation?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
yep, as per email 27th feb

I _think_ you need to ask des to update the maxPostSize in tomcat
server.xml (It's an attribute on the http connector I think). Ideally, set
it to 0 (==unlimited).

Looks to me like this is hitting the default max post size limit. There may
be other limits imposed by the edina apache, but I suspect not.

HTH
e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Oh yes - sorry lost track of that one. Will do

Owen

**Comment by ostephens** [comment]
Increased the post limit on test.kbplus.ac.uk but still same problem.
Checking the post, realised that when you go over 1249 IEs the POST has over 10k parameters - and tracked this back to default  maxParameterCount in Tomcat. Have requested this be increased on test to check this is cause.

**Comment by ostephens** [comment]
maxParameterCount increased on live. This should resolve the immediate problem, so closing this issue. Further work/discussion required on longer term approach.
