### ISSUE TITLE
Where Jusp stats are not available for a Title, cells in renewals spreadsheet should be blank, not zero

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#728]
At the moment where there are no stats available in the Fact table for a inst/title/provider combo the relevant cell in the Renewals spreadsheet is set to '0'. This should instead be left blank were there are no stats, and only set as 0 if the Jusp stats report zero usage.

This is so institutions can differentiate between 'zero usage' and 'usage not known'

e.g. see http://demo.kbplus.ac.uk/kbplus/issueEntitlement/show/565431 - shows no information from Jusp. While screenshot here shows zeroes in spreadsheet.

![screen shot 2014-03-13 at 12 24 21](https://f.cloud.github.com/assets/576174/2409243/fb954dfa-aaaa-11e3-84d3-ff3de7baaf1e.png)

**Comment by ianibbo** [comment]
I don't think this is as straightforward as implied. We use summations in
the spreadsheets. What if we have 1 zero and 11 nulls in a year?

**Comment by ostephens** [comment]
Good point - I'll find out

**Comment by ostephens** [comment]
I asked JUSP team "What would the API give us in the JR1 etc. reports if the stat was missing - would it just be a blank, or a zero?"

Paul N said:

---

The API would show a zero:

ReportPeriods": [{"Start":"2012-04","End":"2012-04","Reports":{"JR1":0,"JR1a":0,"JR1GOA":0,"JR1-JR1a":0}}]

Unless the month in question was before the first known or after the last known usage of that journal, in which case it would return

"ReportPeriods":null

---

Which suggests there is no way we can currently track 'null' figures from suppliers. This has been fed back to the user who raised this issue initially, so I'm closing this for now
