### ISSUE TITLE
Import of Renewals Spreadsheet does not create IEs on dev.kbplus.ac.uk

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#730]
Upload a Renewals Spreadsheet via e.g. http://dev.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsUpload

Preview shows IEs to be created correctly
![screen shot 2014-03-13 at 21 49 55](https://f.cloud.github.com/assets/576174/2415761/86235b4e-aaf9-11e3-8a5b-1333cec686aa.png)

When 'Accept and Process' clicked create Subscription, but no package linked and no IEs created:

![screen shot 2014-03-13 at 21 51 33](https://f.cloud.github.com/assets/576174/2415774/b4b13ac6-aaf9-11e3-94be-d65393eed802.png)

**Comment by ianibo** [comment]
Is this still an issue? bit confused...

**Comment by ostephens** [comment]
Will check on test now code deployed and get back to you

**Comment by ianibo** [comment]
any news?

**Comment by ostephens** [comment]
This is same symptoms as reported in #784. We don't need two issues for it - closing this in favour of #784
