### ISSUE TITLE
File naming of Subscriptions Taken spreadsheet

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#733]
As with #732, same behaviour for file naming the Subscriptions Taken spreadsheet

When downloading a 'Subscriptions Taken' spreadsheet e.g. from http://test.kbplus.ac.uk/kbplus/subscriptionImport/generateImportWorksheet/35 the file name has extra single inverted commas at the start and end. How this is handled seems to vary from browser to browser, but in at least some cases the result is a file with an extension like

.xls'

Which then won't open in Excel without renaming first.

I've tested as follows:

Firefox 27.0.1 Mac OS X = includes inverted commas in name and downloads file that fails to open
Chrome 35.0.1895.0 canary Mac OS X = does not include inverted commas in name, downloads file which opens OK without renaming
Safari 7.0.2 Mac OS X = includes interested commas in name, but then adds '.xls' on the end - so filename is like 'NewSubscriptionTemplate.xls'.xls. Name clearly odd, but opens OK without renaming

We've also had reported that IE9 includes the inverted commas in name and file then fails to open until it has been renamed

**Comment by ianibo** [comment]
System uses content disposition to set filename, and http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html states that a filename is a quoted string, so I think we're looking at browser misbehaviour really. Changed to remove quotes so this will work with broken browsers. Hope it doesn't break browsers following the standard.
