### ISSUE TITLE
Titles not indexed on http://www.kbplus.ac.uk

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#734]
On www.kbplus.ac.uk not all titles are indexed for the 'All Titles' search (http://www.kbplus.ac.uk/kbplus/titleDetails/index). On live service only 11234 titles listed. 

On demo.kbplus.ac.uk which should be very close to the same data (synced in the last 5 days) there are 21687 titles indexed.

Example title (as of 2014-03-20 09:20) "Aging, Neuropsychology, and Cognition" http://www.kbplus.ac.uk/kbplus/titleDetails/edit/7580

Possibly linked to similar issue previously reported where some packages weren't indexed?

**Comment by ianibo** [comment]
The same fix for packages should also be working for titles - This is
deployed on dev and test. Can we confirm / check it is an issue there first?

On 20 March 2014 09:20, Owen Stephens notifications@github.com wrote:

> On www.kbplus.ac.uk not all titles are indexed for the 'All Titles'
> search (http://www.kbplus.ac.uk/kbplus/titleDetails/index). On live
> service only 11234 titles listed.
> 
> On demo.kbplus.ac.uk which should be very close to the same data (synced
> in the last 5 days) there are 21687 titles indexed.
> 
> Example title (as of 2014-03-20 09:20) "Aging, Neuropsychology, and
> Cognition" http://www.kbplus.ac.uk/kbplus/titleDetails/edit/7580
> 
> Possibly linked to similar issue previously reported where some packages
> weren't indexed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/734
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibbo** [comment]
Just tested on test and the latest title in the db is findable as the top
result in free text search.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Closing for now due to inactivity. Please repopen with test case from test if problem seen again.
