### ISSUE TITLE
Add Coverage Note to batch edit functions on /titleDetails/show

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#735]
e.g. http://test.kbplus.ac.uk/kbplus/titleDetails/show/13
Data managers often need to add the same coverage note to all/majority of TIPPs for a TI. At the moment they have to click through to the TIPP details to do this. If the Coverage Note could be edited via the batch edit function on titleDetails/show it would save them time

**Comment by iyawnis** [comment]
This issue appears to be addressed on 4.1-dev, as there is batch update option for Coverage note. Waiting confirmation from Ian.

**Comment by iyawnis** [comment]
Comfirmed from Owen
