### ISSUE TITLE
Package import on test does not link additional platforms to TIPPs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#736]
If a package import file is uploaded containing columns like:
platform.admin.name / platform.admin.url
platform.admin:1.name / platform.admin:1.url

These platforms are created (if they do not already exist) but no link is made between the platform and the TIPP.

**Comment by iyawnis** [comment]
@ostephens  anything on this ?

**Comment by ostephens** [comment]
This is still an issue, but not urgent to fix. Happy for this not to be fixed for 4.2 - more urgent things to do
