### ISSUE TITLE
'Add Entitlements' and 'Link Package' do not display on subscriptionDetails/additionalInfo

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#738]
The links to 'Add Entitlements' and 'Link Package' do not display when you go to the Subscription Details / Additional Information tab

e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/history/3630

**Comment by ianibo** [comment]
I'm getting KB+ test down at the moment, but test branch hasn't been
updated - any ideas why? Was this test URL from test just now? _confused_

On 1 April 2014 12:20, Owen Stephens notifications@github.com wrote:

> The links to 'Add Entitlements' and 'Link Package' do not display when you
> go to the Subscription Details / Additional Information tab
> 
> e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/history/3630
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/738
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
Also getting it down - have just sent email to list to find out why

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
fixed on dev
