### ISSUE TITLE
Add KB+ 4.1-dev branch to Xavier hudson

### ISSUE THREAD

**Issue by ianibo** [k-int/KBPlus#743]
Set up the KB+ 4.1-dev branch to build triggered by git commits on the Xavier copy of Hudson. The build should run unit and functional tests and report build  failures.

**Comment by iyawnis** [comment]
The set up is complete. There are 3 jobs , build, unit test,functional tests. Functional tests also deploy KBPlus for the duration of the tests. Email notifications will be enabled once its confirmed that everything works correctly. Wiki page for setup misses some details for functional tests ,which will be added soon.

**Comment by iyawnis** [comment]
It doesn't look like the is a 'ready' (plugin etc)  way of adding build status info on GitHub, although this is possible for Jenkins. Closing issue, but will look further into it. For now notification emails for failed builds will be sent to Ian and the commiter who broke the build.
