### ISSUE TITLE
Searching on https://kbplus.k-int.com/kbplus/myInstitutions/JISC_Collections/currentTitles is case sensitive

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#750]
E.g. 
https://kbplus.k-int.com/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=all&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=american&validOn=2014-05-07

Finds no hits

https://kbplus.k-int.com/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=all&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=American&validOn=2014-05-07

(uppercase A in 'American') finds 2 hits.

Searching from the 'Search text:' box should be case insensitive

**Comment by iyawnis** [comment]
Assuming I am on the correct page, I cant seem to reproduce this problem. Does it appear on this screen?
![untitled](https://cloud.githubusercontent.com/assets/2336352/2956571/45e8cba4-da92-11e3-80da-392d6d84331e.png)

**Comment by ostephens** [comment]
That's the correct screen, but on all deployed versions of the code I see the problem. 

Compare 
http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=all&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=CUr&validOn=2014-05-13
![screen shot 2014-05-13 at 13 43 39](https://cloud.githubusercontent.com/assets/576174/2957222/44bd428c-da9c-11e3-8513-12938f0f30d0.png)

and

http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=all&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=Cur&validOn=2014-05-13

![screen shot 2014-05-13 at 13 44 26](https://cloud.githubusercontent.com/assets/576174/2957227/6106661c-da9c-11e3-8e5a-3d25def62f7d.png)
