### ISSUE TITLE
Not all packages indexed in ES on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#755]
Not all packages are being successfully indexed in ES on test. Noted after the build today (2014-05-21 12:00)

http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=&sorting=sortname&order=asc&search=yes&_fct%3AendYear%3A2018=&_fct%3AstartYear%3A2013=&_fct%3Acpname%3Agruyter=&_fct%3Acpname%3Ade=
Currently finds only 858 packages
On live 
http://www.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=&sorting=sortname&order=asc&search=yes&_fct%3AendYear%3A2018=&_fct%3AstartYear%3A2013=&_fct%3Acpname%3Agruyter=&_fct%3Acpname%3Ade=
Currently finds 1042

Owen

**Comment by ianibo** [comment]
This this is an operational issue - refer to edina?

**Comment by ostephens** [comment]
No longer an issue. Note to self - future problems in this area should be treated as operational issues unless proved otherwise
