### ISSUE TITLE
Basic/Advanced and Export options should not appear on /packageDetails/previous/ 

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#759]
See also #758 
e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/previous/925
Basic/Advanced and Export options should not show on this page
Also link to 'Advanced'/'Basic' views (e.g. "Includes Expected or Expired titles, switch to the Advanced view to hide them") should not display at top of table of TIPPs on this page

Also link to 'Advanced'/'Basic' views (e.g. "Includes Expected or Expired titles, switch to the Advanced view to hide them") should not display at top of table of TIPPs on this page

![screen shot 2014-05-21 at 16 56 45](https://cloud.githubusercontent.com/assets/576174/3042786/a1a3ecd4-e100-11e3-87fb-debcfdc667eb.png)

**Comment by iyawnis** [comment]
Does this look as you expect? 
![untitled](https://cloud.githubusercontent.com/assets/2336352/3043640/865cf878-e108-11e3-9796-d335ca21c154.png)

**Comment by ostephens** [comment]
Yes that looks right thanks.
