### ISSUE TITLE
Only non-deleted IEs should in SubscriptionDetails advanced view and "Record Status" should not display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#762]
e.g. 
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/8590?mode=advanced

![screen shot 2014-05-21 at 18 13 04](https://cloud.githubusercontent.com/assets/576174/3043899/69c6095e-e10b-11e3-9cc3-68d0befd5f25.png)

Record status should not display
Only IEs that are not Deleted should display in this list, even in the Advanced view

Users can Delete IEs using the 'Delete' action on the right.
Users can re-instate IEs from the 'Add Entitlements' page

So no need to display the status (all should be live/current) and no need for users to be able to edit status

Assigning to Ian in first instance rather than Ioannis just in case there are any gotchas with only displaying the non-deleted items in the advanced view.

**Comment by ianibo** [comment]
Um.. Users can re-instate IEs from the add entitlements page - is that quite right?  Not sure I fully agree with the logic here - especially if we end up with IEs being created when they should be re-instated??

**Comment by ianibo** [comment]
Really don't agree with the logic here, but in the absence of any response, am implementing.
