### ISSUE TITLE
Property related custom text on To Dos

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#765]
Allow addition of custom text to To Dos depending on property being updated.
Specifically add the following custom text:

If accessEndDate updated add custom text:
"The accessEndDate is the date on which a title will leave (or left) a package. If you accept this change the title will be removed from your subscription on this date"

If accessStartDate updated add custom text:
"The accessStartDate is the date on which a title will join (or joined) a package. If you accept this change the title will be added to your subscription on this date"

Currently the messages are like:

"Information about title "Biomedical Materials" changed in package Institute of Physics:NESLI2:Science Platform (Option 1):2014. accessEndDate was updated from "null"(null) to "2014-04-01"(Tue Apr 01 00:00:00 BST 2014). Accept this change to make the same update to your issue entitlement"

Suggest that the final sentence "Accept this change to make the same update ..." is not required if there is custom text for the property present. An idea - could this phrase be the default 'custom text' for properties where no other custom text is defined?

Would be ideal, but not required, if custom text per property could be edited via /admin/manageContentItems

**Comment by iyawnis** [comment]
Is this (currently) only applicable to License and TitleInstancePackagePlatform? Also how important is it to keep track of locale at this time? I have made changes to use messages from Content Items,when available but I cant figure how to keep track of current locale. Message keys are like kbplus.[model name, eg license].change.[attribute name / default]. You can then add keys for any attribute of the model and the message will be picked up.

**Comment by ostephens** [comment]
I think yes - currently only applicable to Licence and TitleInstancePackagePlatform (@ianibbo can confirm)

Not sure about locale - not used currently afaik - possible @ianibbo had idea that user might set locale in profile?

**Comment by iyawnis** [comment]
Content Item key set as kbplus.change.license/tipp.default/property_name. Property name should be the same with the id attribute of html elements (visible with browser dev tools)
