### ISSUE TITLE
Access End date should display on /packageDetails/previous

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#767]
e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/previous/327

In order the user knows when the title left the package, the 'Access End' date should be displayed.

Suggest for consistency this is displayed in same place as in 'advanced' mode on packageDetails/current
![screen shot 2014-05-22 at 16 31 51](https://cloud.githubusercontent.com/assets/576174/3055924/3d074f3e-e1c6-11e3-88e7-085482d12baf.png)

See also #766

**Comment by iyawnis** [comment]
Just a note, this information (and more ) was available when the user used Advanced mode.

![previous](https://cloud.githubusercontent.com/assets/2336352/3056268/40bf8ee0-e1c9-11e3-8335-45cf0a8e36a4.png)
