### ISSUE TITLE
Downloading Docs from test fails

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#769]
E.g. from  http://test.kbplus.ac.uk/kbplus/licenseDetails/index/1
trying to download doc "5:JISC_Collections_NESLi2_Lic_IOP_Institute_of_Physics_NESLi2_2011-2012_01012011-31122012.xml"
http://test.kbplus.ac.uk/kbplus/docstore/index/bf4fd09d-a303-4e04-a13f-faa2a34aeed6

Get error

```
Error 500: Internal Server Error

URI
/kbplus/docstore/index/bf4fd09d-a303-4e04-a13f-faa2a34aeed6
Class
groovy.lang.GroovyRuntimeException
Message
Ambiguous method overloading for method java.util.zip.ZipFile#<init>. Cannot resolve which method to invoke for [null] due to overlapping prototypes between: [class java.io.File] [class java.lang.String]
Trace

    Line | Method
->>  176 | streamResponseDoc in com.k_int.kbplus.DocstoreService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     73 | retrieve          in     ''
|     25 | index . . . . . . in com.k_int.kbplus.DocstoreController
|    195 | doFilter          in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|     65 | doFilter          in com.k_int.kbplus.filter.ApiauthFilter
|   1145 | runWorker . . . . in java.util.concurrent.ThreadPoolExecutor
|    615 | run               in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . in java.lang.Thread
```

Spot checking several docs same issue affects all existing docs I checked.
Uploading a new doc and then trying to download it works OK
e.g. see doc "4913: Screen Shot 2014-05-22 at 16.31.51.png" from http://test.kbplus.ac.uk/kbplus/licenseDetails/index/1 - uploaded that now and downloads OK

Tried before and after running "Docstore migration" (http://test.kbplus.ac.uk/kbplus/admin/docstoreMigrate) - saw same behaviour

**Comment by ianibbo** [comment]
This is because the docs haven't been migrated from docstore I suspect.
Operational issue. Suggest pass back to edina

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
As noted ran the Docstore migration job from the UI and still saw the same issue.
I guess this may mean that migration job not succeeding, or not succeeding in all cases
Have sent email to kbplus-software-development to get Edina to look at success/failure of migration

**Comment by ianibbo** [comment]
It's really hard for us to test as the original automated docstore
migration worked on all our servers. Would like to try and avoid getting
operational issues into github if at all possible.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK closing on here - will await response on mailing list

**Comment by ianibo** [comment]
Hmm.. If you're getting that exception trying to get a doc from docstore,
the migration won't work either. Just run a migration here and all seems to
work OK :/

On 23 May 2014 10:14, Owen Stephens notifications@github.com wrote:

> OK closing on here - will await response on mailing list
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/769#issuecomment-43987492
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
