### ISSUE TITLE
Facets on packageDetails/index are based on tokenised values

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#772]
e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/index

Both Content Provider and Consortia Name facets are based on tokenised values rather - should display non-tokenised values
![screen shot 2014-05-27 at 16 34 17](https://cloud.githubusercontent.com/assets/576174/3093649/7f8e6f58-e5b4-11e3-8dc2-f5af22ebbf7a.png)

Also effects facets on
subscriptionDetails/linkPackage
e.g. http://test.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/8591

Also effects facets of /renewalsSearch
e.g. http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsSearch

**Comment by ianibo** [comment]
NONONO This is because the install instructions haven't been followed. Please remove this issue.

**Comment by julianladisch** [comment]
If you also have this issue: The solution is to properly install elastic search mappings:
https://github.com/k-int/KBPlus/tree/dev-integration/conf_hints/es_mappings
