### ISSUE TITLE
Package search does not sort by title correctly

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#773]
e.g.
http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=&sorting=sortname&order=desc

Doesn't seem to sort alphabetically by package name

![screen shot 2014-05-27 at 16 57 12](https://cloud.githubusercontent.com/assets/576174/3093998/9a9d89c0-e5b7-11e3-9ee5-82c87ce7c7e8.png)

**Comment by ianibo** [comment]
This is sorted on relevance by term frequency

On 27 May 2014 16:57, Owen Stephens notifications@github.com wrote:

> e.g.
> 
> http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=&sorting=sortname&order=desc
> 
> Doesn't seem to sort alphabetically by package name
> 
> [image: screen shot 2014-05-27 at 16 57 12]https://cloud.githubusercontent.com/assets/576174/3093998/9a9d89c0-e5b7-11e3-9ee5-82c87ce7c7e8.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/773
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
(with no criteria it's a natural ordering)

On 27 May 2014 17:08, ianibbo@gmail.com ianibbo@gmail.com wrote:

> This is sorted on relevance by term frequency
> 
> On 27 May 2014 16:57, Owen Stephens notifications@github.com wrote:
> 
> > e.g.
> > 
> > http://test.kbplus.ac.uk/kbplus/packageDetails/index?offset=0&pkgname=&sorting=sortname&order=desc
> > 
> > Doesn't seem to sort alphabetically by package name
> > 
> > [image: screen shot 2014-05-27 at 16 57 12]https://cloud.githubusercontent.com/assets/576174/3093998/9a9d89c0-e5b7-11e3-9ee5-82c87ce7c7e8.png
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/773
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
