### ISSUE TITLE
Login link from public home page goes to wrong screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#777]
On login the user should be directed to the institutional dashboard that is set in their user profile as 'Default Dashboard'

Currently link from public home page (http://test.kbplus.ac.uk/kbplus) goes to http://test.kbplus.ac.uk/kbplus/myInstitutions/dashboard rather than directing user to their default (http://test.kbplus.ac.uk/kbplus/myInstitutions/{institution code}/dashboard)

Think caused by new /views/templates/_loginDiv.gsp - think this should use controller:home + action:index instead of myInstitutions/dashboard

**Comment by iyawnis** [comment]
Yes that is correct, the Login I copied into _loginDiv.gsp was pointing to the wrong place.
