### ISSUE TITLE
Problem adding title to a package (i.e. new TIPP)

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#783]
To add a Title to a Package (i.e. create a new TIPP) you type the title into a box on the Package page
e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/show/301

When you type the title into the "Title To Add" box on this page, there is a lookup that displays titles matching the string you have typed. Up to 10 titles are displayed matching the typed string.

Where the full title of one journal appears as a substring in >10 other titles in some cases the title you wish to add is not in the first 10 titles retrieved in the lookup, and there is no way to force the title you wish to add to appear in the drop down.

e.g. try typing 'Social Science' (which is title http://test.kbplus.ac.uk/kbplus/titleDetails/show/22066) - there are >=10 journals that contain the phrase 'Social Science' as part of their (longer) title.

Screenshot to try and illustrate problem.

![screen shot 2014-06-19 at 15 45 32](https://cloud.githubusercontent.com/assets/576174/3328838/9042c6aa-f7c0-11e3-9254-4a83b72398c3.png)

Solution might be to order retrieved titles by length/alphabetically? Or to allow lookup by an Identifier to allow more precise lookup when needed? Whatever is simpler I think.

**Comment by ianibo** [comment]
THese searches are left anchored and should be sorted by title. This means that in a search for "Social Science" that hit should always come first, and that exactly typing in the title should similarly show that hit first, and then any other titles with extra characters after. Is it possible to say exactly which title was being searched for above, so we can investigate some more.

**Comment by ostephens** [comment]
The search was for http://test.kbplus.ac.uk/kbplus/titleDetails/show/22066 which is just called 'Social Science"

In the screenshot above the titles aren't sorted alphabetically by title (Social Science Japan Journal comes after Social Science Quarterly)

**Comment by ianibbo** [comment]
Ah OK.. Sorting is added in 4.1.1 then and should resolve this.
