### ISSUE TITLE
Uploading a subscriptions or renewals spreadsheet does not link package or create IEs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#784]
Looks like 4.1 has broken this - although don't know why we missed this in testing :(

If I try to upload a Renewals Spreadsheet (e.g. via http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/renewalsUpload) or a Subscription Spreadsheet (e.g. via http://test.kbplus.ac.uk/kbplus/subscriptionImport/importSubscriptionWorksheet/35) it does not successfully create a subscription with the package linked and does not create any IEs

E.g. uploaded 'Renewals Spreadsheet' at 

http://test.kbplus.ac.uk/kbplus/myInstitutions/Staffordshire_University/renewalsUpload

Preview is OK:
![screen shot 2014-06-20 at 12 00 28](https://cloud.githubusercontent.com/assets/576174/3339328/3a8b9ab6-f86a-11e3-8cf3-b9853e66e56e.png)

But resulting subscription has no package or IEs attached http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/8609

**Comment by iyawnis** [comment]
Can you provide me with the spreadsheet you used for the test? I am defining functional test before solving this issue. Thank you

**Comment by ostephens** [comment]
Sending a renewals spreadsheet example to your email as Github doesn't take attachements afaik

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Fixed - caused by changes made to try and deal with post size restrictions. Reset now post restrictions lifted.
