### ISSUE TITLE
Add unit tests to k-int hudson for KB+, and make sure Hudson does CI builds on whatever branch we are actively developing agains

### ISSUE THREAD

**Issue by ianibo** [k-int/KBPlus#785]
To make sure we catch brittle unit tests which break when fixing errors before the deployment hits the edina CI environment.

**Comment by iyawnis** [comment]
Currently Hudson will build and run tests for 4.1-dev and newdev. Email notifications have not been enabled for functional tests, till all the random failures are fixed.
