### ISSUE TITLE
Write SQL to list licences with association with document that doesn't exist

### ISSUE THREAD

**Issue by desreid** [k-int/KBPlus#789]
Described originally by Owen as "We have a situation where some licence records in KB+ are linked to documents that don't exist. This causes errors such as:
(from http://www.kbplus.ac.uk/kbplus/licenseDetails/index/4602 )"

Error 500: Internal Server Error
URI
/kbplus/licenseDetails/index/4602
Class
org.hibernate.ObjectNotFoundException
Message
No row with the given identifier exists: [com.k_int.kbplus.Doc#31]....etc

Requirement from OS:
We need to identify all the situations where this problem is present and fix the records. At the end of the process we'd need a list of affected licences

**Comment by desreid** [comment]
Tangent: In investigating this problem I found a typo in the Doc.groovy domain file. In the mappings, two columns (doc_user_fk and doc_migrated) have been mapped to the same variable 'user'. While the mapping is easily fixed, the effect it's had on what data is now in those columns will need consideration. I believe this version of the Doc.groovy file has been live since Feb, although the typo was committed in December. Owen, I suggest you log a separate ticket for this. (It turns out though that this is not the cause of problem outlined in this ticket.)

**Comment by desreid** [comment]
The cause of this type of error is that the license has rows in the doc_context table that refer to rows in the doc table that don't exist. That is, there are rows in the doc_context table whose foreign key dc_doc_fk does not match up with a corresponding primary key (doc_id) in the doc table. 

In the specific case of license 4602, it has 13 entries in the doc_context table, one is for the 'domain' 'partnersAccess' and refers to dc_doc_fk 31, and no such row exists in the doc table. When the xEditableFieldNote tries to pull in the information for partnersAccess by calling getNote on the License object, it then fails with the "No row with the given identifier exists" that you see in the browser. (The complete XML for the onixpl license for license 4602 actually _is_ in the doc table, it's just this partnersAccess fragment that's missing.) This type of integrity issue can be avoided by enforcing foreign key constraints at the DB level, and I suggest we do this when we migrate to mysql 5.5 (though we'll have to sort out the existing data integrity problems first)

To follow, some SQL that generates the list of affected licenses.

**Comment by ostephens** [comment]
Just to note that the partnersAccess isn't a fragment of the onixpl - it is a separate KB+ licence property, not specifically related to onixpl

**Comment by desreid** [comment]
```
SELECT doc_context.dc_lic_fk, COUNT(doc_context.dc_lic_fk) FROM doc_context LEFT JOIN doc ON doc.doc_id = doc_context.dc_doc_fk WHERE doc.doc_id IS NULL GROUP BY doc_context.dc_lic_fk;
```

This SQL lists all the licenses which will throw the "No row with the given identifier exists" error, and the count of the number of affected rows in the doc_context table. 

Here is the output. There are 334 licenses affected.

+-----------+------------------------------+
| dc_lic_fk | COUNT(doc_context.dc_lic_fk) |
+-----------+------------------------------+
|         4 |                            3 |
|        17 |                            3 |
|        19 |                            3 |
|        22 |                            3 |
|        24 |                            1 |
|        75 |                            3 |
|        78 |                            3 |
|        82 |                            1 |
|        98 |                            3 |
|       100 |                            3 |
|       107 |                            3 |
|       109 |                            3 |
|       118 |                            3 |
|       124 |                            1 |
|       125 |                            3 |
|       132 |                            1 |
|       154 |                            3 |
|       168 |                            1 |
|       169 |                            3 |
|       174 |                            3 |
|       176 |                            1 |
|       223 |                            3 |
|       225 |                            1 |
|       260 |                            3 |
|       264 |                            1 |
|       266 |                            3 |
|       521 |                            1 |
|       522 |                            1 |
|       533 |                            1 |
|       534 |                            1 |
|       539 |                            3 |
|       543 |                            1 |
|       544 |                            1 |
|       560 |                            1 |
|       595 |                            1 |
|       596 |                            1 |
|       600 |                            3 |
|       607 |                            3 |
|       673 |                            1 |
|       680 |                            3 |
|       682 |                            1 |
|       690 |                            1 |
|       693 |                            1 |
|       699 |                            1 |
|       728 |                            1 |
|       731 |                            3 |
|       734 |                            1 |
|       751 |                            1 |
|       756 |                            1 |
|       761 |                            3 |
|       769 |                            1 |
|       794 |                            1 |
|       796 |                            1 |
|       803 |                            1 |
|       805 |                            1 |
|       806 |                            1 |
|       811 |                            3 |
|       835 |                            1 |
|       850 |                            1 |
|       854 |                            1 |
|       874 |                            1 |
|       879 |                            1 |
|       884 |                            1 |
|       917 |                            1 |
|       967 |                            1 |
|       969 |                            1 |
|       981 |                            1 |
|       983 |                            1 |
|       984 |                            1 |
|       987 |                            1 |
|       994 |                            1 |
|       997 |                            1 |
|      1005 |                            1 |
|      1013 |                            3 |
|      1014 |                            1 |
|      1030 |                            1 |
|      1039 |                            1 |
|      1044 |                            3 |
|      1103 |                            1 |
|      1114 |                            2 |
|      1120 |                            3 |
|      1121 |                            1 |
|      1123 |                            1 |
|      1130 |                            2 |
|      1160 |                            1 |
|      1161 |                            1 |
|      1162 |                            1 |
|      1193 |                            3 |
|      1194 |                            1 |
|      1200 |                            1 |
|      1201 |                            1 |
|      1204 |                            1 |
|      1274 |                            3 |
|      1296 |                            1 |
|      1343 |                            1 |
|      1344 |                            1 |
|      1349 |                            1 |
|      1351 |                            1 |
|      1354 |                            1 |
|      1368 |                            1 |
|      1379 |                            1 |
|      1479 |                            1 |
|      1488 |                            1 |
|      1497 |                            1 |
|      1501 |                            1 |
|      1526 |                            1 |
|      1546 |                            3 |
|      1557 |                            1 |
|      1558 |                            1 |
|      1559 |                            1 |
|      1585 |                            1 |
|      1597 |                            3 |
|      1605 |                            3 |
|      1623 |                            1 |
|      1635 |                            1 |
|      1638 |                            1 |
|      1672 |                            1 |
|      1693 |                            1 |
|      1696 |                            1 |
|      1705 |                            3 |
|      1708 |                            1 |
|      1712 |                            1 |
|      1742 |                            1 |
|      1768 |                            2 |
|      1781 |                            1 |
|      1783 |                            1 |
|      1793 |                            1 |
|      1816 |                            3 |
|      1827 |                            1 |
|      1834 |                            1 |
|      1871 |                            3 |
|      1876 |                            1 |
|      1879 |                            1 |
|      1900 |                            2 |
|      1913 |                            1 |
|      1915 |                            3 |
|      1922 |                            1 |
|      1956 |                            1 |
|      1978 |                            1 |
|      1979 |                            1 |
|      1989 |                            3 |
|      1999 |                            1 |
|      2035 |                            1 |
|      2059 |                            1 |
|      2072 |                            1 |
|      2082 |                            1 |
|      2099 |                            2 |
|      2115 |                            1 |
|      2116 |                            2 |
|      2149 |                            1 |
|      2194 |                            1 |
|      2226 |                            1 |
|      2231 |                            1 |
|      2274 |                            1 |
|      2278 |                            1 |
|      2299 |                            1 |
|      2310 |                            3 |
|      2321 |                            1 |
|      2356 |                            1 |
|      2358 |                            1 |
|      2389 |                            1 |
|      2390 |                            1 |
|      2414 |                            3 |
|      2424 |                            1 |
|      2429 |                            1 |
|      2447 |                            1 |
|      2449 |                            2 |
|      2466 |                            1 |
|      2490 |                            1 |
|      2498 |                            1 |
|      2522 |                            1 |
|      2531 |                            2 |
|      2534 |                            1 |
|      2553 |                            1 |
|      2585 |                            1 |
|      2605 |                            3 |
|      2608 |                            1 |
|      2618 |                            3 |
|      2639 |                            1 |
|      2673 |                            1 |
|      2716 |                            3 |
|      2719 |                            3 |
|      2747 |                            3 |
|      2757 |                            1 |
|      2779 |                            1 |
|      2844 |                            1 |
|      2848 |                            1 |
|      2869 |                            1 |
|      2871 |                            2 |
|      2878 |                            3 |
|      2900 |                            1 |
|      2917 |                            1 |
|      2918 |                            2 |
|      2926 |                            3 |
|      2944 |                            1 |
|      2956 |                            1 |
|      2957 |                            1 |
|      2959 |                            1 |
|      2980 |                            1 |
|      2988 |                            3 |
|      3000 |                            1 |
|      3024 |                            1 |
|      3035 |                            3 |
|      3062 |                            1 |
|      3064 |                            1 |
|      3077 |                            1 |
|      3086 |                            1 |
|      3093 |                            1 |
|      3127 |                            1 |
|      3129 |                            1 |
|      3134 |                            1 |
|      3169 |                            3 |
|      3176 |                            2 |
|      3184 |                            1 |
|      3199 |                            1 |
|      3202 |                            1 |
|      3218 |                            1 |
|      3223 |                            3 |
|      3224 |                            1 |
|      3242 |                            1 |
|      3262 |                            1 |
|      3264 |                            2 |
|      3274 |                            3 |
|      3283 |                            2 |
|      3284 |                            1 |
|      3308 |                            1 |
|      3317 |                            1 |
|      3327 |                            1 |
|      3345 |                            1 |
|      3354 |                            1 |
|      3359 |                            1 |
|      3378 |                            3 |
|      3396 |                            1 |
|      3419 |                            1 |
|      3421 |                            2 |
|      3466 |                            1 |
|      3467 |                            1 |
|      3472 |                            1 |
|      3505 |                            3 |
|      3507 |                            2 |
|      3520 |                            3 |
|      3525 |                            1 |
|      3530 |                            1 |
|      3591 |                            1 |
|      3604 |                            1 |
|      3616 |                            2 |
|      3629 |                            1 |
|      3644 |                            1 |
|      3649 |                            2 |
|      3659 |                            1 |
|      3662 |                            1 |
|      3675 |                            1 |
|      3677 |                            2 |
|      3684 |                            1 |
|      3706 |                            1 |
|      3711 |                            1 |
|      3741 |                            1 |
|      3751 |                            3 |
|      3775 |                            2 |
|      3787 |                            3 |
|      3796 |                            1 |
|      3797 |                            1 |
|      3805 |                            1 |
|      3830 |                            1 |
|      3832 |                            2 |
|      3839 |                            3 |
|      3861 |                            1 |
|      3894 |                            1 |
|      3896 |                            1 |
|      3915 |                            1 |
|      3928 |                            1 |
|      4003 |                            3 |
|      4011 |                            1 |
|      4014 |                            1 |
|      4031 |                            1 |
|      4033 |                            2 |
|      4040 |                            3 |
|      4086 |                            1 |
|      4124 |                            1 |
|      4134 |                            1 |
|      4162 |                            1 |
|      4175 |                            1 |
|      4192 |                            3 |
|      4197 |                            1 |
|      4220 |                            3 |
|      4221 |                            1 |
|      4229 |                            1 |
|      4233 |                            1 |
|      4253 |                            1 |
|      4266 |                            1 |
|      4271 |                            1 |
|      4272 |                            1 |
|      4297 |                            1 |
|      4301 |                            1 |
|      4317 |                            3 |
|      4321 |                            2 |
|      4322 |                            1 |
|      4344 |                            1 |
|      4348 |                            1 |
|      4381 |                            2 |
|      4389 |                            3 |
|      4399 |                            1 |
|      4402 |                            1 |
|      4431 |                            1 |
|      4445 |                            1 |
|      4458 |                            1 |
|      4462 |                            1 |
|      4481 |                            2 |
|      4496 |                            1 |
|      4513 |                            1 |
|      4520 |                            1 |
|      4536 |                            1 |
|      4618 |                            2 |
|      4619 |                            3 |
|      4633 |                            1 |
|      4663 |                            3 |
|      4690 |                            2 |
|      4726 |                            3 |
|      4735 |                            1 |
|      4753 |                            2 |
|      4756 |                            3 |
|      4770 |                            1 |
|      4795 |                            2 |
|      4801 |                            1 |
|      4804 |                            3 |
|      4865 |                            3 |
|      4876 |                            1 |
|      4888 |                            1 |
|      4894 |                            3 |
|      4921 |                            1 |
|      4925 |                            3 |
|      4973 |                            1 |
|      4984 |                            1 |
|      5016 |                            1 |
+-----------+------------------------------+

**Comment by desreid** [comment]
RE partnersAccess is not part of OnixPL doc - noted, thanks Owen. 
Can you see a way to untangle this Owen? With your understanding of the data and an overview of how it's input, you are probably best placed. Going through 334 by hand would seem epic.

**Comment by ostephens** [comment]
I'd definitely consult @ianibo but there seem to be two obvious options to me:

1) Remove all the 'hanging' doc_context records
2) For each of the 'hanging' doc_context create a new doc record with an explanatory note (e.g. "This value has been deleted")

It would be worth including a check of the doc_context status and licence status when we report - because 'deleted' is possible status for  both of these. While it doesn't change the options, we don't really need to worry about inserting new doc records where the record has already been marked as 'deleted'.

Either way we'd want to inform the affected institutions to prompt them to check any non-deleted licence records that have been affected so we need to check this information anyway.

The status is a value which is de-referenced by the refdata_value table - so you need to go via that table to establish the status of the licence and doc_context if that makes sense

**Comment by ostephens** [comment]
NB For option (2) above - it would need to be a separate doc record for each doc_context even though many of the existing doc_context records affected point to the same doc_id - this is incorrect as far as I know and they should really point at different doc_id - so if we were to create new doc records to resolve this issue we'd need one per doc_context.

**Comment by ianibo** [comment]
OOI why is that incorrect?

On 11 July 2014 12:10, Owen Stephens notifications@github.com wrote:

> NB For option (2) above - it would need to be a separate doc record for
> each doc_context even though many of the existing doc_context records
> affected point to the same doc_id - this is incorrect as far as I know and
> they should really point at different doc_id - so if we were to create new
> doc records to resolve this issue we'd need one per doc_context.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/789#issuecomment-48718986.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ostephens** [comment]
Perhaps that was too sweeping, but I suspect mostly incorrect - due to issue #741 now corrected.

**Comment by ianibbo** [comment]
Right - yes - specific license behaviour is at a level below the generic
structure

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by desreid** [comment]
Update:
Of the licenses found, 26 have a status of 'Deleted', and the rest are 'Current'
Query used follows:

```
SELECT doc_context.dc_lic_fk, st.rdv_value, COUNT(doc_context.dc_lic_fk) FROM doc_context LEFT JOIN doc ON doc.doc_id = doc_context.dc_doc_fk LEFT JOIN license l ON l.lic_id = doc_context.dc_lic_fk LEFT JOIN refdata_value st ON l.lic_status_rv_fk = st.rdv_id WHERE doc.doc_id IS NULL AND st.rdv_value != 'Current' GROUP BY doc_context.dc_lic_fk;
```

**Comment by desreid** [comment]
Update:
The status of all the doc_context rows concerned is null. That is the dc_status_fk is null. What does that indicate? 

query used:

```
SELECT doc_context.dc_lic_fk, doc_context.dc_status_fk, doc_status.rdv_value FROM doc_context LEFT JOIN doc ON doc.doc_id = doc_context.dc_doc_fk LEFT JOIN refdata_value doc_status ON doc_context.dc_status_fk = doc_status.rdv_id WHERE doc.doc_id IS NULL;
```

**Comment by ostephens** [comment]
I guess that literally it means no-one has explicitly stated the status and so viewed as unknown/unset.

In practice however, the implicit assumption would be that these are 'current' (on the basis they haven't been set to 'deleted'.

Now you raise this, I suspect we don't actually use the doc_context status - so telling you to look at that was probably a bum-steer from me - sorry

**Comment by ostephens** [comment]
Would be good to get this issue resolved. @desreid @ianibbo any views on whether the correct approach is either:

1) Remove all the 'hanging' doc_context records
2) For each of the 'hanging' doc_context create a new doc record with an explanatory note (e.g. "This value has been deleted")

Are there other options?
(1) seems simpler?

Owen

**Comment by desreid** [comment]
Another option (from a logical perspective at least) would be to delete the problem licenses altogether. I'd guess that you wouldn't want to do that. 1) is certainly the simplest option. Shall I start writing some SQL to do that?

**Comment by ostephens** [comment]
Thanks Des - we definitely need to preserve the licences that don't have a status of 'deleted'.
If you could write the relevant SQL for (1) then we can try it on test to check it has the desired effect.

**Comment by desreid** [comment]
OK, so just to be sure what I'm doing here.... I'm writing SQL to delete rows from the doc_context table. The rows to be deleted will be those who have a foreign key dc_doc_fk which doesn't have a corresponding doc_id in the doc table. Correct? That corresponds to the 601 rows returned by this query:

```
SELECT dc.dc_id FROM doc_context dc LEFT JOIN doc d ON dc.dc_doc_fk = d.doc_id WHERE dc.dc_doc_fk IS NOT NULL AND d.doc_id IS NULL;
```

**Comment by desreid** [comment]
The corresponding (destructive) delete for the above would be 

```
DELETE FROM doc_context WHERE doc_context.dc_id IN (SELECT dc.dc_id FROM doc_context dc LEFT JOIN doc d ON dc.dc_doc_fk = d.doc_id WHERE dc.dc_doc_fk IS NOT NULL AND d.doc_id IS NULL)
```

If you give the nod Owen I can run this on dev.

**Comment by ostephens** [comment]
OK - lets try this on dev and see what happens

**Comment by desreid** [comment]
OK, that's done on dev. 601 rows deleted. Seems to have resolved the issue affecting 4602, at least. Let me know if all looks well. 

I had to correct the delete query slightly to:

```
DELETE FROM dc USING doc_context dc LEFT JOIN doc d ON dc.dc_doc_fk = d.doc_id WHERE dc.dc_doc_fk IS NOT NULL AND d.doc_id IS NULL;
```

**Comment by ostephens** [comment]
I've done some checking and that seems to have resolved the issue for those affected licences, and as far as I can tell has not caused any new issues.

Please go ahead and run this on test, demo and live. Before we do the delete on live can we do an equivalent select statement for all fields in doc_context and paste the results here so we have a list of those affected licences?

Thanks

Owen

**Comment by desreid** [comment]
OK, that's now done on test and demo. Oddly, far fewer rows were deleted on test. 235 rows, compared to 601 on dev and demo. Any idea why that might be? test and dev should be copies of live.

**Comment by desreid** [comment]
On live there are 429 affected licenses, listed below, and 601 rows would be deleted from doc_context. 

mysql> SELECT doc_context.dc_lic_fk, COUNT(doc_context.dc_lic_fk) FROM doc_context LEFT JOIN doc ON doc.doc_id = doc_context.dc_doc_fk WHERE doc.doc_id IS NULL GROUP BY doc_context.dc_lic_fk;
+-----------+------------------------------+
| dc_lic_fk | COUNT(doc_context.dc_lic_fk) |
+-----------+------------------------------+
|         4 |                            3 | 
|         6 |                            1 | 
|        17 |                            3 | 
|        19 |                            3 | 
|        22 |                            3 | 
|        23 |                            1 | 
|        24 |                            1 | 
|        75 |                            3 | 
|        78 |                            3 | 
|        79 |                            1 | 
|        82 |                            1 | 
|        98 |                            3 | 
|       100 |                            3 | 
|       103 |                            1 | 
|       107 |                            3 | 
|       109 |                            3 | 
|       114 |                            1 | 
|       118 |                            3 | 
|       124 |                            1 | 
|       125 |                            3 | 
|       128 |                            1 | 
|       132 |                            1 | 
|       135 |                            1 | 
|       139 |                            1 | 
|       146 |                            1 | 
|       154 |                            3 | 
|       168 |                            1 | 
|       169 |                            3 | 
|       174 |                            3 | 
|       176 |                            1 | 
|       180 |                            1 | 
|       213 |                            1 | 
|       223 |                            3 | 
|       225 |                            1 | 
|       260 |                            3 | 
|       264 |                            1 | 
|       266 |                            3 | 
|       521 |                            1 | 
|       522 |                            1 | 
|       529 |                            1 | 
|       533 |                            1 | 
|       534 |                            1 | 
|       539 |                            3 | 
|       543 |                            1 | 
|       544 |                            1 | 
|       560 |                            1 | 
|       594 |                            1 | 
|       595 |                            1 | 
|       596 |                            1 | 
|       600 |                            3 | 
|       607 |                            3 | 
|       614 |                            1 | 
|       618 |                            1 | 
|       665 |                            1 | 
|       667 |                            1 | 
|       673 |                            1 | 
|       680 |                            3 | 
|       682 |                            1 | 
|       690 |                            1 | 
|       693 |                            1 | 
|       699 |                            1 | 
|       728 |                            1 | 
|       731 |                            3 | 
|       734 |                            1 | 
|       751 |                            1 | 
|       756 |                            1 | 
|       761 |                            3 | 
|       769 |                            1 | 
|       789 |                            1 | 
|       794 |                            1 | 
|       795 |                            1 | 
|       796 |                            1 | 
|       801 |                            1 | 
|       803 |                            1 | 
|       805 |                            1 | 
|       806 |                            1 | 
|       811 |                            3 | 
|       835 |                            1 | 
|       849 |                            1 | 
|       850 |                            1 | 
|       854 |                            1 | 
|       874 |                            1 | 
|       879 |                            1 | 
|       883 |                            1 | 
|       884 |                            1 | 
|       916 |                            1 | 
|       917 |                            1 | 
|       947 |                            1 | 
|       967 |                            1 | 
|       968 |                            1 | 
|       969 |                            1 | 
|       981 |                            1 | 
|       983 |                            1 | 
|       984 |                            1 | 
|       985 |                            1 | 
|       987 |                            1 | 
|       990 |                            1 | 
|       994 |                            1 | 
|       997 |                            1 | 
|      1005 |                            1 | 
|      1013 |                            3 | 
|      1014 |                            1 | 
|      1030 |                            1 | 
|      1039 |                            1 | 
|      1044 |                            3 | 
|      1103 |                            1 | 
|      1114 |                            2 | 
|      1120 |                            3 | 
|      1121 |                            1 | 
|      1123 |                            1 | 
|      1130 |                            2 | 
|      1160 |                            1 | 
|      1161 |                            1 | 
|      1162 |                            1 | 
|      1193 |                            3 | 
|      1194 |                            1 | 
|      1200 |                            1 | 
|      1201 |                            1 | 
|      1204 |                            1 | 
|      1274 |                            3 | 
|      1296 |                            1 | 
|      1343 |                            1 | 
|      1344 |                            1 | 
|      1349 |                            1 | 
|      1351 |                            1 | 
|      1354 |                            1 | 
|      1368 |                            1 | 
|      1379 |                            1 | 
|      1479 |                            1 | 
|      1488 |                            1 | 
|      1495 |                            1 | 
|      1497 |                            1 | 
|      1501 |                            1 | 
|      1521 |                            1 | 
|      1526 |                            1 | 
|      1546 |                            3 | 
|      1552 |                            1 | 
|      1557 |                            1 | 
|      1558 |                            1 | 
|      1559 |                            1 | 
|      1585 |                            1 | 
|      1597 |                            3 | 
|      1605 |                            3 | 
|      1623 |                            1 | 
|      1631 |                            1 | 
|      1635 |                            1 | 
|      1638 |                            1 | 
|      1672 |                            1 | 
|      1681 |                            1 | 
|      1693 |                            1 | 
|      1696 |                            1 | 
|      1705 |                            3 | 
|      1708 |                            1 | 
|      1712 |                            1 | 
|      1737 |                            1 | 
|      1742 |                            1 | 
|      1768 |                            2 | 
|      1780 |                            1 | 
|      1781 |                            1 | 
|      1783 |                            1 | 
|      1788 |                            1 | 
|      1793 |                            1 | 
|      1816 |                            3 | 
|      1824 |                            1 | 
|      1827 |                            1 | 
|      1834 |                            1 | 
|      1871 |                            3 | 
|      1875 |                            1 | 
|      1876 |                            1 | 
|      1879 |                            1 | 
|      1900 |                            2 | 
|      1913 |                            1 | 
|      1915 |                            3 | 
|      1920 |                            1 | 
|      1922 |                            1 | 
|      1951 |                            1 | 
|      1956 |                            1 | 
|      1978 |                            1 | 
|      1979 |                            1 | 
|      1989 |                            3 | 
|      1995 |                            1 | 
|      1999 |                            1 | 
|      2029 |                            1 | 
|      2035 |                            1 | 
|      2059 |                            1 | 
|      2072 |                            1 | 
|      2077 |                            1 | 
|      2082 |                            1 | 
|      2099 |                            2 | 
|      2115 |                            1 | 
|      2116 |                            2 | 
|      2145 |                            1 | 
|      2149 |                            1 | 
|      2194 |                            1 | 
|      2223 |                            1 | 
|      2226 |                            1 | 
|      2231 |                            1 | 
|      2271 |                            1 | 
|      2274 |                            1 | 
|      2278 |                            1 | 
|      2299 |                            1 | 
|      2310 |                            3 | 
|      2314 |                            1 | 
|      2321 |                            1 | 
|      2356 |                            1 | 
|      2358 |                            1 | 
|      2388 |                            1 | 
|      2389 |                            1 | 
|      2390 |                            1 | 
|      2414 |                            3 | 
|      2424 |                            1 | 
|      2429 |                            1 | 
|      2447 |                            1 | 
|      2449 |                            2 | 
|      2466 |                            1 | 
|      2490 |                            1 | 
|      2497 |                            1 | 
|      2498 |                            1 | 
|      2506 |                            1 | 
|      2522 |                            1 | 
|      2531 |                            2 | 
|      2534 |                            1 | 
|      2553 |                            1 | 
|      2573 |                            1 | 
|      2585 |                            1 | 
|      2605 |                            3 | 
|      2608 |                            1 | 
|      2618 |                            3 | 
|      2629 |                            1 | 
|      2639 |                            1 | 
|      2672 |                            1 | 
|      2673 |                            1 | 
|      2716 |                            3 | 
|      2719 |                            3 | 
|      2747 |                            3 | 
|      2757 |                            1 | 
|      2774 |                            1 | 
|      2779 |                            1 | 
|      2842 |                            1 | 
|      2844 |                            1 | 
|      2848 |                            1 | 
|      2869 |                            1 | 
|      2871 |                            2 | 
|      2878 |                            3 | 
|      2894 |                            1 | 
|      2900 |                            1 | 
|      2917 |                            1 | 
|      2918 |                            2 | 
|      2926 |                            3 | 
|      2930 |                            1 | 
|      2944 |                            1 | 
|      2954 |                            1 | 
|      2956 |                            1 | 
|      2957 |                            1 | 
|      2959 |                            1 | 
|      2980 |                            1 | 
|      2988 |                            3 | 
|      2993 |                            1 | 
|      3000 |                            1 | 
|      3024 |                            1 | 
|      3035 |                            3 | 
|      3062 |                            1 | 
|      3064 |                            1 | 
|      3066 |                            1 | 
|      3077 |                            1 | 
|      3084 |                            1 | 
|      3086 |                            1 | 
|      3093 |                            1 | 
|      3127 |                            1 | 
|      3129 |                            1 | 
|      3134 |                            1 | 
|      3169 |                            3 | 
|      3176 |                            2 | 
|      3184 |                            1 | 
|      3197 |                            1 | 
|      3199 |                            1 | 
|      3202 |                            1 | 
|      3218 |                            1 | 
|      3223 |                            3 | 
|      3224 |                            1 | 
|      3236 |                            1 | 
|      3242 |                            1 | 
|      3262 |                            1 | 
|      3264 |                            2 | 
|      3274 |                            3 | 
|      3283 |                            2 | 
|      3284 |                            1 | 
|      3308 |                            1 | 
|      3317 |                            1 | 
|      3327 |                            1 | 
|      3345 |                            1 | 
|      3353 |                            1 | 
|      3354 |                            1 | 
|      3359 |                            1 | 
|      3378 |                            3 | 
|      3396 |                            1 | 
|      3419 |                            1 | 
|      3421 |                            2 | 
|      3464 |                            1 | 
|      3466 |                            1 | 
|      3467 |                            1 | 
|      3472 |                            1 | 
|      3505 |                            3 | 
|      3507 |                            2 | 
|      3520 |                            3 | 
|      3523 |                            1 | 
|      3525 |                            1 | 
|      3530 |                            1 | 
|      3562 |                            1 | 
|      3591 |                            1 | 
|      3600 |                            1 | 
|      3604 |                            1 | 
|      3616 |                            2 | 
|      3625 |                            1 | 
|      3629 |                            1 | 
|      3644 |                            1 | 
|      3649 |                            2 | 
|      3657 |                            1 | 
|      3659 |                            1 | 
|      3662 |                            1 | 
|      3675 |                            1 | 
|      3677 |                            2 | 
|      3684 |                            1 | 
|      3703 |                            1 | 
|      3706 |                            1 | 
|      3711 |                            1 | 
|      3738 |                            1 | 
|      3741 |                            1 | 
|      3751 |                            3 | 
|      3775 |                            2 | 
|      3787 |                            3 | 
|      3791 |                            1 | 
|      3796 |                            1 | 
|      3797 |                            1 | 
|      3805 |                            1 | 
|      3830 |                            1 | 
|      3832 |                            2 | 
|      3839 |                            3 | 
|      3861 |                            1 | 
|      3894 |                            1 | 
|      3896 |                            1 | 
|      3915 |                            1 | 
|      3923 |                            1 | 
|      3928 |                            1 | 
|      3965 |                            1 | 
|      4003 |                            3 | 
|      4008 |                            1 | 
|      4011 |                            1 | 
|      4014 |                            1 | 
|      4031 |                            1 | 
|      4033 |                            2 | 
|      4040 |                            3 | 
|      4066 |                            1 | 
|      4086 |                            1 | 
|      4099 |                            1 | 
|      4124 |                            1 | 
|      4133 |                            1 | 
|      4134 |                            1 | 
|      4162 |                            1 | 
|      4172 |                            1 | 
|      4175 |                            1 | 
|      4192 |                            3 | 
|      4196 |                            1 | 
|      4197 |                            1 | 
|      4220 |                            3 | 
|      4221 |                            1 | 
|      4227 |                            1 | 
|      4229 |                            1 | 
|      4233 |                            1 | 
|      4253 |                            1 | 
|      4263 |                            1 | 
|      4266 |                            1 | 
|      4271 |                            1 | 
|      4272 |                            1 | 
|      4297 |                            1 | 
|      4301 |                            1 | 
|      4317 |                            3 | 
|      4321 |                            2 | 
|      4322 |                            1 | 
|      4341 |                            1 | 
|      4344 |                            1 | 
|      4348 |                            1 | 
|      4381 |                            2 | 
|      4389 |                            3 | 
|      4399 |                            1 | 
|      4402 |                            1 | 
|      4417 |                            1 | 
|      4430 |                            1 | 
|      4431 |                            1 | 
|      4445 |                            1 | 
|      4456 |                            1 | 
|      4458 |                            1 | 
|      4462 |                            1 | 
|      4481 |                            2 | 
|      4496 |                            1 | 
|      4513 |                            1 | 
|      4520 |                            1 | 
|      4536 |                            1 | 
|      4602 |                            1 | 
|      4618 |                            2 | 
|      4619 |                            3 | 
|      4626 |                            1 | 
|      4633 |                            1 | 
|      4663 |                            3 | 
|      4668 |                            1 | 
|      4690 |                            2 | 
|      4702 |                            1 | 
|      4726 |                            3 | 
|      4729 |                            1 | 
|      4735 |                            1 | 
|      4753 |                            2 | 
|      4756 |                            3 | 
|      4762 |                            1 | 
|      4770 |                            1 | 
|      4795 |                            2 | 
|      4801 |                            1 | 
|      4804 |                            3 | 
|      4823 |                            1 | 
|      4865 |                            3 | 
|      4876 |                            1 | 
|      4888 |                            1 | 
|      4894 |                            3 | 
|      4902 |                            1 | 
|      4921 |                            1 | 
|      4925 |                            3 | 
|      4933 |                            1 | 
|      4973 |                            1 | 
|      4984 |                            1 | 
|      5016 |                            1 | 
+-----------+------------------------------+
429 rows in set (0.25 sec)

**Comment by desreid** [comment]
I have now run the delete on live too.

**Comment by ostephens** [comment]
Thanks Des - this seems to have resolved the issue
