### ISSUE TITLE
Write SQL to list all titles which are attached to the same ISSN or eISSN

### ISSUE THREAD

**Issue by desreid** [k-int/KBPlus#794]

**Comment by desreid** [comment]
The SQL I've written for this returns 427 rows. Due to the number of results I won't paste here, but does that sound right? Again, this SQL isn't particularly fast, but fine for one off reports. 

```
 SELECT * FROM (SELECT i.id_value, COUNT(i.id_value) AS duplicatecount FROM title_instance ti LEFT JOIN identifier_occurrence ido ON ti.ti_id = ido.io_ti_fk LEFT JOIN identifier i ON i.id_id = ido.io_canonical_id LEFT JOIN identifier_namespace idn ON idn.idns_id = i.id_ns_fk WHERE (idn.idns_ns = 'eISSN' OR idn.idns_ns = 'ISSN') GROUP BY i.id_value) duplicateISSNs WHERE duplicatecount > 1 ORDER BY duplicatecount DESC;
```

An oddity here is that, for example, 1750-4732 has three corresponding titles in title_instance,  one of which is via a different instance of 1750-4732 in the identifier table. In other words, the identifier 1750-4732 occurs twice in the identifier table. Does the identifier table need a unique constraint on the id_value?

A sample of the output: 

ISSN | number of occurences
| 1750-4732        |              3 | 
| 1753-6561        |              3 | 
| 1754-1611        |              3 | 
| 1754-6834        |              3 | 
| 1754-9493        |              3 | 
| 1755-1536        |              3 | 
| 1755-7682        |              3 | 
| 1755-8166        |              3 | 
| 1755-8417        |              3 | 
| 1755-8794        |              3 | 
| 1753-4631        |              3 | 
| 1753-2000        |              3 | 
| 1750-9378        |              3 | 
| 1751-0147        |              3 | 
| 1751-0473        |              3 | 
| 1751-0759        |              3 | 
| 1752-0509        |              3 |

**Comment by ianibbo** [comment]
A unique constraint on ID and ID Type might not be a bad idea (On id alone
is not a good idea - world ending paradoxes may ensue)  - not entirely sure
how this has happened tho if they have the same type - as this should be
enforced at the app level.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
The occurrence of the repeated identifiers is due to them appearing in different namespaces (ISSN and eISSN).

This is a problem, but I don't think the solution is straightforward. It is valid for the same IDs to appear in different namespaces of course - and generally this is not a problem.
However ISSN is a bit of a unique case in that while we support two namespaces ISSN and eISSN, actually in reality there is a single namespace (ISSN) and it just happens that some refer to the electronic version and some refer to the print version of a journal.

The duplication arises when the data managers are given one file where it is claimed that the identifier is an ISSN for the print copy, and another file where it is claimed the same ISSN is for the e copy.

I don't know what the solution is, but while a unique constraint for ID+ID Type combo might be sensible, it wouldn't actually solve the problem - these duplications could still occur.

**Comment by ostephens** [comment]
In terms of the report - this looks OK, but the report needs to list the actual titles in question (suggest journal title (title.ti_title) + KB+ Title ID (title.ti_id).

I think it would be OK to have one row per title (based on ti_id) and repeat the identifiers across multiple rows

**Comment by desreid** [comment]
RE uniqueness. I see now that, as Ian says, the constraint should be uniqueness across id and id type, not on id alone. What you say Owen is that 

> It is valid for the same IDs to appear in different namespaces of course

But in this case the same ID / namespace combination appear twice. 

The data for 1750-4732 is in three places, one for eISSN and two for ISSN

```
|  9528 | osteopathic medicine and primary care | 1750-4732 | eISSN   | 
| 21592 | osteopathic medicine and primary care | 1750-4732 | ISSN    | 
| 21593 | osteopathic medicine and primary care | 1750-4732 | ISSN    | 
```

We should add the constraint as soon as the data is fixed, because you need to know how this is happening. Ian says the app should prevent it, so is data being edited outside the app?

**Comment by ostephens** [comment]
Checking the system - these three Identifier Occurrences point to two Identifiers - so the uniqueness across identifier+id type is not being broken

|  9528 | osteopathic medicine and primary care | 1750-4732 | eISSN   | 
Identifier: 28185
IO: 28197

| 21592 | osteopathic medicine and primary care | 1750-4732 | ISSN    | 
Identifier: 62017
IO: 58884

| 21593 | osteopathic medicine and primary care | 1750-4732 | ISSN    | 
Identifier: 62017
IO: 58885

**Comment by desreid** [comment]
Hmm, Ok I'm with you. I can see how it's happening now. Are we in agreement that should be prevented, though - or am I misunderstanding?

**Comment by iyawnis** [comment]
I am assuming these tickets no longer need to be open ? #793  #792 as well?
