### ISSUE TITLE
Write SQL to list 'floating titles'

### ISSUE THREAD

**Issue by desreid** [k-int/KBPlus#795]
As defined by Christina:

> should be a "floating title" list - which should be titles which are not linked to any packages

**Comment by desreid** [comment]
The query for this is

```
SELECT ti.ti_id, ti_title FROM title_instance ti LEFT JOIN title_instance_package_platform tipp ON ti.ti_id = tipp.tipp_ti_fk LEFT JOIN package p ON tipp.tipp_pkg_fk = p.pkg_id WHERE p.pkg_id IS NULL;
```

This returns 1403 rows, and It turns out that all these titles aren't connected to a tipp or, therefore, a package.

**Comment by desreid** [comment]
Have emailed the results to Christina

**Comment by ostephens** [comment]
As I think you realised, but just for completeness, titles aren't connected directly to a Package. Titles can have TIPPs, which are connected to a Package. A query for Titles without TIPPs is sufficient, the additional check for a package should not be required

**Comment by desreid** [comment]
Yes, thanks I realised that must be the case when I saw the results.
