### ISSUE TITLE
Adjust lefthand col in Package display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#8]
http://projects.k-int.com/kbplus/package/show/19 - maybe left align the lefthand col and make narrower for readability?

**Comment by ianibo** [comment]
tricky.. i think it's the entry "Forschende Komplementrmedizin und Klassische Naturheilkunde / Research in Complementary and Classical Natural Medicine" thats causes the odd alignment. I _think_ the right alignment works best, but the oversized title causes it to look a bit odd. 

Having said that.. completely happy to change it if you direct me to do so.. Want to suggest a hard-wired column alignment (50/50?) and specify left align?

Or specify a different layout - 2 lines, title above, next line split into platform?

**Comment by ostephens** [comment]
Can we limit the lefthand col to be at max 50% of table? Think that would probably do the trick?

**Comment by ianibo** [comment]
Fixed in M3
