### ISSUE TITLE
Title Instances showing incorrect 'To date'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#80]
e.g. http://knowplus.edina.ac.uk/kbplus/titleInstance/show/9636
This title runs from 1996 to current - i.e. no end date specified in col 7 of the Subscription Offered file (AnnualReviews_socialsciencescollection_2012_2014_Nesli2.csv)

However, in the TI display (and elsewhere) the end date is listed as 2014. This is the end date of the Sub Offered (i.e. the subscription lasts from 2012-2014) but not the 'to date' for the journal title, which should be left blank in this case, indicating the the coverage is up to the most recent issue available.

**Comment by ianibbo** [comment]
Have a vague recollection of a requirement to default rules in from SO..
Perhaps I dreamt that, perhaps not. Should end dates deffo not be defaulted
from SO? (It sounds like deffo not, but the phrase "In this case" worries
me ;))

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Thu, Jul 26, 2012 at 10:25 AM, ostephens <
reply@reply.github.com

**Comment by ianibbo** [comment]
Heya..

Just checked -code-, and it's actually defaulting the value from the tipp
record.. Which could mean that the tipp has the end date set wrong too I
guess?

Defaulting end dates from the tipp when null -is- the right thing to do,
correct? So question becomes why does this tipp have a date

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
And there was a typo trying to use the start date from the tipp!!! -oops-

**Comment by ostephens** [comment]
It is correct behaviour to default dates in IEs from TIPPs if they are blank
Agreed in this case it is the TIPP that has imported incorrectly

**Comment by ostephens** [comment]
Looks like this is fixed

**Comment by ianibbo** [comment]
Cool, cheers.

Stopped the tipp defaulting date in from the header :)

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Fri, Jul 27, 2012 at 9:55 AM, ostephens <
reply@reply.github.com
