### ISSUE TITLE
Use "No linked packages" not "No linked subscriptions" on /addLicense

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#804]
e.g. http://dev.kbplus.ac.uk/kbplus/myInstitutions/Aberystwyth_University/addLicense

![screen shot 2014-09-19 at 09 18 28](https://cloud.githubusercontent.com/assets/576174/4333453/76fb474a-3fe0-11e4-8a61-7394337e71ed.png)

**Comment by ianibbo** [comment]
Hey Ioannis..

This isn't quite the full picture here.. Owen wants the packages linked to
the license to be shown, not the subscriptions.. So it's not just changing
the label, but changing the relationships navigated under. If you look at
the package screen there is a linked license - it's the reciprocal relation
that owen wants shown here.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iyawnis** [comment]
@ostephens  Do we also want to update currentLicenses screen, or only addLicense?

**Comment by ostephens** [comment]
Just addLicense 

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936
