### ISSUE TITLE
Coverage column in subscription details screen should be editable as text box

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#82]
Coverage is an IE level attribute. It should be editable in the Subscription details screen (e.g. http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Westminster/subscriptionDetails/224).

Please make this editable as a text box - at the moment we won't control the values entered

**Comment by ianibo** [comment]
Is that coverage depth or coverage note? I'll assume the former.
