### ISSUE TITLE
Previous/Expected Jasper Report incorrect SQL

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#823]
The previous_expected jasper report produces many more lines than expected in the output. I believe this is because the SQL in the report references the package table unnecessarily, resulting in a duplication of lines in the output. From KBPlus / app / grails-app / conf / resources / jasper_reports / previous_expected_pkg.jrxml:

```
<defaultValueExpression><![CDATA[$P{select&Expected&Previous}.equals("Expected")
? "select tipp_id, ti_title from package, title_instance_package_platform, title_instance where tipp_pkg_fk = $P!{search_pkg_id} AND tipp_ti_fk = ti_id AND tipp_access_start_date > '$P{compare_date}'"
: "select tipp_id, ti_title from package, title_instance_package_platform, title_instance where tipp_pkg_fk = $P!{search_pkg_id} AND tipp_ti_fk = ti_id AND tipp_access_start_date <= '$P{compare_date}'"]]></defaultValueExpression>
```

This either needs the 'package' tables removing OR (if package name / details required in output) needs to have an additional condition linking tipp_pkg_fk to pkg_id in the package table:

```
<defaultValueExpression><![CDATA[$P{select&Expected&Previous}.equals("Expected")
? "select tipp_id, ti_title from title_instance_package_platform, title_instance where tipp_pkg_fk = $P!{search_pkg_id} AND tipp_ti_fk = ti_id AND tipp_access_start_date > '$P{compare_date}'"
: "select tipp_id, ti_title from title_instance_package_platform, title_instance where tipp_pkg_fk = $P!{search_pkg_id} AND tipp_ti_fk = ti_id AND tipp_access_start_date <= '$P{compare_date}'"]]></defaultValueExpression>
```

OR

```
<defaultValueExpression><![CDATA[$P{select&Expected&Previous}.equals("Expected")
? "select tipp_id, ti_title from package, title_instance_package_platform, title_instance where tipp_pkg_fk = pkg_id AND tipp_pkg_fk = $P!{search_pkg_id} AND tipp_ti_fk = ti_id AND tipp_access_start_date > '$P{compare_date}'"
: "select tipp_id, ti_title from package, title_instance_package_platform, title_instance where tipp_pkg_fk = pkg_id AND tipp_pkg_fk = $P!{search_pkg_id} AND tipp_ti_fk = ti_id AND tipp_access_start_date <= '$P{compare_date}'"]]></defaultValueExpression>
```

In the latter case obviously you may wish to select additional fields from the package table to display, which would mean further modifications to the report - this may need to wait for feedback from the data managers (due by the end of this week)

**Comment by iyawnis** [comment]
Referencing the package table is unnecessary, but I dont think it would create duplication, although I will check it. I was asked to include package as a way of filtering, but they didnt request that the package is part of the report.

**Comment by ostephens** [comment]
e.g.
select tipp_id, ti_title from package, title_instance_package_platform, title_instance where tipp_pkg_fk = 453 AND tipp_ti_fk = ti_id AND tipp_access_start_date > 20150101

(on a copy of data from 2014-09-01) finds (incorrectly) 2156 results, but

select tipp_id, ti_title from title_instance_package_platform, title_instance where tipp_pkg_fk = 453 AND tipp_ti_fk = ti_id AND tipp_access_start_date > 20150101

finds (correctly) 2 results

**Comment by iyawnis** [comment]
Well guess thats sufficient evidence that it does matter . Updating now.
