### ISSUE TITLE
CSV export of Package/Subscription comparison includes field delimiter characters within fields

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#825]
When you export a comparison - e.g. http://test.kbplus.ac.uk/kbplus/packageDetails/compare?startB=&dateB=2014-10-01&startA=&pkgA=com.k_int.kbplus.Package%3A111&endA=&dateA=2014-10-01&pkgB=com.k_int.kbplus.Package%3A396&endB=&format=csv

If there is a comma within a field (specifically title is an issue) then trying to open the file in Excel or similar does not work correctly. E.g. the line:

Alcoholism, Clinical and Experimental Research,,1977-01-01 00:00:00.0,,,,,,

Leads to "Alcholism" in col 1 and "Clinical and Experimental Research" in col 2 

The usual way to deal with this would be to enclose the field in inverted commas when the field contains the field delimiter character:
"Alcoholism, Clinical and Experimental Research",,1977-01-01 00:00:00.0,,,,,,

**Comment by iyawnis** [comment]
Fixed the error but keeping the code till its decided what we will be doing with this screen. If its decided that we want CSV only, could you verify specifically which fields should be included?
