### ISSUE TITLE
Package upload does not create TIPPs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#826]
Uploading a Package on http://test.kbplus.ac.uk gives errors when it tries to create TIPPs
![screen shot 2014-10-06 at 20 33 40](https://cloud.githubusercontent.com/assets/576174/4532079/dcfeee22-4d8f-11e4-820c-306d2a8f21ec.png)

The error given is

```
Problem saving tipp: grails.validation.ValidationErrors: 1 errors Field error in object 'com.k_int.kbplus.TitleInstancePackagePlatform' on field 'controlledPropertiesHashCode': rejected value [null]; codes [com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.java.lang.Integer,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.java.lang.Integer,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.java.lang.Integer,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.java.lang.Integer,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable,nullable.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,nullable.controlledPropertiesHashCode,nullable.java.lang.Integer,nullable]; arguments [controlledPropertiesHashCode,TIPP]; default message [Property [{0}] of class [{1}] cannot be null]
```

Seems to happen with any Package upload

**Comment by ianibo** [comment]
Think this was an error introduced with some of the property changes - but
it was rolled back, so should have vanished when live was copied over to
test... Will investigate - but hope this isn't an artefact of test.

On 6 October 2014 20:36, Owen Stephens notifications@github.com wrote:

> Uploading a Package on http://test.kbplus.ac.uk gives errors when it
> tries to create TIPPs
> [image: screen shot 2014-10-06 at 20 33 40]
> https://cloud.githubusercontent.com/assets/576174/4532079/dcfeee22-4d8f-11e4-820c-306d2a8f21ec.png
> 
> The error given is
> 
> Problem saving tipp: grails.validation.ValidationErrors: 1 errors Field error in object 'com.k_int.kbplus.TitleInstancePackagePlatform' on field 'controlledPropertiesHashCode': rejected value [null]; codes [com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.java.lang.Integer,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertie
>  sHashCode.nullable.error.java.lang.Integer,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.error,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.controlledPropertiesHashCode,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable.java.lang.Integer,com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode.nullable,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.com.k_int.kbplus.TitleInstancePackagePlatform.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.controlledPropertiesHashCode,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable.java.lang.Integer,titleInstancePackagePlatform.controlledPropertiesHashCode.nullable,nullable.com.k_int.kbplus.TitleIn
>  stancePackagePlatform.controlledPropertiesHashCode,nullable.controlledPropertiesHashCode,nullable.java.lang.Integer,nullable]; arguments [controlledPropertiesHashCode,TIPP]; default message [Property [{0}] of class [{1}] cannot be null]
> 
> Seems to happen with any Package upload
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/826.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibbo** [comment]
This property is no longer in the code - not sure whats going on.....

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Have added a drop column to the db script - although this should not be
needed if everything is working as we expect with the test deployments.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Drop script should fix this - pls retest once deployed and holler if still
bust.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by iyawnis** [comment]
@ostephens any feedback on this?

**Comment by ostephens** [comment]
Fixed and tested
