### ISSUE TITLE
Date selector control on Data Manager Change log is different to other date selectors

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#827]
E.g. date selector for setting subscription start/end dates looks like:

![screen shot 2014-10-08 at 09 43 36](https://cloud.githubusercontent.com/assets/576174/4557786/3419b6ae-4ed7-11e4-8a5b-8cf9392f47ae.png)

But date selector on data manager change log looks like:

![screen shot 2014-10-08 at 09 43 45](https://cloud.githubusercontent.com/assets/576174/4557781/23709b74-4ed7-11e4-8eb8-421cf24d7a77.png)

Not a major issue. Slightly more frustrating that the latter doesn't work on Safari 7.1, but does work OK in Chrome

**Comment by iyawnis** [comment]
I will replace the selectors on DM change log with the other one today.

**Comment by iyawnis** [comment]
is this an issue elsewhere ?

**Comment by ostephens** [comment]
Not as far as I'm aware
