### ISSUE TITLE
Preserve Package choices on package comparison screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#829]
Is it possible to preserve the package choices on the package comparison screen? Currently once you hit compare these choices are blanked.

**Comment by iyawnis** [comment]
Yes it is possible, will do tomorrow. 

Note to self:

```
    initSelection : function (element, callback) {
        var obj= {id:params.pkgInstance.id,text:params.pkgInstance.name};
        callback(obj);
    } 
```
