### ISSUE TITLE
Fix Org Combo add

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#830]
context : com.org : id
newObj : com.Combo
recip : fromOrg / toOrg
toOrg: fromOrg/toOrg

**Comment by ianibo** [comment]
Can't make any sense of this issue - also worried about the incorrect assumptions in the package consortia tab.. please review that fix before changing anything on combo

**Comment by iyawnis** [comment]
This is referring to Add Incoming/Outgoing combos in http://localhost:8080/demo/org/edit/1 
Issue was mostly note to self about how the addToCollection works

**Comment by iyawnis** [comment]
It looks like this is an issue with all title/org/license - /edit pages, due to the way gsp automatically generates these forms.  Are these editing features used at all ?
