### ISSUE TITLE
Consortia members not displayed on Package Consortia tab

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#831]
E.g.
http://test.kbplus.ac.uk/kbplus/packageDetails/consortia/38

Not listing consortia member orgs on this screen

**Comment by iyawnis** [comment]
I can't test it, that screen needs inst_ADM rights, and the package
consortia org link to be displayed .

**Comment by ianibo** [comment]
How about loading the dump I gave you and then granting your use adm rights?

Lets discuss in the office on tuesday!

On 17 October 2014 18:28, Ioannis Latousakis notifications@github.com
wrote:

> I can't test it, that screen needs inst_ADM rights, and the package
> consortia org link to be displayed .
> On 17 Oct 2014 12:24, "Owen Stephens" notifications@github.com wrote:
> 
> > E.g.
> > http://test.kbplus.ac.uk/kbplus/packageDetails/consortia/38
> > 
> > Not listing consortia member orgs on this screen
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/KBPlus/issues/831.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/831#issuecomment-59546833.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
