### ISSUE TITLE
Link Package search doesn't work on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#832]
e.g.

http://test.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/10036?offset=0&id=10036&pkgname=JSTOR&search=yes

Seems to just return all results

**Comment by iyawnis** [comment]
found problem, forgot to change parameter name from pkgname to q in gsp after refactoring, will be fixed asap.

**Comment by ianibo** [comment]
Seems to work on test. closing. please reopen with more info if still broken
