### ISSUE TITLE
Jasper Reports Changes

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#839]
### Match Coverage Note
- Add another report that will search packages with the addition of content provider (Org Role - Content Provider) 
### No URL report
- Filter packages by start/end dates
- Show TIPP ID not Title ID
- On match coverage and no URL, add package id and package status

**Comment by iyawnis** [comment]
TODO
- Add another report that will search packages with the addition of content provider (Org Role - Content Provider) 
- Filter packages by start/end dates

**Comment by ostephens** [comment]
Request from Magaly:
Can the following information be added to the previous_expected_pkg report
TI Identifiers (assume this really means ISSN and eISSN)
Coverage Note (tipp_coverage_note)
URL (tipp_host_platform_url)

I guess same requests would also apply to the previous_expected_sub report, although this hasn't been explicitly requested so lower priority.

I'm guessing adding the Identifiers is the tricky part of this request? I can double check these are definitely needed if you want?

**Comment by ostephens** [comment]
btw would you prefer these requests are added to separate github issues?

**Comment by iyawnis** [comment]
In the future yes. Are the DMs expecting the pdf to be readable ? Or they only care for csv ?

**Comment by iyawnis** [comment]
If they need it readable I guess I will have to change page orientation to be landscape.

**Comment by iyawnis** [comment]
Added issn, eissn, coverage note, platform url, page orientation changed to landscape.
1b6b8cd037afc10244b92576a774d232bd4be382
