### ISSUE TITLE
Sorting list of IEs in Subscription Details tab

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#84]
In Subscription Details tab (e.g. http://knowplus.edina.ac.uk/kbplus/myInstitutions/University_of_Westminster/subscriptionDetails/224) it should be possible to sort by any of the columns in the display. Suggest that clicking column heading triggers (in cycle) "sort ascending", "sort descending", "no sort"

**Comment by ianibo** [comment]
Done for title sort as agreed, need to defer ISSN/eISSN, may need denormalisation to work.
