### ISSUE TITLE
"Accept All" can result in earlier changes overwriting later changes

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#841]
If there are a number of pending changes/To Do items for the same field, and 'Accept All' is clicked, it looks like they may not be applied in the order the changes occurred, resulting in sometimes an earlier change overwriting a later change.

Have tried this with TIPP http://dev.kbplus.ac.uk/kbplus/tipp/show/83568
Changed 'Coverage Note' field to value 'Change 1'
Then changed 'Coverage Note' field to value 'Change 2'

Both changes came through to Subscription http://dev.kbplus.ac.uk/kbplus/subscriptionDetails/index/8910?sort=&order=&filter=Epidemiologia+e+Psichiatria+Sociale&pkgfilter=&asAt=

Clicked 'Accept All'

Coverage Note for IE http://dev.kbplus.ac.uk/kbplus/issueEntitlement/show/1073925 now 'Change 1' where I'd expect it to be 'Change 2'

![screen shot 2014-11-14 at 17 01 42](https://cloud.githubusercontent.com/assets/576174/5049755/03ab4274-6c20-11e4-89b2-9d9c4fcb2476.png)

This doesn't always seem to happen though - in other circumstances I've seen two changes on the same data field applied in the correct order via 'Accept All'.

**Comment by iyawnis** [comment]
Was hoping simply setting sort order in PendingChange would fix it, but it didnt. Will look into detail tomorrow.

**Comment by iyawnis** [comment]
Owen can you test that with single changes on Dates, the correct date is applied to target? I have found an issue caused by timezones, but not sure if its on my machine or on the code. What needs to be tested: On a tipp change one of the date properties. Then on target subscription accept change and check the applied date matches the date of tipp. It looks like I am not able to edit tipps on test.

**Comment by ostephens** [comment]
Happy to test, but this change needs merging into newdev to get it up on the dev instance I can test on

**Comment by iyawnis** [comment]
Yes I know, the thing I need you to test is not relevant, thats why I suggested accepting single changes.

**Comment by ostephens** [comment]
Ah - got you - will test asap

**Comment by ostephens** [comment]
As far as I can see date changes are applied correctly:

Changed 'Access Start' date to 2014-11-01 on http://test.kbplus.ac.uk/kbplus/tipp/show/82129
![screen shot 2014-11-17 at 16 35 21](https://cloud.githubusercontent.com/assets/576174/5073201/2dd013c2-6e78-11e4-90e1-7abc7fd6b070.png)

Saw To Do notification in linked subscription http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/3630

![screen shot 2014-11-17 at 16 34 26](https://cloud.githubusercontent.com/assets/576174/5073211/47487e02-6e78-11e4-9cf5-01b8d3cc6d53.png)

Accepted this and can see correct date in Issue Entitlement and in To Do History on Sub

![screen shot 2014-11-17 at 16 35 21](https://cloud.githubusercontent.com/assets/576174/5073229/6907e582-6e78-11e4-98e2-49236875a4b5.png)

![screen shot 2014-11-17 at 16 34 37](https://cloud.githubusercontent.com/assets/576174/5073242/80753512-6e78-11e4-890b-2cd7595b47c8.png)

**Comment by iyawnis** [comment]
Ok thanks, there is an issue on my machine with timezone converting, needed to know if its something requiring immediate action.
