### ISSUE TITLE
Copy access to/from dates from TIPP when creating entitlements using 'Link with entitlements' to add package to subscription

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#842]
When IEs are created for a subscription using 'Link with entitlements' to add package to subscription, the Access To/Access From dates don't seem to be copied.

http://dev.kbplus.ac.uk/kbplus/subscriptionDetails/linkPackage/ with parameter addType=With

E.g. This http://dev.kbplus.ac.uk/kbplus/subscriptionDetails/index/10345?mode=advanced has IE 
http://dev.kbplus.ac.uk/kbplus/issueEntitlement/show/1126526 which has not Access End date

This was created using 'Link with entitlements' function from TIPP

http://dev.kbplus.ac.uk/kbplus/tipp/show/38386 which has Access End date set

---

If you add the IE using the 'Add Entitlements'  (using the form action "/kbplus/subscriptionDetails/processAddEntitlements") then the Access End date is copied from the TIPP

See IE http://dev.kbplus.ac.uk/kbplus/issueEntitlement/show/1126525 which was created from the same TIPP, but using the processAddEntitlements form action

**Comment by iyawnis** [comment]
Could it be because we are not using the DerivedAccessStartDate / End Date during copy ? The code seems to be copying accessStartDate/EndDate of tipp. If thats null then its not copied. Derived is checking the tipp start/end date, and if null returns the pkg.startDate / endDate

**Comment by ostephens** [comment]
Don't think so - in the example I posted the accessEndDate was set on the TIPP. We shouldn't use the Derived because the Sub has its own rule for Derived on IEs I think

**Comment by iyawnis** [comment]
Hm thats the only thing that would make sense cause if you look at addToSubscription@218 at https://github.com/k-int/KBPlus/blob/newdev/app/grails-app/domain/com/k_int/kbplus/Package.groovy , accessStartDate seems to be copied. Guess it needs more investigation ..

**Comment by ostephens** [comment]
I'll re-test - give me a moment

**Comment by ostephens** [comment]
Re-testing seems to confirm the issue, but agreed from that Package.groovy the code definitely looks like these should be copied.

Started with package 24 and added variety of Access Start/Access End dates to three TIPPS - screenshot:

![screen shot 2014-11-14 at 23 40 25](https://cloud.githubusercontent.com/assets/576174/5055217/0da0ecd8-6c58-11e4-8a44-3fb52fd5e09a.png)

Then created Subscription and used Link with Entitlements - IEs created do not have Access Start/Access End dates:

![screen shot 2014-11-14 at 23 41 04](https://cloud.githubusercontent.com/assets/576174/5055229/3e990ec4-6c58-11e4-99d8-f49b56180c28.png)

**Comment by ostephens** [comment]
Might have something - think Package.groovy using 

from Package.groovy (line 228->):
 def new_ie = new IssueEntitlement(status: live_issue_entitlement,
                                          subscription: subscription,
                                          tipp: tipp,
                                          accessStart:tipp.accessStartDate,
                                          accessEnd:tipp.accessEndDate,
                                          startDate:tipp.startDate,
                                          startVolume:tipp.startVolume,
                                          startIssue:tipp.startIssue,
                                          endDate:tipp.endDate,
                                          endVolume:tipp.endVolume,
                                          endIssue:tipp.endIssue,
                                          embargo:tipp.embargo,
                                          coverageDepth:tipp.coverageDepth,
                                          coverageNote:tipp.coverageNote).save()

Think lines 231/232 should use 'accessStartDate' and 'accessEndDate' rather than 'accessStart' and 'accessEnd'?

cf SubscriptionDetailsController.groovy lines 618/619
