### ISSUE TITLE
Zendesk 'Support' link not showing in test/dev

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#844]
The Support link not displaying in test/dev at the moment.
Not sure if this is cause, but also noted that getting the error:

Failed to load resource: the server responded with a status of 404 (Not Found) http://www.kbplus.ac.uk/kbplus/static/plugins/jquery-1.9.1/js/jquery/jquery.min.map

in browser console

**Comment by ostephens** [comment]
Sorry - that jquery error is a red herring - also see the same error on live, where the Support link shows without a problem

**Comment by iyawnis** [comment]
I never had this link, but as far as I know comes from setting the configuration for zendesk url. Any idea what that link is supposed to be so I can test ? ZenDeskBaseURL

**Comment by iyawnis** [comment]
nvm got it. looking into issue now
