### ISSUE TITLE
'Spotlight' search box does not always display on Safari on live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#846]
Under some circumstances the Spotlight search box does not display - I've only managed to recreate this in Safari - does not affect Ff or Chrome on Mac.

Issue seems to occur when you use the 'www' URL, and resolves if you use 'service':

http://www.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/dashboard - click icon:
![screen shot 2014-11-19 at 18 03 08](https://cloud.githubusercontent.com/assets/576174/5111229/eea643b0-7016-11e4-8d9d-37e08835f94b.png)

http://service.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/dashboard - click icon:
![screen shot 2014-11-19 at 18 03 25](https://cloud.githubusercontent.com/assets/576174/5111258/03217cd8-7017-11e4-8040-2ccd05a03e26.png)

**Comment by iyawnis** [comment]
I am not even sure where that search is coming from, as its not in the gsp files for spotlight.. will try to reproduce from home. .. if possible can you do an inspect element and post it here?

**Comment by iyawnis** [comment]
There might be a console error too.

**Comment by ostephens** [comment]
Can't see any relevant console errors. The element is:

```
<ul class="nav pull-right">
              <li>
                          <a class="dlpopover" href="#" data-original-title="" title="">
                                       <i class="icon-search icon-white"></i>
                          </a>
             <div class="popover fade bottom in" style="width: 400px; top: 40px; left: -118px; display: block;">                    
                          <div class="arrow"></div>
                          <div class="popover-inner">
                                       <h3 class="popover-title">search</h3>
                                       <div class="popover-content"></div>
                          </div>
             </div>
             </li>
</ul>
```

**Comment by iyawnis** [comment]
Error doesn't appear on safari 7.1, using  Ill try to figure this out tomorrow.

**Comment by iyawnis** [comment]
Just tested on safari 8 and it works... Are there specific steps to replicate this problem ?

**Comment by ostephens** [comment]
Hmm - now can't recreate, although could recreate consistently last night. Weird, but have to put it down to weirdness at my end for now. I'll close this and open again if it recurs

**Comment by ianibbo** [comment]
Might have been a cached resource expiring I guess.. Will keep an eye out.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
