### ISSUE TITLE
Adding an Org Link to a Licence without specifying an Org Role leads to a Grails error

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#847]
Adding an Org Link to a licence:

![screen shot 2014-11-25 at 12 06 15](https://cloud.githubusercontent.com/assets/576174/5182545/7fb88b32-749b-11e4-947d-19450ae0d1c6.png)

It is currently possible to select and organisation but not set a role in the drop down. Doing this leads to a grails error, and the licence no longer being accessible due to that error (see below).

Carrying out the same operation on a Subscription rather than a licence leads to an OrgRole link which lacks a specified role - see http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/4463. Licences should work in the same way

http://test.kbplus.ac.uk/kbplus/licenseDetails/index/2889

Error 500: Internal Server Error
URI
/kbplus/licenseDetails/index/2889
Class
java.lang.NullPointerException
Message
Cannot get property 'value' on null object
Trace
    Line | Method
->>  530 | doFilter  in /licenseDetails/index.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: Cannot get property 'value' on null object
->>   44 | doCall    in /WEB-INF/grails-app/views/licenseDetails/index.gsp

---

Caused by NullPointerException: Cannot get property 'value' on null object
->>   50 | doCall    in gsp_demo_licenseDetails_nav_gsp$_run_closure1

---

|     77 | doCall    in gsp_demo_licenseDetailsindex_gsp$_run_closure2
|    269 | run . . . in gsp_demo_licenseDetailsindex_gsp
|    195 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter  in     ''
|     65 | doFilter  in com.k_int.kbplus.filter.ApiauthFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

**Comment by iyawnis** [comment]
Tested locally, fix works. Issue was with new  gsp code for consortia screen.
