### ISSUE TITLE
JSON exports from publicExport page not working

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#848]
from http://www.kbplus.ac.uk/kbplus/publicExport

Try to retrieve http://www.kbplus.ac.uk/kbplus/publicExport/pkg/1059?format=json

get error:

Error 500: Internal Server Error
URI
/kbplus/publicExport/pkg/1059
Class
java.lang.NullPointerException
Message
Cannot get property 'value' on null object
Trace
    Line | Method
->>  238 | doCall    in com.k_int.kbplus.PublicExportController$_pkg_closure2_closure10_closure13

---

|    214 | doCall    in com.k_int.kbplus.PublicExportController$_pkg_closure2_closure10
|    174 | pkg . . . in com.k_int.kbplus.PublicExportController
|    195 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter  in     ''
|     65 | doFilter  in com.k_int.kbplus.filter.ApiauthFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

**Comment by ianibo** [comment]
Already fixed in git - spotted it last week - _Should_ be fixed on dev,

On 26 November 2014 at 15:22, Owen Stephens notifications@github.com
wrote:

> from http://www.kbplus.ac.uk/kbplus/publicExport
> 
> Try to retrieve
> http://www.kbplus.ac.uk/kbplus/publicExport/pkg/1059?format=json
> 
> get error:
> 
> Error 500: Internal Server Error
> URI
> /kbplus/publicExport/pkg/1059
> Class
> java.lang.NullPointerException
> Message
> Cannot get property 'value' on null object
> Trace
> Line | Method
> ->> 238 | doCall in
> 
> ## com.k_int.kbplus.PublicExportController$_pkg_closure2_closure10_closure13
> 
> | 214 | doCall in
> com.k_int.kbplus.PublicExportController$_pkg_closure2_closure10
> | 174 | pkg . . . in com.k_int.kbplus.PublicExportController
> | 195 | doFilter in
> grails.plugin.cache.web.filter.PageFragmentCachingFilter
> | 63 | doFilter in grails.plugin.cache.web.filter.AbstractFilter
> | 150 | invoke in net.bull.javamelody.JspWrapper
> | 285 | invoke . in
> net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
> | 198 | doFilter in net.bull.javamelody.MonitoringFilter
> | 176 | doFilter in ''
> | 65 | doFilter in com.k_int.kbplus.filter.ApiauthFilter
> | 1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
> | 615 | run in java.util.concurrent.ThreadPoolExecutor$Worker
> ^ 745 | run . . . in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/848.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ostephens** [comment]
Confirmed fixed on Dev - sorry should have checked! (and I was so pleased with myself for spotting it!)

**Comment by ianibo** [comment]
:) ta! (Good spot tho!)
