### ISSUE TITLE
Request to change 'Help' link in 'Institutions' drop down menu

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#849]
At the foot of the "Institutions" dropdown menu there is a link to the current support site:
https://knowledgebaseplus.wordpress.com/kb-support/

Jisc are moving the content to the Jisc collections website - can this link be updated to:
http://www.jisc-collections.ac.uk/KnowledgeBasePlus/Help/User-guides/

(or make this part of the in-app config available to admin users?)

**Comment by iyawnis** [comment]
Its been added to messages.properties.

**Comment by ostephens** [comment]
Thanks Ioannis. To update this in the future is that editing message.properties file, or is the property accessible via the Web UI?

**Comment by iyawnis** [comment]
The file needs to be editted. In the future this can be changed. The advantage of messages.properties over demo-config is that different link can be provided for each supported language.
