### ISSUE TITLE
'Edit' link no longer showing for KB+ editors on /titleDetails/index

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#851]
Previously on http://www.kbplus.ac.uk/kbplus/titleDetails/index an Edit link displayed for KB+ editors. This no longer seems to display

![screen shot 2014-11-26 at 22 12 35](https://cloud.githubusercontent.com/assets/576174/5209760/57002360-75ba-11e4-846e-378f12f262ff.png)

**Comment by ianibbo** [comment]
Link only shows for users with ADMIN role - don't think this was added in
this release tho. Who should the edit link show for?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Think this all goes back to

https://github.com/k-int/KBPlus/issues/516

If you can suggest a change we can look at getting it in before wed.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Definitely not displaying for ADMIN users either at the moment (which it was before the release)

**Comment by ianibo** [comment]
Ok.. investigating - code hasn't changed since that release.

**Comment by ostephens** [comment]
May be taking a stab in the dark, but is it that in the TitleDetailsController index function result.editable is set (line 137), then result is set to ESSearchService.search(params) on line 151 (the latter being new have moved a load of stuff into ESSearchService)

**Comment by ianibbo** [comment]
Yes, thats it exactly - don't know when that was done - part of shifting to
ES service I guess - anyway - fixed on 4.2 maint and newdev.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Confirmed fixed on dev
