### ISSUE TITLE
deletedTitleManagement screen shows no titles

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#852]
There are titles with status 'deleted' on live, but none of these appear in the 'Deleted Title Management' screen http://www.kbplus.ac.uk/kbplus/dataManager/deletedTitleManagement

e.g. of title with status 'deleted' http://www.kbplus.ac.uk/kbplus/titleDetails/show/5475

Think status was changed via the 'title merge' function http://www.kbplus.ac.uk/kbplus/admin/titleMerge since this is the only way (except via Data Explorer) that a user can set Title Status to Deleted afaik

During investigation I noted 2 issues:
1) that via Title Merge the ref data value is set using:
RefdataCategory.lookupOrCreate("TitleInstanceStatus", "Deleted") (AdminController.groovy line 341)

while the deletedTitleManagement uses:
RefdataCategory.lookupOrCreate( 'Title Status', 'Deleted' ); (DataManagerController.groovy line 307)

2) I manually changed the status for a title on Test via Data Explorer (see http://test.kbplus.ac.uk/kbplus/titleInstance/show/18816) - this led to one 'deleted' title being reported on the deletedTitleManagement screen but no title information displayed. 

Looking at deletedTitleManagement.gsp I think this may be using "titleInstanceList" as opposed to 'titleList' which is set in DataManagerController.groovy?

**Comment by ianibo** [comment]
Yep, we need to just remove deletedTitleManagement  - it was an
experimental idea that never really got adopted - should have been removed.

On 28 November 2014 at 12:13, Owen Stephens notifications@github.com
wrote:

> There are titles with status 'deleted' on live, but none of these appear
> in the 'Deleted Title Management' screen
> http://www.kbplus.ac.uk/kbplus/dataManager/deletedTitleManagement
> 
> e.g. of title with status 'deleted'
> http://www.kbplus.ac.uk/kbplus/titleDetails/show/5475
> 
> Think status was changed via the 'title merge' function
> http://www.kbplus.ac.uk/kbplus/admin/titleMerge since this is the only
> way (except via Data Explorer) that a user can set Title Status to Deleted
> afaik
> 
> During investigation I noted 2 issues:
> 1) that via Title Merge the ref data value is set using:
> RefdataCategory.lookupOrCreate("TitleInstanceStatus", "Deleted")
> (AdminController.groovy line 341)
> 
> while the deletedTitleManagement uses:
> RefdataCategory.lookupOrCreate( 'Title Status', 'Deleted' );
> (DataManagerController.groovy line 307)
> 
> 2) I manually changed the status for a title on Test via Data Explorer
> (see http://test.kbplus.ac.uk/kbplus/titleInstance/show/18816) - this led
> to one 'deleted' title being reported on the deletedTitleManagement screen
> but no title information displayed.
> 
> Looking at deletedTitleManagement.gsp I think this may be using
> "titleInstanceList" as opposed to 'titleList' which is set in
> DataManagerController.groovy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/852.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
removed.

**Comment by ostephens** [comment]
Fair enough - laying bets we are going to be asked about removing titles with the status 'deleted' in the very near future...

Although solution may actually be to remove from ES index?

**Comment by ostephens** [comment]
Or at least, limit results set from "All Titles" ES Search if that's more appropriate than not indexing them

**Comment by ostephens** [comment]
I'll add something to the enhancement requests spreadsheet in anticipation so I don't forget :)
