### ISSUE TITLE
Rewrite pkg method on PublicExportController to select individual properties rather than deserialising tipp

### ISSUE THREAD

**Issue by ianibo** [k-int/KBPlus#856]
pkg method in PublicExportController needs to be rewritten so that

result.tipps = TitleInstancePackagePlatform.executeQuery("select tipp "+base_qry, qry_params, [max:result.max, offset:result.offset]);

Is replaced with

result.tipps = TitleInstancePackagePlatform.executeQuery("select tipp.startDate, tipp.endDate,..... "+base_qry, qry_params, [max:result.max, offset:result.offset]);

And the subsequent code changed to t[0], t[1] instead of t.startDate, t.endDate.

Identifiers ISSN, ISBN, DOI will need to be manually selected using a specific query (Suggest selecting t.title.id in the query and then issuing a specific query against IdentifierOccurrence for that title and the specific namespace.

Currently this controller consumes a massive amount of CPU time and database time deserialising domain objects, and given that the methods seem to be regularly hit by remote machine to machine interfaces we stand to benefit substantially from optimising.

**Comment by iyawnis** [comment]
Is there a better way of selecting all the required identifiers with a single query ? This one is doing issn and eissn.. 

select id_is.value, id_ei.value from IdentifierOccurrence io_is, IdentifierOccurrence io_ei , Identifier id_is, Identifier id_ei, IdentifierNamespace ns_is, IdentifierNamespace ns_ei where io_is.ti.id = :id and io_ei.ti.id = :id and id_is.ns = ns_is and id_ei.ns = ns_ei and io_is.identifier = id_is and io_ei.identifier = id_ei and lower(ns_is.ns) = 'issn' and lower(ns_ei.ns) = 'eissn'

**Comment by ianibbo** [comment]
Not if you want them as 2 columns in one row. If you want two rows with
"type" and "value" then probably - but either way this should be pretty
efficient.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
