### ISSUE TITLE
Cannot add an identifier in a new namespace

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#857]
Trying to add an identifier to a title/package/organisation you cannot add a new namespace - I thought this used to be possible?

If you try to add a new namespace then only the 'namespace' portion of the ID is shown in the pick list - see screenshots below.

Although I _think_ this is a change of behaviour, it may not be undesirable? If it was possible to add ID namespaces via a separate 'namespace' management screen then we could avoid additions of incorrect namespaces through mis-typing when adding IDs? This is just a thought - happy for function to be fixed otherwise.

![screen shot 2015-01-28 at 10 34 05](https://cloud.githubusercontent.com/assets/576174/5936160/cc29400e-a6d9-11e4-870a-4dac947df054.png)
![screen shot 2015-01-28 at 10 28 47](https://cloud.githubusercontent.com/assets/576174/5936161/cdec69a2-a6d9-11e4-9523-f24fc6bc75e5.png)

**Comment by iyawnis** [comment]
Just got aware of this and fixed it..

**Comment by ostephens** [comment]
OK - that's fine :) I'll close
