### ISSUE TITLE
Core Dates - UI

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#864]
Make Core Assertion dates editable from UI. Probably through subscr > IE table (core). Popup might be the way to go. Talk with owen.

**Comment by ostephens** [comment]
Pop-up would be OK with me if that's the easiest/best way to go. 

Should be able to edit these dates from both IE list on /subscriptionDetails/index/ and the IE details page /issueEntitlement/show/

**Comment by iyawnis** [comment]
Work nearly complete, working on displaying validation error msg ( currently only checking that startDate < endDate ) any comments are welcome 
![screenshot from 2015-03-20 14 26 29](https://cloud.githubusercontent.com/assets/2336352/6753372/51c4b79c-cf0d-11e4-9ff3-6cff22532e4d.png)
![screenshot from 2015-03-20 14 26 15](https://cloud.githubusercontent.com/assets/2336352/6753376/54444f6e-cf0d-11e4-8429-d746c5c9c199.png)

**Comment by ostephens** [comment]
Thanks Ioannis - this looks great. Have raised some new issues to handle feedback on this
