### ISSUE TITLE
New Core functionality on Test: Layout issues

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#865]
Following #864 

1) Need to remove the current 'Core Start Date' and 'Core End Date' from the display
2) Suggest we replace this with a 'Core' column with the True/False values in it (then don't need the 'Core' label in each cell)
3) The clickable 'True' and 'False' values should be underlined with a dotted line to indicate they can be edited by clicking
4) Can we use uppercase T and F for True/False

Example screen layout:
![screen shot 2015-03-25 at 16 56 35](https://cloud.githubusercontent.com/assets/576174/6830159/f2eaedfc-d30f-11e4-9e3d-6ce7d2247cc5.png)

**Comment by ostephens** [comment]
Looks good, but need to take out the 'Edit' options in the "Core Status" column header:

![screen shot 2015-03-27 at 16 02 21](https://cloud.githubusercontent.com/assets/576174/6871552/4f523b90-d49b-11e4-9757-285f1eb748c7.png)

**Comment by iyawnis** [comment]
Ah well spotted, will fix now.
