### ISSUE TITLE
New Core functionality on Test: Lightbox issues

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#866]
Following #864 

The popup lightbox for editing Core dates:
1) Rename the 'Extend' button on the Lightbox popup to 'Add'
2) Add a 'Close' button to the Lightbox popup (currently no obvious way to close this popup)
3) Using Safari Date controls/boxes on Lightbox popup do not work correctly. Clicking on the control icon does nothing. Clicking in date box triggers a date chooser popup. Behaviour should be that clicking on control icon triggers the date chooser and clicking in the date box allows you to edit manually (this is how other date control/boxes work in the system)

**Comment by iyawnis** [comment]
On 3, not sure how this box behaves differently from the rest, as the code has been copied, although I will look into it.

**Comment by ianibbo** [comment]
Not sure about add over extend. In some cases adding dates will simply
change what is there.. Want to avoid support calls where people say.. I
clicked add and nothing happened.

**Comment by ostephens** [comment]
Ok. How about 'Modify'?

**Comment by iyawnis** [comment]
Is there any particular reason why we should change the button name? Extend conveys the function quite good I believe..  By the way does this look ok ? Edit brings up the date editing that exists around the app(works as you described)
.
![screenshot from 2015-03-27 10 59 43](https://cloud.githubusercontent.com/assets/2336352/6866512/fef5eb58-d470-11e4-9b34-e3653a0d51b1.png)

**Comment by ostephens** [comment]
I really don't like 'Extend' - if you are adding information for the first time it doesn't make sense (you aren't extending anything).

That latest screenshot looks good to me

**Comment by ostephens** [comment]
Sorry - still no Close button on that screenshot as per (2)

**Comment by latusaki** [comment]
Top right ? also clicking anywhere outside the modal will close it (as with other modals)

**Comment by ostephens** [comment]
Ah - my bad - yes it is there top right - thanks

**Comment by ostephens** [comment]
Looks good on test - Think this can be closed @latusaki
