### ISSUE TITLE
New Core functionality on Test: Add sort/filter by Core True/False?

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#867]
Following #865 

If we have new column for the Core True/False value is it easily possible to enable sorting or filtering by this value so that institutions can easily find their current Core titles within a subscription?

Happy to add this to the list of enhancement requests if this is seen as out of scope for current work @ianibbo ?

**Comment by iyawnis** [comment]
This is possible, although it worths mentioning that the core values are calculated dynamically, and it is not a stored value, as it can be different based on the lookup date.

**Comment by ostephens** [comment]
Yes - understood

**Comment by iyawnis** [comment]
@ianibo  this also means that on each refresh we have to load all IE, calculate core status, sort, and then display only the subset currently visible (based on offset -max). Is this ok?

**Comment by iyawnis** [comment]
Feature implemented, will merge as soon as Ian confirms.

**Comment by ianibbo** [comment]
Confirmed
