### ISSUE TITLE
New Core functionality on Test: Add core_status_id back to /subscriptionDetails/index/ display

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#869]
Alongside the Core dates, we have a 'Core Status' currently. This is set on the Issue Entitlement as core_status_id (ref data value lookup for display).

Following #864 this has been removed from the display. It needs to be added back. See also other layout changes in #865 

Suggest this is in the same column as the Core True/False label on a second line in the same cell.

This is just set at the subscription/IE level and so it will be possible to conflict with the Core True/False. This isn't ideal but I think it is the best we can do for now

**Comment by iyawnis** [comment]
Sorry Owen, we have trouble understanding what you are asking for here.

**Comment by ostephens** [comment]
This is about the current Core Status - controlled by core_status_id in Issue Entitlements. This can be set to (via Ref values):
- Yes
- No
- Print
- Electronic
- Print + Electronic

Screen shot showing this in the current system:

![screen shot 2015-03-30 at 11 44 00](https://cloud.githubusercontent.com/assets/576174/6894940/941d53d4-d6d2-11e4-9cd4-d357e571e0d5.png)

Since this information isn't replicated in the new Core functionality (which only deals with dates) it still needs to be displayed & editable. Suggest we rename this (in the UI) 'Core Medium' (inline with #870) and display as a second line in the new 'Core Status' col underneath True/False calculated value?

**Comment by iyawnis** [comment]
Right this is all clear now. Ian suggested we rename the Medium column to Entitlement Medium as well, whats your opinion on this? Finally, on the ref values available to core medium, shouldnt we remove the Yes, No ?

**Comment by ostephens** [comment]
Happy to rename the Medium to Entitlement Medium - makes sense

Agreed we should really remove the Yes and No but unless we have a way of transforming them into the Dates we will have lost information so I'd be happy for them to be removed from the drop down options as long as any existing values are kept & displayed (unless we are already doing something to transform these Yes/No values into dates?)

**Comment by iyawnis** [comment]
I dont think there is something to do about the current settings, as the core status is now dynamic.. What date range would we be generating? Also, the current statuses are updated from JUSP imports if im not mistaken.

**Comment by ostephens** [comment]
Yes - this is what I mean - there is no way we can take a simple 'Yes' from the current Core status and create a date range. Therefore we should not delete the "Yes" but leave it as the new Core Medium value.

New Core dates should be being created from a combination of both the JUSP imports and any existing Core Start/End dates in KB+

**Comment by iyawnis** [comment]
Does this look sensible for now ? 
![screenshot from 2015-03-30 15 05 06](https://cloud.githubusercontent.com/assets/2336352/6897880/3efac3b6-d6ee-11e4-8458-314a44f0a633.png)

**Comment by ostephens** [comment]
I'd probably reverse the order (Core Status first, Core Medium second). But yes - generally happy with that
