### ISSUE TITLE
Content Provider name: DataTables warning, JSON formatting error

### ISSUE THREAD

**Issue by julianladisch** [k-int/KBPlus#877]
Clicking the Content Provider name in the Content Provider line of the package edit screen results in this error message:

"DataTables warning (table id = 'escr_tab'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error."

Example:
Clicking on "Springer" in the line "Content Provider Springer" on
https://www.kbplus.ac.uk/test/package/edit/1

It looks like [views/ajax/refdataSearch.gsp](https://github.com/k-int/KBPlus/blob/1222a8031c944a3762839d171891aff3d4dc8f06/app/grails-app/views/ajax/refdataSearch.gsp) returns the string "refdataSearch.gsp" instead of JSON.

**Comment by ostephens** [comment]
If it is going to do anything think the link to Springer here should go to the Org page - e.g. https://www.kbplus.ac.uk/test/organisations/info/6

For modifying relationships between Packages and Orgs this should be done via
https://www.kbplus.ac.uk/test/packageDetails/show/1

**Comment by iyawnis** [comment]
The implementation of that link has been unfinished since 2012 from what I can see. I will talk with @ianibbo  and either finish it or change what the link is doing.

**Comment by iyawnis** [comment]
Not sure how I missed it, but that screen already has an Org Links table where you can add a content provider. The `Content Provider`  field is redundant, I will remove it now

**Comment by iyawnis** [comment]
![package_edit](https://cloud.githubusercontent.com/assets/2336352/7294130/584cacdc-e9a2-11e4-9bd7-977dc97737b0.png)
