### ISSUE TITLE
CSV IE Export

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#879]
Following the changes to XML and JSON export for issue entitlements, I have adjusted CSV export. Since we get a flat view this is what I am going with, any feedback welcome. Should the dates be separated differently ?

![screenshot from 2015-04-08 12 40 05](https://cloud.githubusercontent.com/assets/2336352/7044551/6909cdfa-ddec-11e4-98af-c3e1dacbf62f.png)

**Comment by ostephens** [comment]
Apologies for the delay in responding. I'm OK with this but for the 'KB+ Import Format' (which is also a csv format created from the XML) I've gone with just stating a max/min range for the core dates. I'm not sure we need to be consistent here but I think either approach has pros/cons.
