### ISSUE TITLE
TitleInstitutionProvider edit screen

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#880]
It has been mentioned that we probably want a screen for editing TIP (the new domain for handling JUSP status).Any specific layouts in mind, or should I just have a go at it ? 

I imagine there will be a paged list view,  with columns for title Inst and prov, clicking one will bring up a screen where you can edit all TIP fields including the Core assertions. And also a button somewhere obvious for creating new TIP / deleting... 

One thing I am not too sure about is if we need to give the users the option of editing TIPs directly, maybe this screen should be view only apart from the core assertion dates which will be editable
 ?

**Comment by ostephens** [comment]
I don't think we should give the option of editing TIPs directly except the Core assertion dates (which should work via the same lightbox popup as elsewhere).

I also don't think we should give the option of creating a new TIP directly at least in the first instance. My preference would be people do this via Subscriptions to be honest. If we get demand for being able to add TIPs directly we can consider it later.

**Comment by ostephens** [comment]
Apart from that what you've described sounds like what I had in mind so please go ahead and give it a go.

**Comment by iyawnis** [comment]
@ostephens Is this screen admin - only, or should it be related to institutions? Also, do we need to display the JUSP identifiers for each TIP ?

**Comment by ostephens** [comment]
This should be related to institutions
I don't think we need to display the JUSP Identifiers for each TIP

**Comment by iyawnis** [comment]
Is there a more user friendly name for TIP? For example, under institution menu should the option be ~view tips ? Or is there another name to use ?

**Comment by ostephens** [comment]
Good question. We haven't thought of one so far.
But perhaps we should call it 'Edit Core titles' for the moment?

**Comment by iyawnis** [comment]
I sent you a mail with two screenshots. Any feedback is welcome. If its ok this will be pushed to test.
One thing I just noticed, name column will be renamed to title ^_^

**Comment by ostephens** [comment]
They look good.

Two questions:
![screenshot from 2015-04-22 11 56 14](https://cloud.githubusercontent.com/assets/576174/7273095/39b226cc-e8e8-11e4-9aef-8452ed7a4287.png)

Where do the hyperlinks for the Title and Provider go in the table display?
How difficult would it be to include a link to the relevant Subscriptions/Issue Entitlements for each of these?

On the latter point very happy for that to be a future enhancement - just wondering if this is easy or difficult

**Comment by iyawnis** [comment]
Title points to titleDetails/show and provider to org/show.  How would we link to a subscription ? A tip contains these references :                       title: TitleInstance,      institution: Org,     provider: Org

**Comment by ostephens** [comment]
OK - great. Think this is ready to push to test please.

**Comment by iyawnis** [comment]
74c44a26c2823d8a8e6ae36af8cb5589d9400ea8

**Comment by ostephens** [comment]
@latusaki does this page list all the titles that the institution has a subscription to? Or only those with core dates?

**Comment by iyawnis** [comment]
This screen will fetch all available TIPs for the institution. TIPs are generated from importing JUSP data, or by adding core dates to IEs.

**Comment by ostephens** [comment]
I think since these are going to be a mix of those with and without core dates we probably need to have some way of telling at least whether the title is currently Core in the same way on Subscriptions?

**Comment by iyawnis** [comment]
Yeah it wont be any trouble. Same True / False value as in Subscription ?

**Comment by ostephens** [comment]
Currently awaiting some feedback from sites who are testing this - this should be with us by 6th May (next Wed) so suggest we wait until we've got that feedback until we make changes in case there are some other suggestions about how these values should be presented. Once I've got this, I'll update this issue.

**Comment by ostephens** [comment]
Just to note I think we are going to have some further updates to this screen requested following the feedback - but I'll do these through separate issues

**Comment by iyawnis** [comment]
Yeah I think it will be more appropriate.
