### ISSUE TITLE
No module found with name [bootstrap-typeahead]

### ISSUE THREAD

**Issue by julianladisch** [k-int/KBPlus#885]
This page
https://www.kbplus.ac.uk/test/package/create
https://www.kbplus.ac.uk/demo/package/create
throws this error message:

```
Error applying layout : main
Error processing GroovyPageView: Error executing tag <r:layoutResources>: No module found with name [bootstrap-typeahead]
Error executing tag <r:layoutResources>: No module found with name [bootstrap-typeahead]
```

This page can be reached via "Data Explorer" → "Package" → "Create Package".

**Comment by ianibbo** [comment]
Yeah - these links need to be removed from the interface -  Ideally the
only way to create packages in KB+ is via the import facilities.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by julianladisch** [comment]
The link is still there:
https://github.com/k-int/KBPlus/blob/dev-integration/app/grails-app/views/package/list.gsp#L25

**Comment by iyawnis** [comment]
These links will probably be removed on release 5.

**Comment by julianladisch** [comment]
What does it mean that this issue is closed?

**Comment by iyawnis** [comment]
This is a known issue, there is no need to fix it as that interface will be
removed for the users . Users are to use different options for adding
packages as Ian suggested. The links may be left visible to system admins
for testing purposes. In that context they may be reviewed.

**Comment by ianibbo** [comment]
Hi Julian,

It's really to indicate that the issue will disappear when we remove the
data explorer menu. We left it for convenience after the initial data model
was constructed, but it was never intended for use by anyone other than the
dev team. By all means, submit a fix to remove the link from the gsp [Or I
may do that tomorrow if I get a chance] but by the time R5 is released the
whole data manager menu is likely to have gone.

However.... if you have requirements for functions provided by the explorer
menu that aren't covered elsewhere, now would be a really good time to flag
those up. I understand that Liam is organising a call to discuss
collaborating on the development, and this could be a good candidate area?

Either way, let us know what it is you would like to do with this page [Or
were you simply testing all the links?] and we'll make sure that we have a
way to provide that function.

best,
Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Hey again - Link removed and committed to dev-integration. Will commit to test and push to test server this weekend. Just waiting for @ostephens to finish his usage statistics testing as the test deploy will reset the test db for him.
