### ISSUE TITLE
Grails 2.3.11: Problems copying method. Incompatible JVM?

### ISSUE THREAD

**Issue by julianladisch** [k-int/KBPlus#887]
Grails 2.3.11 doesn't work with latest JDK, see
https://github.com/spring-projects/spring-loaded/issues/98
for details.

Possible solution: Switch to Grails 2.5.0, the maintenance line for Grails 2.x.

**Comment by iyawnis** [comment]
Upgraded to 2.5.1 here 61e865f5edb5539f3706f937d6326a1116c1d31b ,will keep testing before merging to dev-integration to make sure everything works.
