### ISSUE TITLE
Typo(?) on ONIX-PL Comparison page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#889]
On https://www.kbplus.ac.uk/kbplus/onixplLicenseCompare/matrix/compare there is a Supply Term (if present in ONIX-PL)

"Compliance With Open URLS tandard"

should be

"Compliance With OpenURL Standard"

Not sure where this comes from - doesn't seem to be in github code. Possibly a typo in Config.groovy on the server?

**Comment by iyawnis** [comment]
Looking at the code and this example onix licence  https://github.com/k-int/KBPlus/blob/dev-integration/manual_test_data/onix/TX-DRAFT%20Nature%20Publishing%20Group%20Academic%20License%20Template-ople-t-1375739573670.xml , that must have been a typo in an xml.

**Comment by ostephens** [comment]
I don't think it is in the XML - I've checked the XML files and the typo isn't in there - and as far as I've been able to check it appears for every file.

The XML file in the test suite does not include the relevant term

I meant to include a screenshot in previous comment - here it is

![screen shot 2015-04-23 at 14 55 54](https://cloud.githubusercontent.com/assets/576174/7299627/f60f3a12-e9ce-11e4-8662-6e7b784f1411.png)

**Comment by iyawnis** [comment]
I found the code, but its correct... line 65 @ https://github.com/k-int/KBPlus/blob/dev-integration/app/grails-app/conf/Config.groovy

**Comment by iyawnis** [comment]
I am guessing this was originally created with typo, typo saved in db, and then it stayed like that. Will investigate when done with pkg delete.

**Comment by ostephens** [comment]
I wondered if on the server config.groovy was different?

Otherwise I'm baffled why it is not displaying correctly

**Comment by ostephens** [comment]
Ok - cheers

**Comment by iyawnis** [comment]
I made a change to one of the Config values, and it wasn't reflected to the interface after restarting the system, so I guess it must be retrieved from Database after creation..

**Comment by ostephens** [comment]
Had a chat to @sosguthorpe  - he said the headings are converted from camelCase for a readable display, and because of the uppercase letters in the heading 'OpenURLStandard' the string isn't being split correctly. Not quite sure where this happens, but this is probably what we need to look for
