### ISSUE TITLE
NESLI2 Springer Option 1 Closed Consortium Agreement 2011_2012 not showing correct TIPPs/IEs

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#89]
See: http://knowplus.edina.ac.uk/kbplus/subscription/show/81

The Springer Option 1 Close Consortium package is created successfully:
http://knowplus.edina.ac.uk/kbplus/package/show/22

I think this is the package that ought to be linked to the NESLi2 'Subscription Offered' - but this is only showing a handful of titles out of the almost 2000 in the package.

The relevant import file /System - Data/Current/springer_option1closedconsortiumagreement_2011_2012_Nesli2.csv

**Comment by ianibo** [comment]
Investigating as a priority.. no answer yet, but have spotted one of the
ISSNs appearing in 2 apparently different ways?

../Masters/springer_master_2011-2012.csv:Journal of Urban
Health,2277-9078,2277-9086,,,,,,,,,,,,,SpringerLink,host,,SpringerLink,administrative,

../Subscriptions
Offered/springer_option1closedconsortiumagreement_2011_2012_Nesli2.csv:CSI
Transactions on
ICT,2277-9078,2277-9086,,,,,,,,,,,,,SpringerLink,host,,SpringerLink,administrative,

Is that right?

On 31 July 2012 14:17, ostephens <
reply@reply.github.com

> wrote:
> 
> See: http://knowplus.edina.ac.uk/kbplus/subscription/show/81
> 
> The Springer Option 1 Close Consortium package is created successfully:
> http://knowplus.edina.ac.uk/kbplus/package/show/22
> 
> I think this is the package that ought to be linked to the NESLi2
> 'Subscription Offered' - but this is only showing a handful of titles out
> of the almost 2000 in the package.
> 
> The relevant import file /System -
> Data/Current/springer_option1closedconsortiumagreement_2011_2012_Nesli2.csv
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/89

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ostephens** [comment]
No - looks like errors in the Master file with more than one ISSN inaccurate

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment]
Appears to happen the second time a particular occurrence of title-package-platform appears in a subsequent SO definition file.. In this case, shedl ok, nesli negotiated version of this package causes problems. Fixed first stage importer to add to ies array instead of attempting to create a second tipp (in staging area) which is subsequently ignored by second stage import.

**Comment by ianibo** [comment]
Tested. Seems OK now. Will deploy new dataset along with wed updated.
