### ISSUE TITLE
Package Delete

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#890]
When an admin tries to delete a package he will be shown a list of actions that will be done automatically, or the user needs to act upon. 

Currently this list contains Documents / Notes (refs to them will be deleted automatically), Subscriptions, TIPPs ( just their number, will be deleted automatically). Items that will be deleted without notification are identifier occurances and orgroles, 

For subscriptions, he will be notified if there are any subscriptions with status !='Deleted. 

The user will then have to set the status to deleted in order to delete the package. Is this correct?

Also, when the package is deleted, should we delete any linked subscriptions as well, or just the links to the package?

Finally, I assume that pending changes for the deleted package do not need to be removed.

**Comment by iyawnis** [comment]
Also, should I be removing documents from database completely? Is there a way for a document to be shared between a package and another entity ?

**Comment by ostephens** [comment]
Agreed that should not allow Packages to be deleted if there are any subscriptions with status !='Deleted'
As a result agreed that user will then need to change any related Subscriptions to 'Deleted' before they can delete package
When Package Deleted assume TIPPs will be deleted. If TIPPs attached to IEs those IEs also deleted

Any links to subscriptions (i.e. entries in subscription_package) featuring the package should be deleted.

However, Subscriptions should not be deleted (as a Sub can be attached to multiple Packages).

I think any pending changes from the Package/or it's TIPPs should be removed as these can no longer apply

**Comment by ostephens** [comment]
Not sure about shared documents - check with @ianibbo 
I'd say if the document/note is left unattached to anything else it should be removed but obviously don't want to remove it if it is linked from elsewhere

**Comment by ostephens** [comment]
Does deleting IEs have implication for TIPs?

**Comment by iyawnis** [comment]
No, IE is not connected to TIP in any way.

**Comment by latusaki** [comment]
I found the code, but its correct... line 65 @ https://github.com/k-int/KBPlus/blob/dev-integration/app/grails-app/conf/Config.groovy

**Comment by iyawnis** [comment]
![pkg_detai](https://cloud.githubusercontent.com/assets/2336352/7317260/bcf5d18e-ea76-11e4-9e38-a622dd0e7ec6.png)

![pkg_del](https://cloud.githubusercontent.com/assets/2336352/7317262/c47ec64a-ea76-11e4-92d6-3cd5919ffedb.png)

![true_detail](https://cloud.githubusercontent.com/assets/2336352/7317314/585e1b0e-ea77-11e4-9206-2b0b554a3726.png)

**Comment by iyawnis** [comment]
@ostephens  How does the above look? Any comments ?

**Comment by iyawnis** [comment]
Confirm Delete becomes enabled once subscriptions are deleted (currently only item that needs user action)

**Comment by iyawnis** [comment]
![final](https://cloud.githubusercontent.com/assets/2336352/7317574/feaf1bb4-ea79-11e4-94bc-5ab9ceb9e772.png)

**Comment by ostephens** [comment]
Looks good.
Would that window report on the number of attached IEs that would also be deleted (as a result of the TIPP deletions)?
Think it should probably flag Subscriptions that will be affected even if they have status Deleted? Just to emphasise to the user the extent of what they are doing

**Comment by iyawnis** [comment]
![final](https://cloud.githubusercontent.com/assets/2336352/7320604/8676f8b2-ea95-11e4-9708-b0635bb8f977.png)

Added (Deleted) infront of deleted subs, number of IEs given as well.

**Comment by ostephens** [comment]
Looks good
