### ISSUE TITLE
Titile Count - linkPackage

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#895]
"Add count of the number of titles in each package to the display on the Subscription Details - Link Package".

Should the count be added in parenthesis next to package name, or a separate column ?

**Comment by iyawnis** [comment]
![screenshot from 2015-04-30 14 34 01](https://cloud.githubusercontent.com/assets/2336352/7413727/02a7c132-ef46-11e4-86e1-fef5a290683f.png)

**Comment by ostephens** [comment]
Think this should be in line with the display on the Package Search (https://www.kbplus.ac.uk/test/packageDetails/index) - that is, in brackets after the title:

**Comment by iyawnis** [comment]
Right, ill just take the brackets out of the link part. Cheers.
