### ISSUE TITLE
Re-work Current Subscription screen in line with changes made to Current Licences list in 4.2

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#897]
Row 240

The only obvious difference is the way 'Delete' works. I am also adding a calendar popup on valid on for both. Form controls will be moved to the left, as with licences. Anything else?

**Comment by ostephens** [comment]
Basic changes:
- Add 'Action' column on right of table and change Delete to a button in that column and get rid of select option on left side
- Change wording of 'New Subscription (Empty)' to 'Add New Subscription'
- Suggest search boxes should be in same order and same alignment on both screens, but not sure it matters which one is changed as long as both the same. Also move Search button to same location on both screens
- Remove 'Last updated' column

Additional change:
- Add filter to allow users to show subscriptions that are nearing the Renewal Date or the End Date. Month units probably OK for this. E.g. "Show Subscriptions with Renewal/End date in the next X months"
  ![screen shot 2015-04-30 at 18 55 01](https://cloud.githubusercontent.com/assets/576174/7419060/77b98c16-ef6a-11e4-8400-fb887dec9fbb.png)

**Comment by iyawnis** [comment]
![screenshot from 2015-05-01 11 36 22](https://cloud.githubusercontent.com/assets/2336352/7429253/54e6490e-eff6-11e4-9e10-a2382ead8f3f.png)

**Comment by iyawnis** [comment]
@ostephens  does this look ok ?

**Comment by iyawnis** [comment]
not sure if Search should be bellow the form inputs.

**Comment by ostephens** [comment]
Needs to say 'month' after the 'within 1'
Would be nice to have a little spacing between the two filter rows
I think Search positioned so it more clearly applies to all the search/filter settings - maybe setting further to right and surrounding options+search with a border?

**Comment by iyawnis** [comment]
kk . Looking at css options already.

**Comment by ostephens** [comment]
And should apply to the layout on the current licence search page as well

**Comment by iyawnis** [comment]
![screenshot from 2015-05-01 14 37 43](https://cloud.githubusercontent.com/assets/2336352/7430810/aa92848a-f00f-11e4-9534-f886a13e2938.png)
