### ISSUE TITLE
Move Start Date and End Date onto single line on the Subscription Details - Current Entitlements

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#899]
Not sure which dates this one refers to..

**Comment by ostephens** [comment]
Hmm - I think the idea was to make the top part of the display more compact and so this refers to the Subscription Start and Subscription End dates.

However, looking at the display, this doesn't seem a great idea - it would save a minimal amount of space, mean this was different layout to other similar pages, and I suspect make the display messier.

Suggest we don't do this unless you disagree?
