### ISSUE TITLE
Filter list to only display licences which the current user can view or copy on the Add Licence

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#900]
Row 63, does this refer to the search box within subscriptionDetails/index for linking a licence to a sub ?

**Comment by ostephens** [comment]
Refers to https://www.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/addLicense
As far as I know on this screen all 'template' licences are shown, whether or not the user actually has permission to view/copy the licence. Permission to view/copy is based on the organisational links to the licence (membership of the licensing consortium) and the 'public' flag on the licence.

The desire is that you only see those licences that the user is allowed to view/copy

**Comment by iyawnis** [comment]
'based on the organisational links to the licence (membership of the licensing consortium) '  is this the licensee or licensor org links, or something else?

**Comment by ostephens** [comment]
This is defined in the code I think - see checkPermissions on the licence domain object https://github.com/k-int/KBPlus/blob/dev-integration/app/grails-app/domain/com/k_int/kbplus/License.groovy

Does that make sense?
