### ISSUE TITLE
Add a ‘copy this licence’ to the Licence Details page so that a copy can be created directly from this page

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#901]
There is a problem with this. Copy and Delete require an organization shortcode to work. 

For the screen they currently are placed this comes from 'myInstitutions/Anglia_Ruskin_University/'. 

When inside the licence, URL changes to 'licenseDetails/index'. Which means we lose the current institution. The institution is used to determine if they user should be able to copy/delete based on his institution access rights. 

Should I be using licensee, and when not available licensor (for templates) as a reference point ? So when licensee is available, the access rights of the user for that org will be checked. If no licensee is set, we will be testing the access rights based on licensor.

**Comment by ostephens** [comment]
The reference point should be the Institutions with which the user has an 'Editor' relationship. Suggest that a list of Orgs could be part of the action box so that the user can choose if they belong to multiple Orgs, but that default should be the one that is their default dashboard.

Would that work?

**Comment by iyawnis** [comment]
Right, then the user can select from the list in which institution the licence will go.. ok

**Comment by iyawnis** [comment]
This will allow copying of licences across institutions,is it ok ?

**Comment by ostephens** [comment]
I think this is OK - presumably this would only occur if the user had Editor affiliations to both of the relevant institutions?

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by iyawnis** [comment]
Yes that is correct. Ok I'll implement it this way then.

**Comment by iyawnis** [comment]
![screenshot from 2015-05-06 14 48 34](https://cloud.githubusercontent.com/assets/2336352/7494346/fb1cce4a-f3fe-11e4-8d8f-8f72e50f7570.png)

any comments on 'Target Institution'? Maybe it should be expressed differently ?

**Comment by ostephens** [comment]
Suggest put "Copy licence for..." above the institution name
