### ISSUE TITLE
Enable an ‘unlink’ function to remove incorrectly linked packages on the Subscription Details - Current Entitlements

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#903]
Do we need any indication of what will be deleted? Or simply 'All IEs for {package name} will be deleted' message ?

**Comment by ostephens** [comment]
Follow the pattern of the Package Delete and show a warning with the number of IEs to be deleted (don't need Subs/TIPPs in this case just the IEs of course) and they have to click "Confirm" to continue

**Comment by iyawnis** [comment]
Ok working on removing Pending Changes now. Does this look ok ?

![screenshot from 2015-05-07 12 51 54](https://cloud.githubusercontent.com/assets/2336352/7514718/f6cdfb8e-f4b7-11e4-970d-51b6e273cf50.png)
![screenshot from 2015-05-07 12 52 42](https://cloud.githubusercontent.com/assets/2336352/7514719/f6cefaa2-f4b7-11e4-919b-ffc4e257f966.png)

**Comment by ostephens** [comment]
Generally looks good to me - but maybe bring display style in line with #890 - i.e. tabular layout with same cols:
![final](https://cloud.githubusercontent.com/assets/2336352/7320604/8676f8b2-ea95-11e4-9708-b0635bb8f977.png)

**Comment by iyawnis** [comment]
All Done ?
![screenshot from 2015-05-07 15 07 19](https://cloud.githubusercontent.com/assets/2336352/7517068/c0cda1a2-f4ca-11e4-8bcd-2f12f1293b84.png)

**Comment by ostephens** [comment]
Yep - looks good

**Comment by iyawnis** [comment]
Currently the Delete Action on IEs table in SubscriptionDetails, sets the IE status as deleted. Is this what I should be doing or should I actually remove them from the database? 

Because of the above, currently when unlinking a package with an IE that was deleted using that action, the pop up says it will delete x number of IEs when the visible number is different.

**Comment by iyawnis** [comment]
Looks like even with Advance view, IEs with status deleted still are not visible.

**Comment by ostephens** [comment]
Suspect this needs referring to @ianibbo for comment - my instinct is that we should remove IEs from db in this case

**Comment by iyawnis** [comment]
@ianibbo suggested to check with you ^_^

**Comment by ostephens** [comment]
OK - if he is comfortable with removing IEs from db then that seems right approach to me.

I don't think there are any things that can hang off IEs we need to consider?
