### ISSUE TITLE
Core on Test: Some Core data not successfully migrated from KB+ old format

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#904]
e.g. https://www.kbplus.ac.uk/test/ajax/getTipCoreDates?editable=true&tipID=58935

Gives error:

URI
/test/ajax/getTipCoreDates
Class
java.lang.IllegalArgumentException
Message
Cannot format given Object as a Date

TRACE
    Line | Method
->>  310 | format          in java.text.DateFormat

---

|    157 | format          in java.text.Format
|     41 | toString . . .  in com.k_int.kbplus.CoreAssertion
|   2982 | valueOf         in java.lang.String
|    128 | debug . . . . . in org.apache.commons.logging.impl.SLF4JLog
|    731 | getTipCoreDates in com.k_int.kbplus.AjaxController
|    198 | doFilter . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter        in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke . . . .  in net.bull.javamelody.JspWrapper
|    285 | invoke          in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter . . .  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter        in     ''
|   1142 | runWorker . . . in java.util.concurrent.ThreadPoolExecutor
|    617 | run             in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . in java.lang.Thread

**Comment by ostephens** [comment]
Possibly because the Core End Date not set in the original IE Core dates?

**Comment by iyawnis** [comment]
Yes I have just fixed this issue.

**Comment by ostephens** [comment]
What will be the outcome if there is no end date? Are you filling one in, or will it be left blank? If the latter, how will this affect the True/False measure?

**Comment by iyawnis** [comment]
Core dates have already been implemented to accept null end date, I just missed that scenario there. 
With a null end-date, if the date you are looking up core status is after the Start Date, True is returned.

**Comment by ostephens** [comment]
OK - currently I don't seem to be able to enter a null end date in the Core Date edit pop-up - is this a bug then?

**Comment by iyawnis** [comment]
T_T  will fix it now
