### ISSUE TITLE
Core on Test: Title search on TIP screen is left anchored

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#905]
e.g. on https://www.kbplus.ac.uk/test/myInstitutions/University_of_Huddersfield/tipview

Title search box has help text "Partial terms accepted"

Search box is left anchored so e.g. 'historical' doesn't find 'The English Historical Review'
Suggest search box should find text wherever it appears in title.

If this is not possible, would prefer remove 'partial terms accepted' text

**Comment by iyawnis** [comment]
%rheumatic% will find Annals of the Rheumatic Diseases, how should I change the text to suggest this?

**Comment by ostephens** [comment]
Would it be possible to add the % automatically?
This seems to be the behaviour in other parts of the system (e.g. the 'Filter' box on /subscriptionDetails/index etc.)

**Comment by iyawnis** [comment]
Yes I can do that, I was just thinking that by this we take away the option of exact matches. Should I add '%' on start and end for the string ?

**Comment by ostephens** [comment]
Yes please
