### ISSUE TITLE
Core on Test: Core Titles should have yellow highlighted cells in 'Renewals Comparison' spreadsheet

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#906]
In the 'Current Sub' column in the Renewals Comparison spreadsheet (Col V in the spreadsheet) currently those titles that are "Core" are highlighted as Yellow cells rather than green.

This has been lost with the new Core status.

If the Core Status value is 'True' in the spreadsheet, then the Current Sub cell should be coloured yellow

**Comment by iyawnis** [comment]
@ostephens  This is the one coming from Institution Menu > Generate Renewals Worksheet correct ?

**Comment by ostephens** [comment]
Yes - via the 'Comparison Basket' (https://www.kbplus.ac.uk/test/myInstitutions/JISC_Collections/renewalsSearch)

**Comment by iyawnis** [comment]
Right this is what I get, the first title ('28442) has an IE which is core, so which cell should be yellow ? Also, is it normal that I get empty cells on most columns ? 
![screenshot from 2015-05-08 13 13 37](https://cloud.githubusercontent.com/assets/2336352/7536106/49f3e428-f584-11e4-9647-f265ad461074.png)

**Comment by ostephens** [comment]
Not so common to have empty cells in some columns but can happen if the relevant information hasn't been added in KB+. However, I'm not sure why Core Status and Core Status Checked columns are empty - I would have expected these to be completed for 28442 (but not 28443 which isn't a current IE)

In this case there are no Core titles in the sub, so no cells would be yellow

I generated a renewals spreadsheet and have marked it up - hope this makes it clearer

![screen shot 2015-05-08 at 13 25 45](https://cloud.githubusercontent.com/assets/576174/7536241/0d493cd8-f586-11e4-9e62-0a07a263b672.png)

**Comment by iyawnis** [comment]
Is there any other export that applies similar highlighting ?

**Comment by ostephens** [comment]
Don't think so

**Comment by ostephens** [comment]
core_status values in the Spreadsheet are now as the SubscriptionDetails:

True(this sub)
False(this sub)
False(never)

This fix tests:
 if ((ie_info.core_status) && (ie_info.core_status != "False")) 

This is never the case - so cells now _always_ appear shaded Yellow, whether title is Core or not.

Need to update test to account for new values in core_status

**Comment by iyawnis** [comment]
Fixed on 5f5d0aa68a1ec20111bd8c4a43bab49282a4b0b2
