### ISSUE TITLE
Core: Change Core True/False binary flag, to trinary flag on Subscription/IE

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#909]
Rather than the simple 'True/False' value for Core status, use three values.

For Core Status values on:

/subscriptionDetails/index
/issueEntitlement/show
Renewals Spreadsheet
- "True (this Sub)" [i.e. title Core in this subscription (based on 'as at' date)]
- "False (this Sub)" [i.e. not core in this sub, but there are core dates (based on 'as at' date)]
- "False (never)" [i.e. no core dates]

See #910 for Core values on /myInstitutions/{org_short_code}/tipview

**Comment by iyawnis** [comment]
So when 'asAt' is being used we use that for the Core flag, rest of the time we use today.

**Comment by iyawnis** [comment]
![screenshot from 2015-05-13 15 25 21](https://cloud.githubusercontent.com/assets/2336352/7612697/4bc54d92-f984-11e4-956f-efcac278572b.png)

**Comment by ostephens** [comment]
Yes - think that is correct - use asAt when it is being used, rest of the time we use today.
Any suggestions for improving the display/terminology for the trinary status welcome, but I've not been able to come up with anything

**Comment by iyawnis** [comment]
Yeah it doesnt look great, ill keep it in mind.

**Comment by ostephens** [comment]
Apologies - I think I've cocked up here. I'd forgotten how the 'AsAt' date actually worked.

I've now realised that the labels of True(this sub) and False(this sub) don't actually work. I guess they need to be date based instead. So:

True (yyyy-MM-dd)
False (yyyy-MM-dd)
False (Never)

where yyyy-MM-dd is the date being used to check core status.
(I'm open to other ideas but this is the best I can come up with at the moment)

Owen

**Comment by ostephens** [comment]
I guess ideally if todays date is being used then we should stick to the terminology used else where:

True(Now)
False(Now)
False(Never)

and only use an actual date if the asAt date is set.

**Comment by iyawnis** [comment]
On worksheet exports we only need to use (Now) correct ?

**Comment by iyawnis** [comment]
![screenshot from 2015-05-19 11 00 46](https://cloud.githubusercontent.com/assets/2336352/7700406/68a21440-fe16-11e4-81df-cd1588711d66.png)

**Comment by ostephens** [comment]
On the worksheets we include the date in a separate column, so I guess we don't really need the qualifier in the status?

Note we need to make sure any changes to the worksheet are taken account of in terms of #906 and #916

**Comment by iyawnis** [comment]
We would still need at least the False(Never)? Or is that flag not important for the exports? Now for the other two flags, we could either drop (Now) as it doesnt serve any purpose, or keep it for the sake of consistency... what do you think?

**Comment by ostephens** [comment]
Agreed we still need to differentiate the two different 'False' statuses so lets keep Now/yyyy-MM-dd/Never in the exports for the sake of consistency.

**Comment by ostephens** [comment]
Or not - I see you've already made a commit!

**Comment by iyawnis** [comment]
No worries I'll make the changes, committed so I could move with other code.
