### ISSUE TITLE
Core: Change Edit Dates button, to trinary flag on TIP/Edit Core

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#910]
Similar to #909 
See also other issues related to TIP/Edit Core screen

Currently on the TIP/Edit Core screen doesn't display the Core status flag, just a button to edit the Core status. However, since this screen mixes TIPs with and without Core dates, it needs to be clear which titles currently have Core dates.

Use a similar approach to that taken in subscriptionDetails/index with trinary calculated value but since this is not viewed in the context of the Subscription, always use the current date as the calculation date, and use the values:
- "True (now)" [i.e. title is Core as of the current date]
- "False (now)" [i.e. not currently core, but there are core dates]
- "False (never)" [i.e. no core dates]

**Comment by iyawnis** [comment]
![screenshot from 2015-05-13 15 50 29](https://cloud.githubusercontent.com/assets/2336352/7613295/cf67b948-f987-11e4-8e8b-ca9921a0d240.png)

**Comment by iyawnis** [comment]
Will add the dotted underline as well on Status to indicate 'editable'

**Comment by ostephens** [comment]
OK - looks good
