### ISSUE TITLE
Core: Add filtered views to TIP/'Edit Core Titles' screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#911]
Users want to be able to easily see those titles that already have Core dates attached, and those that don't.

Need to support three options:
- All TIPs
- Core (all TIPs with any Core dates) [relates to "True (now)" and "False (now)" values in #910]
- Not Core (all TIPs with no Core dates) [relates to "False (never)" value in #910]

Suggest we do this as separate 'tabs' on the screen, but happy to be done via on screen filters if that is much easier/quicker

**Comment by iyawnis** [comment]
Which view should be the default one ?

**Comment by ostephens** [comment]
I'd say the list of Core ones

**Comment by latusaki** [comment]
![screenshot from 2015-05-13 16 33 11](https://cloud.githubusercontent.com/assets/2336352/7614300/c966f36e-f98d-11e4-90f8-0eec400106d5.png)

**Comment by iyawnis** [comment]
![screenshot from 2015-05-13 16 32 59](https://cloud.githubusercontent.com/assets/2336352/7614303/ce6fa8c4-f98d-11e4-9669-e82ce69a9572.png)

**Comment by iyawnis** [comment]
Think its good enough. Any comments ?
![screenshot from 2015-05-13 16 35 17](https://cloud.githubusercontent.com/assets/2336352/7614336/0ea51000-f98e-11e4-9a96-6a768c3fa95b.png)

**Comment by ostephens** [comment]
Think that looks good. Thanks
