### ISSUE TITLE
Core: Add feedback to Core editing screen so it is clear when an edit has been successfully made

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#912]
When you extend or edit Core dates in the lightbox/pop-up currently the only indication an edit has been successful is by examining the data. This is harder when an existing date range has been extended rather than a new date range added

Add feedback messages on screen to indicate successful/non-successful edits

**Comment by iyawnis** [comment]
I will add messages for few scenarios, rest down the road.
![screenshot from 2015-05-13 16 45 17](https://cloud.githubusercontent.com/assets/2336352/7614554/7624aed8-f98f-11e4-9702-9958ca5f26a9.png)
