### ISSUE TITLE
Core: On subscriptionImport/importSubscriptionWorksheet/ preview columns need removing/renaming

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#916]
When importing Subscriptions either via:

/subscriptionImport/importSubscriptionWorksheet/
or
/myInstitutions/{org_shortcode}/renewalsUpload

Should use Core Medium to populate the Core Medium value for any IEs created. This should be how the import previously worked as the Core Medium field is what used to be the Core status field - which used to be imported from this spreadsheet.

However Core Medium is in the 11th Col of the spreadsheet rather than the 9th Col (which now contains the new Core Status calculated value)

Also on the preview screen the Core Medium should be shown in place of the "Core?" col, and the "Core Start Date" and "Core End Date" should be removed from the preview

**Comment by ostephens** [comment]
Just noticed - this is also true on the screen:
/myInstitutions/{org_shortcode}/renewalsUpload - needs modifying here as well

**Comment by iyawnis** [comment]
Can you send me a file that I can use to test the fix is working ?

**Comment by iyawnis** [comment]
@ostephens  this looks correct ?
![screenshot from 2015-05-19 17 16 08](https://cloud.githubusercontent.com/assets/2336352/7707999/c4352b24-fe4a-11e4-99cf-fcb763d8f43a.png)

**Comment by iyawnis** [comment]
Also, should this  work for /subscriptionImport/importSubscriptionWorksheet/ ?

**Comment by ostephens** [comment]
That looks right to me
I've sent a separate (v similar) test sheet for the importSubscriptionWorksheet via email

**Comment by iyawnis** [comment]
Yeap populated correctly.
