### ISSUE TITLE
Public Export Formats

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#918]
I have sorted the JSON export to use the same export service as package details. How to I handle rest of the formats? Should I provide all the options available for export through packageDetails? What about the current exports of publicExport, should they be trashed?

**Comment by ostephens** [comment]
I've talked to Magaly and we should be aiming to support four export formats which would be available from both publicExport and packageDetails. The current publicExport options can be trashed and instead we will have:
- "JSON" [as currently used in packageDetails]
- "XML"  [as currently used in packageDetails]
- "KBPlus (CSV)" [this is the export currently called "KBPlus Import Format" - it should be renamed and the new name used on both publicExports and packageDetails and subscriptionDetails where it is also used]
- "KBART II (TSV)" [this is a new export format - I need to write a new xslt for this. It should be available in both places]

N.B. providing KBART II export is another enhancement request - see line 93 of Enhancement Reqs spreadsheet

**Comment by ianibbo** [comment]
As I discussed with M - what about the "Old" KBart file? Are people not
downloading / using that?

We need to be careful as it looks to me [From the logs] Like some automated
bots already consume that feed and process the information in that form -
so we don't [I assume?] want to break those systems?

I did have a chat with M about this.

e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Asked M before responding to this and she said the 4 formats would suffice. However, I'd agree that we don't want to break anything. Can we get any more info on the automated bots consuming the existing feed?

**Comment by ostephens** [comment]
In updated test deployment the old URL for csv exports are broken. These are still included in the 'cufts style index' csv (https://www.kbplus.ac.uk/test/publicExport/idx?format=csv). These look like:

publicExport/pkg/867?format=csv

With either need to reinstate the old csv at these URLs (which would be in line with "don't break anything") or redirect them to the new CSV export:

publicExport/pkg/867?format=xml&transformId=kbplus&mode=

Given Ian's comments above I'd suggest that for now we reinstate the old csv for these links but only have these links in the "CUFTS style" file.

I also note that in updated test deployment the CUFTS Style XML file https://www.kbplus.ac.uk/test/publicExport/idx?format=xml is broken - needs fixing or link removing. Fixing preferred.

**Comment by iyawnis** [comment]
Fixed the XML and re-instatiated the CSV, so the generated links in idx are usable.
