### ISSUE TITLE
Break down usage term display into user types

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#923]
I need some feedback, does this look ok? Should I just try and make the 'User' cell a bit higher?

![screenshot from 2015-06-10 15 32 35](https://cloud.githubusercontent.com/assets/2336352/8085044/1bd3139a-0f86-11e5-9a8b-41659e62455b.png)

**Comment by ostephens** [comment]
I'd say the user types ("Authorized User", "Licensee") should be bigger and bolder
Overall looks good to me

**Comment by iyawnis** [comment]
Ok done.. moving to Individual specifications for each UsageTerm ... sigh..
