### ISSUE TITLE
UsageTerms clarification

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#925]
In the current onixpl configuration we are looking for UsageTerm with UsageType: 'AccessViaSecureAuthentication'. On the example onixpl licence from the specification we have UsageType: Access, UsageMethod:SecureAuthentication. Is there some connection here? Is AccessViaSecureAuthentication a deprecated UsageType ?

**Comment by ostephens** [comment]
It looks like AccessViaSecureAuthentication is deprecated - at least it doesn't seem to be in the current documentation, and the only mention I've been able to find for it is in a specification document from several years ago (before KB+)
