### ISSUE TITLE
OnixPl Upload 

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#926]
When uploading an existing onixpl licence, repalce doesnt seem to delete the old terms of the licence, resulting in duplicates. Creating new  entry is using the same name as original, which can cause confusion.

**Comment by ostephens** [comment]
I'm not completely sure about this, but if the comparison process, and the display of a single licence, doesn't require us to store ONIX-PL terms, this part of the upload process can be taken out completely?
