### ISSUE TITLE
Onix comparison screen rework

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#929]
There are no specific requirements for this task, I have replaced the two select boxes with a type down.
Users will search for the licence they want and click add, the licence is then moved to the box bellow. This can be repeated for each licence the user wants to add. When finished they can select comparison points which has not changed and compare. 

![screenshot from 2015-06-16 16 24 11](https://cloud.githubusercontent.com/assets/2336352/8186765/239c545c-1444-11e5-9134-24cf948327e8.png)

**Comment by ostephens** [comment]
I need to think about this a bit more. What you've done here looks like an improvement and maybe sufficient - I'll have a look and get back to you.

**Comment by ostephens** [comment]
Overall looks good and does the job. Sending individual pieces of feedback separately so will close this
