### ISSUE TITLE
LicenceDetails: Link to Subscription

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#933]
What should be the subscriptions available to link with the licence? Is it only current subscriptions (the ones visible in http://localhost:8080/demo/myInstitutions/Aberystwyth_University/currentSubscriptions 
by default ?

**Comment by ostephens** [comment]
Yes - I think just current subscriptions

**Comment by iyawnis** [comment]
Also, if a subscription is already linked to a licence, I assume we dont want it in the list?

**Comment by ostephens** [comment]
Agreed

**Comment by latusaki** [comment]
Final question hopefully, do we want to display subscriptions that belong to Orgs with Role Licensee in Licence Org links? I dont see any other way of knowing which institution the licence belongs to.

**Comment by iyawnis** [comment]
I have a licence that has orgLink - licensee to De Montfort University and JISC. I only have access to JISC. Should the subscriptions of   De Montfort University  be available for linking the licence or not ?

**Comment by iyawnis** [comment]
![screenshot from 2015-06-17 15 01 30](https://cloud.githubusercontent.com/assets/2336352/8208856/b4c00db2-1501-11e5-9d0e-496a900952a7.png)

**Comment by ostephens** [comment]
You should only be able to link subscriptions for an Org you belong to. So in your example, if you only have access to Jisc, only the Jisc subs should be available for linking.

**Comment by ostephens** [comment]
Looks good
