### ISSUE TITLE
Add ‘email contact’ to Licence on the Licence Details

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#934]
Is there a reason why this is not done with custom properties ? 

Should it be just a new String field ?

**Comment by ostephens** [comment]
I think the reason not to do it as a custom property is that it isn't to do with licence terms (which the custom properties address) but admin data around the licence.

Just a new string field

**Comment by ianibbo** [comment]
I thought the custom props were becoming a bucket for anything users wanted
to store related to the license?

Not that it matters - go ahead and create a new DB field

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
