### ISSUE TITLE
ONIX PL ghost licence

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#936]
It looks like comparing against a ghost licence, while not showing the ghost licence column is not as simple as I thought. I will look a bit more into it, but I think its not going to work. Making it work like that would potentially take a lot of time. 

In this case, I will make sure the users will be directed to a comparison of their desired licence with the ghost licence, without having to go through the standard process of selecting two licences for comparison, but the result screen will be the same as if they had done that. 

Do you think this will be sufficient ( if the original approach of showing one column is  proven not straight forward)

**Comment by ostephens** [comment]
I think this would probably be OK. I'd suggest we start with this and show it to users for feedback - if they feel strongly we'll know it is worth putting in more effort to see if we can achieve hiding the template licence column
