### ISSUE TITLE
Licence Exports

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#939]
For the currentLicences export, should I just return a document that will list the licences and subscriptions of the currently visible licences ( with current filters)? Should I return only the data visible on the screen or more data should 0be added ?

For the licenceDetails export, any specific requests or just put all the Licence fields and the custom properties in ?

I think the onix comparison export is a significant piece of work, even though we got the data ready formating them for csv export is probably going to be couple of days work. Is this priority 1 or should I do the other exports, and top priority tasks first?

**Comment by iyawnis** [comment]
There is already an XML export for licence, should the same fields go to CSV (including any extra custom properties)

**Comment by iyawnis** [comment]
Fields currently in XML: 
"LicenceReference" "NoticePeriod" "LicenceURL" "LicensorRef" "LicenseeRef" "LicenceProperties"

**Comment by iyawnis** [comment]
For single licence export in CSV format, should the headers be on top row, or be displayed vertically ?

**Comment by ostephens** [comment]
Headers on top row
