### ISSUE TITLE
TitleDetails edit Identifiers

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#941]
"Warn titleDetails when adding an ISSN that is already used for a title. Change title edit form." Does this apply on anything other than titleDetails/edit?

**Comment by iyawnis** [comment]
![screenshot from 2015-06-24 16 48 09](https://cloud.githubusercontent.com/assets/2336352/8334622/d16eed2c-1a90-11e5-9ca0-d71eb0d25d9d.png)

**Comment by iyawnis** [comment]
This is visible when trying to add an identifier that already belongs to other titles.
![screenshot from 2015-06-24 16 49 05](https://cloud.githubusercontent.com/assets/2336352/8334639/f3c0eb78-1a90-11e5-99cd-cafd6573519b.png)

**Comment by ostephens** [comment]
Looks good. Think this is the only place it is needed
