### ISSUE TITLE
Add option to copy Notes and Documents from previous subscription

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#943]
"When using ‘renewal’ process add option to copy Notes and Documents from previous subscription on the Subscription Details - Current Entitlements" 

Do we want to duplicate the documents, or only create new references from the new subscription?

New references mean that edits on the Document will be reflected everywhere. Deleting a document from one subscription will not affect others (as only the reference is deleted).

**Comment by ostephens** [comment]
Just create new references
