### ISSUE TITLE
Lower Case Identifiers

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#946]
We still have uppercase identifiers, need to make sure everything is lowercased

**Comment by d3vAdv3ntur3s** [comment]
After checking, all namespaces are already lower cased (see: refdataCreate in the Identifier), however, there are existing ones that need to be changed with a MYSQL script. 

I will write the query and include in the upgrade-pre-txt

**Comment by d3vAdv3ntur3s** [comment]
UPDATE identifier_namespace SET idns_ns = lower(idns_ns);

**Comment by iyawnis** [comment]
Checked the database and running the script wont create dups.
