### ISSUE TITLE
KB+ Licence Comparison 

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#949]
I think this is done ?
![screenshot from 2015-07-08 14 56 40](https://cloud.githubusercontent.com/assets/2336352/8571968/a8a510aa-2581-11e5-967a-5af722ead266.png)

![screenshot from 2015-07-08 14 56 53](https://cloud.githubusercontent.com/assets/2336352/8571974/ad025630-2581-11e5-9df1-288b3331a23a.png)

**Comment by ostephens** [comment]
Sending feedback via individual issues - happy to close this one and tackle each piece individually. Overall looking v good
