### ISSUE TITLE
Securing public org page by user

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#951]
What should I be using to access which users should have access to the public Org page for journal/licences ? There are two options, `UserOrg.formalRole.authority` or `UserOrg.formalRole.roleType` or I could check both. The institution managers will need to add a comma separated list of the roles that will be allowed in the new org settings screen (reuse of Custom Properties)

**Comment by ostephens** [comment]
Suggest we check both
Default (i.e. if no values in the new setting, or setting doesn't exist) that as long as the user is affiliated to the org in question by any role, then they can view
Also need an option to allow anyone to view (no auth needed at all) - possibly by adding the role 'public' to the list? Or another mechanism
