### ISSUE TITLE
Large number of Pending Changes causing timeout

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#952]
This has been addressed by separating the interface thread from PC processing. When Accept/Reject  all is used the screen updates and the user will see this: 
![screenshot from 2015-07-15 11 51 50](https://cloud.githubusercontent.com/assets/2336352/8696935/bfad13bc-2ae8-11e5-845f-4f2fb6619f59.png)

Refreshing the screen will make the user see the changes that have been applied so far. Interactions with PendingChanges are blocked during processing. This is applied to LicenceDetails, PackageDetails, and SubscriptionDetails.

**Comment by ostephens** [comment]
Looks good to me
