### ISSUE TITLE
Licence comparison "SupplyCopy" methods should be enumerated in result cell not in comparison point

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#954]
The SupplyCopy usage term in the ONIX-PL licence has a 'UsageMethod' :

```
<Usage>
            <UsageType>onixPL:SupplyCopy</UsageType>
            <UsageStatus>onixPL:Permitted</UsageStatus>
            <LicenseTextLink href="Ex030102"/>
            <User>onixPL:AuthorizedUser</User>
            <UsedResource>onixPL:LicensedContentPart</UsedResource>
            <UsageMethod>onixPL:Post</UsageMethod>
            <UsageMethod>onixPL:Fax</UsageMethod>
            <UsageMethod>onixPL:SecureElectronicTransmission</UsageMethod>
            <UsageQuantity>
                <UsageQuantityType>onixPL:NumberOfCopiesPermitted</UsageQuantityType>
                <QuantityDetail>
                    <Proximity>onixPL:NotMoreThan</Proximity>
                    <Value>1</Value>
                    <QuantityUnit>onixPL:Copies</QuantityUnit>
                </QuantityDetail>
            </UsageQuantity>
            <UsageRelatedAgent>
                <UsageAgentRelator>onixPL:ReceivingAgent</UsageAgentRelator>
                <RelatedAgent>onixPL:ThirdPartyLibrary</RelatedAgent>
            </UsageRelatedAgent>
            <UsageRelatedPlace>
                <UsagePlaceRelator>onixPL:PlaceOfReceivingAgent</UsagePlaceRelator>
                <RelatedPlace>onixPL:CountryOfLicensee</RelatedPlace>
            </UsageRelatedPlace>
        </Usage>
```

Currently the first one of these is being used to create the comparison point, and the others aren't displayed:
<img width="1173" alt="screen shot 2015-07-15 at 14 25 24" src="https://cloud.githubusercontent.com/assets/576174/8699517/ed13e97e-2afd-11e5-82ad-479b6c421e1a.png">

Instead all methods should be enumerated in the comparison result cells, and not used in the comparison point at all - from the Spec:
<img width="946" alt="screen shot 2015-07-15 at 14 30 17" src="https://cloud.githubusercontent.com/assets/576174/8699551/2c8412b4-2afe-11e5-81c1-abcc64f19c0a.png">

**Comment by iyawnis** [comment]
Is this for every UsageTerm or only SupplyCopy?
Should I test if UsageMethod.size() > 1 and then display it it in the cell, or make a specific case for SupplyCopy and always show in cell

**Comment by ostephens** [comment]
I'd originally said that this was a specific case for 'SupplyCopy', but looking at it again, I think this should be handled consistently across all elements (the other place UsageMethod appears is in the Access UsageTerm)

So UsageMethod should always display as a list in the cell - even if there is only one usage method element. This is to ensure we get consistent comparison points in all cases.

**Comment by iyawnis** [comment]
Is this ok ? I thought we should avoid another list as cells would get too high.
![screenshot from 2015-07-15 15 06 11](https://cloud.githubusercontent.com/assets/2336352/8700332/0c7192b2-2b03-11e5-9dcd-872643bb6507.png)

**Comment by ostephens** [comment]
Yes - looks good

**Comment by ostephens** [comment]
Oh - perhaps need a bullet point in front as with the other two lines in the cell
