### ISSUE TITLE
Where licence term contains extra uppercase letters, adding spaces to terms for display is incorrect

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#960]
For the ONIX-PL licence comparison display terms in the licence XML have spaces added to them for display. E.g.:

```
<GeneralTermType>onixPL:NoticeProcedure</GeneralTermType>
```

Leads to Comparison point display of "Notice Procedure"

This mechanism fails when there are additional uppercase letters in the term:

```
<SupplyTermType>onixPL:ComplianceWithOpenURLStandard</SupplyTermType>
```

leads to "Compliance With Open URLS tandard" instead of "Compliance With OpenURL Standard"
and

```
<GeneralTermType>onixPL:NotificationOfLicenseeIPAddresses</GeneralTermType>
```

leads to "Notification Of Licensee IPA ddresses" instead of "Notification Of Licensee IP Addresses"

Suggest either rule that says "don't split if there are multiple consecutive uppercase letters in the term" or have special cases for identified terms (so far only these two identified)

**Comment by iyawnis** [comment]
For now I will hard code the result, but I will talk with Steve and Ian to find better approaches. Wondering if 'last upper case before lowercase is start of new word' will do the trick
