### ISSUE TITLE
In KB+ Licence Comparison (licenceCompare/compare/compare) use correct values for mouseovers

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#965]
When you mouseover the icons in the new KB+ Licence Comparison view the mouseovers should ideally use the reference value from the licence (e.g. 'Yes', 'No', 'Other'). Alternatively the mouseovers could be removed from this view.

The current mouseovers (e.g. 'Prohibited by licence','Detailed by licence') should not be used as these maybe misleading in some cases:

<img width="1234" alt="screen shot 2015-07-16 at 11 07 01" src="https://cloud.githubusercontent.com/assets/576174/8720530/30249b70-2bab-11e5-81a0-fd639dfe33da.png">

**Comment by iyawnis** [comment]
@ostephens  "Not defined by the licence" should stay the same ?

**Comment by ostephens** [comment]
Should be "Not set" I think.

This is subtle but want to avoid suggesting that the actual licence document doesn't say anything about the condition, but rather that no-one has bothered to populate the property for this licence

**Comment by iyawnis** [comment]
"No Limit" Should be under the check icon ? Or plain text

**Comment by ostephens** [comment]
Plain text
