### ISSUE TITLE
Relabel new licence reports

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#969]
New licence reports accessible from /licenseDetails and /currentLicenses:

XML Export (Subscriptions & Packages)
XML (with IssueEntitlements)

Should be labelled:

Licensed Subscriptions/Packages (CSV)
Licensed Issue Entitlements (CSV)

**Comment by iyawnis** [comment]
I assume you mean Licensed Subscriptions/Packages (XML) ?

**Comment by ostephens** [comment]
Oh yes. Just looking at the XSLT to give you the csv from that XML now - will have with you today

**Comment by iyawnis** [comment]
Ok fixed for these, if we need to add another export create new issue for it. Cheers!
