### ISSUE TITLE
Licence JSON export should include all custom properties and notes

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#970]
JSON export (e.g. https://www.kbplus.ac.uk/test/licenseDetails/index/6558?format=json) should include all custom properties and all notes attached to the properties (the equivalent XML https://www.kbplus.ac.uk/test/licenseDetails/index/6558?format=xml has already been updated to include these)

**Comment by iyawnis** [comment]
There are other JSON exports which take their licences from the same function used for the licence JSON export (Package JSON and Sub JSON). Will it be ok for the licence properties and notes to be visible on those?

**Comment by ostephens** [comment]
Yes
