### ISSUE TITLE
Add new licence export to /licenseDetails

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#971]
Add the following export to /licenseDetails:

Licensed Subscriptions/Packages (CSV)

XSLT being sent via email
Should be applied to "Licensed Subscriptions/Packages (XML)" - i.e.
https://www.kbplus.ac.uk/test/licenseDetails/index/5165?format=xml&format_content=subpkg

**Comment by iyawnis** [comment]
Do we keep the XML export ? Or only many the CSV available ?

**Comment by ostephens** [comment]
I think just link the CSV - the XML is available if they want it and know the URL - we can document that.
Also can you do the same on /myInstitutions/{shortcake}/currentLicenses

Also on /currentLicences please rename "XML (with IssueEntitlements)" to "Licensed Issue Entitlements (CSV)" (same as #969 but on currentLicenses screen)

**Comment by ostephens** [comment]
Also noticed a problem with the xslt used for the Licensed IEs CSV transform - I'll send you an update by email

**Comment by iyawnis** [comment]
Is the new xsl working? Trying to apply transform on the following XML returns empty document 

```
<?xml version="1.0" encoding="UTF-8"?><Licences>
 <Licence>
  <LicenceReference>Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113</LicenceReference>
  <LicenceID>5165</LicenceID>
  <Subscriptions>
   <Subscription>
    <SubscriptionID>9837</SubscriptionID>
    <SubscriptionName>Duke</SubscriptionName>
    <SubTermStartDate>2014-01-01</SubTermStartDate>
    <SubTermEndDate>2014-12-31</SubTermEndDate>
    <ManualRenewalDate/>
    <Packages/>
   </Subscription>
   <Subscription>
    <SubscriptionID>9818</SubscriptionID>
    <SubscriptionName>new</SubscriptionName>
    <SubTermStartDate>2014-01-01</SubTermStartDate>
    <SubTermEndDate>2015-12-24</SubTermEndDate>
    <ManualRenewalDate/>
    <Packages>
     <Package>
      <PackageID>472</PackageID>
      <PackageName>Cambridge University Press:Master</PackageName>
      <PackageContentProvider>Cambridge University Press</PackageContentProvider>
     </Package>
     <Package>
      <PackageID>30</PackageID>
      <PackageName>Cambridge University Press:NESLI2:Humanities and Social Science Collection:2010-2012:Year 2</PackageName>
      <PackageContentProvider>Cambridge University Press</PackageContentProvider>
     </Package>
    </Packages>
   </Subscription>
  </Subscriptions>
 </Licence>
 <Licence>
  <LicenceReference>Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113</LicenceReference>
  <LicenceID>5808</LicenceID>
  <Subscriptions>
   <Subscription>
    <SubscriptionID>2767</SubscriptionID>
    <SubscriptionName>New Scientist Archive</SubscriptionName>
    <SubTermStartDate>2013-10-01</SubTermStartDate>
    <SubTermEndDate>2016-09-30</SubTermEndDate>
    <ManualRenewalDate/>
    <Packages/>
   </Subscription>
   <Subscription>
    <SubscriptionID>3358</SubscriptionID>
    <SubscriptionName>just-style</SubscriptionName>
    <SubTermStartDate>2014-02-04</SubTermStartDate>
    <SubTermEndDate>2016-02-03</SubTermEndDate>
    <ManualRenewalDate/>
    <Packages/>
   </Subscription>
  </Subscriptions>
 </Licence>
 <Licence>
  <LicenceReference>Copy of BioOne/Jisc Collections/Complete Journals/2015</LicenceReference>
  <LicenceID>6167</LicenceID>
  <Subscriptions/>
 </Licence>
```

**Comment by ostephens** [comment]
That XML is missing a closing &lt;/Licences&gt; tag
If I add the tag and run it through the XSLT I supplied (licenced_subscriptions_packages.xsl) I get:

licence_id,licence_ref,subscription_id,subscription_name,subscription_start_date,subscription_end_date,subscription_renewal_date,package_id,package_name,package_provider
"5165","Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113","9837","Duke","01/01/2014","31/12/2014","",
"5165","Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113","9818","new","01/01/2014","24/12/2015","","472","Cambridge University Press:Master","Cambridge University Press",
"5165","Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113","9818","new","01/01/2014","24/12/2015","","30","Cambridge University Press:NESLI2:Humanities and Social Science Collection:2010-2012:Year 2","Cambridge University Press",
"5808","Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113","2767","New Scientist Archive","01/10/2013","30/09/2016","",
"5808","Copy of American Chemical Society/Jisc Collections/Legacy Archives/2013-2113","3358","just-style","04/02/2014","03/02/2016","",
