### ISSUE TITLE
XML on publicExport for packages only includes 10 titles

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#975]
The XML export (and so the KBPlus/KBART exports based on this) only includes 10 titles from the package. Should include all titles (as JSON currently does)

**Comment by iyawnis** [comment]
Are there cases where we want to restrict the number of exported titles when using XML? Or should we always export all

**Comment by iyawnis** [comment]
The existing code for some reason only set 10.000 titles as a default for CSV and JSON, I have changed it to include XML

**Comment by ostephens** [comment]
Thanks (for some reason it seemed to behave differently on publicExport to elsewhere
