### ISSUE TITLE
Grails error when trying to view Org options on test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#976]
Trying to view new Org config/options screen - e.g. https://www.kbplus.ac.uk/test/organisations/config/502 gives a Grails error:

Error 500: Internal Server Error
URI
/test/organisations/config/502
Class
org.hibernate.ObjectNotFoundException
Message
No row with the given identifier exists: [com.k_int.custprops.PropertyDefinition#34]
Trace
    Line | Method
->>  530 | doFilter  in /organisations/config.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: No row with the given identifier exists: [com.k_int.custprops.PropertyDefinition#34]
->>   23 | doCall    in /WEB-INF/grails-app/views/organisations/config.gsp

---

Caused by ObjectNotFoundException: No row with the given identifier exists: [com.k_int.custprops.PropertyDefinition#34]
->>   61 | run       in gsp_demo_templates_custom_props_gsp

---

|     46 | doCall    in gsp_demo_organisationsconfig_gsp$_run_closure2
|     56 | run . . . in gsp_demo_organisationsconfig_gsp
|    198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter  in     ''
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by iyawnis** [comment]
This doesn't seem to happen now.. i will double check the code, but it is quite strange to get this exception as there isnt anything hardcoded there..

**Comment by ostephens** [comment]
Confirmed no longer happening for me

**Comment by iyawnis** [comment]
We already got an issue for this for test.
