### ISSUE TITLE
Add link to new 'public licence display' from Institutional Title list

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#979]
e.g. from https://www.kbplus.ac.uk/test/myInstitutions/uoborsetshire/currentTitles

Suggest link is added under the title in the first col. Labelled 'Check current licence terms'

**Comment by iyawnis** [comment]
Should the whole link be visible, as to make copying easier, or should I show some placeholder text?

**Comment by iyawnis** [comment]
Ah sorry, you already answered this.

**Comment by iyawnis** [comment]
Is this ok ?
![screenshot from 2015-07-20 16 38 13](https://cloud.githubusercontent.com/assets/2336352/8779908/bb1fabde-2efd-11e5-809a-607144ced4d7.png)

**Comment by iyawnis** [comment]
Made the journalLicence form method `GET` so that the url can be used to share search. Journal will accept kb+ id using namespace kb:<id>. I dont find the `Check current licence terms` really nice, I think we should use something smaller..

**Comment by ostephens** [comment]
Thanks. I'll see if I can come up with something shorter
