### ISSUE TITLE
On test: trying to view Org Options get a Grails error

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#984]
e.g. https://www.kbplus.ac.uk/test/organisations/config/502

Think related to new custom property to control 'public' licence view

Error 500: Internal Server Error
URI
/test/organisations/config/502
Class
org.hibernate.ObjectNotFoundException
Message
No row with the given identifier exists: [com.k_int.custprops.PropertyDefinition#34]

TRACE:
    Line | Method
->>  530 | doFilter  in /organisations/config.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: No row with the given identifier exists: [com.k_int.custprops.PropertyDefinition#34]
->>   23 | doCall    in /WEB-INF/grails-app/views/organisations/config.gsp

---

Caused by ObjectNotFoundException: No row with the given identifier exists: [com.k_int.custprops.PropertyDefinition#34]
->>   61 | run       in gsp_demo_templates_custom_props_gsp

---

|     46 | doCall    in gsp_demo_organisationsconfig_gsp$_run_closure2
|     56 | run . . . in gsp_demo_organisationsconfig_gsp
|    198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter  in     ''
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by ostephens** [comment]
Looks like this might just be this particular Org? e.g. https://www.kbplus.ac.uk/test/organisations/config/390 is fine

**Comment by iyawnis** [comment]
Trying to test this I noticed problem is not visible any more. Also it appears I dont have access to organisations/list, but do have access to organisations/show  (view only) ... is this ok ? Should I have access to /list as well ?

**Comment by ostephens** [comment]
@latusaki I've added admin rights to your account on the test server - so you should have access to /list now. Let me know if any probs.

Closing this issue

**Comment by iyawnis** [comment]
Question was mostly, if non admins should be able to view /show /users /config (view-only) or, if similar to /list , those views should be only available to admins. Or /list should be available to users .

**Comment by ostephens** [comment]
/list doesn't need to be visible to users
/config should only be accessible to users who are affiliated to the org. If they are affiliated as editor they should be able to edit
