### ISSUE TITLE
Data missing from KB+ Test

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#986]
Some data that is on live KB+ does not seem to be appearing on test. e.g.

e.g. https://www.kbplus.ac.uk/test/myInstitutions/Lancaster_University/currentLicenses?offset=&max=190
shows <190 licences on test
https://www.kbplus.ac.uk/kbplus/myInstitutions/Lancaster_University/currentLicenses?offset=&max=190
shows >190 licences on live

Picking an example licence:
https://www.kbplus.ac.uk/kbplus/licenseDetails/index/7864
Created 2015-06-01 09:40:04

on test equivalent URL https://www.kbplus.ac.uk/test/licenseDetails/index/7864 gives Grails error:

Error 500: Internal Server Error
URI
/test/licenseDetails/index/7864
Class
java.lang.NullPointerException
Message
Cannot get property 'reference' on null object
Trace
    Line | Method
->>   37 | index     in com.k_int.kbplus.LicenseDetailsController

---

|    198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    198 | doFilter  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter  in     ''
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by ostephens** [comment]
Another example of data not being copied live->test when test is deployed:
https://www.kbplus.ac.uk/kbplus/packageDetails/show/1 - has 'Public' flag set to 'Yes'
https://www.kbplus.ac.uk/test/packageDetails/show/1 - Public flag is not set

**Comment by ianibbo** [comment]
Sure about this? Think I changed this n test when testing something else..
Is it the same after the redeploy to test?

**Comment by ostephens** [comment]
Checked this afternoon just before I reported this issue - which was soon after the deploy to test today.

**Comment by ianibo** [comment]
OK - got it

When test was uber broken the /s3 filesystem wasn't getting mounted and we
updated the deploy script to run a db dump we had to hand instead of the
latest backup.

When test got fixed this never got reverted. Have fixed this now, next test
deploy should sort it. Not running now in case HH has done some test setup.

Chalk it up to infrastructure woes.

sorry
Ian.

On 11 August 2015 at 16:21, Owen Stephens notifications@github.com wrote:

> Another example of data not being copied live->test when test is deployed:
> https://www.kbplus.ac.uk/kbplus/packageDetails/show/1 - has 'Public' flag
> set to 'Yes'
> https://www.kbplus.ac.uk/test/packageDetails/show/1 - Public flag is not
> set
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/986#issuecomment-129927689.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibbo** [comment]
cool - thanks - have fixed now, see other thread.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
@ianibbo noticed today that there are some significant differences in data on live and on test. Over 8000 licences on live (https://www.kbplus.ac.uk/kbplus/lic/list?offset=8000&max=100) while less that 6800 on test (https://www.kbplus.ac.uk/test/lic/list?offset=6700&max=100)

Not sure if this is the same issue again, or something else?

**Comment by ianibbo** [comment]
Does test have any new filters or other functionality that would or should
account for this? Before I start digging.. Will speak with I and r about it
tomorrow and do some SQL.

**Comment by ostephens** [comment]
There have been some changes to some filters on the current licence view I think and that was my first thought, but I did those counts via the data explorer listings rather than via the app screens to try to avoid any data filters being the issue.

**Comment by ianibo** [comment]
Data deffo different :/

Test

mysql> select lic_status_rv_fk,count(_) from license group by
lic_status_rv_fk;
+------------------+----------+
| lic_status_rv_fk | count(_) |
+------------------+----------+
|               37 |     6126 |
|               39 |      661 |
|               40 |        5 |
|               42 |        1 |
+------------------+----------+
4 rows in set (0.01 sec)

Live

mysql> select lic_status_rv_fk,count(_) from license group by
lic_status_rv_fk;
+------------------+----------+
| lic_status_rv_fk | count(_) |
+------------------+----------+
|               37 |     7212 |
|               39 |      800 |
|               40 |       20 |
|               42 |        1 |
|               43 |        3 |
|              285 |        3 |
+------------------+----------+
6 rows in set (0.00 sec)

On 20 August 2015 at 09:28, Owen Stephens notifications@github.com wrote:

> There have been some changes to some filters on the current licence view I
> think and that was my first thought, but I did those counts via the data
> explorer listings rather than via the app screens to try to avoid any data
> filters being the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/KBPlus/issues/986#issuecomment-132935058.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
Updated deploy script to terminate old test DB with extreme prejudice.
It'll work or we'll have an empty db from now on.

On 20 August 2015 at 09:42, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Data deffo different :/
> 
> Test
> 
> mysql> select lic_status_rv_fk,count(_) from license group by
> lic_status_rv_fk;
> +------------------+----------+
> | lic_status_rv_fk | count(_) |
> +------------------+----------+
> |               37 |     6126 |
> |               39 |      661 |
> |               40 |        5 |
> |               42 |        1 |
> +------------------+----------+
> 4 rows in set (0.01 sec)
> 
> Live
> 
> mysql> select lic_status_rv_fk,count(_) from license group by
> lic_status_rv_fk;
> +------------------+----------+
> | lic_status_rv_fk | count(_) |
> +------------------+----------+
> |               37 |     7212 |
> |               39 |      800 |
> |               40 |       20 |
> |               42 |        1 |
> |               43 |        3 |
> |              285 |        3 |
> +------------------+----------+
> 6 rows in set (0.00 sec)
> 
> On 20 August 2015 at 09:28, Owen Stephens notifications@github.com
> wrote:
> 
> > There have been some changes to some filters on the current licence view
> > I think and that was my first thought, but I did those counts via the data
> > explorer listings rather than via the app screens to try to avoid any data
> > filters being the issue.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/KBPlus/issues/986#issuecomment-132935058.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson
