### ISSUE TITLE
Add 'Sector' to editable fields on Manage Organisation screen

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#987]
For an institution to appear on the list of institutions to which a user can affiliate (from the users Profile screen), the organisation's 'sector' (org.sector) must be equal to 'Higher Education'.

Currently the only screen where this can be edited is /org/edit/, which is accessed via the Data Explorer. To enable Data Managers/KB+ Admins to be able to edit this without going via the Data Explorer to /org/edit/, add the Sector as an editable field on 'organisations/show/'

e.g. https://www.kbplus.ac.uk/kbplus/organisations/show/1

This can be under the 'Org Type' editable field already on this screen

**Comment by ianibbo** [comment]
Don't think this is correct..

Data explorer actually points to https://www.kbplus.ac.uk/kbplus/org/index
and https://www.kbplus.ac.uk/kbplus/org/show/1

Wheras Admin -> Manage Organisations points to
https://www.kbplus.ac.uk/kbplus/organisations/list and
https://www.kbplus.ac.uk/kbplus/organisations/show/1.

Will add the required editing to the manage orgs link not Explorer?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Sorry - missed this. I believe that we need to add the new edit option to /organisations/show/

<img width="965" alt="screen shot 2015-08-16 at 23 42 20" src="https://cloud.githubusercontent.com/assets/576174/9295745/ad8e7256-4470-11e5-9f1f-bd630ff50900.png">

**Comment by ostephens** [comment]
Fixed by @ianibbo
