### ISSUE TITLE
Transfer IEs between TIPPs

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#992]
I am not sure what will happen here. If we are deleting a TIPP, does that mean we deleted the package? What choices do we give to the user to perform the transfer? Do they need to select a new package that  has the same subscription as the IE being deleted ?

**Comment by ostephens** [comment]
We need to implement ability to hard delete TIPPs independently of deleting the package - sometimes a title has been added to a package in error, and the TIPP needs removing. Sometimes it happens that the Title has been accidentally added to the package twice (i.e. two TIPPs for the same TI) - on needs deleting and the other preserving.

Suggest the simplest way of implementing this would be like the Title Merge https://www.kbplus.ac.uk/kbplus/admin/titleMerge. This is not going to be a common thing to do, and keeping it simple like this avoids us having to build some complicated search interface to find the two TIPPs etc.

So - just have the ability to enter two TIPP IDs - one to transfer from, one to transfer to. Click 'Look up TIPP info' button - shows the Title, the package name, TIPP coverage details (start/end date) & include coverage note, and the IEs attached to each one (prob don't need the details, just number of IEs)

Then a button to complete the transfer.

Does that make sense? Basically same as Title Merge workflow but with a bit more detail on the screen at the pre-merge stage.

No assumption that the two TIPPs have to be in the same package btw

**Comment by iyawnis** [comment]
I assume any IEs already related to the target TIPP will not be affected?

**Comment by iyawnis** [comment]
Also, do we need to delete pending changes that were generated by changes on the source TIPP ?

**Comment by iyawnis** [comment]
@ostephens  also I think it would be good to add some grouping (similar to 'Buld Tasts') 
for actions like User Merger, Title MErger, IE Transfer, Package Delete ?

**Comment by iyawnis** [comment]
![screenshot from 2015-08-12 13 57 26](https://cloud.githubusercontent.com/assets/2336352/9224419/14d937ea-40fa-11e5-8670-1d2148289419.png)

**Comment by ostephens** [comment]
Agreed IEs already on TIPP won't be affected
I think pending changes should follow the IE
Agreed about that grouping - also 'Expunge Deleted Titles' should go in there? "Data Management Tasks"?

**Comment by iyawnis** [comment]
That on is under Data Manager menu, while the others are under Admin Menu...

**Comment by ostephens** [comment]
Yes - M has already asked for that to be moved to Admin Menu (so will need doing for 5.0)
