### ISSUE TITLE
Test: 'Unlink' package option shows, but does not work

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#994]
'Unlink' package option has been added to /subscriptionDetails/details/ but does not work: 
e.g. https://www.kbplus.ac.uk/test/subscriptionDetails/details/10068

Clicking the 'Unlink' button does not result in any action

**Comment by iyawnis** [comment]
this broke from the TIPPDeletions introduced after the unlink was implemented. The pending change document  format is different for some reason than the rest. I will look if I should change the TIPP Deletion document or modify the code to work with this document.
