### ISSUE TITLE
Test: Core/Medium column on Subscriptions Details page should be 'Entitlement Medium'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#997]
On Test some changes to the Subscriptions Details page have led to the 'Core' and 'Medium' column being re-instated in error. This column should be the 'Entitlement Medium (P/E)' as on live.

Screenshot from test showing incorrect col header/info:

<img width="1209" alt="screen shot 2015-08-10 at 11 30 45" src="https://cloud.githubusercontent.com/assets/576174/9169538/b01d03a6-3f53-11e5-8c35-ce65b89ce4e4.png">

Screenshot from live showing correct col header/info

<img width="1206" alt="screen shot 2015-08-10 at 11 30 52" src="https://cloud.githubusercontent.com/assets/576174/9169529/9ca17e38-3f53-11e5-94a8-3dec4e63a028.png">

The other changes to the Subscriptions Details page are correct and should be retained (e.g. merging of ISSN/eISSN into title cell)

**Comment by iyawnis** [comment]
Does this table seem correct?
![screenshot from 2015-08-10 11 56 42](https://cloud.githubusercontent.com/assets/2336352/9169996/f18230c0-3f56-11e5-8320-ea1161b8f4a2.png)

**Comment by ostephens** [comment]
That's the current version on Live. We were going to merge the ISSN/eISSN into the Title Cell - so the final layout I'd expect would be:

<img width="1237" alt="screen shot 2015-08-10 at 12 02 33" src="https://cloud.githubusercontent.com/assets/576174/9170088/bfe87370-3f57-11e5-8d06-92f38907e53d.png">
